### ISSUE TITLE
Problem with load simple x86 OS

### ISSUE THREAD

**Issue by coderaiser** [copy/v86#1]
Hi, thank you for such interesting project. Could you please help me?
When I try to load floppy image of my [os](http://coderaiser.github.io/nemizida) nothing happens and console show next error:

```
Uncaught Unimplemented: Unknown floppy size: 4E00 
```

Thing is image size is smaller then 1.4 Mb but everything works fine on [jemul8](https://github.com/asmblah/jemul8).

When I try to load full 1.4 image size, then this error occures:

```
Uncaught RangeError: Maximum call stack size exceeded
```

You could get image from [url](https://github.com/coderaiser/nemizida/releases/tag/v0.1.0).

Thank you.

**Comment by ItsTheAwesomestChannel85** [comment]
If you Çee this message right no,kÞleaseØdial (8lÒ) ###-#### and tell›hem that yäu haveëfoun
 úhs flasE drive, and go to our address,MwhicÆ s 32½¤West 22nd Strent, Co##n ton K(####4. ‚nce yoØ getŠthere, tell uÁ tat you h›ve found §his flÅsh drive a‘dötha| weÌshould caim it bacN if we w]nt itk If we say no, *ou are fèee to do w_atever you wznt to th×s flaÌh driv¢. Else, y©u do NO{ pave pe:mission to change any con
ents of thisBf¬ash driz or even des~roy the flxsh drive!
 §Thaßk you!
ˆ
N¥te t’at if you gžve Ahe flash nri˜eTdamaged or the ©oñÁents of the flash driveßwas chs7ged, tuere my be a chance´that we may dial 911 =ue to invading ÷popôe' ñrvacy.
