### ISSUE TITLE
Why use C macros?

### ISSUE THREAD

**Issue by h8liu** [copy/v86#10]
Hi copy,

Why do you use C macros? Or in other words, why not write it just in javascript? Is it for better performance? Or is it just for your own convenience?

**Comment by ZaDarkSide** [comment]
Can we remove the C preprocessor dependency altogether including all macros associated with building the library? It's useless dependency now, all the code generated from macros can be used in source and later refactored if needed.

**Comment by copy** [comment]
Most macros should be refactored to functions, so that code isn't repeated too much. Doing that part later will be a pain. It shouldn't be too hard, I just haven't found the time to do it yet.
