### ISSUE TITLE
hardcoded 'partfile_alt_format'

### ISSUE THREAD

**Issue by farhan-ct** [copy/v86#1001]
### Discussed in https://github.com/copy/v86/discussions/1000

<div type='discussions-op-text'>

<sup>Originally posted by **farhan-ct** March  5, 2024</sup>
Hi,

I observed that the option 'partfile_alt_format' is hardcoded as false, which results in not considering fixed chunks made using gnu split. Is there any specific reason why this was done?</div>

@copy

**Comment by farhan-ct** [comment]
@copy

**Comment by copy** [comment]
It was a prototype that was never used. The current format has the advantage that you can't get the chunk size wrong (you'd get 404s). 

Feel free to send a PR to expose the alternative format, if you really want to use it.

**Comment by farhan-ct** [comment]
This is what I am using currently, same as mentioned in main.js demo page

1. I edited the built libv86.js file and hardcoded `partfile_alt_format` to true.
2. I split my image using `split -b 1M -a8 -d --additional-suffix .img <image-name>.img <some-prefix>-`
3. 
```
  hda: {
    url: <.img url>,
    size,
    async: true,
    fixed_chunk_size: 1024 * 1024,
    use_parts: true,
  }

```

and it's working great.

I am closing this issue for now, thank you!
