### ISSUE TITLE
how did you build this

### ISSUE THREAD

**Issue by SX-9** [copy/v86#1004]
what articles or docs you read to understand and implement this all in wasm?

**Comment by copy** [comment]
- https://developer.mozilla.org/en-US/docs/WebAssembly
- https://webassembly.github.io/spec/core/
- https://pdos.csail.mit.edu/6.828/2006/readings/i386/toc.htm
- https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html
- http://ref.x86asm.net/geek32.html
- https://www.sandpile.org/
