### ISSUE TITLE
cirrus vga

### ISSUE THREAD

**Issue by SX-9** [copy/v86#1006]
add support for cirrus vga

**Comment by copy** [comment]
Which guest OSes use cirrus vga, and what for?

**Comment by SX-9** [comment]
> Which guest OSes use cirrus vga, and what for?

im developing my own os and it uses framebuffer with cirrus vga driver

**Comment by copy** [comment]
I'd suggest using bochs vga extensions instead, which is supported by most emulators and OSes: https://wiki.osdev.org/Bochs_VBE_Extensions
