### ISSUE TITLE
Instructions Prefixes not implemented?

### ISSUE THREAD

**Issue by aaron-elkins** [copy/v86#101]
According to `src/instructions.js`, I can not see any code related to instruction prefixes, why v86 can boot so many OSes without implementing instruction prefixes?

Any help to better understand this issue?

**Comment by copy** [comment]
All prefixes are implemented:

- Segment prefixes set `cpu.segment_prefix`, which is read [here](https://github.com/copy/v86/blob/e9ca7ed33c1200defec6d3855a9764fa3504af31/src/cpu.js#L2146) and set [here](https://github.com/copy/v86/blob/e9ca7ed33c1200defec6d3855a9764fa3504af31/src/instructions.js#L106) and in other places
- String prefixes also set a flag and are set [here](https://github.com/copy/v86/blob/e9ca7ed33c1200defec6d3855a9764fa3504af31/src/instructions.js#L1244) and read [here](https://github.com/copy/v86/blob/e9ca7ed33c1200defec6d3855a9764fa3504af31/src/string.js#L50)
- Address-size and operand-size prefixes are set [here](https://github.com/copy/v86/blob/e9ca7ed33c1200defec6d3855a9764fa3504af31/src/instructions.js#L106)

As you can see, the prefix instructions recursively call `do_op` to run the next instruction and then clear the prefix. If there's an exception it is caught [here](https://github.com/copy/v86/blob/e9ca7ed33c1200defec6d3855a9764fa3504af31/src/cpu.js#L421) and all prefixes are cleared [here](https://github.com/copy/v86/blob/e9ca7ed33c1200defec6d3855a9764fa3504af31/src/cpu.js#L871).

**Comment by aaron-elkins** [comment]
Will review the code you mentioned. thanks.

**Comment by aaron-elkins** [comment]
After reviewing the code you mentioned, I just want to say your solution to instruction prefixes is elegant, and easy to read, :)
