### ISSUE TITLE
NX bit support

### ISSUE THREAD

**Issue by FunnyCorgi** [copy/v86#1016]
I saw the old post about adding NX bit support, and I think it is a good idea. Can you put it on a to do list?

**Comment by FunnyCorgi** [comment]
It would allow more operating systems to run on V86.

**Comment by FunnyCorgi** [comment]
And yes, I realize this is basically a repost, but it really needs to be added.

**Comment by FunnyCorgi** [comment]
And yes, I changed from my school account(@FunnyDoggs) to my personal account(this account)

**Comment by FunnyCorgi** [comment]
Yes I know, I am wondering if it is added or is going to be added.

**Comment by FunnyCorgi** [comment]
Sorry I hadn't read it yet, will do so.

**Comment by spetterman66** [comment]
You should not force people on GitHub to add features, they have a life too. Rather, read up on documentation and make your own NX bit implementation. It would also improve your programming skills :D

**Comment by FunnyDoggs** [comment]
Its just I don't know whether to get contributor access to for it to let me make a pull or just fork it.

**Comment by FunnyDoggs** [comment]
> You should not force people on GitHub to add features, they have a life too. Rather, read up on documentation and make your own NX bit implementation. It would also improve your programming skills :D

I'm not trying to, I just don't know how pull requests really work...
