### ISSUE TITLE
Bugs in PS/2 implementation

### ISSUE THREAD

**Issue by Bananymous** [copy/v86#1018]
I was trying to get my os to boot on v86 and PS/2 keyboard did not work. I looked into v86's PS/2 code and found 2 possible bugs.

src/ps2.js:570 Reports current scan code set as 2 although only scan code set 1 seems to be supported.

src/ps2.js:708 Identify response's second byte is missing a hexadecimal prefix. Standard PS/2 keyboard should identify as 0xAB 0x83.

If these are actual bugs I'm curious how other operating systems function. Do they assume unknown devices are keyboards using scan code set 1.

**Comment by copy** [comment]
Fun fact: This code is 10 years old this year. Time to go middle school.

> src/ps2.js:708 Identify response's second byte is missing a hexadecimal prefix. Standard PS/2 keyboard should identify as 0xAB 0x83.

Could you send a PR to fix this?

> src/ps2.js:570 Reports current scan code set as 2 although only scan code set 1 seems to be supported.

Good question. I suspect that the value `2` is incorrect anyway (according to [this](https://wiki.osdev.org/PS/2_Keyboard#Commands) it should return `0x43` for set 1 or `0x41` for set 2). Probably should be changed and tested.

**Comment by Bananymous** [comment]
> according to [this](https://wiki.osdev.org/PS/2_Keyboard#Commands) it should return 0x43 for set 1 or 0x41 for set 2

I'm not sure if that table is correct. I took a quick look on other documentation, but they just told that it will respond with the scan code set (not specified further). Qemu and Bochs do respond with byte 0x01-0x03 depending on the current set. I don't have any real hardware to test this.

I took a quick look in SerenityOS's code base to check how they handle PS/2. They only care about the first byte of identification. For the scan code set determination they use set 1 if translation is enabled, and set 2 if not. Translation is taken as kernel command line parameter.

**Comment by copy** [comment]
> I'm not sure if that table is correct. I took a quick look on other documentation, but they just told that it will respond with the scan code set (not specified further). Qemu and Bochs do respond with byte 0x01-0x03 depending on the current set. I don't have any real hardware to test this.

Let's change it to 1 then.

In any case, it seems that all OSes that v86 runs at a moment (which is a fair amount) use the first scan code set and don't issue this command.
