### ISSUE TITLE
Far Jump in 16bits address size issue

### ISSUE THREAD

**Issue by aaron-elkins** [copy/v86#102]
The implementation of 16bits far jump in this line 

[segment selector](https://github.com/copy/v86/blob/master/src/instructions.js#L1168)

In Intel manual it writes: 

```
EA cd JMP ptr16:16
```

Here it means ptr16 is the segment selector, and then comes the 16bits displacement, but it the code above, why `cpu.switch_seg(reg_cs, cpu.read_imm16());` comes after `var ip = cpu.read_imm16();`

Wired, maybe i miss-understood something?

**Comment by aaron-elkins** [comment]
Is this issue relative to instruction encoding?

**Comment by copy** [comment]
See section 4.3 (Pointer data types) of the Intel manual.

**Comment by aaron-elkins** [comment]
Thanks, that makes sense. 

segment selector are 16 bits from 16th bit to 31th bit. :) (In case of ptr16:16)
