### ISSUE TITLE
PIC disables all IRQs on initialization

### ISSUE THREAD

**Issue by 52871299hzy** [copy/v86#1025]
Intel 8259A [datasheet](https://pdf.datasheetcatalog.com/datasheet/Intel/mXtuutu.pdf) specifies that after receiving ICW1, the Interrupt Mask Register is cleared, indicating that all interrupts are enabled. However in v86, this actually disables all interrupts, as `irq_mask = 0` turns off all IRQs.

Below is part of the source code of my toy OS.

```cpp
#define PORT_PIC_MASTER 0x20
#define PORT_PIC_SLAVE  0xA0
#define IRQ_SLAVE       2

static void init_intr() {
  outb(PORT_PIC_MASTER, 0x11);
  outb(PORT_PIC_SLAVE, 0x11);
  outb(PORT_PIC_MASTER + 1, 32);
  outb(PORT_PIC_SLAVE + 1, 32 + 8);
  outb(PORT_PIC_MASTER + 1, 1 << 2);
  outb(PORT_PIC_SLAVE + 1, 2);
  outb(PORT_PIC_MASTER + 1, 0x3);
  outb(PORT_PIC_SLAVE + 1, 0x3);
  printf("pic master mask: %x\n",inb(PORT_PIC_MASTER + 1));
  printf("pic slave mask: %x\n",inb(PORT_PIC_SLAVE + 1));
  outb(PORT_PIC_MASTER + 1, 0x0); //manually enable all irqs
  outb(PORT_PIC_SLAVE + 1, 0x0);
}
```

On qemu it outputs both mask as 0, but on v86 it outputs both mask as 0xff.

**Comment by copy** [comment]
Indeed, nice find. Wanna send a PR?
