### ISSUE TITLE
ability to run .elf kernel

### ISSUE THREAD

**Issue by Ponali** [copy/v86#1033]
hi, when i managed to compile [an assembly kernel from someone else](https://github.com/DayDun/CarlOS/) into its own .elf file (build.kernel.elf), i wanted to try using it with v86, but it says to use "bzimage".
i was trying to find a way to convert the .elf to a bzimage format, but to no avail, and directly importing the .elf file simply throws an error without any GUI notification. here is what DevTools gathered:
![image](https://github.com/copy/v86/assets/91608163/c4dc19ab-48e7-4f41-89fd-157156a749f2)
![image](https://github.com/copy/v86/assets/91608163/b3fcfb3c-9b8a-46af-adf0-881e21820f12)

it would be nice to add support for kernels with raw format (.elf). if there is no way to do so, it would be nice to link a tutorial on converting to a bzimage format - i'm kinda new to the subject of virtualization '._.

**Comment by SuperMaxusa** [comment]
According to [kernel sources](https://github.com/DayDun/CarlOS/blob/3e6ead1b446ea99dc0d6fa3de3b418a78a3a8677/src/kernel.asm#L9-L16), it's a [multiboot image](https://www.gnu.org/software/grub/manual/multiboot/multiboot.html). 
Did you try to load image with multiboot option? (now not available on v86 demo) https://github.com/copy/v86/commit/df0d136208af7db8ebc2259c3cf51775d58c52a6

**Comment by copy** [comment]
The bzimage format is somewhat documented here (you can probably learn more by reading v86 or kernel sources): https://www.kernel.org/doc/Documentation/x86/boot.txt

As already mentioned, multiboot is another format that should work in v86, but feel free to reopen if it doesn't.
