### ISSUE TITLE
Cannot run KolibriOS

### ISSUE THREAD

**Issue by ace-dent** [copy/v86#1034]
Using Chrome - Version 116.0.5845.187 (Official Build) (x86_64), on macOS Intel laptop.
After initial boot of KolibriOS, the emulator hangs on loading the desktop. Historically this worked and would load.

**Comment by ace-dent** [comment]
After flushing cache seems to be working... I think the issue was setting `Networking proxy` to <kbd>space</kbd> rather than blank (i.e. " " vs "").

**Comment by copy** [comment]
Indeed, we need a try-catch here:

https://github.com/copy/v86/blob/c69cbd7854d7cbda08679c389973aa87c9fb37bd/src/browser/network.js#L101

**Comment by SuperMaxusa** [comment]
> Obviously this shouldn't cause a crash(?)....

On Chrome, space in Networking proxy (if more technically, in WebSocket constructor) caused this error in console that crashed an emulator:
```
Uncaught DOMException: Failed to construct 'WebSocket': The URL ' ' is invalid.
```

On Firefox, it's just tries connect to URL from address bar:
![firefox_network_blank](https://github.com/copy/v86/assets/41739128/03aa7943-b676-4575-883d-a46e43dc5f2e)

**Comment by ace-dent** [comment]
@copy - Thanks for the quick response and for this wonderful tool! It has allowed me to explore multiple OS withe ease.

Does this issue also expose an underlying issue on KolibriOS, that I should report back to their team?

**Comment by copy** [comment]
> Does this issue also expose an underlying issue on KolibriOS, that I should report back to their team?

No, the issue was specific to v86.
