### ISSUE TITLE
When attempting to install debian in the emulator, from both disk and cd-rom, I get a bugged out screen.

### ISSUE THREAD

**Issue by FunnyCorgi** [copy/v86#1037]
I press "Graphical Install" from the install menu, and then it will begin to read a lot from the IDE device. Then, it goes idle with this screen:
![image](https://github.com/copy/v86/assets/166766151/123b8d35-a3c4-4227-8d49-bda0d9e0bb3f)

**Comment by FunnyCorgi** [comment]
Oh wait, I think you just have to wait like 5 minutes. It seems to be starting now.

**Comment by FunnyCorgi** [comment]
So if someone else is having this problem, it seems like it corrects itself.

**Comment by SuperMaxusa** [comment]
> Then, it goes idle with this screen:

see https://github.com/copy/v86/issues/641
