### ISSUE TITLE
Booting windows XP

### ISSUE THREAD

**Issue by corped12** [copy/v86#1039]
I tried booting off of a windows XP sp3 iso and it said "(setup cannot access this drive)" and pressing enter would give me this
![Screenshot 2024-05-14 5 44 41 PM](https://github.com/copy/v86/assets/161154933/11edbc8c-fea1-4898-bc11-e68038103678)

**Comment by 36479756** [comment]
You have to set it up on QEMU then load the .img file into the section wich says hard disk image
