### ISSUE TITLE
Audio not working / Soundcard not fully configured on demo Windows 2000 image

### ISSUE THREAD

**Issue by andrigamerita** [copy/v86#1049]
Hi, I noticed that with the Windows 2000 image included on copy.sh/v86 apparently there are no system sounds, except for a PC speaker beep that can be heard when a Windows error message box is shown.
I went to try and play an audio file, and Windows Media Player says "Cannot play back the audio stream: no audio hardware is available, or the hardware is not responding (Error=80040256)".
I went to check in both the Sound Control Panel and the Device Manager, and it seems the case is that, indeed, no working sound card is installed.
Also, the volume mixer icon is not present in the system tray.

![image](https://github.com/copy/v86/assets/37557992/c9caa6f2-8506-4fe6-9850-946c9dc24e24)

This is really strange, as apparently in Windows 98 the audio works. I tried in both Firefox and Chromium, but there's no difference, so it seems to me like the Windows 2000 system is either missing drivers, or is just not even seeing the sound card device. I did try to force install the SoundBlaster 16 driver on the only device I could see in Device Manager that is marked as "not configured correctly", the PCI device in picture, as I thought that could be the thing after reading issue #982 (even though the user in question hasn't explained with which device exactly they messed with, so I might be totally off), then I saved a dump of the HDD to my computer, and started from that since Windows asked me to restart to apply the changes, but no dice: my change was saved, but the OS just said that the device could not be started.

I encountered several unrelated issues trying to both make my own Windows 2000 HDD by installing from a WinWorld ISO, and using other random preinstalled QEMU images I found online, so I hope this issue can be fixed within the demo one, because for all other intents and purposes that one just works. I also want to clarify that my issue seems somewhat related to that one I mentioned, but it's totally different under the surface (the user there managed to install the soundcard device, but I still got the exclamation mark saying the device isn't working, and also my issue affects different browsers), so I'm even more confused at what could be going on.

**Comment by andrigamerita** [comment]
Nevermind! I feel kinda stupid for solving this 5 minutes after spending 15 minutes of time to write this issue, but:
* That PCI device has nothing to do with all of this, it's something else unrelated
* The soundcard has to be installed by going into System Properties > Hardware > Add/Remove Hardware Wizard > Add/troubleshoot a device > Add a new device > No, I want to select hardware from a list > Sound, video and game controllers > Creative Technology Ltd. > Sound Blaster 16 or AWE32 or compatible (WDM); and it actually requires no reboot.

Classic Windows settings being extra confusing! Anyway, this does mean that the image loaded in copy.sh in indeed not set-up correctly; you should probably either update the virtual hard disk image, or just update the savestate file that gets loaded. I'm changing the title for this issue but leaving it open.

**Comment by copy** [comment]
Thanks for the report, I fixed this in the windows2k image.

Finally we can play pinball with (choppy) sound!

[![pinball](https://github.com/user-attachments/assets/bcc868d7-b487-4dd2-8439-11e98c65f8cd)](http://copy.sh/v86/?profile=windows2000)
