### ISSUE TITLE
Way to use with a on screen keyboard? Like in iOS

### ISSUE THREAD

**Issue by kmakblob** [copy/v86#105]
Hello, huge fan of this project just having trouble while using on mobile because the iOS keyboard only allows you two type in a text box. I was wondering if there is functionality for this or if not any hints for implementing it myself? Thanks, kmak

**Comment by copy** [comment]
Currently we're focusing an invisible input field when you tap on the screen, which works on Android. I'll see what we can do about iOS.

**Comment by Efreak** [comment]
Just came here to mention this. If you add an invisible input field, it would be nice to also have function keys available buttons on the screen. It might also be worth seeing how the Hacker Keyboard and other Android keyboards with function keys work (I've used them in the terminal, but have no idea what they do in the browser).

**Comment by copy** [comment]
We're already using a hidden input, which works on Android as far as I have tested. I don't have an iOS device to test right now, so it would be nice if someone could try and figure out how to show the keyboard (if it doesn't work already). The relevant code for Android is [here](https://github.com/copy/v86/blob/master/src/browser/main.js#L1094-L1115).

**Comment by copy** [comment]
> It might also be worth seeing how the Hacker Keyboard and other Android keyboards with function keys work (I've used them in the terminal, but have no idea what they do in the browser).

Function keys work using Hacker Keyboard:

![](http://i.imgur.com/ri5m6KD.png)

**Comment by czenzel** [comment]
I found a light fix for iOS. I say "light" because it works on the text-mode terminals. Make the div tag that is pre-formatted have an attribute of contenteditable="true" It opens the keyboard on iOS 10 and allows the input and processes the commands quite well. Function keys not tested yet.

**Comment by copy** [comment]
> I found a light fix for iOS. I say "light" because it works on the text-mode terminals. Make the div tag that is pre-formatted have an attribute of contenteditable="true" It opens the keyboard on iOS 10 and allows the input and processes the commands quite well. Function keys not tested yet.

Does this work if the div is focused using `.focus()`? Also if it's invisible? (currently we're using an invisible text input).
