### ISSUE TITLE
KolibriOS image has changed location

### ISSUE THREAD

**Issue by ace-dent** [copy/v86#1054]
Cannot load [KolibriOS](http://copy.sh/v86/?profile=kolibrios), with error message `Loading //builds.kolibrios.org/eng/data/data/kolibri.img failed.`. This is because of changes on the project's build server.

The equivalent path is now `//builds.kolibrios.org/en_US/data/data/kolibri.img` - i.e. `ENG` has changed to `en_US`.
Thanks :-)

**Comment by jdsuhlmann** [comment]
this is still an issue for me

**Comment by ace-dent** [comment]
@jdsuhlmann - Doesn't work for me either. I presume the fix is just in Git currently, and not yet released to the live website.
I did notice there seems to be a `fallback` that isn't working ([here](https://github.com/copy/v86/blob/9acbeecf97c37f3f71b6f3bbc2a3fdea4df8a4d2/src/browser/main.js#L540-L546))?...

**Comment by corped12** [comment]
when I tried copying and pasting the download link into chrome I got a 404 not found error

**Comment by ace-dent** [comment]
@corped12 - I think the file transfer link is without protocol (so can be `http` *or* `https`). I'm not sure this works with a browser?

**Comment by corped12** [comment]
they actually changed from that link to  https://builds.kolibrios.org/en_US/data/data/kolibri.img

**Comment by copy** [comment]
Should be fixed now.
