### ISSUE TITLE
Arch not working in example dir

### ISSUE THREAD

**Issue by sefsepta** [copy/v86#106]
I cloned it localally and everything works besides the arch linux example. I have read the code and it is trying to grab arch3.img from a dir that isnt in the local copy that dir is (/v86-images). And the arch quick start doesnt work in the local copy either. Just wanted to know how to get arch running on local. Thanks, khaki

**Comment by copy** [comment]
The disk image is 16 GB, it's too large to provide as a download. In order to run it, make your own installation using QEMU like this:

```
qemu-img create arch-hd.img 16G
qemu-system-i386 -cdrom arch.iso -hda arch-hd.img
```
