### ISSUE TITLE
Creating GUI with cosmos gives error

### ISSUE THREAD

**Issue by SanskarSontakke** [copy/v86#1066]
I was creating a simple COSMOS 2022 GUI with C# .

COSMOS version : 2022 (latest which is available on the COSMOS website).
Visual Studio version : 2022 (latest).
After running the code it says "NULL reference exception occurred. halting Now"
Here's the screen shot
![image_2024-06-28_194952153](https://github.com/copy/v86/assets/76463065/9b4c7a82-40e4-4ee6-ab56-5760df618207)

Here is my Code in Before Run and Run function : 

```
protected override void BeforeRun()
{
    System.Console.Clear();
    System.Console.WriteLine("\n\n");
    this.VFS = new CosmosVFS();
    Sys.FileSystem.VFS.VFSManager.RegisterVFS(this.VFS);
    System.Console.ForegroundColor = System.ConsoleColor.Green;
    System.Console.WriteLine("VFS                  :OK");
    this.commandManager = new CommandManager();
    System.Console.WriteLine("Command manager      :OK");
    System.Console.WriteLine("Cosmos boot          :OK");
    DelayInMS(10000);
    System.Console.ForegroundColor = System.ConsoleColor.White;
    System.Console.Clear();

    System.Console.WriteLine("Booted successfully you can write any command. \n");
}

protected override void Run()
{
    Canvas canvas = FullScreenCanvas.GetCurrentFullScreenCanvas();
    canvas.Clear(Color.Black);

    String response;
    System.Console.WriteLine("\n");
    String input = System.Console.ReadLine();
    response = this.commandManager.processInput(input);

    System.Console.WriteLine(response);
}
```

The compiler does not give me ant error while compiling.
The only thing I know that it runs totally fine until it executes this line : 
`Canvas canvas = FullScreenCanvas.GetCurrentFullScreenCanvas();`

The `DelayInMS()` function is already declared and has no problems.

**Comment by copy** [comment]
This looks completely unrelated to v86, closing.
