### ISSUE TITLE
Age of empires 2 crashes when you try to start a game

### ISSUE THREAD

**Issue by dylaniscool54** [copy/v86#1067]
the menu works fine however if u play death match or any option as soon as the game is meant to start the screen colors invert and glitch out followed by the game closing

**Comment by copy** [comment]
Does it work in qemu? Could you upload the image for us to reproduce?

**Comment by dylaniscool54** [comment]
yes it works in qemu

**Comment by SuperMaxusa** [comment]
Did you install VBEMP (if guest OS is Windows 9x) or other driver?

**Comment by SuperMaxusa** [comment]
Did you install VBEMP (if the guest OS is Windows 9x) or other driver?

**Comment by dylaniscool54** [comment]
im switching to windows 98.
it opened it qemu but i didnt try start a game
im gonna run on v86|
![image](https://github.com/copy/v86/assets/106529128/6e425d28-1278-4756-a235-82a3b2fe234e)
😎

**Comment by dylaniscool54** [comment]
just tested its very playable in qemu more than windows 2k

**Comment by dylaniscool54** [comment]
![image](https://github.com/copy/v86/assets/106529128/f11030f3-051a-4ba6-9a1d-ac6b40296547)
LETS GOOOO 3 weeks of work!!!!!

**Comment by SuperMaxusa** [comment]
Cool! Just for interest: what version of DirectX do you have installed? (you can check this in `dxdiag`) 
I have tested on Windows 95 OSR2.5 and DirectX 7, Trial version works fine. Would be helpful for issue #893 too.

![aoe2](https://github.com/copy/v86/assets/41739128/fc48c1e7-0dc8-496a-8807-249cc1310088)

**Comment by copy** [comment]
@SuperMaxusa @dylaniscool54 That's so cool, I'm thinking of adding this to the website. Is the performance decent? Could one of you send me the disk image?

**Comment by SuperMaxusa** [comment]
> Is the performance decent?

Mostly playable, but the sound is choppy and it's in all the DirectDraw games I have tested (Ace Of Emperies I-II Trial, Diablo Pre-Release Demo).

**Comment by dylaniscool54** [comment]
Super Maxusa's disk is probs better than mine since mine uses windows 98

i lost my image

**Comment by SuperMaxusa** [comment]
> since mine uses windows 98

Second Edition (4.10.2222)?
