### ISSUE TITLE
Cant boot arch linux!

### ISSUE THREAD

**Issue by bobmcdouble3** [copy/v86#107]
I grabbed an arch linux iso from the site but it sadly doesnt boot heres the error:
ERROR: '/dev/disk/by-label/ARCH_201212' device did not show up after 30 seconds...
Falling back to interactive prompt
You can try to fix the problem manually, log out when you are finished
sh: can't access tty; job control turned off

is there a special image or something?

**Comment by jyf007** [comment]
i.copy.sh/arch/ i wanna this path as a squanshfs image to mount ,and make a mirror of v86 site.
