### ISSUE TITLE
BUG: Ctrl+S KeyStroke Freezes the Shell - At Official Web Too

### ISSUE THREAD

**Issue by evonox** [copy/v86#1070]
A tried the reverse search with Ctrl+R in the shell and it works. However the Ctrl+S forward search freezes the terminal. The same behavior / bug is also on the official ArchLinux profile website www.copy.sh.

**Comment by SuperMaxusa** [comment]
https://stackoverflow.com/a/791800

In few words, Ctrl + S (XOFF) is also key command that freeze the screen[^1] (see https://en.wikipedia.org/wiki/Software_flow_control#Representation) and this may conflict with forward search, `stty -ixon` turns off XON/XOFF in your session.

[^1]: For unfreeze use [Ctrl + Q](https://web.cecs.pdx.edu/~rootd/catdoc/guide/TheGuide_38.html)

**Comment by evonox** [comment]
@SuperMaxusa : Wow, I checked it and it really works. Thank you very much for extending my Linux knowledge.

**Comment by copy** [comment]
Let's close this then.
