### ISSUE TITLE
Linux - Rebooting - Causes error in JavaScript

### ISSUE THREAD

**Issue by evonox** [copy/v86#1073]
This error is displayed in the browser's console when I try to reboot the Linux distro.
![image](https://github.com/copy/v86/assets/4886999/402a8cbd-02dd-4718-ba61-b84e87fa5f57)

**Comment by evonox** [comment]
Official COPY.SH web for ArchLinux is returning this error.
![image](https://github.com/copy/v86/assets/4886999/94d84600-f18a-4107-a840-7aa796742931)

**Comment by dylaniscool54** [comment]
i think its meant to send restart but sends reset which doesnt exist

**Comment by evonox** [comment]
> i think its meant to send restart but sends reset which doesnt exist

I do not call restart method in my code. It is inside the V86.js script.
