### ISSUE TITLE
DSL start screen wont close

### ISSUE THREAD

**Issue by puzzleboxsoftworks** [copy/v86#1076]
When i start DSL The screen on Dillo wont close when I Try to click it.How do i fix?

**Comment by SuperMaxusa** [comment]
Did you try **left click** on top-left corner of the window/**right click** on this window on the taskbar -> **Close**?

**Comment by puzzleboxsoftworks** [comment]
Yes I Did It Did not work.

**Comment by puzzleboxsoftworks** [comment]
I also cant open anything else
