### ISSUE TITLE
resizing dom terminal

### ISSUE THREAD

**Issue by coderofsalvation** [copy/v86#1090]
Thank you for this wonderful project.
I'm trying to resize the (dom) terminal using this javascript:

```
emulator.screen_adapter.set_size_text(120,120)
emulator.screen_adapter.update() 
```
which correctly adds the right amount of `<span>` elements.
However, the buildroot example still seems stuck in 80x25, even after running this in the session:

```
/root% export TERM=xterm                                                                                                
/root% export COLUMNS=120                                                                                               
/root% export ROWS=120                                                                                                  
/root% resize                                                                                                           
COLUMNS=80;LINES=25;export COLUMNS LINES; 
```

any ideas?

**Comment by SuperMaxusa** [comment]
You can only set text mode resolution supported by VGA: https://en.wikipedia.org/wiki/VGA_text_mode#PC_common_text_modes
If you need freely change terminal resolution, you can try use a serial port with xterm.js: https://github.com/copy/v86/issues/172#issuecomment-396976546

**Comment by copy** [comment]
The vga screen can only be configured by the guest OS.
