### ISSUE TITLE
linux kernel crashing in browsers

### ISSUE THREAD

**Issue by progrium** [copy/v86#1093]
When I build an Alpine image using kernel 6.1.94-lts, booting without initial state in chrome and webkit, it seems to get stuck here:

<img width="792" alt="Screenshot 2024-07-24 at 6 20 21 PM" src="https://github.com/user-attachments/assets/fc583082-255e-4231-b55b-6d16900546a3">

Whatever its doing, it retries. And in Chrome eventually it boots, but I haven't seen it happen in Webkit yet. However, running this via a Nodejs script (like the initial state examples) consistently just works.

**Comment by SuperMaxusa** [comment]
Are you using the [latest version](https://github.com/copy/v86/releases/tag/latest) of v86? #1069

**Comment by progrium** [comment]
Hah, ugh. Ok, I knew this seemed familiar. Thank you.
