### ISSUE TITLE
my idea for the V86 Browser

### ISSUE THREAD

**Issue by jeffy79** [copy/v86#1096]
hey is it possible for the Supermium browser in v86 because i would love to watch YouTube vids as i use the browser thats my idea   and here's the Wikipedia page on Supermium by the way https://en.wikipedia.org/wiki/Supermium oh and the devs behind Supermium are planning to get Supermium working on windows 2000 btw so if they get that done can we use Supermium on windows 2000 on the v86 site  and here is a Supermium like thing for 9x based based windows by the way  https://youtu.be/xbeqLmSVqvs?si=0gu254HPnYNEfF9Q

**Comment by copy** [comment]
If they port supermin to Windows 2000, I'll add it to the image. Although I don't think the performance will be good enough to watch youtube videos.

Until then, let's close this issue.
