### ISSUE TITLE
Windows 95 sound support

### ISSUE THREAD

**Issue by jeffy79** [copy/v86#1101]
hey how come there is no sound for windows 95 are you able to add sound to it and the start up sound for windows 95 also has no sound at all can you fix that would be great

**Comment by copy** [comment]
Should be possible, Windows 95 detects our SB16 automatically.

**Comment by SuperMaxusa** [comment]
- download "Windows 95 and Windows 98 driver" for Soundblaster 16 from https://www.claunia.com/qemu/drivers/index.html
 - unzip archive and unpack all files from `sbw9xup.exe` as zip archive (the installer runs into MS-DOS mode which gives graphical artefacts)
 - copy driver files to blank floppy image (WinImage or https://askubuntu.com/a/484340)
 - mount floppy to VM and open Control Panel -> Add New Hardware Wizard
 - press Next, select No -> select "Sound, video and game controllers" 
 - select manufacture `Creative Labs` and model `Creative Labs Sound Blaster 16 or AWE-32`
 - press Finish -> press OK -> Copy from: `A:` -> "Do you want to restart your computer now?" -> No
 
Everything works except MIDI playback.

![win95-sb16](https://github.com/user-attachments/assets/8c148955-f591-426f-8e47-90113279d115)

**Comment by SuperMaxusa** [comment]
> what about sound for Windows NT 4.0

The driver is available, but the floppy drive doesn't work in this version.

**Comment by SuperMaxusa** [comment]
It works in updated profile, can we close this issue?
