### ISSUE TITLE
Why does Android x86 doesnt work?

### ISSUE THREAD

**Issue by Tubrolines** [copy/v86#1103]
<img width="712" alt="Capture" src="https://github.com/user-attachments/assets/605bd5dd-d5b0-4285-8687-6603ed4afb95">

hmm.. thats weird?

**Comment by SuperMaxusa** [comment]
It's a your custom image? If so, make sure that this image is bootable and not corrupted.

**Comment by spetterman66** [comment]
Because you have added the HDA as a CDROM image accidentally?

**Comment by Tubrolines** [comment]
nope, i didnt add any HDA and CDROM or custom image accidentally. All i just went to website and just clicked Android-x86

**Comment by SuperMaxusa** [comment]
Any messages in the DevTools log (F12 -> Console)? Also, try cleaning browser cache and try again.

**Comment by Tubrolines** [comment]
<img width="397" alt="Capture" src="https://github.com/user-attachments/assets/5fba6612-77da-4709-abf2-ae53753284a6">
ohh thats why!

**Comment by Tubrolines** [comment]
<img width="397" alt="Capture" src="https://github.com/user-attachments/assets/fac64f1c-0a3c-4709-b9da-1279a8f622fb">


ohh thats why!
