### ISSUE TITLE
lots of images are available by default, why only 26 listed on index?

### ISSUE THREAD

**Issue by ProgrammerIn-wonderland** [copy/v86#1106]
v86 has 81 images in https://github.com/copy/v86/blob/master/src/browser/main.js  (I counted them all because I'm crazy) but index.html only lists 26, maybe there should be a "other options" dropdown which lists all the options? I thought windows nt4 was quite cool and its sort of a bummer more people dont know about the other options

**Comment by spetterman66** [comment]
It's supposed to show a few highlights in the homepage, so people don't get overwhelmed by the amount of options there are. Yeah, an Other Options dropdown would be a great idea :)

**Comment by GavinGoGaming** [comment]
If you go to debug (/debug.html) on the site there are all of them, but it will show a ton of debug info

**Comment by copy** [comment]
I'm planning to redo the front page at some point (similar to https://winworldpc.com/library/operating-systems).

**Comment by ProgrammerIn-wonderland** [comment]
That would be lovely, on that note actually, a good friend of mine was suggesting adding removable/hotswappable CD images so you can transport more than just the current removable floppy's, might be something to consider adding if you do a redesign I think

**Comment by copy** [comment]
Done, thanks for the suggestion: https://copy.sh/v86/
