### ISSUE TITLE
Windows Me support

### ISSUE THREAD

**Issue by jeffy79** [copy/v86#1110]
would you be able to add Windows Millennium Edition to v86 or no ? just curious ofc

**Comment by copy** [comment]
Sure, could you provide a working (max 1GB) disk image?

**Comment by jeffy79** [comment]
i don't got one I was just curious if it would be possible to add windows ME to v86 thats all

**Comment by dylaniscool54** [comment]
install that on qemu raw .img disk and setup it up.

when its done boot it as a harddisk file in v86

**Comment by copy** [comment]
https://copy.sh/v86/?profile=windows-me
