### ISSUE TITLE
audio is sometimes blocked by the browser's autoplay detection

### ISSUE THREAD

**Issue by jeffy79** [copy/v86#1121]
this is on fire fox but for some reason the start up sound on windows 2000 it has sound and then for some reason on some days it does not have sound when i use it is there a fix for that ?

**Comment by copy** [comment]
The problem is probably this:

> The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page

It happens when you open the page without a "gesture" (e.g. by copy-pasting the url). The browser tries to prevent audio autoplaying. 

A fix would be to resume the audio context on the next event (e.g. click or key press). A PR would be welcome.

**Comment by dylaniscool54** [comment]
![image](https://github.com/user-attachments/assets/89c5b9fe-ce2c-44b1-8d9f-9f6eb52984c7)

https://developer.chrome.com/blog/autoplay/#webaudio

you need to create some sort of start button on your webpage before v86 is loaded.

**Comment by copy** [comment]
> you need to create some sort of start button on your webpage before v86 is loaded.

My suggestion would be to do it when clicking on the screen to lock the mouse.
