### ISSUE TITLE
[feature request] ZST support on disk images

### ISSUE THREAD

**Issue by Darin755** [copy/v86#1124]
Does v86 support using zst compression on raw disk images? As far as I can tell ZST only works on snapshots. I am trying to use hda with a disk image but the image is far to big for Github so I am looking to shrink it down. When I use ZST compression I get something that is approximately 7% of the original size. Is there any way I can boot from this image using compression?

**Comment by SuperMaxusa** [comment]
See https://github.com/copy/v86/commit/8aa33c70117a44e584dbbbb64e2fc360a62f8a29, you need to leave `.zst` at end of the file name and specify the original size in bytes.

```js
hda: {
    url: "hdd.img.zst",
    async: false,
    size: <mb> * 1024 * 1024
}
```

**Comment by Darin755** [comment]
> See [8aa33c7](https://github.com/copy/v86/commit/8aa33c70117a44e584dbbbb64e2fc360a62f8a29), you need to leave `.zst` at end of the file name and specify the original size in bytes.
> 
> ```js
> hda: {
>     url: "hdd.img.zst",
>     async: false,
>     size: <mb> * 1024 * 1024
> }
> ```

Thanks! Maybe that could be added to the docs at some point
