### ISSUE TITLE
a issue

### ISSUE THREAD

**Issue by jeffy79** [copy/v86#1128]
hey i think this just might be on fire fox but the boot versions of the windows computers but from windows 95 up to windows 2000 the start up screen is not working or even showing up at all or is the site just down in general ?

**Comment by copy** [comment]
Works for me, are you using the right url? Maybe your internet was wonky?

![Screenshot_2024-08-21_13-03-57](https://github.com/user-attachments/assets/971bedbe-8189-45a1-9e84-1d8fe0d2d94d)

**Comment by jeffy79** [comment]
well what URL are you talking bout bc the one i use is this for v86 https://copy.sh/v86/ and it works just fine and im on Ethernet and on fire fox and i tested it on chrome and even then it did not work on chrome so im guessing it must be a issue with the site rather than on my end
