### ISSUE TITLE
Save State fails on Linux 3.18 with 1GB of RAM

### ISSUE THREAD

**Issue by GasparYYC** [copy/v86#113]
Hi,
  Seems the Save state only works with a smaller memory footprint. Works fine with default size.
When I created a 1GB of RAM instance of Linux 3.18 the error in the Browser is: Failed - No File.

Thanks

**Comment by copy** [comment]
I think the browser is either refusing to write a large file or allocate a big buffer. Could you try running the following in a JavaScript console?

```javascript
function download(file_or_blob, name)
{
    var a = document.createElement("a");
    a["download"] = name;
    a.href = window.URL.createObjectURL(file_or_blob);
    a.dataset["downloadurl"] = ["application/octet-stream", a["download"], a.href].join(":");

    if(document.createEvent)
    {
        var ev = document.createEvent("MouseEvent");
        ev.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
        a.dispatchEvent(ev);
    }
    else
    {
        a.click();
    }
}
download(new Blob(new Uint8Array(1 << 30)), "test.bin")
```

If it doesn't work, it's unlikely that this can be fixed on our side.

**Comment by GasparYYC** [comment]
I have tested and the max limit for the "Save State" button to produce a file is 480 MB + 8 MB (video).
The js script did not work with the 480+8 for some reason, still returned the error:
``Uncaught TypeError: Failed to construct 'Blob': Array length exceeds supported limit.(…)
(anonymous function) @ VM340:19``

I did find a reference in Chronium that the limit is 500MB+1 byte which apparently is now fixed and in the main branch the ability to write much larger buffers to disk, so maybe Chrome will eventually do that.

**Comment by copy** [comment]
I thought so, I'll close this as it's not fixable on our side.
