### ISSUE TITLE
Error when trying to follow windows xp image creation docs with qemu

### ISSUE THREAD

**Issue by FunnyCorgi** [copy/v86#1130]
I was able to create a disk image using the first command, and I have the cdrom file in my directory, but when I try running the second command, I get this:
Unable to init server: Could not connect: Connection refused
gtk initialization failed

Can someone help me with configuring this image?

Note: I am installing to disk image in qemu on github codespace, and I believe I need the "-smp 2 --enable-kvm" to go through windows installation. Command used here:
sudo qemu-system-x86_64 -m 512 -smp 2 --enable-kvm -drive file=winxp.img,format=raw, -cdr
om en_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-73974.iso

EDIT: got image for cdrom with:
wget https://archive.org/download/WinXPProSP3x86/en_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-73974.iso

**Comment by FunnyCorgi** [comment]
When using the noted command for KVM I got the same output as the other command.

**Comment by FunnyCorgi** [comment]
Is the problem  that I haven't specified a port for KVM to use?

**Comment by Pixelsuft** [comment]
Try running without `sudo`

**Comment by FunnyCorgi** [comment]
That didn't fix it, i got this instead:
Unable to init server: Could not connect: Connection refused
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize KVM: Permission denied

**Comment by FunnyCorgi** [comment]
also tried running the command that doesn't use KVM with `sudo` but that didn't work either.

**Comment by Pixelsuft** [comment]
Try another display backend with something like `-display sdl`

**Comment by FunnyCorgi** [comment]
Ok, that sort of worked. now I get 
qemu-system-x86_64: Display 'sdl' is not available

**Comment by copy** [comment]
Are you running qemu in codespaces? There's probably no X server running in codespaces, so no screen to complete the installation. 

If you're on windows, you can use [qemu for windows](https://qemu.weilnetz.de/w64/), and use `-accel whpx` instead of `-enable-kvm`

**Comment by FunnyCorgi** [comment]
Ok, I'll try that.

**Comment by FunnyCorgi** [comment]
@copy can I just install the xauth package and do it that way?

**Comment by FunnyCorgi** [comment]
also @copy if i get this to work can I make a PR with it as a profile somehow?

**Comment by FunnyCorgi** [comment]
I installed xauth, and then ran it again, but it still didn't work. Should I just use WINE or something, or do I need actual windows?

**Comment by SuperMaxusa** [comment]
> If you're on windows, you can use [qemu for windows](https://qemu.weilnetz.de/w64/), and use `-accel whpx` instead of `-enable-kvm`

Small note from my experience: by default Windows XP with whpx very slow, to fix this press <kbd>F5</kbd> on Windows Setup (while loading drivers) and select "Advanced Configuration and Power Interface (ACPI) PC" (https://emulation.gametechwiki.com/index.php/Windows_2000/XP/Vista_emulators#Type_1_Hypervisors)
Also check your host Windows edition, Hyper-V is not available on Home Edition.

> Should I just use WINE or something, or do I need actual windows?

What is your host system?

**Comment by FunnyCorgi** [comment]
host system of wine install: ubuntu 22.04.4

**Comment by FunnyCorgi** [comment]
ok will do thank you!

**Comment by FunnyCorgi** [comment]
I got it working with a codespace! use https://git.mollomm1.dev/Mollomm1/DesktopOnCodespaces, and install qemu-system in the kvm after you use the instructions in on the linked page. Then the sea commands as on the docs!

**Comment by FunnyCorgi** [comment]
@SuperMaxusa & @copy  what cpu do I need to emulate because ACPI PC option does not show up for me, it says something like: `i486 computer, standard pc`

**Comment by FunnyCorgi** [comment]
It is seeming to be install normally(have gotten to graphical and "installing device" and "setup will complete in approximately 30 minutes."

**Comment by FunnyCorgi** [comment]
I  now have "13 minutes" left until the installation finishes. But I will say, performance on this system config with DesktopOnCodespaces is not great, and it started out with 39 minutes remaining, but it has literally(this is not a joke) been two hours.
