### ISSUE TITLE
Request: option to insert cd rom while running?

### ISSUE THREAD

**Issue by FunnyCorgi** [copy/v86#1137]
I have found that if I am trying to start my windows XP image, and I put a cd from with files on it to see if I could browse it in the windows XP in v86, but if I put the cdrom and HDD image in the setup menu, then start, it seems to get confused and windows XP doesn't boot. It just stays saying "Booting from Hard Disk."

**Comment by chschnell** [comment]
This is a duplicate of PR #901.

**Comment by FunnyCorgi** [comment]
Oh it is? Sorry I didn't know. =)
