### ISSUE TITLE
possible Protoweb support for v86 ?

### ISSUE THREAD

**Issue by jeffy79** [copy/v86#1138]
@copy will v86 ever get support for Protoweb bc that would sure be great please

**Comment by SuperMaxusa** [comment]
You can set the proxy manually in a VM: https://protoweb.org/wiki/internet-explorer-3-0/, it worked for me without any problems a few months ago.

**Comment by jeffy79** [comment]
Protoweb works on v86 and thanks for the help but warp stream does not seem to work on v86 what do i need to do on v86 to make it work ?

**Comment by SuperMaxusa** [comment]
For me, Flash Player doesn't work, even with decreasing the security level in Internet Explorer, RealPlayer works fine (you can switch in the rating panel, see the support page for setup), Windows Media Player also works but crashes after 10 seconds,

 ![realplayer-w2k](https://github.com/user-attachments/assets/4c99dbee-d716-4d86-9e5d-6f2aaa778179)

**Comment by jeffy79** [comment]
well what URL are you talking bout bc the one i use is this for v86 https://copy.sh/v86/ and it works just fine and im on Ethernet and on fire fox and i tested it on chrome the boot versions that is and even then it did not work on chrome so im guessing it must be a issue with the site rather than on my end and this is the issue im having btw see when ever i go on to the boot versions of windows 9x and windows 2000
![363249943-b94eb8a6-f719-4010-b046-6ce2c88028b3](https://github.com/user-attachments/assets/462a1380-262a-4d27-b51f-10cd1eaac37a)

**Comment by jeffy79** [comment]
is this supposed to happen with the boot verions @SuperMaxusa or what

**Comment by SuperMaxusa** [comment]
That image you have taken from "Take screenshot" button? Have you checked the browser console errors (press <kbd>F12</kbd> -> tab "Console") in both browsers?

Closer to the issue, I used the "Windows 2000" profile (not `windows2000-boot`) from the main page.

**Comment by jeffy79** [comment]
hey super do you use discord at all or no ?

**Comment by SuperMaxusa** [comment]
Sorry, I'm a busy now and can't help you individually, however I have a step-by-step guide for you:

 - run `networking.bat` and then start Internet Explorer
 - click "Tools" -> "Internet Options" -> "Connections" -> "Local Area Network (LAN) settings" -> "Use a proxy server"
 - type the proxy address and port from https://protoweb.org/wiki/servers/
 - in Internet Explorer, go to `http://www.warpstream.net/support/winxp.html` and follow the "RealPlayer Setup Guide" (it's about 5 MB to download, so be patient)
 - After installing and configuring RealPlayer, go to the WarpStream home page, select a video, near "Rating" select quality (note: the default proxy in v86 has a speed limit of 40 KB), personally I tested a "56K Modem" quality.
 
You can also build your own Windows 2000 image and run unlocked by speed websockproxy (see documentation in Readme) to make this easier.

**Comment by jeffy79** [comment]
i know how to do the real player thing after some trial and error my self super also do you have a discord super or no ?

**Comment by copy** [comment]
Let's close this as everything seems to be working as expected.

**Comment by SuperMaxusa** [comment]
@jeffy79 I rarely check my Discord, feel free join to our [Gitter chat](https://gitter.im/copy/v86), I'm there too.
