### ISSUE TITLE
Invalid memory size

### ISSUE THREAD

**Issue by PierrickI3** [copy/v86#114]
I am trying to load my own img file (windows 10) but when I use your demo web site at http://copy.sh/v86/ and set the memory to 2048 MB and the video memory to 128 MB, a message dialog appears and says "invalid memory size - ignored" and then it boots the img (but unfortunately, it complains that there isn't enough memory to create a ramdisk).

What are the valid memory sizes?

I am using Chrome 53.0.2785.116 on a PC with 16GB of RAM.

**Comment by copy** [comment]
Memory size must be below 2048MB due to how signed JavaScript numbers work (see `2048 * Math.pow(2, 20) | 0`). In this case it should probably be handled more gracefully by using the biggest possible value instead.

**Comment by DaniellPlasmmer** [comment]
Can node.js fix that limit?
