### ISSUE TITLE
Could you make a new URL and Make it not blockable cause its blocked by lightspeed thanks!

### ISSUE THREAD

**Issue by bahabryra** [copy/v86#1141]
Could you make a new URL and Make it not blockable cause its blocked by lightspeed thanks!

**Comment by bahabryra** [comment]
and also Can I help

**Comment by ProgrammerIn-wonderland** [comment]
This isn't copy's responsibility. If you believe the website to be falsely blocked by your web filter, please file a report at https://archive.lightspeedsystems.com/

**Comment by dylaniscool54** [comment]
use a vpn

**Comment by copy** [comment]
Let's close this as there's nothing to on v86's side.

**Comment by bahabryra** [comment]
sorry :(
