### ISSUE TITLE
windows 10/11 support

### ISSUE THREAD

**Issue by bahabryra** [copy/v86#1148]
just wondering would it be able to handle windows 10 and 11 Ill give you the disk images if needed

**Comment by bahabryra** [comment]
also does this run on github pages with the docker workflow???

**Comment by bahabryra** [comment]
one more thing can I help I would love to be a collaberator

**Comment by SuperMaxusa** [comment]
> would it be able to handle windows 10 and 11

No, for Windows 10 it's lack of NX-bit, Windows 11 requires 64-bit mode, which is not supported in v86 (and SSE4.2 for new builds).

> also does this run on github pages with the docker workflow???

I think yes, it works on GitHub Pages without problems

> one more thing can I help I would love to be a collaberator

See #537 and https://github.com/copy/v86/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by bahabryra** [comment]
can I be a collaberator

**Comment by bahabryra** [comment]
please

**Comment by bahabryra** [comment]
it doesent say anything about collaberator???

**Comment by copy** [comment]
Let's close this in favor of #845. Note that this is currently not planted, and as far as I know nobody is working on it.
