### ISSUE TITLE
booting my own assembly program that I compiled fails with "boot failed: could not read the boot device"

### ISSUE THREAD

**Issue by FunnyCorgi** [copy/v86#1158]
i have an assembly program that prints out "Hello, Felix"(Felix being the name of one of my close friends) I compiled with nasm and runs fine in qemu, but is refuses to boot in v86. Files(compiled and asm) are attached.
[Hello_felix_assembly.zip](https://github.com/user-attachments/files/17033306/Hello_felix_assembly.zip)

**Comment by SuperMaxusa** [comment]
How do you mount your program in v86? It works for me when I select the binary file as the floppy image

https://github.com/copy/v86/blob/58d43361499d65e24295b20cb3857f123e261337/src/floppy.js#L97-L98

**Comment by FunnyCorgi** [comment]
Oh, I'll try that. I was doing it on the HDD.

**Comment by FunnyCorgi** [comment]
Your right! It did work. Thank you!
