### ISSUE TITLE
Networking not working.

### ISSUE THREAD

**Issue by simpleuserdontwatch** [copy/v86#1167]
I am trying to get networking working on Alpine Linux (v86)
But, when i try to run the network.sh file, it gives me this
![image](https://github.com/user-attachments/assets/1023a510-776d-4f54-b299-90770bd031dd)
Please fix it.

Version: lastest
Image: [https://drive.google.com/file/d/1SHGoeEyAE8t17SYV4FSqs_4RO0dMhEm8/view?usp=drive_link](Right here!)

**Comment by simpleuserdontwatch** [comment]
for some reason, github didnt want to format the link :/

**Comment by SuperMaxusa** [comment]
Have you set the URL for WebSocket/wisp relay? (see [docs/networking.md](https://github.com/copy/v86/blob/master/docs/networking.md))
```js
net_device: {
    type: "ne2k",
    relay_url: <"ws(s)://...", "wisp(s)://..." or "fetch">,
},
```

Also any error messages in browser console (press F12 -> Console)?

**Comment by simpleuserdontwatch** [comment]
> Have you set the URL for WebSocket/wisp relay? (see [docs/networking.md](https://github.com/copy/v86/blob/master/docs/networking.md))
> 
> ```js
> net_device: {
>     type: "ne2k",
>     relay_url: <"ws(s)://...", "wisp(s)://..." or "fetch">,
> },
> ```
> 
> Also any error messages in browser console (press F12 -> Console)?

Still nothing.
![image](https://github.com/user-attachments/assets/50d0d704-4aac-4163-865c-a8cb3aa39029)
![image](https://github.com/user-attachments/assets/06b7f2a8-451e-47aa-9531-5e11c6c7ba3a)
