### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by yonas** [copy/v86#117]
During boot, the following crash occurs:

`panic: bad APIC LVT delivery mode: 0xffffdfef`

Tested today, November 21, 2016, with `FreeBSD-11.0-RELEASE-i386-bootonly.iso`

![screenshot from 2016-11-21 14-32-29](https://cloud.githubusercontent.com/assets/110130/20497957/3448e7be-aff9-11e6-87a8-79e402be2b6f.png)

**Comment by copy** [comment]
This works now, took some time to update the website. Also: http://copy.sh/v86/?profile=freebsd

**Comment by yonas** [comment]
@copy Awesome, thanks!
