### ISSUE TITLE
Website in normal mode cannot load emulation due to a missing HTML element

### ISSUE THREAD

**Issue by Ponali** [copy/v86#1173]
V86 Version: [c9041eb4](https://github.com/copy/v86/commits/c9041eb4) (Oct 20, 2024 21:10)

I am running on Arch Linux, and this bug only seems to work on Chrome (flatpak). Brave (flatpak) and Firefox (pacman) does not seem to have this issue.
The version of Chrome i'm using is "Version 129.0.6668.100 (Official Build) (64-bit)".

No specific OS or disk image is relevant, i've checked.

This issue doesn't happen when in debug.html, only when in normal mode, so finding this issue's error code was from going to the DevTools console.

---
I had to go through some hoops because the code used was minified, but here is a very nerdy and in-depth explanation of what I can gather:

I have copy pasted the error in case this would help:
```
Uncaught TypeError: Cannot read properties of null (reading 'value')
    at e (v86_all.js:51:197)
    at r (v86_all.js:26:118)
    at d (v86_all.js:48:430)
e @ v86_all.js:51
r @ v86_all.js:26
d @ v86_all.js:48
load
(anonymous) @ v86_all.js:71
(anonymous) @ v86_all.js:72
```

NOTE: Either it's thanks to a very useful Chrome/Chromium feature, or the website code wasn't minified properly, I can see a beautified version of the code, which is why there are Space, End of Line and Tab characters scattered everywhere.

Going into the source code (v86_all.js:51) let me to find that the following code was faulty:
`c("video_memory_size").value`
This happened because the output value of `c("video_memory_size")` was `null`.

Going to the definition of said function `c` led me to find it was an alias of `document.getElementById`:
```
function c(r) {
        return document.getElementById(r)
}
```

---
This basically boils down to this:

The script tries to find a supposed DOM element with its "id" attribute being `video_memory_size`, and getting its value, but because such DOM element doesn't exist, it freaks out and returns an error, since it's obviously impossible to retrieve a value from nothing.

One way this could get fixed is to first check if such DOM element exists before retrieving its value (e.g. if statement) or simply adding a try-catch statement of where this occurs and handle the error with something else.

**Comment by copy** [comment]
The element has been renamed in ca7fe7542c58ba00ea4cf8edb64ed63161b07f42 (both in the html and the js). You probably have a cached version of the js.

I've renamed the js file, so hopefully a browser that reloads the html will also pick up the new js file.

**Comment by Ponali** [comment]
I can confirm this might have been a cached JavaScript file, I saw that upon you renamed it, more content appeared on that file.
The website now operates fine without any notable issues or errors, so thanks for the help.
