### ISSUE TITLE
Add new DSL (Damn Small Linux) ISOs

### ISSUE THREAD

**Issue by randompersononinternet69** [copy/v86#1174]
I only saw one DSL on here, and I have 3 ISOs of other versions of DSL:
* [Damn Small Linux Core](https://distro.ibiblio.org/damnsmall/dslcore/dslcore_alpha.iso)
* [Damn Small Linux New (not really new, it's old too)](https://distro.ibiblio.org/damnsmall/dsl-n/current/dsl-n-01RC4.iso)
* [Damn Small Linux 2024](https://damnsmalllinux.org/2024-download.html)

**Comment by copy** [comment]
The first two are not sufficiently different/interesting compared to the existing DSL image.

DSL 2024 is cool, but it's also very bloated, downloading more than 150 MB in the boot process and taking over 3 minutes to boot.
