### ISSUE TITLE
MS-DOS 6 fails setup with "can't write to disk" error

### ISSUE THREAD

**Issue by DarkKnight64** [copy/v86#118]
Setup used:
copy.sh
Blank .VDI hard disk file
MS-DOS 6.0 Disk 01 acquired from winworldpc.com - works fine on vbox.
Latest commit (Nov 22 2016)
- The first setup disk boots. Looks weird at the bottom.
- As soon as Setup asks to "configure disk" pressing Y will give an error and throws user to the local copy of DOS on Setup Disk 1.

**Comment by Wasserboy08** [comment]
maybe the vdi file wasnt working on copy.sh?

**Comment by DarkKnight64** [comment]
Perhaps, but what files does copy.sh take?

**Comment by copy** [comment]
> Perhaps, but what files does copy.sh take?

We only support raw disk images at the moment. You can convert between the formats using `qemu-img`.

**Comment by copy** [comment]
Can't reproduce. I'll upload an MS-DOS image soon.
