### ISSUE TITLE
Can't boot Windows NT 3.1

### ISSUE THREAD

**Issue by SmallBOX-tech** [copy/v86#1183]
Help! Why I can't boot Windows NT 3.1? Can anybody help me?

Version v86: c9041eb4
Browser: Chrome/macOS

![Uploading Screenshot 2024-11-15 at 11.31.30.png…]()

(The BSOD and the console)

But, when I test the provided Windows NT 3.1, it just booted successfully, why it can happen?

**Comment by SuperMaxusa** [comment]
Your screenshot is not showing, can you reupload it?

**Comment by SmallBOX-tech** [comment]
![Uploading Screenshot 2024-11-15 at 11.31.30.png…]()

**Comment by SmallBOX-tech** [comment]
<img width="1440" alt="Screenshot 2024-11-15 at 11 31 30" src="https://github.com/user-attachments/assets/49081557-097c-4e89-96f7-ad7409c71584">

**Comment by SmallBOX-tech** [comment]
Can you see it?

**Comment by Pixelsuft** [comment]
Install using QEMU, without ACPI/APIC support and likely without CDROM (copy files to hard drive, run installation from ms-dos) (otherwise it MAY bsod with inaccessible_boot_device code). This configuration should work.

**Comment by SmallBOX-tech** [comment]
Ok I'll try

**Comment by SmallBOX-tech** [comment]
> > Can you see it?
> 
> Yes, thank you.
> 
> Did you install using QEMU or another emulator/virtual machine?

I try instaling it using v86, but it just shows that error

**Comment by SuperMaxusa** [comment]
> I try instaling it using v86, but it just shows that error

I think it's better to install using QEMU, not v86, as suggested earlier. I used this guide for Windows NT 3.1 installation a while ago: https://gunkies.org/wiki/Installing_Windows_NT_3.1_on_Qemu, it doesn't use CDROM either, you can skip steps about mouse and network drivers.

**Comment by SmallBOX-tech** [comment]
Ok thanks for the suggestion

**Comment by SmallBOX-tech** [comment]
But strangely, the beta version Windows NT 3.1 just worked fine (specifically build 438)

**Comment by SmallBOX-tech** [comment]
![Uploading Screenshot 2024-11-19 at 07.47.30.png…]()

**Comment by SmallBOX-tech** [comment]
<img width="1440" alt="Screenshot 2024-11-19 at 07 47 30" src="https://github.com/user-attachments/assets/3c6b2826-a6de-4bdf-9707-d8c851e446d9">

**Comment by SmallBOX-tech** [comment]
Why the beta version of Windows NT 3.1 can work, but the final version aren't?

**Comment by SuperMaxusa** [comment]
I got a working Windows NT 3.1 Workstation, it seems that `PROCESS1_INITIALIZATION_FAILED` BSOD can appear if you incorrectly configurated the hard drive in emulator (for example, system was installed on primary hard drive, but on v86 that image installed as secondary hard drive). 

I installed MS-DOS in QEMU, copied all the files from the installation CD and `winnt /F /C`. Command for QEMU:
```sh
qemu-system-i386 -m 64 -hda harddrive.img -cdrom install_cd.iso
```

![winnt31](https://github.com/user-attachments/assets/f83e0b82-da3e-4bb5-8a8f-e1cae2762c58)

**Comment by SmallBOX-tech** [comment]
Ok, i'll try it. But can you give me the link of the hard disk?

**Comment by SuperMaxusa** [comment]
> can you give me the link of the hard disk?

Sorry, I don't have the opportunity to upload it at this moment.

**Comment by SmallBOX-tech** [comment]
That's okay. But thank for the suggestion.
