### ISSUE TITLE
Allow to embed CORS proxy URL in "fetch" relay_url

### ISSUE THREAD

**Issue by chschnell** [copy/v86#1188]
https://github.com/copy/v86/blob/298da237c2e8ae3b605ab60a5f873884a96ed054/src/browser/starter.js#L314-L317

My suggestion would be to change this to:

```javascript
if(relay_url.startsWith("fetch")) {
    const fetch_options = {};
    if(relay_url.length > 6 && relay_url[5] === ":") {
        fetch_options.cors_proxy = relay_url.slice(6);
    }
    this.network_adapter = new FetchNetworkAdapter(this.bus, fetch_options);
}
```

Things would behave as before when passing only `fetch` to `config.net_device.relay_url`, but when passing something like:

```
fetch:https://example.com/?url=
```

then CORS proxy `https://example.com/?url=` would be used.

**Comment by copy** [comment]
Cheers!
