### ISSUE TITLE
Lags with mouse

### ISSUE THREAD

**Issue by m-emelchenkov** [copy/v86#119]
Mouse cursors are not synchronised, so seriously that can't be really usable. OS macOS Sierra, browser Safari 10.0.1.

**Comment by m-emelchenkov** [comment]
Checked with Chrome—the same fail.

**Comment by m-emelchenkov** [comment]
A friend just checked on his Mac—works well. Probably depends on CPU speed? Need a fix anyway, sometime :) Cool thing bro, anyway!

**Comment by copy** [comment]
Click on the screen with the browser's cursor or try the lock mouse button. Does this work?

Unfortunately there's no better solution for this, the emulator can only send relative mouse movements to the OS (i.e., move mouse by 3, not set mouse position to 3).

**Comment by m-emelchenkov** [comment]
I tried clicking, nothing changes. To better understand what happens, please look this screencast which I recorded for you. (Sorry, it's packed because GitHub do not allow to upload video files).

[Bugreport.mp4.zip](https://github.com/copy/v86/files/619590/Bugreport.mp4.zip)

**Comment by copy** [comment]
The pointer lock api isn't supported in Safari. try using the lock mouse button in Chrome again.

**Comment by m-emelchenkov** [comment]
Works fine in Chrome! Thank you!
