### ISSUE TITLE
GPU paravirtualization with WebGL rendering

### ISSUE THREAD

**Issue by brion** [copy/v86#120]
This may sound a bit out there, but I'm interested in being able to run things like a modern Linux GNOME desktop, which involves a lot of OpenGL rendering and pixel pushing -- things that will be very slow when emulated in software that's itself an emulator running in a JIT. :)

Current QEMU versions support GPU paravirtualization using libvirt-gpu / virgl3d, with suitable guest-side Linux drivers upstreamed and available in for instance Fedora 24. This exposes a virtual device through which low-level commands inside the Mesa 3D driver are serialized and sent through to the host side, where they are rendered with OpenGL backing.

It should be possible to expose the same virtual gpu interface as QEMU to be picked up by the guest-side drivers, and do rendering via WebGL which is a variant of OpenGL ES.

It may be possible to use emscripten to cross-compile the existing virgl3d renderer; alternately it should be possible to write a native JS/WebGL renderer.

I'd be interested in experimenting with this but am not sure how feasible it will be. :)

References:
* https://virgil3d.github.io
* https://youtu.be/pSYQIyICwu4

**Comment by copy** [comment]
This is a quite interesting idea. We've already discussed virtio-gpu support a bit in #51.

Virtio is already supported (only for virtio-9p), so the first step would be adding virtio-gpu support. Even the 2D API could improve performance quite a bit. The real issue I see is translating graphic commands (efficiently) to WebGL for the 3D part. I can't predict how feasible this will be.

One thing to keep in mind that the CPU performance of the emulator – even modulo rendering – is quite slow. There's a benchmark in the Arch Linux image if you want to get an idea. I do intend to improve the CPU performance for some real world use-cases next year, so some contributions on the graphics side would play into my hands.

If you're interested in working on this, I'd certainly help you on the emulator side.

**Comment by brion** [comment]
Ah great, I missed that issue when looking. :) Closing this issue out in preference.

It might be possible to cross-compile the existing C virglrenderer (which used by QEMU) to JS with emscripten as a first pass test. Probably depends largely how scary the OpenGL stuff it does is, and whether it requires shader features that can't be easily done in WebGL...

I'll do some more research on it and see if it makes sense, but simpler acceleration is probably a bigger priority.

(On the CPU speed front I have some crazy ideas for dynamic translation of runs of code into JS functions, sort of a mish-mash of techniques from QEMU and emscripten. Might not go anywhere but it's fun research.)
