### ISSUE TITLE
Cant set RAM higher then 900mb

### ISSUE THREAD

**Issue by Wasserboy08** [copy/v86#121]
when i try to run somthing with more then 800 or 900 mb of ram its loading images forever

**Comment by copy** [comment]
I can't reproduce this. How much RAM does your host machine have? Are there any messages in the browser console (press F12 to open it)? Can you run the following in the browser console: `new Uint8Array(1024 * 1024 * 1024)`

**Comment by Wasserboy08** [comment]
my machine has 4gigs of ram [32-bit]

**Comment by jadr2ddude** [comment]
Click run on this: http://www.w3schools.com/code/tryit.asp?filename=FBHB1SZEG7IM

**Comment by warpcoil** [comment]
@jadr2ddude Don't click on "run this", by using alert(new Uint8Array(1024 * 1024 * 1024)), you will crash the browser.

A better approach would be

`var x = new Uint8Array(1024 * 1024 * 1024);
alert(x.length);`

**Comment by Wasserboy08** [comment]
Error: uncaguht  RangeError

**Comment by jadr2ddude** [comment]
Invaid typed array length?

**Comment by jadr2ddude** [comment]
@warpcoil hmm? Doesnt crash mine

**Comment by jadr2ddude** [comment]
Ok. So that means that is not a problem with v86. It is above the max size supported by your browser.

**Comment by copy** [comment]
> Ok. It appears that this is a bug with chrome. Can close this issue since it is not a problem with v86.

This is also my conclusion.
