### ISSUE TITLE
Links on copy.sh doesn't work anymore

### ISSUE THREAD

**Issue by jonasandero** [copy/v86#124]
For example, https://copy.sh/v86/?profile=linux3 says 

> Loading //i.copy.sh/images/linux3.iso failed. Check your connection and reload the page to try again.

**Comment by copy** [comment]
I can't reproduce the problem, do you have access to this file? https://i.copy.sh/images/linux3.iso

**Comment by copy** [comment]
Closed as can't reproduce.
