### ISSUE TITLE
Multitasking

### ISSUE THREAD

**Issue by SpaceboyRoss01** [copy/v86#130]
I'm working on my own os in c++ and I've noticed in this emulator's cpu that there is a function called do_task_switch. How to I trigger the call?

**Comment by jadr2ddude** [comment]
This is done via x86 instructions. Here is an article I found: http://samwho.co.uk/blog/2013/06/01/context-switching-on-x86

**Comment by copy** [comment]
What @jadr2ddude wrote is correct, particular `do_task_switch` will do a hardware context switch, but you probably want software context switching for reasons mentioned in the article.

Hardware context switch isn't fully implemented in v86 and not used by most operating systems.
