### ISSUE TITLE
need improve the arch image and make mirror site

### ISSUE THREAD

**Issue by jyf007** [copy/v86#136]
i.copy.sh/arch/ i wanna this path as a squanshfs image to mount ,and make a mirror of v86 site.
and add network to arch linux
or make ?profile=linux3 add openssh (sftp is prefer )or dropbear.

**Comment by copy** [comment]
Use this to build a small Linux image with openssh: https://buildroot.org/

The Arch Linux still supports networking, use the following commands: `ifconfig enp0s5 down; rmmod ne2k-pci; modprobe ne2k-pci; ifconfig eth0 up; dhcpcd -w4 eth0`
