### ISSUE TITLE
Add ReactOS to Quickstart

### ISSUE THREAD

**Issue by CSRedRat** [copy/v86#137]
Please add http://ReactOS.org to Quickstart on https://copy.sh/v86/
It's work fine :)

**Comment by copy** [comment]
Indeed, I'll do this soon.

**Comment by copy** [comment]
Here you go: https://copy.sh/v86/?profile=reactos

It seems to be quite slow, if you have any idea how to make it faster (disable background processes?), let me know.

**Comment by CSRedRat** [comment]
ReactOS was hung after boot and Start -> Programs

**Comment by binarymaster** [comment]
![image](https://cloud.githubusercontent.com/assets/578406/23946463/8d48f570-098b-11e7-8a6c-ab9166151fd5.png)

There is a minor issue with OS name, it should be without space, like FreeBSD or KolibriOS.

**Comment by copy** [comment]
@binarymaster Will fix, thanks.

@CSRedRat I'm aware of this issue. It happens randomly, but I'm not sure how to fix it yet. It's related to this error:

```
(drivers/filesystems/cdfs/fsctl.c:469) CdfsVerifyVolume() called
(drivers/filesystems/cdfs/fsctl.c:488) Device object B0231E20  Device to verify B02355A0
(drivers/filesystems/cdfs/fsctl.c:497) Same volume!
(drivers/filesystems/cdfs/common.c:120) Failed to read after successful verify, aborting
```
