### ISSUE TITLE
I need to step to step build your project.

### ISSUE THREAD

**Issue by thanhchinhvn** [copy/v86#140]
I follow this. 
# grab the main repo
git clone https://github.com/copy/v86.git && cd v86

# grab the disk images
wget -P images/ https://copy.sh/v86/images/{linux.iso,linux3.iso,kolibri.img,windows101.img,os8.dsk,freedos722.img,openbsd.img}

# grab closure compiler
wget -P closure-compiler https://dl.google.com/closure-compiler/compiler-latest.zip
unzip -d closure-compiler closure-compiler/compiler-latest.zip compiler.jar

# build the library
make build/libv86.js

# run the tests
./tests/full/run.js

**I have a error** 

[root@localhost v86]# node tests/full/run.js 

/root/v86/tests/full/run.js:194
    function send_work_to_worker(worker, message)
    ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/root/v86/tests/full/run.js:186
        tests = tests.filter(test => test.name === TEST_NAME);
                                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/root/v86/tests/full/run.js:194
    function send_work_to_worker(worker, message)
    ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**How can i troubleshot it?**
**Thanks**

**Comment by copy** [comment]
This is a bug. What's your node version?

As a temporary workaround, remove [this line](https://github.com/copy/v86/blob/27f8afffac56e7fbd951490c51a691580958daf7/tests/full/run.js) and try again.

**Comment by thanhchinhvn** [comment]
Thanks so much, It run. But i don't know run it with brower. How can i run it with web service?

**Comment by copy** [comment]
Run `make build/libv86.js` and open the examples in the examples folder.

**Comment by thanhchinhvn** [comment]
Sincerely thanks, 
I follow your tips, i run v86 by "Python's SimpleHTTPServer" and web run but i had a problem when i chose run one image. It failed.
**"Loading //i.copy.sh/images/freedos722.img failed. Check your connection and reload the page to try
 again."**
How i change **url //i.copy.sh/images/ to my local //../images/?**

**Comment by copy** [comment]
What hostname are you on? [Current detection](https://github.com/copy/v86/blob/fee07cc8b33dc41df3eb8751558efc1fbf920170/src/browser/main.js#L6) checks if it contains a dot, which fails for `127.0.0.1`, for example.

**Comment by thanhchinhvn** [comment]
**Hostname=Test** and i changed     /** @const */
    var ON_LOCALHOST = location.host.indexOf(".") === -1;

    /** @const */
    var HOST = ON_LOCALHOST ? "" : "//127.0.0.1/"; but it not work and i try chang **//127.0.0.1:8000/** it not work **"Loading //i.copy.sh/images/freedos722.img failed. Check your connection and reload the page to try
again."** how can i run it?

I use command root@Test:~''v86$ python -m SimpleHTTPServer

**Comment by copy** [comment]
Open `debug.html`. Or run `make`.

**Comment by thanhchinhvn** [comment]
Thank so much!!!
