### ISSUE TITLE
KolibriOS link dont work

### ISSUE THREAD

**Issue by DartPower** [copy/v86#141]
This link to image is broken, but file is downloading successfully
https://copy.sh/v86/?profile=kolibrios

Error:
![image](https://cloud.githubusercontent.com/assets/2005369/24082406/181f944a-0cd6-11e7-877d-b6ae9e17eac7.png)

Downloads:
![image](https://cloud.githubusercontent.com/assets/2005369/24082408/228f6586-0cd6-11e7-9374-dc42236585f3.png)

**Comment by jadr2ddude** [comment]
Can you look at the browser console for errors?

**Comment by DartPower** [comment]
![image](https://cloud.githubusercontent.com/assets/2005369/24083807/5ac6c35e-0cef-11e7-92df-c4c65ce1c9f5.png)

Opera 43.0.2442.1144

**Comment by copy** [comment]
Thanks for reporting. You can use this as a fallback for now: http://copy.sh/v86/?profile=kolibrios

@XVilka @yogev1978 Can one of you set up https on builds.kolibrios.org so that this url works: https://builds.kolibrios.org/eng/data/data/kolibri.img

**Comment by copy** [comment]
Here's a fallback with https: https://copy.sh/v86/?profile=kolibrios-fallback

**Comment by copy** [comment]
Fixed by temporarily loading from my server on https.
