### ISSUE TITLE
Producing archlinux-like snapshot

### ISSUE THREAD

**Issue by ChrisJefferson** [copy/v86#142]
Hi,

I work on an open-source maths project ( www.gap-system.org ), and I'd love to be able to provide an interface for users to try. I'd like to based off the 'Arch Linux' example, as it loads fast, but I can't figure out how the snapshot was generated, so I can make a new one with my own extra program inserted (because I know how to build it easily in Arch Linux). Is there any kind of guide anywhere to how this snapshot was created?

**Comment by copy** [comment]
There's a *save state* button in the user interface. There's an example of using the API [here](https://github.com/copy/v86/blob/master/examples/save_restore.html) and it's documented [here](https://github.com/copy/v86/blob/master/docs/api.md#restore_statearraybuffer-state).

The disk image is a normal installation that was created using QEMU.

**Comment by ChrisJefferson** [comment]
Thanks for the QEMU pointer. The arch-linux example is also doing something else special, where it is getting files off the filesystem by http, from `i.copy.sh`. Is that explained somewhere obvious I've missed (sorry if a bug report isn't really the place to ask this kind of thing)

**Comment by copy** [comment]
Yes, when you pass a [filesystem configuration](https://github.com/copy/v86/blob/master/docs/filesystem.md) to v86, you can mount the filesystem in Linux using `mount host9p -t 9p /mnt`.

In the Arch Linux image on copy.sh, we mounted the root filesystem using 9p during boot, so all files are loaded from there and no accesses to the raw disk image are necessary. This is documented [here](https://github.com/copy/v86/blob/master/docs/linux-9p-image.md#using-initcpio). This is just an optimisation, Arch Linux could also boot normally.

**Comment by copy** [comment]
Feel free to reopen if you have more questions.
