### ISSUE TITLE
Minix 2 8086 doesn't boot

### ISSUE THREAD

**Issue by davidgiven** [copy/v86#145]
Hey, some of the source code has timestamps in this century, of course it's still relevant!

The boot loader works, but once the kernel loads then it hangs with the processor status saying 'Speed: 0 kIPS'. No idea what's going on.

If you're interested, I enclose a boot floppy image. Follow the obvious prompt at the boot menu --- when it works you should get some messages and then a login prompt.

[minix2.zip](https://github.com/copy/v86/files/880285/minix2.zip)

For reference, I want to host some slightly modernised images for Minix 2 on my website, and am looking for an emulator so that people can try them in their browser.

**Comment by davidgiven** [comment]
Update: after having spotted the bug about missing 286 features, I suddenly remembered that while it's all 8086 code, it autodetects processor features and will use extended features for more memory. Then I found the debug version. Yes, it's printing 'Unimplemented: 286 tss' and freezing, so that's the same bug.

But it's also possible to tell Minix not to use these features. It still doesn't work, but differently. Press ESC at the boot prompt, then type 'processor=86', then 'boot'. It prints a few messages and then hangs, but this time the CPU is spinning rather than stalled, and no messages appear on the debug console.

**Comment by copy** [comment]
It would indeed be pretty cool to get this running.

> But it's also possible to tell Minix not to use these features. It still doesn't work, but differently. Press ESC at the boot prompt, then type 'processor=86', then 'boot'. It prints a few messages and then hangs, but this time the CPU is spinning rather than stalled, and no messages appear on the debug console.

It seems that QEMU has the same problem. Maybe Seabios doesn't support such old operating systems? Which emulator/configuration boots this image?

**Comment by davidgiven** [comment]
qemu fails, but differently (you get lots of I/O errors, right?) I haven't tracked that one down yet, but I think the minix fdd driver is doing something a bit nonstandard. I see a similar problem in pcjs. qemu boots it quite happily from a hard disk image, and I've attached a vmdk for it. It's pretty much the same as the floppy disk image, but installed onto an empty hard drive.

[minix2hd.zip](https://github.com/copy/v86/files/880521/minix2hd.zip)

Floppy boot does work in virtualbox, as well as real hardware of course, which makes me think that it's not *entirely* Minix's fault.

I think the hang on boot is something entirely different, though.

**Comment by copy** [comment]
@davidgiven The Minix HD image now boots successfully in v86.

I probably won't be looking into the FD issues.

**Comment by davidgiven** [comment]
Awesome --- thanks!
