### ISSUE TITLE
hdd regression: status DRDY

### ISSUE THREAD

**Issue by vdloo** [copy/v86#151]
Hi,

I noticed that somewhere between commit 77e91283b6639b608a2681091c7b68a5563c8075 and the current trunk (74d2170d53b001453356bf934829469990dbd9bc) something has broken relating to loading the hard drive. I'm using an Archlinux image that I've built with [these scripts](https://github.com/vdloo/archlinux-v86-builder/tree/c90ca7389813e5d83e34b9d9998b8d62aae096fe).

On the older branch the image booted OK:
![noerror](https://cloud.githubusercontent.com/assets/1437341/25559465/fa29ffb8-2d3a-11e7-9673-c64829560f4b.png)

On the newer branch it fails right after loading the initial ramdisk using the same image:
![drdy](https://cloud.githubusercontent.com/assets/1437341/25559470/08caf298-2d3b-11e7-951f-5dfc759e65c1.png)

This image does not use a 9p filesystem and it's booting from a raw qemu hard disk image, not a saved state.

**Comment by copy** [comment]
Thanks for the report!
