### ISSUE TITLE
Setting RAM and VRAM for default Operating Systems

### ISSUE THREAD

**Issue by chantheman1288** [copy/v86#158]
It would be really nice if the homepage of your copy.sh/v86 allowed you to change the amount of RAM the default listed operating systems have, so when you opened Windows 98, for example, you could input the amount of RAM and VRAM you want it to have before starting.

**Comment by copy** [comment]
For OSes that aren't restored from snapshot, this is already the case. For those that are restored from snapshot (Windows 95/98, Arch Linux, FreeBSD and ReactOS), it's not technically possible unless the OS supports hot swapping RAM.

If you need more RAM in any snapshot for a good reason, let me know and I'll bump it.

**Comment by chantheman1288** [comment]
Oh, ok, that makes sense. By the way, your project is very cool. I’m a high school senior about to enter into Computer Engineering, so I was very interested when I saw it. Do you have any resources you’d recommend for how you got started? I was interested in emulating 8086 processing a while back, but found it difficult to find resources about how the actual processor worked, and resources for how to optimize reading the intructions.

**Comment by copy** [comment]
> Oh, ok, that makes sense. By the way, your project is very cool. I’m a high school senior about to enter into Computer Engineering, so I was very interested when I saw it. Do you have any resources you’d recommend for how you got started? I was interested in emulating 8086 processing a while back, but found it difficult to find resources about how the actual processor worked, and resources for how to optimize reading the intructions.

This is what I used:

- Intel's manuals
- http://ref.x86asm.net/coder32.html
- http://sandpile.org/
- nasm and a hex editor
- https://pdos.csail.mit.edu/6.828/2011/readings/i386/toc.htm
