### ISSUE TITLE
Send key to emulator programatically?

### ISSUE THREAD

**Issue by samtulach** [copy/v86#159]
Hello everyone!
Can I send key to emulator? Like input will be `d` emulator simulate `d` key press.

**Comment by AmaanC** [comment]
Yep, it's part of the API here:
https://github.com/copy/v86/blob/master/docs/api.md#keyboard_send_scancodesarraynumber-codes

Example:

To send `abc`:

```
var options = {};
var emulator = new V86Starter(options);
...
emulator.keyboard_send_scancodes([0x1e, 0x30, 0x2e])
```

**Comment by samtulach** [comment]
Thanks for your response!

Hmm... Good, but I need to send the char as string. It is possible to convert it? I can't find it on internet, how to convert in to requested _make code_ format.

**Comment by tracker1** [comment]
You could map the `charCodeAt` value, using this table as a starting point...

https://msdn.microsoft.com/en-us/library/aa299374(v=vs.60).aspx

**Comment by copy** [comment]
There's also `emulator.keyboard_send_text` which takes a string. It only works if the guest keyboard layout is US. Don't consider it stable.

**Comment by copy** [comment]
I'll close this, feel free to reopen if you have more questions.
