### ISSUE TITLE
How to use the console for Windows 98 emulation ?

### ISSUE THREAD

**Issue by 7485** [copy/v86#160]
Hello, 
I have a problem in the emulation of Windows 98.
I don't understand how the consoles works.
I can't type anything inside. The cursor blinks, but I can't write.
Have you any solution ?
Thanks
(sorry for my bad english, I am french).

**Comment by copy** [comment]
Windows 98 doesn't connect to the serial console by default. I need to install something like Kermit 95 for console access through the serial.
