### ISSUE TITLE
Building BuildRoot Image with X11 Support

### ISSUE THREAD

**Issue by czenzel** [copy/v86#164]
Hello everyone,

I am sorry if I didn't RTM (leaving out the "F" for niceness) about this, but I tried building an image with Buildroot containing X11. The virtual machine boots correctly and I am dumped into the Buildroot image I created and all the command lines work correctly.

When I try to run "startx" it states that "no screens found." I am wondering if I missed something in the drivers for X11 or the kernel for this to happen.

After the X11 Server exits from buildroot then my console starts outputting weird characters and I can no longer type into the command line (forcing a restart of the VM in the browser) because it becomes inoperable.

If anyone can help me out with building an image with X11 support it would be appreciated!

Thanks
Chris Zenzel

**Comment by copy** [comment]
The correct driver is `vesa`, can you check that this driver is loaded in your `Xorg.0.log`?

The corresponding sections in `xorg.conf` should look like this:

```
Section "Device"
	Identifier  "Card0"
	Driver "vesa"
EndSection

Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	Monitor    "Monitor0"
	SubSection "Display"
		Depth     24
		Modes "1024x768"
	EndSubSection
EndSection
```

**Comment by czenzel** [comment]
Thank you. I got it to work. The next issue is that buildroot tries to load xterm in startx, but I believe I can fix that. (Buildroot does not compile xterm). Thanks @copy!
