### ISSUE TITLE
ALT+Function keys freeze keyboard

### ISSUE THREAD

**Issue by sebastianmihai** [copy/v86#165]
(Browsers: Firefox 54, IE11)

Steps to reproduce:

- From the demo page, start MSDOS
- Press ALT-F2
- Try typing anything; you will notice nothing registers

Similarly, you can use the Linux 2.6 demo. Press ALT-F2 and then ALT-F1 again to return to the first terminal. Nothing can then be typed in this first terminal.

**Comment by ErnWong** [comment]
I can reproduce this on Firefox 57.

A blur event (e.g. minimising and reopening the browser window) seems to be able to temporarily fix the problem after pressing `ALT-F2`.

**Comment by ErnWong** [comment]
On firefox:

The release of the ALT key does not seem to be sent through: 
```
20:05:37+671 [PS2 ] port 64 read: 0x11
log.js:13:9
20:05:37+672 [PS2 ] Port 60 read (kbd)  : 0x38
log.js:13:9
20:05:37+673 [PS2 ] port 64 read: 0x10
log.js:13:9
20:05:37+673 [PS2 ] port 64 write: 0xAE
log.js:13:9
20:05:37+673 [PS2 ] Enable Keyboard
log.js:13:9
20:05:37+780 [PS2 ] port 64 read: 0x11
log.js:13:9
20:05:37+780 [PS2 ] Port 60 read (kbd)  : 0x3C
log.js:13:9
20:05:37+781 [PS2 ] port 64 read: 0x10
log.js:13:9
20:05:37+782 [PS2 ] port 64 write: 0xAE
log.js:13:9
20:05:37+782 [PS2 ] Enable Keyboard
log.js:13:9
20:05:37+887 [PS2 ] port 64 read: 0x11
log.js:13:9
20:05:37+889 [PS2 ] Port 60 read (kbd)  : 0xBC
log.js:13:9
20:05:37+889 [PS2 ] port 64 read: 0x10
log.js:13:9
20:05:37+890 [PS2 ] port 64 write: 0xAE
log.js:13:9
20:05:37+890 [PS2 ] Enable Keyboard
log.js:13:9
```

Until the blur event triggers the key up:

```
20:05:58+302 [PS2 ] port 64 read: 0x11
log.js:13:9
20:05:58+302 [PS2 ] Port 60 read (kbd)  : 0xB8
log.js:13:9
20:05:58+303 [PS2 ] port 64 read: 0x10
log.js:13:9
20:05:58+303 [PS2 ] port 64 write: 0xAE
log.js:13:9
20:05:58+304 [PS2 ] Enable Keyboard
log.js:13:9
```


Meanwhile, on Chrome, the ALT key release is sent through:

```
log.js:13 20:08:20+698 [PS2 ] port 64 read: 0x11
log.js:13 20:08:20+699 [PS2 ] Port 60 read (kbd)  : 0x38
log.js:13 20:08:20+700 [PS2 ] port 64 read: 0x10
log.js:13 20:08:20+702 [PS2 ] port 64 write: 0xAE
log.js:13 20:08:20+704 [PS2 ] Enable Keyboard
log.js:13 20:08:20+774 [PS2 ] port 64 read: 0x11
log.js:13 20:08:20+775 [PS2 ] Port 60 read (kbd)  : 0x3C
log.js:13 20:08:20+780 [PS2 ] port 64 read: 0x10
log.js:13 20:08:20+783 [PS2 ] port 64 write: 0xAE
log.js:13 20:08:20+784 [PS2 ] Enable Keyboard
log.js:13 20:08:20+905 [PS2 ] port 64 read: 0x11
log.js:13 20:08:20+907 [PS2 ] Port 60 read (kbd)  : 0xBC
log.js:13 20:08:20+909 [PS2 ] port 64 read: 0x10
log.js:13 20:08:20+911 [PS2 ] port 64 write: 0xAE
log.js:13 20:08:20+913 [PS2 ] Enable Keyboard
log.js:13 20:08:20+931 [PS2 ] port 64 read: 0x11
log.js:13 20:08:20+933 [PS2 ] Port 60 read (kbd)  : 0xB8
log.js:13 20:08:20+935 [PS2 ] port 64 read: 0x10
log.js:13 20:08:20+936 [PS2 ] port 64 write: 0xAE
log.js:13 20:08:20+938 [PS2 ] Enable Keyboard
```

**Comment by ErnWong** [comment]
On the first glance, I suspect it's something along the lines of Firefox not emitting key-up for the alt key when other keys are pressed (or the KeyboardEvent is different). A possible workaround is to handle the alt key as a special case using keyboardEvent.altKey or similar. I'll probably have a look into it tomorrow.

**Comment by ErnWong** [comment]
Pressing ALT+A in https://jsbin.com/vocehicipe/6/edit?html,js,output

![image](https://user-images.githubusercontent.com/2609018/35115037-ab05f21c-fceb-11e7-8338-82db2106aba4.png)

Going clockwise from top left, the browsers are: Firefox 57, Chrome 63, IE11, and Edge 41.

Other modifier keys appear to work fine apart from ALT.

In this case, we probably have to simulate the keyup event ourselves after an ALT keydown event. Upon receiving an ALT keydown event, we can pretend that the key is held down until we receive another KeyboardEvent where `event.altKey` is no longer `true`, in which case we send the ALT keyup to the bus before the key that the event is associated with. We can then ignore actual ALT keydown from Chrome.

**Comment by ErnWong** [comment]
Thanks @sebastianmihai for the bug report! A fix for it has been merged with this repository. Note: the fix won't appear on https://copy.sh/v86/ until the changes get pushed to the server.
