### ISSUE TITLE
Build fails when following instructions on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by SQLServerIO** [copy/v86#166]
I started with a fresh install.
did a apt update and apt upgrade
apt installed:
java default-jre
make
node nodejs-legacy

cut and paste from the instructions
when executing make build/libv86.js I get this error:

java.lang.NullPointerException: No warning class for name: inferredConstCheck 

make build/v86_all.js also fails with the same error.

I get the same build errors on my Windows 10 box as well.

**Comment by copy** [comment]
Fixed in 82fc184c7960432ed1170b9447fcc638a2adfafb.
