### ISSUE TITLE
example basic.html fails with type error.

### ISSUE THREAD

**Issue by SQLServerIO** [copy/v86#167]
libv86.js now successfully builds. 
I ran the tests and all of them pass.

When running examples/basic.html using make run (the python simple http server) I now get this error:
when testing examples/basic.html I get this error.
libv86.js:5 Uncaught TypeError: Cannot use 'in' operator to search for 'Math' in undefined
    at Object.$jscomp.polyfill (libv86.js:5)
    at libv86.js:5
    at libv86.js:1108
$jscomp.polyfill @ libv86.js:5
(anonymous) @ libv86.js:5
(anonymous) @ libv86.js:1108
basic.html:10 Uncaught ReferenceError: V86Starter is not defined
    at window.onload (basic.html:10)

test results
Using 1 cpus
Starting test: FreeDOS boot
Passed test: FreeDOS boot (took 2.106s)

Starting test: FreeDOS boot with Bochs BIOS
Passed test: FreeDOS boot with Bochs BIOS (took 3.939s)

Starting test: Windows 1.01 boot
Passed test: Windows 1.01 boot (took 0.983s)

Starting test: Sol OS
Passed test: Sol OS (took 1.39s)

Starting test: Linux
Passed test: Linux (took 33.142s)

Starting test: Windows 98
Missing disk image: /home/theo/v86/tests/full/../../images/windows98.img, test skipped

Starting test: Linux 3
Passed test: Linux 3 (took 52.617s)

Starting test: KolibriOS
Passed test: KolibriOS (took 38.838s)

Starting test: Linux with Bochs BIOS
Passed test: Linux with Bochs BIOS (took 37.456s)

Starting test: OpenBSD
Passed test: OpenBSD (took 61.611s)

**Comment by copy** [comment]
Thanks for the report.
