### ISSUE TITLE
Unable to upload files to interpreter for MS-DOS or custom OS's

### ISSUE THREAD

**Issue by ndrewxie** [copy/v86#171]
When using MS-DOS or a custom ISO, both the "send files to emulator" and the "get file from emulator" buttons are missing.

**Comment by copy** [comment]
The filesystem feature is based on [virtio](https://wiki.libvirt.org/page/Virtio), which is not supported by Windows or older operating systems. There are virtio drivers for some Windows versions, but as far as I know there are none for the 9p filesystem transport.

**Comment by ndrewxie** [comment]
MS-DOS has a way to access files (obviously), so you could just create a default folder called "uploads" or something and upload files there.

**Comment by ndrewxie** [comment]
The main problem is that you can't install any software on MS-DOS because of this problem.
