### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by luis140219** [copy/v86#174]
When going to http://copy.sh/v86/?profile=archlinux on IE11, I get an error:

O objeto não suporta a propriedade ou o método 'slice'.

The object is a TypedArray. Mozilla documentation states TypedArray.prototype.slice is available on Chrome and Firefox, but not on IE.

**Comment by copy** [comment]
This should be easily fixable, but we probably use other APIs that aren't supported by IE.

Does Edge work?

**Comment by luis140219** [comment]
I'm using Windows 8.1, so I cannot test Edge. Mozilla documentation states Edge status is unknown ('?').

Here is the link to the documentation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice

**Comment by BobVul** [comment]
That particular function should be supported in Edge: https://kangax.github.io/compat-table/es6/#test-typed_arrays_%TypedArray%.prototype.slice_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;

**Comment by copy** [comment]
I tested Edge now and it works.

IE 11 support would be nice for users that don't have Windows 10, but I don't think that justifies the effort required to support an unmaintained browser (it will just get worse with time). I'd suggest installing Firefox.

**Comment by luis140219** [comment]
Found: src/pci.js line 477

**Comment by luis140219** [comment]
Polyfill (works on IE):

```javascript
<<typedarray>>.prototype.slice = function(s, t) {
  var result = new <<typedarray>>(t - s);
  for (var i = 0; i < (t - s); i++)
  {
    result[i] = this[i + s];
  }
  return result;
}
```
