### ISSUE TITLE
Visual oddity when booting ReactOS installer/bootcd

### ISSUE THREAD

**Issue by MailYouLater** [copy/v86#179]
When booting the ReactOS Installation CD (a.k.a. "bootcd") in v86 (by itself, without any other drives) the graphics get messed up. I'm unsure exactly how to describe it, so I'm including a screenshot.

![image](https://user-images.githubusercontent.com/1279475/34085038-0ee9309e-e33f-11e7-9981-885f6d68c5d6.png)

Is this an issue with v86, ReactOS, or another instance where both need improvement to fix it?

FYI, this screenshot is of the official 0.4.7 release downloaded from the project's SourceForge project: [Link](https://sourceforge.net/projects/reactos/files/ReactOS/0.4.7/ReactOS-0.4.7-iso.zip/download), but this also occurs with the latest (to date) nightly builds, and I've also seen it on several older builds too (sorry, I don't remember which ones, it has been a while).

Thanks.

**Comment by MailYouLater** [comment]
For reference, this is what it looks like at the same point when running in QEMU:
![image](https://user-images.githubusercontent.com/1279475/34221445-e4865900-e56c-11e7-891d-d114d6d7c06f.png)

**Comment by BenNottelling** [comment]
Seeing a glitch with the DOS 6.22 install floppy.. maybe related? 
![screen shot 2017-12-21 at 12 13 41 am](https://user-images.githubusercontent.com/17304943/34246519-e2ad581e-e5e3-11e7-8755-d72dbb4a922a.png)

**Comment by ErnWong** [comment]
Interesting! The vga emulation has correctly picked up the size (80x50) of this text mode, yet there seems to be an extra column of text that ReactOS program has written into the display buffer memory...

When aligning the character data bits in groups of 80:
![reactos - memory align 80](https://user-images.githubusercontent.com/2609018/34512776-47a13ba6-f0c9-11e7-959f-0b2508bbdc30.png)

In groups of 81:
![reactos - memory align 81](https://user-images.githubusercontent.com/2609018/34512778-49654fea-f0c9-11e7-908f-fe47cd5f0bcb.png)

As produced by QEMU (zoom in to see the grid and column numbers)
![reactos - qemu](https://user-images.githubusercontent.com/2609018/34512781-4f5ec1ec-f0c9-11e7-88e9-bc71101795f9.png)

See if you can spot the extra column of space characters (`0x20`) and box drawing characters (`0xC4`) in the memory tables.

**Comment by MailYouLater** [comment]
I'm not as much of a developer as I'd like to be, so I'm having some difficulty understanding what I've read, but I dug through the ReactOS sources and it seems to me that it has a method of detecting the size it should be. So I'm wondering if it's ReactOS 'detecting' incorrectly or v86's virtual hardware 'reporting' incorrectly.

Note: I don't fully understand what I'm looking at, but it looks to me like it fills up a line of the screen with spaces, checks to see how many characters are in that line, and from that point forward it fills lines up with that many characters, so my guess would be that v86 is accepting one more character than it should, or reporting that one more character is on the line than there are, or something like that.

**Comment by ErnWong** [comment]
Ahh, that's it!

https://github.com/copy/v86/blob/6c44a716ccc8a1c1b44e4940586c5f93cce4f13f/src/vga.js#L1146-L1147

The value it returns should be `79` instead of `80` in this video mode ~~ it's one of those weird places where the device register should be interpreted as one less than the actual value.

![image](https://user-images.githubusercontent.com/2609018/34637833-5cd597d6-f323-11e7-9946-cd71df51f005.png)

Thanks @MailYouLater ! This fix will be added along with other graphical fixes, so it may take a while before it gets released.

That DOS glitch is still a mystery though.

**Comment by MailYouLater** [comment]
Sweet. I'll be glad to see when this change gets pushed.

I am wondering though...
If the 80 should be 79 in https://github.com/copy/v86/blob/6c44a716ccc8a1c1b44e4940586c5f93cce4f13f/src/vga.js#L1146-L1147
Should the 50 be 49 in 
https://github.com/copy/v86/blob/6c44a716ccc8a1c1b44e4940586c5f93cce4f13f/src/vga.js#L1148-L1149

The DOS glitch doesn't seem to be related, so it should probably get its own issue.

**Comment by ErnWong** [comment]
Good spotting, but don't worry, I've noticed the row number too and it's going to be part of the VGA improvement. In fact, the 0x12 register should be a completely different number AFAIK. [(Nitty gritty details)](https://gist.github.com/ErnWong/90b9bc7ab37cdc2ca2b6d75d48180623)

**Comment by MailYouLater** [comment]
Wow. Thanks for the 'nitty gritty detail'. I find that to be very interesting, and I'm looking forward to seeing when everything you're working on gets pulled in.
