### ISSUE TITLE
Image file

### ISSUE THREAD

**Issue by Noahbob2233** [copy/v86#187]
In cpanel were do i put the images for the buttons

**Comment by BenNottelling** [comment]
Like the buttons on the index page? Go to the source folder for where v86 is stored and then make a new folder called "images" then put the disk images there. 
Like how it is on his website:
https://copy.sh/v86/ is where v86 is and https://copy.sh/v86/images is where the images are

**Comment by copy** [comment]
@Noahbob2233 Feel free to reopen if you need any more help.
