### ISSUE TITLE
Arch linux having trouble

### ISSUE THREAD

**Issue by Broyojo** [copy/v86#192]
There is something going very wrong with arch linux. Maybe there is something wrong with the kernal? Here is a picture after you boot it up:

![25307187-dadd-4b06-be50-74b6d7f1d4dc](https://user-images.githubusercontent.com/20409082/36208216-55e7ba88-1166-11e8-9b84-95a79af79aeb.jpeg)

**Comment by copy** [comment]
Thanks for the report. I can reproduce this, will be fixed in the next release in a couple of days.

**Comment by copy** [comment]
Fixed. Let me know if the problem occurs again.
