### ISSUE TITLE
Screenshot feature broken in Chrome

### ISSUE THREAD

**Issue by 1j01** [copy/v86#195]
It just opens up about:blank, and in the console it says "Not allowed to navigate top frame to data URL"

So maybe a blob URL would work? You could use [FileSaver.js](https://github.com/eligrey/FileSaver.js) to save it. That way there'd be a reasonable point at which to call `revokeObjectURL`, and it'd save a step or two in saving the image. (Are there any other use cases? Comparing screenshots over time?)

**Comment by BenNottelling** [comment]
Right click --> "save image" works fine. Although this should still be fixed

**Comment by copy** [comment]
This has been fixed.
