### ISSUE TITLE
Garbled text after reading from /dev/urandom on Linux

### ISSUE THREAD

**Issue by AmaanC** [copy/v86#201]
Testing on version 4e0ffaa at http://copy.sh/v86/:

- Boot Linux 2 or 3 up (2 takes longer but I can still reproduce it there)
- Run `cat /dev/urandom` for a while and hit Ctrl+C / run `head -c 10000 /dev/urandom`
- You'll see a screen like this once you do it enough times:

![screenshot from 2018-03-21 11-09-05](https://user-images.githubusercontent.com/1172631/37695902-c9e11332-2cf8-11e8-8393-cc78402d4373.png)

The majority of the screenshot is the output of the random bytes, followed by me running `ls -alh`.

- If I save state and restore it, the bug remains
- If I write the random stream to a file, I can't trigger the bug - it needs to be on the screen
- Text is garbled _consistently_ - as you can see "roo" is always shown, for eg. Uppercase characters can all be drawn without problems.
- I can't reproduce this in the exact same ISO files in QEMU, confirming that it's a bug in v86

Looks like a bug that somehow corrupts an internal structure that we also save in the state.

[State for Linux3](https://drive.google.com/file/d/1GGWzW7fnvyKheqJsEIjsC6d84brg269M/view?usp=sharing) for anyone who'd like to take a crack at it.

**Comment by AmaanC** [comment]
Nevermind - I just reproduced it in QEMU too. It just had to be reading from `urandom` significantly longer.

Closing because it's not a bug in v86, but if anyone figures out why it happens, I'd love to know!

![screenshot from 2018-03-21 11-27-25](https://user-images.githubusercontent.com/1172631/37696182-da7e86dc-2cfa-11e8-8f47-ca4e55e6c71f.png)

**Comment by cyberplant** [comment]
The output of that file probably contains a ^N that is changing your character set. You can type ^O to go back to normality. It's not related to v86.

![image](https://user-images.githubusercontent.com/1236332/37728865-24359d00-2d1a-11e8-8a29-79a686228f45.png)

More info here: http://tldp.org/HOWTO/Keyboard-and-Console-HOWTO-4.html
