### ISSUE TITLE
File sharing on Linux 3

### ISSUE THREAD

**Issue by nununoisy** [copy/v86#202]
The 9p filesystem used for sharing files refuses to mount.

In the console it says
`mount: mounting host9p on /mnt failed: Device or resource busy`

I also saw on startup:
`9pnet_virtio: no channels available`

**Comment by AmaanC** [comment]
I see the same messages in the `linux3.iso`, but 9p support works just fine in reality. (Try sending a file to the emulator and then `ls /mnt/` to verify it's accessible, for eg.)

**Comment by nununoisy** [comment]
I admit I never tried sending a file, but I couldn’t download a file.
I was using an iPad though, might this be an entirely separate issue?

**Comment by copy** [comment]
In Linux 3 the virtio filesystem is mounted on `/mnt/`, so if you copy a file to `/mnt/`, for example `cp /bin/cat /mnt/` you can get it at `/cat`. Does that work for you?

**Comment by nununoisy** [comment]
Well it seems that file downloading is just broken on iOS. Closing.
