### ISSUE TITLE
Shift key on iOS does not function

### ISSUE THREAD

**Issue by nununoisy** [copy/v86#205]
Although the keyboard functions on iOS to an extent, any key that would require the SHIFT key does not work with the onscreen keyboard or a physical keyboard (which used to function perfectly).

Can easily be reproduced by typing an ampersand (&), which produces a 7 instead.

**Comment by copy** [comment]
Can you go to http://unixpapa.com/js/testkey.html, press shift and another key and paste the output here?

**Comment by Broyojo** [comment]
Output for shift key on Ipad: 
keydown code=Unidentified keyCode=0
keyup code=Unidentified keyCode=0

**Comment by Broyojo** [comment]
Arrow keys, CMD, Control, and option all give the same output, I don't think this can be fixed it's really Apple's problem. I have experienced this many times before while developing for iOS.

**Comment by copy** [comment]
@Broyojo Cheers.

Closing as not fixable on our side.

**Comment by nununoisy** [comment]
Some other computer emulators have a clipboard box, which automatically types any characters placed in it into the emulator. The shift key works here, maybe a visible text box would work?
