### ISSUE TITLE
Please consider providing an option to use a different network relay address

### ISSUE THREAD

**Issue by bsapwindows** [copy/v86#209]
It would be convenient for user to change it in case Benjamin's relay stopped working. Currently there's no way to change the default value of `network_relay_url` in demo, at least it's not documented. Jor1k has done it by passing the value via url.

**Comment by copy** [comment]
Good idea, I'd accept a pull request.

**Comment by copy** [comment]
There's now an input field on the front page, defaulting to Benjamin's proxy.
