### ISSUE TITLE
Open bios

### ISSUE THREAD

**Issue by LilChickenz** [copy/v86#211]
Hi noob question
how do I open the bios menu

**Comment by copy** [comment]
In the default BIOS the menu is disabled (as it takes extra time from the boot process). If you use the Bochs BIOS (append `&use_bochs_bios=1` to the url, for example [/v86/?profile=linux26&use_bochs_bios=1](http://copy.sh/v86/?profile=linux26&use_bochs_bios=1)) you can open the menu using F12.
