### ISSUE TITLE
Create minimal Linux/BusyBox configs for running v86

### ISSUE THREAD

**Issue by humphd** [copy/v86#213]
I'm trying to build an optimal, minimal kernel and BusyBox command set for using v86 using [buildroot](http://buildroot.org/).  Since the v86 hardware is pretty much set, and since running in the browser means I'm not going to extend it at runtime (i.e., don't need tons of drivers), I'm trying to strip down everything I don't need.  I'm also trying to align the [hardware/cpu/etc](https://github.com/copy/v86#how-does-it-work) with what I can turn on/off in the kernel config.

I'm aware of the [9p](https://github.com/copy/v86/blob/master/docs/linux-9p-image.md) docs, and https://github.com/ysangkok/build-v86-9p-linux.  However, if people here have some knowledge of this process, what to enable/disable, it would be great to either document it in this bug, or for a base `v86_defconfig` to get created.

**Comment by humphd** [comment]
Documenting as I go, please correct me if I'm wrong.

Based on the [cpu definition docs](https://github.com/copy/v86#how-does-it-work), it seems like buildroot's `Target Options` should be:

* Target Architecture: `i386`
* Target Architecture Variant: `pentium mobile`

See https://github.com/buildroot/buildroot/blob/master/arch/Config.in.x86#L55-L59, which defines x86 with SSE and MMX.

**Comment by copy** [comment]
Good idea! Let me know about your findings.

A few thoughts:

- v86 doesn't support all mmx/sse instructions (mostly those operating on floating point numbers). In my experience, applications usually detect mmx/sse support at runtime from cpuid, but compilers may emit mmx/sse instructions if they are configured so
- v86 does support a few newer instructions with their own cpuid feature bits, like rdrand, popcnt and cmpxchg8, but these are likely detected by cpuid and not at compile time
- For performance reasons, it's probably a good idea to set HZ to a lower value, such as `CONFIG_HZ_100`
- `rep movsb`, `rep stosb`, etc. are much faster on v86 than loops, so if you find a configuration that makes the kernel to choose this implementation your `memcpy` and `memset` will be faster

**Comment by BenNottelling** [comment]
This is something I've wanted to do, but not really known how, @humphd if you could share the final result that would be great! 😁

**Comment by humphd** [comment]
I spent the weekend on this and got it working and automated within docker, see https://github.com/humphd/next/pull/83.  This defines a custom "board" for v86 with the various tweaks I need (I've got most hardware disabled, plan 9 enabled, and customizations to the startup scripts in `/etc`).

My build is 4.9M (kernel + rootfs bundled as an ISO), and starts-up with 8M of RAM in use.  I'm probably satisfied with this, and won't tweak it too much more, except to research a few of the things you mention above (I did see the `CONFIG_HZ_100` in https://github.com/buildroot/buildroot/blob/master/arch/Config.in.x86#L55-L59 already).

Taking what I did for my PR and generalizing it for v86 (i.e., not disabling all the stuff I turned off, or having multiple `linux.config` versions that let people choose between some various options) would be pretty easy.  I'm not sure if you'd want a PR here too, or a separate repo?

When I started playing with v86, I didn't know how to use buildroot, and was forced to try different existing images, each of which had some of what I needed, but not the rest.  Now that I understand how it works, it seems like you could spec out a bunch of configurations that work well on v86, and then automate their builds so people can use or tweak.

If any of this is interesting to you, let me know and I'll help make it happen.

**Comment by humphd** [comment]
Solved!  Changing from `Pentium M` to `Pentium Pro` for the Linux Processor config solved it.  As you said above, there must be some issues with MMX, SSE, or other bits that the `Pentium M` was doing that `Pentium Pro` isn't.

Do you agree that `Pentium Pro` makes the most sense, considering others in this list? https://github.com/torvalds/linux/blob/master/arch/x86/Kconfig.cpu

**Comment by copy** [comment]
> Do you agree that Pentium Pro makes the most sense, considering others in this list? 

Yes, although I'm not an expert with particular Intel CPUs.

Could you send me the failing Linux image anyway? My guess is that the problem was a floating point SSE1 instruction, but I want to have a quick look just in case it's something simple to implement.

> Taking what I did for my PR and generalizing it for v86 (i.e., not disabling all the stuff I turned off, or having multiple linux.config versions that let people choose between some various options) would be pretty easy. I'm not sure if you'd want a PR here too, or a separate repo?

I think having one or a few fine-tuned configs in this repo would be cool. Preferably in a new directory (`misc` or so).

**Comment by humphd** [comment]
Here's the an ISO for the Linux image that crashes.  When it boots, run `nled`.  There's not much in there for debugging, but in case it's helpful, here it is.

[v86-linux.iso.zip](https://github.com/copy/v86/files/2125257/v86-linux.iso.zip)

**Comment by copy** [comment]
Indeed the compiler generates `F30F2C` / `CVTTSS2SI` for nled, which is one of the floating point instructions we haven't implemented yet.

**Comment by humphd** [comment]
Finally got around to splitting out this work into a separate repo, if people want to do their own: https://github.com/humphd/browser-vm

**Comment by humphd** [comment]
Also finally finished up the demo that uses all of this stuff:

- Demo: https://humphd.github.io/browser-shell/
- YouTube Video: https://youtu.be/TFxpPbNDlJw
- GitHub: https://github.com/humphd/browser-shell

:heart: v86.  Thanks for all the help answering my questions.

**Comment by copy** [comment]
@humphd FYI, there's complete SSE2 support now. I also went ahead and linked the [browser-vm](https://github.com/humphd/browser-vm) repo in the readme.
