### ISSUE TITLE
Update ReactOS image to 0.4.9 version

### ISSUE THREAD

**Issue by jeditobe** [copy/v86#215]
Update ReactOS image to 0.4.9
It is important because of performance reasons...

**Comment by BenNottelling** [comment]
There is only 0.4.8

**Comment by copy** [comment]
Updated.

Check my record! :o

![screenshot_2018-06-20_16-59-00](https://user-images.githubusercontent.com/1816456/41688902-3f71c64c-74ab-11e8-83a0-bf56543a0dff.png)

**Comment by MailYouLater** [comment]
@copy: Any chance the ReactOS image can get another update once version 0.4.13 gets released? It's scheduled for sometime near the end of this month.
