### ISSUE TITLE
Tabulator issue in lua example

### ISSUE THREAD

**Issue by niansa** [copy/v86#217]
I get a list of all linux commands if i use multiple tabulators in the examples/lua.html

**Comment by mprey** [comment]
Could you explain this more? I would like to help.

**Comment by niansa** [comment]
https://copy.sh/v86/examples/lua.html <-- simply put 2 tabulators into the code textarea

**Comment by niansa** [comment]
![image](https://user-images.githubusercontent.com/20720267/68681232-5be72e80-0563-11ea-98df-39d2b178d033.png)

**Comment by copy** [comment]
Fixed in https://github.com/copy/v86/commit/131f4e128b957771713d567e3128d4bdf409130b.
