### ISSUE TITLE
Evaluate of unicorn.js to provide emulation of x86 instruction set

### ISSUE THREAD

**Issue by sr229** [copy/v86#222]
Currently a project called Unicorn.js has emulation of CPUs, and x86 is supported. Maybe we can look if we can use this on v86 to see if we can fill around the missing parts of the current implementation of x86 here.

**Comment by copy** [comment]
unicorn.js is GPL-licensed, which is incompatible with our license (BSD 2 clause), so unfortunately that's a no.
