### ISSUE TITLE
Kubuntu testing 14.04

### ISSUE THREAD

**Issue by Damakermiddle** [copy/v86#223]
Can someone test kubuntu 14.04 32 bit

**Comment by BenNottelling** [comment]
14.04.5 doesn't boot because it needs PAE

**Comment by ElCresh** [comment]
I suppose, if exist on 14.04, that the alternate versione is better because support non-PAE system.

**Comment by copy** [comment]
Seem to work now.

![Screenshot_2022-05-02_14-47-23](https://user-images.githubusercontent.com/1816456/166290318-a84c384d-037b-42ba-a165-5c1fe0c96dae.png)

**Comment by piusthebiased** [comment]
This is quite nice to see that this project is still alive!  This is extremely irrelevant, however when I was in middle school(hence, Damaker[middle]), I used to use this to do funny stuff with C, quite nostalgic.

Anyways, great work on this project, I (sincerely) appreciate it!

From,
piusthebiased (formerly, Damakermiddle)
