### ISSUE TITLE
Is it feasible to run node.js on a virtual machine?

### ISSUE THREAD

**Issue by liangzeng** [copy/v86#230]
Is it feasible to run node.js on a virtual machine? 

Can give some ideas? I am not a Linux developer.

**Comment by BenNottelling** [comment]
What exactly do you mean? Are you asking if you can run node.js from within v86? Or are you wanting to run v86 from node.js in a virtual machine? Or something else?

**Comment by liangzeng** [comment]
run node.js from within v86 @BenNottelling

**Comment by BenNottelling** [comment]
@liangzeng there's a comment about it on issue #48
