### ISSUE TITLE
Load Save State from Sever

### ISSUE THREAD

**Issue by BenNottelling** [copy/v86#239]
I couldn't find a way to load a save-state from my server. The demo shows it being loaded by the user picking it from their system, but that won't work because I want it on my server. The demo suggested to me that I could load it into a variable, so I tried this:
```
	var client = new XMLHttpRequest();
	client.open('GET', '/wxp_1.bin');
	client.onreadystatechange = function() {
	emulator.restore_state(client.send());
	}
```
But it doesn't seem to do anything, not even show an error in the browser console. How can I load the save-state from my server?

**Comment by copy** [comment]
Your use of `XMLHttpRequest` doesn't look quite right, have a look at this function to see how to do it: https://github.com/copy/v86/blob/master/src/browser/lib.js#L25

**Comment by BenNottelling** [comment]
Oops, my bad. Either way I think it would be good to make an easier way to load the state from the server

**Comment by copy** [comment]
Actually, doesn't `state: { url: "/wxp_1.bin" }` work? (same as for disk images)

**Comment by BenNottelling** [comment]
No that doesn't seem to do anything. Unless for some reason it doesn't work with asycn disk loading?

**Comment by BenNottelling** [comment]
No, That doesn't work @copy It doesn't even make a request for the file. 
![capture](https://user-images.githubusercontent.com/17304943/45650057-f6440300-ba81-11e8-8bdd-7dcaee293968.PNG)

**Comment by copy** [comment]
@BenNottelling Yeah, I can reproduce that. Let me have a look.

**Comment by copy** [comment]
Sorry, it should be `initial_state: { url: "/wxp_1.bin" }`. Does that work for you?

**Comment by BenNottelling** [comment]
![capture](https://user-images.githubusercontent.com/17304943/45651588-b6cbe580-ba86-11e8-99ec-2013440346e0.PNG)
Well at least it tried to load, that maybe be an issue with my save-state

**Comment by BenNottelling** [comment]
I downloaded the save state to my computer and loaded it with the GUI and it worked fine.. so I'm not sure what the issue is.

**Comment by BenNottelling** [comment]
Interesting, I used the code from the save_restore example and the same thing happened when I picked the  save state from my laptop. @copy does that work for you?

**Comment by copy** [comment]
@BenNottelling Do you have the same settings (`network_relay_url` etc.)?

**Comment by BenNottelling** [comment]
Ohh you know what that makes sense now, I didn't set the replay because I have no need for it, but it is set within the web interface. Let me try that!

**Comment by copy** [comment]
This could probably be improved (allow restoring without the same configuration), but I'll close this for now.
