### ISSUE TITLE
WebAssembly Port?

### ISSUE THREAD

**Issue by nepx** [copy/v86#246]
I've taken a look through the code and it looks like a lot of it can be converted into C/C++ rather easily and compiled with Emscripten/Binaryen to produce WebAssembly. The author of [JSLinux](https://bellard.org/jslinux/) did the same thing with his emulator, and it sped it up a lot. Rewriting v86 in C/C++ also opens up the possiblity of creating a native executable, and maybe even a mobile app. 

Adding a dynamic recompiler (#122) seems to be a viable option as well, though that seems like a lot of work. 

I'd love to help on such a project!

**Comment by BenNottelling** [comment]
I'm pretty sure that copy is already working on a WebAssembly port, but I may be mistaken

**Comment by nepx** [comment]
I spent some time today reading through the code, and it doesn't seem as simple as I thought it would. There are a lot of callbacks, which makes translation difficult. I was working on a preliminary port to C during the weekend, but I eventually gave up because the closures were driving me insane. v86 also seems to use function pointers extensively (to differentiate between 16/32 bit operations, various PIC operations, etc.), but I believe a simple `if` statement would be faster. I know C++11 has lambdas and closures now, but [there are a few limitations](https://stackoverflow.com/questions/28746744/passing-lambda-as-function-pointer). 

And I'm also worried that porting it over to a different language/environment might introduce subtle bugs. A massive test suite checks tests every instruction, device, etc. would be awesome for something like this. 

I've also taken a look at the [JSLinux source](https://github.com/levskaya/jslinux-deobfuscated/blob/master/cpux86-ta.js). It depends less on JavaScript dynamicism, so porting it to C -- the CPU core, at least -- would be a breeze. The [latest version](https://bellard.org/tinyemu/) appears to be written fully in C. 

@BenNottelling @copy I'd love to hear more about any new developments!

**Comment by ItsTheAwesomestChannel85** [comment]
Did you get JSLinux from me?

**Comment by filips123** [comment]
Is there any update or some roadmap for WebAssembly version? Having a native library for OS emulation would also be very nice.

Also, you might want to look into Rust instead of C/C++. It provides memory-safety and thread-safety and other things with which it might be easier to write virtual machine and emulation. It should also be quite easy to use it with WebAssermbly. But I'm not sure about all details so it might still be better to use C/C++ or some other language.

**Comment by lights0123** [comment]
AssemblyScript has a [portability](https://www.assemblyscript.org/portability.html) library that would let you use the same TypeScript code for the wasm backend and regular JS build. That could be easier to port. But I'd also recommend Rust for this, the C++ lambda issue exists in Rust but is *much* better explained and dealt with.

**Comment by copy** [comment]
The version at http://copy.sh/v86/ is now based on wasm, written in Rust. The code is in the [wasm](https://github.com/copy/v86/tree/wasm) branch and will be merged soon.
