### ISSUE TITLE
Getting Win 98 to Run

### ISSUE THREAD

**Issue by wwderw** [copy/v86#248]
Just a little background, I created a Win 98 VDI using VBox.  Then I used quem-img to convert that to a raw file.

Since I'm only using this locally, I'm using the debug.html 

The Win 98 splash screen comes up as it should.  Then instead of going to the login screen, it goes to a blank text only screen with an underscore, but I'm unable to proceed any further then that.

I haven't done any editing of any pages, so I don't know if that is necessary or not.

Any ideas?

**Comment by copy** [comment]
Same as  #250.
