### ISSUE TITLE
Is apple rhapsody even possible with only one FDD/what scsi cd driver should I choose?

### ISSUE THREAD

**Issue by hokuco** [copy/v86#249]
I'm trying to run the beta apple rhapsody os from winworldpc on v86, to no avail. My main issue is it requires floppy hot-swapping, as well as a disc drive driver(that's a real tongue-twister). Is there some way I can do this on v86, or should I just image a disc I create with a VM and run that backup?

**Comment by BenNottelling** [comment]
I think that doing it in a VM would he much easier

**Comment by copy** [comment]
Duplicate of #54
