### ISSUE TITLE
Importing files into dos v86 api

### ISSUE THREAD

**Issue by hokuco** [copy/v86#251]
I'm using the v86 api and was wondering if there was any way to import external files(say wolfenstien)via hard disc image while booting dos from the floppy drive. Is this possible?

**Comment by strikersix23** [comment]
you need your own image or floppy of Wolfenstein. so you need to change the boot order to hard disk first i have a copy of freedos that is a good hard disk

**Comment by copy** [comment]
It depends on the filesystem, you may find a library to modify the filesystem before booting. For example, https://www.npmjs.com/package/fatfs.
