### ISSUE TITLE
Persisting data?

### ISSUE THREAD

**Issue by shusain93** [copy/v86#252]
Is it possible to export data/changes to the p9 disk while it was mounted in the VM? I know that we can use `read_file` however I didn't find it suitable for preserving the full disk. 

Can I get access to the raw bytes of the disk? Or is there an easier way for storing data between sessions?

**Comment by copy** [comment]
You could extend [`filesystem.js`](https://github.com/copy/v86/blob/master/lib/filesystem.js) as needed. Right now there's no method for persisting the filesystem.

**Comment by shusain93** [comment]
Awesome, thanks! I'll work on this and probably throw a PR when I get a chance.
