### ISSUE TITLE
Trying to make an arch image and I keep getting this error

### ISSUE THREAD

**Issue by hokuco** [copy/v86#253]
I was trying to use this guide, however when it came time for me to generate arch.img, It failed to generate. My only deviations were as follows: Using virtualbox rather than qemu, and using i686 rather than x86_64 at startup(x86 dodn't show up for some reason). 
https://github.com/copy/v86/blob/master/docs/archlinux.md
How do I fix this?
![virtualbox_gt_03_11_2018_22_08_08](https://user-images.githubusercontent.com/17764452/47959254-63214700-dfb5-11e8-8923-6ae55c7fdcae.png)

**Comment by hokuco** [comment]
If possible does anyone have a premade arch.img? that would make this 1000X easier

**Comment by copy** [comment]
Did you follow the installation guide? https://wiki.archlinux.org/index.php/installation_guide

If you don't need 9p-filesystem based access, a normal Debian installation or a [Buildroot](https://buildroot.uclibc.org/) image would also work.
