### ISSUE TITLE
Not gonna lie im lost at how to set this up.

### ISSUE THREAD

**Issue by chrislightsaber** [copy/v86#255]
So im trying to basically make a website that only has windows 98 for my midterm school project. I just dont understand how to first off get the files to work (without hosting them) and second how i would make it so that on startup it loads the windows 98 image. essentially im just wondering how to only take the windows 98 portion of this or at the very least get everything to work.

**Comment by BenNottelling** [comment]
Take a look at the api

**Comment by chrislightsaber** [comment]
i did i'm still very lost

**Comment by BenNottelling** [comment]
Where are you first lost at?

**Comment by chrislightsaber** [comment]
how to use the index

**Comment by BenNottelling** [comment]
Why there?
What about it confuses you?

**Comment by chrislightsaber** [comment]
It seems like if I run the debug.html that everything should work but I can’t load any images or do anything

**Comment by BenNottelling** [comment]
You have to have it uploaded on a website for anything to correctly work, is it online or local?

**Comment by chrislightsaber** [comment]
It was local and I tried using The compiler but wasn’t sure how to necessarily compile it

**Comment by chrislightsaber** [comment]
Thanks for the help

**Comment by strikersix23** [comment]
If you want a mini server for your phone use this.

https://play.google.com/store/apps/details?id=com.esminis.server.apache&hl=en_US

that's for Android I don't about the iPhone side.

**Comment by strikersix23** [comment]
However it has a few limitions

**Comment by strikersix23** [comment]
if it is alright can i post the link to the snapshot of copys win98.bin for an example

**Comment by BenNottelling** [comment]
Yes that should be fine, I believe

**Comment by copy** [comment]
Sounds like this has been resolved.
