### ISSUE TITLE
Add OpenWRT as a replacement for Buildroot-based images

### ISSUE THREAD

**Issue by sr229** [copy/v86#259]
OpenWRT provides more extensibility compared to Buildroot-based, while the latter is also based on the Buildroot project, it seems to allow package installs via `opkg`. I suggest we go forward with OpenWRT since they provide x86 targeting.

**Comment by copy** [comment]
Something to play around with: https://copy.sh/v86/?profile=custom&hda.url=images/openwrt-18.06.1-x86-legacy-combined-squashfs.img

Main downside is the relatively long boot time compared to buildroot-based images, but it certainly works.

**Comment by sr229** [comment]
I think the main reason for that is because ext4-based images tend to have faster access times than squashfs-based.

**Comment by copy** [comment]
This is now on the website (I updated the link above): https://copy.sh/v86/?profile=openwrt. It boots reasonably fast (~1 minute).
