### ISSUE TITLE
v86 seems to be stuck in  nonblocking pool init on a squashfs-based image

### ISSUE THREAD

**Issue by sr229** [copy/v86#260]
v86 seems to be stuck in initing a `random` non-blocking pool in a squashfs-based image.

[Test image](https://archive.openwrt.org/chaos_calmer/15.05.1/x86/generic/openwrt-15.05.1-x86-generic-combined-squashfs.img).

Note how it is slower compared to ext4-based images.

**Comment by sr229** [comment]
[Test instance with the test image](https://sr229.github.io/LnxSandbox/i686.html)

**Comment by sr229** [comment]
Checking further this seems to be v86 stuck waiting for the squashfs image.

**Comment by copy** [comment]
I'm observing the same behaviour in QEMU. Can you verify that this image is supposed to be booted directly?

**Comment by sr229** [comment]
@copy can confirm this supposed to be booted directly. Might be a issue with how the `squashfs` was built?

**Comment by sr229** [comment]
Update: Tried a `jffs2` image from the [Attitiude Adjustment Release](https://archive.openwrt.org/attitude_adjustment/12.09/x86/kvm_guest/openwrt-x86-kvm_guest-combined-jffs2-128k.img) and it also has the same issue. Tried on QEMU/KVM this image should boot fine

**Comment by copy** [comment]
Doesn't seem to work on qemu either. I'm running it as follows:

```
qemu-system-x86_64 -hda openwrt-x86-kvm_guest-combined-jffs2-128k.img -enable-kvm -m 512
```

The last line of the output is the same as on v86:

```
[    0.463030] Waiting for root device /dev/mtdblock0...
```

**Comment by sr229** [comment]
I'll porbably need to open a ticket about this on the OpenWRT mailing list, the ext4 images does work, however

**Comment by sr229** [comment]
Opened a tracker on [OpenWRT Flyspray](https://bugs.openwrt.org/index.php?do=details&task_id=1961). Hopefully they can clarify why it doesn't work on QEMU (which also has a correlation to not work on v86)

**Comment by copy** [comment]
Feel free to re-open if you find any other v86-specific issues.
