### ISSUE TITLE
Could we use WebGL to accelerate floating point calculations?

### ISSUE THREAD

**Issue by BenNottelling** [copy/v86#261]
Would it maybe be possible to use WebGL to accelerate floating point calculations so we can speed up the CPU emulation? Am I wrong that we could do this? 

Seems like perhaps these would be related to it:
https://github.com/mikolalysenko/glsl-read-float
https://github.com/scrapjs/glsl-to-float

**Comment by copy** [comment]
I don't think GPUs are suitable to accelerate emulation. GPUs are good at many parallel computations, at the cost of worse latency, control flow, etc. See https://en.wikipedia.org/wiki/General-purpose_computing_on_graphics_processing_units.

**Comment by BenNottelling** [comment]
I see, well it was a good idea either way!
