### ISSUE TITLE
Windows 95/98 Rebooting issue in Chrome

### ISSUE THREAD

**Issue by Chiccerino** [copy/v86#264]
If you attempt to restart the operating system, on Win 98 you get stuck on [this](http://prntscr.com/lz72rb) screen and on win 95, you get stuck on [this](http://prntscr.com/lz72yz). Unfortunately you have to reload the entire page to fix the bug as the reset button doesn't exist on 95/98.

**Comment by liudonghua123** [comment]
I have the similar problem, https://github.com/copy/v86/issues/250

**Comment by copy** [comment]
Duplicate of #250.

> as the reset button doesn't exist on 95/98

Yeah, we throw away the state image to save memory space. I think that's the correct behaviour, even if it's slightly inconsistent.
