### ISSUE TITLE
When trying to change monitor type in Display it freezes up and doesnt respond.

### ISSUE THREAD

**Issue by AlmaDev** [copy/v86#267]

**Comment by copy** [comment]
In Windows 98? What did you change it to?

**Comment by BenNottelling** [comment]
I find that big changes cause it to freeze but if I drop it at a little bit at a time it seems ok. Just any OS really

**Comment by AlmaDev** [comment]
I tried changing the monitor resolution from 800 x 600 (default) to 1080 x 720 and then after that, it just froze up. It might just be my computer being slow. Also when I applied the changes, the resolution did not change.

**Comment by ItsTheAwesomestChannel85** [comment]
Windows 98 does the exact same thing to me, except Windows 95 works fine.

**Comment by copy** [comment]
Need more precise reproduction steps.
