### ISSUE TITLE
Cursor in Windows 95

### ISSUE THREAD

**Issue by ItsTheAwesomestChannel85** [copy/v86#268]
Every time I use your Windows 95 emulator, I notice the mouse speed is VERY SLOW. I go in the control panel and do the "fast" cursor, but that hardly changes anything. 
May you also allow me to change the memory/storage on all the OS's? It will help me out a lot!
The reason why I asked you is because virtualbox doesn't seem to want to work, VMWare never fully installs, (since it doesn't go to 100% on the download percentage) and I also cannot find ISO's for it.

Thanks!

**Comment by BenNottelling** [comment]
I'm sorry, you can't find an ISO for it, for what, windows 95?
It's super easy: https://winworldpc.com/product/windows-95/osr-2

**Comment by ItsTheAwesomestChannel85** [comment]
Well, VirtualBox works now, and I wanted windows 98 ISO then, and windows 95, but now I wanted 98, and I downloaded the Windows 98 ISO, finding out it is .7z, and I don't have a lot of storage on my C:\ drive, so I don't want to waste it to just get an ISO.
Nevermind then!
Thanks for the help!

**Comment by copy** [comment]
You can't change the memory or storage because the image is restored from a memory dump (in order to avoid the long boot time).
