### ISSUE TITLE
TempleOS demo?

### ISSUE THREAD

**Issue by graingert** [copy/v86#270]
https://en.wikipedia.org/wiki/TempleOS is somewhat of a popular Internet meme, and would be a good candidate for including on the demo page

**Comment by copy** [comment]
That would indeed be brilliant, but unfortunately we don't support x86-64 and TempleOS only runs on x86-64.

**Comment by Kreijstal** [comment]
aww I guess we will have to wait for v86-64 ;)

**Comment by ThatGuySam** [comment]
For those interested, you can follow x86_64 support here: 
https://github.com/copy/v86/issues/133

**Comment by centuralcreations** [comment]
on a side note, anyone know where to find Terry's ISO files before he started converting to 64bit, he talks about when he did this would love to be able to get it running in the browser..
