### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by ItsTheAwesomestChannel85** [copy/v86#272]
Windows XP does go to the setup utility if you have the correct ISO, but during setup it is unbelievably slow.

I do have VirtualBox and I normally use that. But, I wanted to help out you guys to improve your website and I wanted to try something different.

Anyways, it takes a few minutes to first start the setup utility, then, when it opens, it just doesn't want to go any further than "Press F6 if you need to install a third party SCSI or RAID driver...". 

If you would like to see for yourself, if anyone has a Windows XP ISO that is valid, then try it. It does not work for me, so it probable won't work for you.

**Comment by ItsTheAwesomestChannel85** [comment]
Wait---- I forgot the ISO is a x32 bit, does that affect the chance if it booting up?
Because I don't think there is an official x86 Windows XP ISO somewhere on the Internet that doesn't have a virus program inside it.

**Comment by copy** [comment]
x86 is 32 bit. x32 is not a thing. I think supporting OS installers is very low priority.

**Comment by ItsTheAwesomestChannel85** [comment]
> x86 is 32 bit. x32 is not a thing. I think supporting OS installers is very low priority.

Sorry, I yet did not know what that meant at the time I posted that, and I was new to GitHub so I didn't know how to edit posts.

**Comment by ItsTheAwesomestChannel85** [comment]
Of course, this got closed. Every time I want to post it gets _**BLOCKED!**_

**Comment by kenorb** [comment]
> Of course, this got closed. Every time I want to post it gets _**BLOCKED!**_

You need to report a clear issues. Issue titled "Windows XP" and saying "setup it is unbelievably slow", doesn't really help. This sounds like a feature, not a bug, but it could also be your computer being slow. Please remember, this is Javascript trying to emulate x86 CPU, so it's going to be slow. You didn't specify how you're testing, which operating system (Linux or Windows), which web browser, what's your hardware, didn't post any screenshot, any clear reproducible steps. Secondly, setup being slow (isn't crashing right?), should be addressed to Microsoft. But guess what, Windows XP support has ended.

**Comment by ItsTheAwesomestChannel85** [comment]
> Of course, this got closed. Every time I want to post it gets BLOCKED!
> 
> You need to report a clear issues. Issue titled "Windows XP" and saying "setup it is unbelievably slow", doesn't really help. This sounds like a feature, not a bug, but it could also be your computer being slow. Please remember, this is Javascript trying to emulate x86 CPU, so it's going to be slow. You didn't specify how you're testing, which operating system (Linux or Windows), which web browser, what's your hardware, didn't post any screenshot, any clear reproducible steps. Secondly, setup being slow (isn't crashing right?), should be addressed to Microsoft. But guess what, even they don't support Windows XP, its support has ended.

Thanks!
