### ISSUE TITLE
Windows 200 webpage

### ISSUE THREAD

**Issue by ItsTheAwesomestChannel85** [copy/v86#273]
I currently found a webpage that lets you use windows 2000
The link is here: https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/win2k.cfg&mem=192&graphic=1&w=1024&h=768

**Comment by ItsTheAwesomestChannel85** [comment]
It does have Internet browsers, except they don't run.

**Comment by ItsTheAwesomestChannel85** [comment]
I mean Windows 2000*
If you Çee this message right no,kÞleaseØdial (8lÒ) ###-#### and tell›hem that yäu haveëfoun
 úhs flasE drive, and go to our address,MwhicÆ s 32½¤West 22nd Strent, Co##n ton K(####4. ‚nce yoØ getŠthere, tell uÁ tat you h›ve found §his flÅsh drive a‘dötha| weÌshould caim it bacN if we w]nt itk If we say no, *ou are fèee to do w_atever you wznt to th×s flaÌh driv¢. Else, y©u do NO{ pave pe:mission to change any con
ents of thisBf¬ash driz or even des~roy the flxsh drive!
 §Thaßk you!
ˆ
N¥te t’at if you gžve Ahe flash nri˜eTdamaged or the ©oñÁents of the flash driveßwas chs7ged, tuere my be a chance´that we may dial 911 =ue to invading ÷popôe' ñrvacy.

**Comment by kenorb** [comment]
> It does have Internet browsers, except they don't run.

It runs on mine. Maybe it's too slow on your PC.

![image](https://user-images.githubusercontent.com/266306/54482357-032b8e80-483a-11e9-8f9d-80be395a09b4.png)

**Comment by ItsTheAwesomestChannel85** [comment]
It did run, what I meant is it took forever and webpages don't load.
I did try and fix the error, (by retrying the Internet Connection Wizard) but it no longer wanted to load Mozilla Firefox.
It came up with a BSoD. I checked and changed the link from https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/win2k.cfg&mem=192&graphic=1&w=1024&h=768 to https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/win2k.cfg&mem=20000&graphic=1&w=1024&h=768 and that did make it slightly faster, except the web browser on the Host claimed a BSoD since I had another virtual machine from VirtualBox running, and the web.

**Comment by ItsTheAwesomestChannel85** [comment]
It did run, what I meant is it took forever and webpages don't load. I did try and fix the error, (by retrying the Internet Connection Wizard) but it no longer wanted to load Mozilla Firefox. It came up with a BSoD. I checked and changed the link from https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/win2k.cfg&mem=192&graphic=1&w=1024&h=768 to https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/win2k.cfg&mem=20000&graphic=1&w=1024&h=768 and that broke the Virtual PC, except the Host PC claimed a BSoD since I had another virtual machine from VirtualBox running, and the web.
So I retried it, and used the original, but with resolution 800x600 using the link https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/win2k.cfg&mem=192&graphic=1&w=800&h=600 and, no chance of Mozilla loading the Internet.

**Comment by ItsTheAwesomestChannel85** [comment]
Maybe using Internet Explorer will fix the problem.

**Comment by ItsTheAwesomestChannel85** [comment]
Running Internet Explorer may fix the problem of it not loading the Internet, because what happened is it **_did_** load the webpage, but it **_didn't_** load the Internet.

**Comment by ItsTheAwesomestChannel85** [comment]
> It does have Internet browsers, except they don't run.
> 
> It runs on mine. Maybe it's too slow on your PC.

**Comment by copy** [comment]
That's a pretty cool project, but off-topic for our bug tracker.

**Comment by ItsTheAwesomestChannel85** [comment]
Always closed.
Nothing good happens with my luck...
It's almost if whenever I want to do something or let someone know about something, it always ends up with poor luck.
:(

**Comment by BenNottelling** [comment]
> Always closed.
> Nothing good happens with my luck...
> It's almost if whenever I want to do something or let someone know about something, it always ends up with poor luck.
> :(

This isn't an issue about luck or you letting us know about that web page as being unappreciated, it's just that github issues are for just that, issues. Not discussions. If there is a bug or a regression in compatibility this is the place to mention it, not talk about something. Closing it isn't personal and is simply normal behavior for a github repository. Most of the time there will be another place to talk about the repository/project on hand, weather that be a gitter page, discord server, IRC channel, mattermost server. ect. If your issues are being closed it's because they either don't belong there, don't relate to the repository, or have already been reported. 

Not to mention that all 299 people who follow this repository (including myself) will get an email every time there is a change on here, such as a new issue being opened or a comment on them. 
Nobody is perfect and often there will be small conversations on an issue. I too am guilt of this. There's no reason to act like an attention seeking child because you're new to github and don't yet understand how things work in the open source community.

**Comment by ItsTheAwesomestChannel85** [comment]
Well, I don't mean that...
Anyways, how did you even quote the message I made and DELETED???
Also, yes, on my Outlook I always am notified for GitHub, and the second I log in to my laptop it shows it.

I mean, I get how they want you to know about every specific thing that goes on here on GitHub, but seriously, like if someone else makes an issue about "Windows ME shows up and 'Test' shows up on debug" and they comment that when they click it, nothing happens. (but I get why those are defective buttons) But do you _need_ to know about _THAT?!?!?_

**Comment by BenNottelling** [comment]
> Well, I don't mean that...

Adding "CLOSED :(" to the title really doesn't support that.

> Anyways, how did you even quote the message I made and DELETED???

Reminder: Everyone following get's an email when you post. You may have deleted the comment, but the email is still there, I just copied and pasted. 


Your last comment doesn't even make sense, but either way GitHub is a place for software to be developed and tested, conversations about how something  like Windows ME working or not working is a proper conversation for something like an emulator as it helps keep track of the software's progress. Either way, I'm not going to continue this conversation, it takes time from my day, doesn't achieve anything, and it emails people every time.
