### ISSUE TITLE
ReactOS is now broken

### ISSUE THREAD

**Issue by BenNottelling** [copy/v86#276]
Welp, we broke ReactOS. Even the ISO you have on your website no longer boots. I wonder if it's detecting one of the new SSE instructions and trying to use it
Edit: debug mode still seems to boot though, well, it did when it wasn't the tab I had open. I love how consistent all of this is XD

**Comment by ItsTheAwesomestChannel85** [comment]
Lol

Hated ReactOS anyways ;)

**Comment by BenNottelling** [comment]
Why.. it's honestly really neat

**Comment by copy** [comment]
It's still working for me and there haven't been any changes recently.

**Comment by BenNottelling** [comment]
Did you run it from the snapshot on your website? That still works fine, it's when you're booting from a live CD when I get a BSOD

**Comment by ItsTheAwesomestChannel85** [comment]
> Why.. it's honestly really neat

True, it is neat, except it always crashes and gives me the BSoD, or it runs at 1fps and then 5 min. later of using it, I receive an error from your website saying "Error while reading virtual machine".

**Comment by BenNottelling** [comment]
> > Why.. it's honestly really neat
> 
> True, it is neat, except it always crashes and gives me the BSoD, or it runs at 1fps and then 5 min. later of using it, I receive an error from your website saying "Error while reading virtual machine".

So you're hating on ReactOS because the only use you've had with it was by using a JavaScript X86 emulator? Not very fair of you.

**Comment by ItsTheAwesomestChannel85** [comment]
Not that...

**Comment by ItsTheAwesomestChannel85** [comment]
I mean I've used it on VirtualBox, but still, the OS hates me.
It still runs on 1fps, still crashes/gives me BSOD, and VirtualBox gets the same error of it "can't read" the VM.
That is why I hate ReactOS.

-------------------------------------------------------------------------------------------------------------------
I do like the OS, though. It is neat, except in my opinion, there is no use to have it on a host PC.
