### ISSUE TITLE
copy.sh error with Microsoft Edge

### ISSUE THREAD

**Issue by ItsTheAwesomestChannel85** [copy/v86#277]
Well, I use Microsoft Edge for my default browser, and when I try to download/upload anything on your website, it never allows me to. It works on Chrome, though, and I am starting to wonder if you would have to start everything on your website from scratch, due to all the errors.

**Comment by BenNottelling** [comment]
Didn't work for me, then I opened dev console, and then it worked. 
Mouse capturing doesn't work either though. I think most people agree that edge is garbage though so this likely won't be fixed.
Plus, edge is going to be updated to be chromium based so it should function exactly the same as chrome soon enough, no need to fix it.

**Comment by ItsTheAwesomestChannel85** [comment]
I know it will be chromium-based. I already got their beta version of Microsoft Edge that is like Chromium, except many things didn't work like intended. So I deleted it.

**Comment by copy** [comment]
I think considering that Edge is on the way out, this is a wontfix. I'd accept a pull request.
