### ISSUE TITLE
Lots of storage written to my C:\ drive on virtualization

### ISSUE THREAD

**Issue by ItsTheAwesomestChannel85** [copy/v86#279]
So, I go to your website, load a VM, and for some reason, I check the storage left on my C:\ drive, and it drops like 600MB.
Why does it do this?

**Comment by copy** [comment]
v86 doesn't use any sort of storage (cookies, localStorage or IndexedDB). I suspect your browser is caching disk images, so try clearing site data for copy.sh. At least Firefox is also configurable to not cache to disk at all or clear caches when it's closed.
