### ISSUE TITLE
Issue upgrading to later SeaBIOS

### ISSUE THREAD

**Issue by jester-xbmc** [copy/v86#280]
Hi,

I'm trying to upgrade to a later seabios (https://git.seabios.org/cgit/seabios.git/snapshot/seabios-rel-1.12.1.zip) but getting no where, getting blank screen after updating seabios.bin and vgabios.bin, which options did you use to compile the current version ? (I see you removed the config file here https://github.com/copy/v86/blob/765fc7f06ea6ddf8710ed160af715f7977bf0b92/bios/seabios-config ) which indeed doesn't "fix" the issue 

Any clues would be helpful :)

**Comment by copy** [comment]
[This config](https://gist.github.com/copy/24d108bfe37bdad4938cd219cef752bd) should work on 1.10.2 and 1.12.

**Comment by jester-xbmc** [comment]
Thanks for that, I guess i was missing the PCI VID/DIDs, however, it now boots and displays, but it no longer reads the floppy image, i'm getting "could not read boot disk" (I compiled seabios 1.12.1 and used your 8mb MS-DOS 6.22 image which works fine with the old seabios)

**Comment by copy** [comment]
Indeed, it looks like seabios doesn't recognise v86's ide device any more. Try this patch:

```diff
diff --git a/src/fw/pciinit.c b/src/fw/pciinit.c
index c0634bc..3c06dcc 100644
--- a/src/fw/pciinit.c
+++ b/src/fw/pciinit.c
@@ -230,6 +230,8 @@ static void piix_ide_setup(struct pci_device *pci, void *arg)
     u16 bdf = pci->bdf;
     pci_config_writew(bdf, 0x40, 0x8000); // enable IDE0
     pci_config_writew(bdf, 0x42, 0x8000); // enable IDE1
+
+    storage_ide_setup(pci, arg);
 }
 
 static void pic_ibm_setup(struct pci_device *pci, void *arg)
```

(don't send the patch to seabios, it's probably a bug in v86).

**Comment by jester-xbmc** [comment]
Interesting, indeed that fixes the issue, thanks!

**Comment by copy** [comment]
I'll leave this open to fix the issue with booting unpatched newer seabioses. Low priority though.

**Comment by copy** [comment]
This has been fixed. There's also a script included in the repo to download and build seabios with the proper config: https://github.com/copy/v86/blob/master/bios/fetch-and-build-seabios.sh
