### ISSUE TITLE
Too laggy

### ISSUE THREAD

**Issue by exxprience** [copy/v86#282]
All operating systems are working slow and laggy. How this can be fixed?

**Comment by kenorb** [comment]
> All operating systems are working slow and laggy. How this can be fixed?

Try different browsers, minimalize amount of extensions. Give the priority to the process, disable other apps running in the background. Otherwise, you need a better hardware.

**Comment by chfanghr** [comment]
I wonder if this project can be rewritten using warm. This will do a significant improvement to the performance.

**Comment by filips123** [comment]
@chfanghr See #246.

**Comment by copy** [comment]
> See #246.
