### ISSUE TITLE
Do .ISO files work correctly?

### ISSUE THREAD

**Issue by ITAC85v2** [copy/v86#284]
I have a x86 Windows 98 ISO I have used to boot to on your website.
It works perfect on VirtualBox, except when I tried it on your website, it went fine, until it started downloading display and VGA drivers by default. It all became packed into small pixels, and I made it send CTRL+ALT+DELETE, which rebooted the OS, only finding out the display and VGA were screwed forever.

I converted it to a .IMG file, it works perfectly, so is it that .ISO files are supported, just not stable, or is it that it's just my ISO?

I found it on [winworld](https://winworldpc.com/), and I am not sure if it has been modified slightly or if it's v86.

**Comment by BenNottelling** [comment]
Iso files should work just fine, that's actually how a lot of OSs are booted, for example ReactOS on copy's website is actually a Snapshot of the .iso live CD booted

**Comment by ItsTheAwesomestChannel85** [comment]
Hm, I guess that it is that it doesn't react like it should.
I bet it is slightly modified to work on other things than online virtual machine websites, or made for things like VirtualBox & VMWare.

**Comment by copy** [comment]
Probably was made for hardware in VirtualBox or VMWare. Your best bet is following the install process in qemu to obtain an image that works in v86.

**Comment by ITAC85v2** [comment]
Yes, actually you are right. It seems the ISO file I have is not compatible in v86, which is normal, since normally people would modify some ISO files to work better on certain things. However, I do notice with a Windows 98 FE ISO, it works fine (obtained from All-in-One Windows DVD 2), but it half of the time seems to not work and refuse to boot.

When I convert it to an IMG (I don't know if I did it in vboxmanage or qemu-img), it works with no problems, so I don't know if it could be since ISO files are not a raw virtual disk format and it's more difficult to read from those, or some sort of problem with v86. Either way, it's not a huge problem.
