### ISSUE TITLE
Some functional keys are not passed to the guest systems

### ISSUE THREAD

**Issue by yogev1978** [copy/v86#29]
Some functional keys are not passed to the guest systems. For example, KolibriOS uses:<ul>
<li>WIN key to open the "Start Menu". When this key is pressed right now, the "Start Menu" opens in the host system (Windows)</li>
<li>F5 key to copy files from one folder to another in the file managers. When this key is pressed right now, browser just reloads the page</li>
<li>ALT+TAB to switch between opened windows. When this key is pressed right now, it switches between windows in the host system.</li>
</ul>All this happens even in "Full Screen" mode. I suggest that those keys are either passed to guest system (at least in Full Screen" mode it makes sense), or they are added to the buttons above the guest (similar to "Send CTRL+ALT+DEL" that is there now).

**Comment by copy** [comment]
I'll send F5 to the emulator and block page refresh for now, unless someone complains.

**Comment by yogev1978** [comment]
Thank you very much - I really appreciate that! I don't think many people will complain, since they always can use "Reset" button which essentially does the same as pressing F5.

**Comment by yogev1978** [comment]
I have tested your changes right now on your website:<ul><li>Disabling F5 key works great (behaves as expected)</li>
<li>WIN key now opens the "Start Menu" in the emulator, but it still opens the "Start Menu" in the host system (Windows) at the same time. So unfortunately it's still unusable (as host system "Start Menu" hides the emulator screen).</li>
<li>ALT+TAB works strange. It seems that pressing "Send ALT+TAB" button only sends the button press, but doesn't send button release. So the emulator thinks that ALT+TAB combination was never released.</li></ul>
Hope this test report is helpful for you!

**Comment by copy** [comment]
It doesn't seem to be possible to block the Start Menu in Windows – there's nothing I can do (except adding another button for it).

A release code is sent for alt-tab. Possibly there needs to be a delay between the keydown and keyup.

**Comment by yogev1978** [comment]
Regarding ALT+TAB - I have 0 knowledge in JS, but I have taken a look at your code:
<code>ps2.kbd_send_code(0x38); // alt</code>
<code>ps2.kbd_send_code(0x0F); // tab</code>
<code>ps2.kbd_send_code(0x38 | 0x80);</code>
<code>ps2.kbd_send_code(0x0F | 0x80);</code>

There could be a few reasons why that code doesn't work:<ol><li>You send 2 scancodes (one for ALT, second for TAB). Some websites (although not all) mention that ALT+TAB pressed together has a single special scancode (different from scancodes for ALT or TAB pressed separately): 0xA5: http://www.freepascal.org/docs-html/rtl/keyboard/kbdscancode.html</li>
<li>If websites mentioned in (1) are wrong, then the order for <b>key_up</b> should be reversed: <b>first release TAB and then release ALT</b> (like you do yourself when you work).</li></ol>

**Comment by copy** [comment]
The link in (1) is a different kind of scancode, I guess used in Pascal. For the record, PS2 scancodes can be found here: http://stanislavs.org/helppc/make_codes.html

(2) is makes sense, I'll change it to work that way.

**Comment by yogev1978** [comment]
I have retested ALT+TAB again in KolibriOS, and it's working fine now, thank you!
