### ISSUE TITLE
Internet connectivity in Arch Linux

### ISSUE THREAD

**Issue by MailYouLater** [copy/v86#292]
I've been trying to figure out how to get the Arch Linux image to be able to connect to the internet the way the Linux 3.18 image does, but I can't figure it out.  I found an old issue which indicates that the Arch Linux image could connect to the internet previously, but running `udhcpc` (as is done for the Linux 3.18 image) tells me `-bash: udhcpc: command not found`, running `busybox udhcpc` (because the `udhcpc` binary on the Linux image is a symlink to a `busybox` binary) tells me `udhcpc: SIOCGIFINDEX: No such device`, and running `dhcpcd -w4` (as described in #23) results in this:
```
dev: loaded udev
no valid intervaces found
timed out
forked to background, child pid \<number\>
```

I've tried several times to dig into this more, but I'm having difficulty understanding it.

**Comment by copy** [comment]
There's a `net.sh` script that does the right thing for you. One needs to run `modprobe ne2k-pci` before `dhcpcd`. The reason for this is that the Arch Linux image is restored from a memory dump, and if the driver was already loaded everybody would get the same MAC address.

**Comment by MailYouLater** [comment]
D'Oh❗️❗️
I've been trying to figure this out off and on for over a year, Digging into the source code of different parts of the Linux kernel and not being able to figure this out.  Now it all makes sense.  Thank you so much.  I can hardly believe that in all that time I didn't notice the `~/net.sh` script there. 🤦‍♂

Perhaps you could mention `~/net.sh` at https://github.com/copy/v86/blob/289b8038b1526033c85c0552cf357806c58e3ebb/index.html#L24 similar to how you have `udhcpc` mentioned at https://github.com/copy/v86/blob/289b8038b1526033c85c0552cf357806c58e3ebb/index.html#L30 and/or add a start up script to the Arch image that `echo`es a statement about `~/net.sh` to the terminal, similar to how you have the Linux 3.18 image mention `udhcpc`, as I doubt I'm the only person who didn't notice it.

Thank you.

**Comment by copy** [comment]
I'll close this, I think the script is pretty self-explanatory.
