### ISSUE TITLE
Emulation uses an x86 kernel, but reports an i686 CPU, Linux will not run.

### ISSUE THREAD

**Issue by jojomoore2007** [copy/v86#294]
If you were to open an x86 Debian/Ubuntu-based installer on https://copy.sh/v86/, the emulated machine reports the following:

```
This kernel requires an x86-64 CPU, but only detected an i686 CPU.              
Unable to boot - please use a kernel appropriate for your CPU.                  
```

This happens on many different installers, simply changing the CPU type should fix this issue.

**Comment by copy** [comment]
x86-64 is the 64-bit superset of x86. Try grabbing a 32-bit Linux (usually referred to as i386).

See https://github.com/copy/v86/issues/133
