### ISSUE TITLE
Automatically build libv86 on CI

### ISSUE THREAD

**Issue by filips123** [copy/v86#297]
Can you automatically build `libv86.js` on Travis CI at every commit and publish it to some server or GitHub Pages? This would be very good because users then won't need to install and configure Closure Compiler and other build dependencies.

Can you also configure `Makefile` to also build sourcemap file for `libv86.js`?

Also, the version on [your website](https://copy.sh/v86/) is very old (from 2018). Can you also update it?

**Comment by pitust** [comment]
Actually, here is what I do when I want to use v86:
```sh
wsl wget http://copy.sh/v86/build/libv86.js
```

**Comment by pitust** [comment]
but I didn't know on the website it's old

**Comment by pitust** [comment]
I also noticed maybe `cat` instead of closure compiler (for debug builds)? This would be faster.

**Comment by filips123** [comment]
@copy I'm currently working on PR to build `libv86` in Travis CI and publish it to GitHub Pages. Should I publish ACPI version, non-ACPI version of both?

**Comment by copy** [comment]
> I also noticed maybe cat instead of closure compiler (for debug builds)? This would be faster.

Closure Compiler also does some type checking and linting, I don't think we should disable that.

Closing this issue as it's complete.
