### ISSUE TITLE
"wget deb.debian.org" doesn't work

### ISSUE THREAD

**Issue by safinaskar** [copy/v86#298]
Steps to reproduce:
* Open https://copy.sh/v86/?profile=linux3
* Type `udhcpc`
* Type `wget deb.debian.org`
You will see this:
```
Connecting to deb.debian.org ([2001:4f8:1:c::15]:80)
wget: can't connect to remote host: Network is unreachable
```

**Comment by BenNottelling** [comment]
Is deb.debian.org secured?
SSL is not supported

**Comment by safinaskar** [comment]
> Is deb.debian.org secured?
> SSL is not supported
deb.debian.org can work both using http and https. When I type "wget deb.debian.org" on normal machine, wget uses http.

I see similar error message with commands `wget http://deb.debian.org`, `wget https://deb.debian.org`, `wget google.com`, `wget facebook.com`

**Comment by copy** [comment]
Looks like the websocket proxy doesn't support ipv6. `curl` seems to work fine.

**Comment by safinaskar** [comment]
@copy, okey, so change image such that it doesn't use ipv6 by default. For example, put `sysctl net.ipv6.conf.all.disable_ipv6=1` to start up scripts. I don't want `wget` to fail. In fact, I attempted to run `debootstrap` in this system, `debootstrap` called `wget` and wget failed, I don't want this
