### ISSUE TITLE
Boot SerenityOS

### ISSUE THREAD

**Issue by copy** [copy/v86#299]
Pretty cool hobby OS: https://github.com/SerenityOS/serenity

Requires hardware task switching support: https://github.com/SerenityOS/serenity/blob/7fc903b/Kernel/Scheduler.cpp#L574-L578

**Comment by asiawin** [comment]
Yeah! I dont think you can boot SerenityOS because it's way too large!

**Comment by asiawin** [comment]
Of course! You can boot Cadex OS! Go to https://github.com/opencreeck/Cadex-OS-Official, go to the releases section and download any version of Cadex OS. It's just 4 MB and it can support up to 3 GB of RAM because it's a 32-Bit os and it has some fun things! I would like it if I could run SerenityOS because it is a very good OS!

**Comment by copy** [comment]
Serenity seems to have removed (most uses of) hardware tasking in https://github.com/SerenityOS/serenity/commit/fb41d89384cb5bbdf602ae41ae7e038fb48a34ce. Next blocker: PAE (https://github.com/copy/v86/issues/97)

**Comment by asiawin** [comment]
Oh, I didn't see that! I am now trying to build SerenityOS and it says CMake error. Asked Andreas but he said search google for solution

**Comment by copy** [comment]
This is now working (except for newer versions, which are likely affected by #597): https://copy.sh/v86/?profile=serenity

**Comment by copy** [comment]
(cc @pwmarcz, thanks for the info in https://github.com/copy/v86/pull/599#issuecomment-1013635444)

I fixed an ACPI bug in v86 (it was not being applied). Now running into https://github.com/SerenityOS/serenity/issues/11980 (even with ACPI on in v86). Will wait on a fix on their side and then look into the IDE and graphics issues.

**Comment by supercomputer7** [comment]
https://github.com/SerenityOS/serenity/issues/11980 is closed as it was resolved.
I'm working on support for the QEMU ISA-PC machine type for SerenityOS:
https://github.com/SerenityOS/serenity/pull/12046
I don't know in what state this project is in right now, just thought it might help you somehow :)

**Comment by copy** [comment]
After the ACPI bugfixes we're running into "ASSERTION FAILED: !m_storage_devices.is_empty()". It looks like a bug in v86's pci code, which I'm investigating. A Serenity build with legacy ISA port access would probably work too.

**Comment by copy** [comment]
Seems to be three separate issues (with `enable_ioapic=off acpi=off`):

- v86 doesn't map the IO ports for the IDE controller correctly (they are mapped by seabios to some high port, but v86 only handles the legacy locations). This needs to be fixed on our side.
- Serenity accesses the IDE control port at bar1 with offset 0. v86 maps it at bar1 with offset 2 (same port in a legacy configuration: 0x3f6). I suspect Serenity's behaviour is correct, but I will need to confirm that.
- Lastly, v86 doesn't support configuring graphics registers ([Bochs VBE extensions](https://wiki.osdev.org/Bochs_VBE_Extensions)) through memory-mapped IO. Serenity does support access through port IO, but only enables it if the virtualbox graphics adapter is detected. Probably fairly easy to fix on either side.

I have reasonable workarounds for the latter two issues, but the first one will need some work. After that the latest version of Serenity works in v86.

**Comment by supercomputer7** [comment]
> Seems to be three separate issues (with `enable_ioapic=off acpi=off`):
> 
>     * v86 doesn't map the IO ports for the IDE controller correctly (they are mapped by seabios to some high port, but v86 only handles the legacy locations). This needs to be fixed on our side.
> 
>     * Serenity accesses the IDE control port at bar1 with offset 0. v86 maps it at bar1 with offset 2 (same port in a legacy configuration: 0x3f6). I suspect Serenity's behaviour is correct, but I will need to confirm that.
> 
>     * Lastly, v86 doesn't support configuring graphics registers ([Bochs VBE extensions](https://wiki.osdev.org/Bochs_VBE_Extensions)) through memory-mapped IO. Serenity does support access through port IO, but only enables it if the virtualbox graphics adapter is detected. Probably fairly easy to fix on either side.
> 
> 
> I have reasonable workarounds for the latter two issues, but the first one will need some work. After that the latest version of Serenity works in v86.

As for issue number 3:
Well, for Serenity you could easily fake a VirtualBox graphics adapter and be done with it. I'd argue to not add a kernel commandline option to force Serenity to use IO ports as we talk about virtualized hardware and it seems to me like a better workaround can be achieved. We also can support legacy Bochs graphics adapters but honestly, I don't think it worth anybody time to do that, and instead implementing memory mapped registers seems like the cleanest solution for this problem :)

**Comment by copy** [comment]
I fixed the aforementioned issues. SerenityOS now conveniently checks the PCI revision to see if mmio is available, which v86 incorrectly advertised as available. It seems there have been other fixes on the serenity side, because `enable_ioapic=off acpi=off` isn't necessary any more, so serenity master now works without patches on v86.

I've updated to the latest version: http://copy.sh/v86/?profile=serenity

The only outstanding issue is that networking doesn't work with the public relay at relay.widgetry.org. It works fine when running a [local relay](https://github.com/benjamincburns/websockproxy). I can see the outgoing dhcp packets from serenity as well as incoming packets from unrelated traffic on the relay. There is no response to the dhcp packets that serenity sends out, so either those are dropped by the relay, or their responses are not correctly delivered.

Gently pinging @benjamincburns in case he's aware of any difference between the public relay and the one in the repository.

I've added some network packet logging to https://copy.sh/v86/debug.html, if anybody wants to have a look.

**Comment by benjamincburns** [comment]
I'm not aware of any differences that would break things on your end, but happy to help look into it. I'll have a poke tomorrow.

**Comment by benjamincburns** [comment]
Is it only a problem under SerenityOS?

**Comment by copy** [comment]
Yes, I've only seen this issue happen with SerenityOS.

I made a testcase without the emulator by copying the initial dhcp packet from serenity and udhcpcd, and sending it to the online relay and a local one: http://copy.sh/testcase-serenity-relay.html

Commenting out either `//const packet = packet_udhcpcd;` or `//const ws = new WebSocket("ws://127.0.0.1:8080/");` results in receiving a reply from the dhcp server, e.g.:

```
receive len=342 ethertype=0x800 ipv4.len=328 ipv4.proto=0x11 udp.srcport=67 udp.dstport=68 udp.chksum=0xE70A dhcp.chaddr=00:22:15:78:3d:b4
```

**Comment by benjamincburns** [comment]
Apologies, I got a bit distracted with work things and I wasn't able to look into this until now.

How are you running the local relay? If you aren't using the docker image, perhaps you could give that a try?

**Comment by benjamincburns** [comment]
Got it sorted. I'm not entirely certain what specifically was going wrong, but I bumped the Dockerfile it to use Ubuntu Jammy (for latest `dnsmasq`), and it seems to be working now.

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/803016/180981404-9072eabd-85b8-446f-88f1-6cf117de234a.png">

**Comment by benjamincburns** [comment]
Unfortunately the fix mentioned above introduced a regression in the public relay and had to be temporarily rolled back. I don't have an ETA on a fix yet, but please watch benjamincburns/websockproxy#10 for updates.

**Comment by benjamincburns** [comment]
And we're back
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/803016/181766089-b0f0d2f5-0efa-4ee2-8704-4c03b8e6ef6e.png">

**Comment by copy** [comment]
@benjamincburns Brilliant, cheers!

To summarize: The latest version of Serenity works, without patches, including networking, and loads much faster (#710). 

Enjoy! https://copy.sh/v86/?profile=serenity
