### ISSUE TITLE
make build/libv86.js returns Error 127

### ISSUE THREAD

**Issue by TheDude53** [copy/v86#300]
Running `make build/libv86.js` returns the error code 127. Below is the full output of it.

> mkdir -p build
ls -lh build/libv86.js
ls: cannot access 'build/libv86.js': No such file or directory
Makefile:116: recipe for target 'build/libv86.js' failed
make: [build/libv86.js] Error 2 (ignored)
java -jar closure-compiler/compiler.jar \
        --js_output_file build/libv86.js\
        --define=DEBUG=false\
        --define=ENABLE_ACPI=false\
        --js lib/closure-base.js --generate_exports --externs src/externs.js --warning_level VERBOSE --jscomp_error accessControls --jscomp_error ambiguousFunctionDecl --jscomp_error checkEventfulObjectDisposal --jscomp_error checkRegExp --jscomp_error checkTypes --jscomp_error checkVars --jscomp_error conformanceViolations --jscomp_error const --jscomp_error constantProperty --jscomp_error deprecated --jscomp_error deprecatedAnnotations --jscomp_error duplicateMessage --jscomp_error es3 --jscomp_error es5Strict --jscomp_error externsValidation --jscomp_error fileoverviewTags --jscomp_error globalThis --jscomp_error internetExplorerChecks --jscomp_error invalidCasts --jscomp_error misplacedTypeAnnotation --jscomp_error missingGetCssName --jscomp_error missingProperties --jscomp_error missingReturn --jscomp_error msgDescriptions --jscomp_error nonStandardJsDocs --jscomp_error suspiciousCode --jscomp_error strictModuleDepCheck --jscomp_error typeInvalidation --jscomp_error undefinedNames --jscomp_error undefinedVars --jscomp_error unknownDefines --jscomp_error visibility --use_types_for_optimization --summary_detail_level 3 --language_in ECMASCRIPT5_STRICT\
        --compilation_level SIMPLE\
        --language_in ECMASCRIPT6_STRICT --language_out ECMASCRIPT5_STRICT \
        --output_wrapper ';(function(){%output%}).call(this);'\
        --js src/const.js src/config.js src/io.js src/main.js src/lib.js src/fpu.js src/ide.js src/pci.js src/floppy.js src/memory.js src/dma.js src/pit.js src/vga.js src/ps2.js src/pic.js src/rtc.js src/uart.js src/hpet.js src/acpi.js src/apic.js src/ioapic.js src/state.js src/ne2k.js src/sb16.js src/virtio.js src/bus.js src/log.js src/cpu.js src/translate.js src/modrm.js src/string.js src/arith.js src/misc_instr.js src/instructions.js src/debug.js src/elf.js\
        --js src/browser/screen.js src/browser/keyboard.js src/browser/mouse.js src/browser/speaker.js src/browser/serial.js src/browser/network.js src/browser/lib.js src/browser/starter.js src/browser/worker_bus.js src/browser/dummy_screen.js\
        --js lib/9p.js lib/filesystem.js lib/jor1k.js lib/marshall.js lib/utf8.js
make: java: Command not found
Makefile:116: recipe for target 'build/libv86.js' failed
make: *** [build/libv86.js] Error 127

**Comment by BenNottelling** [comment]
You need to install Java 
Check the wiki for instructions on compiling
