### ISSUE TITLE
Error 10 when running make build/libv86.js

### ISSUE THREAD

**Issue by Nicholassena8190** [copy/v86#302]
Can someone help me?

I been doing this:

# grab the main repo
git clone https://github.com/copy/v86.git && cd v86

# grab the disk images
wget -P images/ https://copy.sh/v86/images/{linux.iso,linux3.iso,kolibri.img,windows101.img,os8.dsk,freedos722.img,openbsd.img}

# grab closure compiler
wget -P closure-compiler https://dl.google.com/closure-compiler/compiler-latest.zip
unzip -d closure-compiler closure-compiler/compiler-latest.zip *.jar

# build the library
make build/libv86.js

# run the tests
./tests/full/run.js

But building the library results in a Error 10.

![image](https://user-images.githubusercontent.com/36643037/68439587-04b91680-017d-11ea-999e-eb20201e2e97.png)

**Comment by jadenp777** [comment]
same problem

**Comment by Nicholassena8190** [comment]
Ok, I figured it out. I'm new to all of this.

I check out a issue: https://github.com/copy/v86/issues/271

The build fails with the latest closure compile.

Closure Compile v20180610 works. Building the library did not result in any errors.

I will be attaching v20180610 of Closure Compile to this comment, so people don't waste their time on figuring why the build is failing.

Closure Compile v20180610:
[ClosureCompile-v20180610.zip](https://github.com/copy/v86/files/3822750/ClosureCompile-v20180610.zip)

Build Results:
![image](https://user-images.githubusercontent.com/36643037/68445125-ddb71080-018d-11ea-9cc3-08f48fac166f.png)
