### ISSUE TITLE
Arch Linux 9P seems to be missing files it thinks it has

### ISSUE THREAD

**Issue by MailYouLater** [copy/v86#306]
I tried to use Arch Linux via v86 on your website to download the v86 sources via git, and it failed.  The way it failed, it looks like there are files that the the Arch Linux image thinks it has that aren't available to it.

    jor1k.js:87 GET https://i.copy.sh/arch/usr/lib/git-core/git-remote-https 404
    filesystem.js:247 Uncaught Error: Could not load file //i.copy.sh/arch/usr/lib/git-core/git-remote-https
![image](https://user-images.githubusercontent.com/1279475/71686642-9fcf0680-2d50-11ea-902d-54122bd3e7df.png)
Going to https://i.copy.sh/arch/usr/lib/git-core/git-remote-https I get this:

    Not Found
    The requested URL /arch/usr/lib/git-core/git-remote-https was not found on this server.
    
    Apache/2.2.15 (CentOS) Server at i.copy.sh Port 443
![image](https://user-images.githubusercontent.com/1279475/71686692-bd9c6b80-2d50-11ea-8788-7a6f08b6087a.png)

I know this occurs for these files:
- https://i.copy.sh/arch/usr/lib/git-core/git-remote-https
- https://i.copy.sh/arch/usr/lib/git-core/git
- https://i.copy.sh/arch/usr/lib/git-core/git-remote-http

I first noticed this problem a few months ago, and at the time I ran a few other commands and was able to find some other files that also appeared to be missing from the server, but I didn't write up an issue at the time, and now I don't remember which files they were.

**Comment by copy** [comment]
Can confirm.

**Comment by copy** [comment]
Fixed.
