### ISSUE TITLE
a web place for v86 success reports?

### ISSUE THREAD

**Issue by martin12333** [copy/v86#309]
Is there already a place on the web, where I could post v86 success reports? For example:

> openwrt-18.06.5-x86-legacy-combined-ext4.img boots OK in v86

**Comment by martin12333** [comment]
(I created a partially related subreddit: 
https://www.reddit.com/r/browserPOSIX/ )

**Comment by copy** [comment]
This issue tracker is fine. Feel free to post any interesting findings.
