### ISSUE TITLE
Foreign keyboard errors

### ISSUE THREAD

**Issue by sylvinus** [copy/v86#31]
Host: OS X Yosemite, French (numerical) keyboard, Chrome
Images: tested with Archlinux & Busybox

Letters and numbers work properly, but other characters such as "." or "/" are not mapped correctly, which renders the shell basically unusable. Fixed by switching the Host OS in English input method.

Thanks!

**Comment by copy** [comment]
Firefox 38 supports `KeyboardEvent.code`, so all keys should work independently of the host keyboard layout with this commit. This means you get whatever keyboard layout is used inside of the guest OS (usually US). Feel free to reopen if there are any more problems.

**Comment by s-macke** [comment]
Indeed it works. It emulates an english keyboard layout no matter of the current keyboard language settings.
