### ISSUE TITLE
MS-DOS missing COM1

### ISSUE THREAD

**Issue by MechaFinch** [copy/v86#311]
I was attempting to use the serial port console on the msdos profile but "`MODE COM1`" gives `Illegal device name - COM1`. Is this a bug or is there something I'm missing? `int 0x14` is also not working.

**Comment by copy** [comment]
Seems to be working:

```
C:\>MODE COM1

Status for device COM1:
-----------------------
Retry=NONE
```

Feel free to reopen if you have more specific reproduction instructions.

**Comment by MechaFinch** [comment]
I don’t remember there being any particular reproduction method and it’s working now in the same environment as the original issue, it probably got fixed at some point given how long it’s been
