### ISSUE TITLE
Windows 10 Not Booting

### ISSUE THREAD

**Issue by Ganesha2282882** [copy/v86#312]
I probably need a 32-bit ISO rather than a 64-bit ISO. Virtual x86 is 32-bit right?

**Comment by BenNottelling** [comment]
Windows 10 will not boot in v86 as it is missing a lot of CPU features that windows 10 needs. Windows XP can boot and maybe with some work you can get something newer to work, but otherwise, no

**Comment by Ganesha2282882** [comment]
@BenNottelling In fact, It does not even download the image.

**Comment by james780** [comment]
its beacause javascript cant read numbers 2^53 or higher

**Comment by james780** [comment]
also beacause it dosent support dell pentium core i7 in javascript
