### ISSUE TITLE
Use Pentium 4 and more Specs

### ISSUE THREAD

**Issue by Ganesha2282882** [copy/v86#313]
Use Pentium 4 and more Specs so we can use Windows 7, 10

**Comment by mmccall0813** [comment]
I don't think it works like that. You can't just switch the emulator to run a more modern CPU, that would probably need an entire rewrite of the emulator and hopes and dreams to emulate something like a Pentium or anything newer.

**Comment by filips123** [comment]
This could probably come with WebAssembly port (#246) and 64-bit support (#133) as it would already require a rewrite.
