### ISSUE TITLE
Is it possible also to Emulate .exe Files?

### ISSUE THREAD

**Issue by LavaMensch** [copy/v86#316]
Hey,

i wanted to inform me if this could be used as an thinfinity virtualui alternative? Also which License is this Software Licensed? Is it allowed to use it for Buisness Purposes?

Thanks

**Comment by copy** [comment]
It might be possible to combine v86 with wine to achieve something like that, but it's out of scope for this project.

The license is [BSD](https://en.wikipedia.org/wiki/BSD_licenses), which does commercial use if you follow the conditions in the [license text](https://raw.githubusercontent.com/copy/v86/master/LICENSE)
