### ISSUE TITLE
Running 64 bit operating systems

### ISSUE THREAD

**Issue by Erudite14** [copy/v86#317]
@copy 
Hi I've been looking at your work for a few months now and I had a few questions:

Is the x86 instruction set written in JavaScript and if so is it the instructions.js file in the src folder?

In the Readme.md in the main directory says that v86 emulates a Pentium level 1 CPU but in the cpu.js file underneath Resources it links to the manual for a Intel 80386 programmers manual, can you clarify this for me? Also is the CPU emulated in the CPU.js file?

 what would need to be done to make this project run a 64 bit operating system?

Please reply as quickly as possible.

**Comment by copy** [comment]
> Is the x86 instruction set written in JavaScript and if so is it the instructions.js file in the src folder?

Yes

> In the Readme.md in the main directory says that v86 emulates a Pentium level 1 CPU but in the cpu.js file underneath Resources it links to the manual for a Intel 80386 programmers manual, can you clarify this for me?

The 80386 manual does include some useful infos to get started, but we actually implement more features.

> what would need to be done to make this project run a 64 bit operating system?

It's quite a bit of work, see https://en.wikipedia.org/wiki/X86-64#Architectural_features. We already have an issue tracking this: https://github.com/copy/v86/issues/133
