### ISSUE TITLE
File questions

### ISSUE THREAD

**Issue by Erudite14** [copy/v86#318]
@copy 
I would really like to make this project run 64bit operating systems but I have a few more questions to ask: what JavaScript script files do you think/know would need to be updated  to run a 64 bit operating system I know the CPU.js needs to have some work done and instructions.js and msyi memory.js(I don't know if memory.js needs work can you confirm this for me?) but other than these files I don't know if any other file needs to be edited to be capable of 64bit can you include any other JavaScript files if I missed any

**Comment by BenNottelling** [comment]
A 64 bit cpu is capable of addressing more memory than a 32 bit so I would assume that memory.js need to be updated

**Comment by copy** [comment]
That's correct, memory.js needs to be changed. Also arith.js and misc_instr.js needs to be extended with new 64-bit instructions and modrm.js needs to be extended to handle 64-bit addressing.
