### ISSUE TITLE
Build/libv86.js and build/v86_all.js

### ISSUE THREAD

**Issue by Erudite14** [copy/v86#319]
@copy 

I have a question Build/libv86.js is created with the make command is invoked but I'm look through the index.html file and in the script tag is build/ v86_all.js can you clarify the confusion? Also I have a question about loader.js does load all the JavaScript files need to run a virtual machine in the browser.

**Comment by BenNottelling** [comment]
Libv86 is for using the API on your own webpage. The pages use v86_all.js instead
Look in the wiki for instructions on building it
