### ISSUE TITLE
V86 for PC 

### ISSUE THREAD

**Issue by Erudite14** [copy/v86#320]
@copy 

Is there a way to create a virtual machine on the actual computer (not just have the virtual machine run in a browser but to have it run on the actual computer) and have the browser act as a interface so when  someone closes the tab the virtual machine isn't destroyed. Is it possible to use node.js to accomplish this task?

**Comment by mmccall0813** [comment]
I can barely understand what you're trying to say, but about the "Node.js to prevent the VM from being destroyed when the user closes the tab". This MIGHT be possible, but it would be impractical and would take up <b>tons</b> of storage if there are a lot of people using the website.

**Comment by copy** [comment]
It's probably possible, but out of scope for this project.
