### ISSUE TITLE
2^53

### ISSUE THREAD

**Issue by Erudite14** [copy/v86#322]
@copy @BenNottelling 

Do you that that the fact that JavaScript can't represent numbers larger than 2^53 would make it impossible to run 64bit OS's or could I use Bigint to circumvent this problem?

**Comment by mmccall0813** [comment]
> Do you that that the fact th...

"Do you that that"

Might wanna edit this. And also, this is already very well known by the devs (not 100% sure but im like 99.98% sure)

**Comment by copy** [comment]
We're very aware of that, and have written some [weird code](https://github.com/copy/v86/blob/master/src/arith.js#L466) to work around it.

These days I would go straight for WebAssembly (e.g., C or Rust) to do any work towards 64-bit. There's a work-in-progress with some wasm parts, but no eta for a release yet.
