### ISSUE TITLE
kernel error in linux mint cinnnamon

### ISSUE THREAD

**Issue by james780** [copy/v86#326]
so i was trying to load into linux mint and i used 32-bit beacause in 64-bit it also gives me a kernel error  beacuase people on reddit were giving me advice to use 32-bit intead for 64-bit
![Screenshot 2020-03-10 at 08 24 10](https://user-images.githubusercontent.com/61988811/76316595-da9d6f80-62a8-11ea-89a6-091fc9fcfdb6.png)

**Comment by copy** [comment]
See #97. It's unlikely that we'll have this feature in the near future, I'd suggest installing a non-PAE kernel or trying a different distribution.
