### ISSUE TITLE
FPU FWAIT instruction

### ISSUE THREAD

**Issue by ker2x** [copy/v86#33]
Hello :)

I'm reading this : https://github.com/copy/v86/blob/master/src/fpu.js#L641
And the FWAIT instruction have "TODO".

I don't have a deep understanding of your code and there might be some stuff i don't understand with `setTimeout(function() { cpu.main_run(); }, 0);` but, to me it seems that FPU instructions are guaranteed to be  atomic and uninterruptible (in the emulator, not on real hardware).

So, isn't it just a NOP and there is absolutely nothing to implement ?

Thx :)

**Comment by ker2x** [comment]
http://www.website.masmforum.com/tutorials/fptute/fpuchap3.htm#fwait

FWAIT (CPU waits while FPU is busy)

Syntax:   fwait (no operand)
This instruction prevents the CPU from executing its next instruction if the Busy bit of the FPU's Status Word is set.

The FPU does not have direct access to the stream of instructions. It will start executing an instruction only when the CPU detects one in the code bits and transmits the information to the FPU. While the FPU is executing that instruction, the CPU can continue to execute in parallel other instructions which are not related to the FPU. Some of the FPU instructions being relatively slow, the CPU could execute several of its own instructions during that period.

The CPU also has some read/write access to the FPU's Status and Control registers even while the FPU is executing an instruction. In some cases, it may be desirable to read/write these registers without delay. But, in most cases, it is preferable or even necessary to wait until the FPU has completed the current instruction before proceeding with the read/write of these registers.

For example, a comparison by the FPU may require several clock cycles to execute and set the bits in the proper fields of the Status Word register. Waiting until the FPU has completed the operation and effectively updated the Status Word is a necessity if reading that Status Word is to have any meaning.

Many of the instructions which read or write to the FPU's Status and Control registers are automatically encoded with the fwait code.
Whenever the FPU is instructed to store a result (such as an integer) intended to be used by a CPU instruction, the latter should be preceded by an explicit FWAIT instruction. (For example, storing the content of a data register to memory as an integer may take some 30 clock cycles to complete.)

Note: Original versions of MASM were inserting an FWAIT instruction in front of every FPU instruction except those specified as "no-wait". This may have been necessary with the earlier co-processors but not on the more modern ones. Such coding may be observed if some old code is disassembled. The CPU can now poll the Busy bit of the Status Word whenever necessary before sending data processing instructions to the FPU.

**Comment by copy** [comment]
Thanks. That's correct. It's phrased a bit differently in the latest manuals, see http://x86.renejeschke.de/html/file_module_x86_id_324.html. 

I'll update the comment.
