### ISSUE TITLE
Adding Kali Linux

### ISSUE THREAD

**Issue by BatDev0** [copy/v86#331]
Enhancment

Add Kali Linux?

**Comment by pitust** [comment]
Why would you want Kali Linux? It's not like it has anny access to local network or anything.

**Comment by pitust** [comment]
And if you can set up a local netowrk for v86, you could just chroot kali linux anyway. because the network service needs linux anyway.

**Comment by copy** [comment]
Probably a bad idea. If there's any tools that make sense having in v86 like a disassembler or so, I can put them into the Arch image.
