### ISSUE TITLE
Cannot boot 9front due to APIC issues

### ISSUE THREAD

**Issue by ddevault** [copy/v86#332]
ISO from here:

http://9front.org/iso/

It almost boots, but runs into this:

https://code.9front.org/hg/plan9front/file/d416b601a9df/sys/src/9/pc/mp.c#l167

**Comment by copy** [comment]
Done: https://copy.sh/v86/?profile=9front

Feel free to send me bootable disk image if you'd like to add anything.

**Comment by ddevault** [comment]
Nice, thanks!
