### ISSUE TITLE
How to disable sound?

### ISSUE THREAD

**Issue by jcubic** [copy/v86#333]
Running Linux give weird sounds (tested on Chrome/Fedora 30), is it possible to disable sound?

**Comment by copy** [comment]
Only through the browser at the moment.

**Comment by ErnWong** [comment]
Starting off with sound disabled and having an unmute/mute button might be a good idea, since in some cases Chrome [requires a gesture](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio) before audio is allowed to play.

**Comment by kilickerem066** [comment]
Right click on the tab, select "(Un)Mute site"

**Comment by copy** [comment]
Fixed in #568
