### ISSUE TITLE
A question about fullscreen.

### ISSUE THREAD

**Issue by 12brendon34** [copy/v86#337]
i have the example page save and restore running on my browser but i can't seem to figure out how to add a fullscreen button i have tried a few times but nothing seems to work.

**Comment by 12brendon34** [comment]
yes it does boot and run but it's difficult to use and it would be nice to have fullscreen.

**Comment by copy** [comment]
There's a button to switch to full screen. If you'd like to extend the examples, see https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
