### ISSUE TITLE
How do i make my own custom images?

### ISSUE THREAD

**Issue by shreejalmaharjan-27** [copy/v86#339]
How do i make my own custom images? I have searched everywhere, i couldnt find it

**Comment by BenNottelling** [comment]
You basically need to create a virtual machine and ensure that the hard drive format is RAW (that means no compression or anything else. )
Qemu works great for that. 
Install the operating system using your virtual machine and then you should be able to boot the raw disk image in v86

**Comment by shreejalmaharjan-27** [comment]
> You basically need to create a virtual machine and ensure that the hard drive format is RAW (that means no compression or anything else. )
> Qemu works great for that.
> Install the operating system using your virtual machine and then you should be able to boot the raw disk image in v86

can i get a bit of tutorial?(im new to this)
