### ISSUE TITLE
Oberon does not boot properly on v86

### ISSUE THREAD

**Issue by wee210** [copy/v86#340]
![Capture](https://user-images.githubusercontent.com/64658108/82606864-cb2e8280-9b85-11ea-81db-4c0fe84579ab.PNG)

(Note: I used Oberon from v86, not an external .img)
When I loaded Oberon on v86, it stayed on this garbled mess forever, even after multiple reloads and resets. It worked in the past, though, so I have no idea exactly what happened here.

**Comment by elixx** [comment]
I thought I was affected by this, too, but when I looked the other day, it seemed to be working for me.
Have you tried with both Firefox and Chrome?

**Comment by elixx** [comment]
It will take some time while loading: 
![image](https://user-images.githubusercontent.com/2325870/82607480-df26b400-9b86-11ea-8571-a1bcd8c7a9fa.png)

And then it should eventually start:
![image](https://user-images.githubusercontent.com/2325870/82607546-fe254600-9b86-11ea-8a9a-2478c5f872fd.png)

**Comment by wee210** [comment]
Unfortunately, I have used Firefox, Internet Explorer, Edge and Chrome, and nothing happened.
I also tried using old versions of Firefox, Chrome and Internet Explorer, no luck.

It stayed at the same screen, even after waiting for about 30 minutes.

**Comment by copy** [comment]
I can sometimes reproduce this, but never quite figured out the issue.

**Comment by elixx** [comment]
It's come and gone for me, a bunch of times. I had given up on it, and now it's working reliably for me. O_o

**Comment by pandruszkow** [comment]
I can confirm that it came up for me at around the 28 second mark. I'm using Firefox 78.0b8 (64-bit) on Windows 10 x64.

**Comment by kilickerem066** [comment]
I tested on **Avast Secure Browser**, **Google Chome**, **Mozilla Firefox** and **Microsoft Edge**. **Internet Explorer** is so slow for testing, so I don't tested on **Interent Explorer**. 

                                                                            ***BUT RESULTS ARE THE SAME! :(***

My operating system is **Microsoft Windows 10 x64** build *1909*, with a **4GB** of *RAM*, and with **Intel i3** processor.

**Comment by copy** [comment]
This should be fixed now (I made a new installation of Oberon that doesn't require a boot floppy).
