### ISSUE TITLE
Cannot 'make' when installing on linux.

### ISSUE THREAD

**Issue by h4yd3n-ng** [copy/v86#341]
I'm a newbie to this kind of stuff, and when running make build/libv86.js, I get the following result;
root@hn:/var/www/hn.fyi/test/emu/v86# make build/libv86.js
wget -P closure-compiler https://dl.google.com/closure-compiler/compiler-20190709.zip
--2020-05-24 13:45:58--  https://dl.google.com/closure-compiler/compiler-20190709.zip
Resolving dl.google.com (dl.google.com)... 2a00:1450:4007:805::200e, 216.58.204.110
Connecting to dl.google.com (dl.google.com)|2a00:1450:4007:805::200e|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7342217 (7.0M) [application/zip]
Saving to: ‘closure-compiler/compiler-20190709.zip.2’

compiler-20190709.zip.2                 100%[=============================================================================>]   7.00M  --.-KB/s    in 0.1s

2020-05-24 13:45:58 (47.5 MB/s) - ‘closure-compiler/compiler-20190709.zip.2’ saved [7342217/7342217]

unzip -d closure-compiler closure-compiler/compiler-20190709.zip \*.jar
Archive:  closure-compiler/compiler-20190709.zip
replace closure-compiler/closure-compiler-v20190709.jar? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: closure-compiler/closure-compiler-v20190709.jar
mv closure-compiler/*.jar closure-compiler/compiler.jar
mv: target 'closure-compiler/compiler.jar' is not a directory
Makefile:158: recipe for target 'closure-compiler/compiler.jar' failed
make: *** [closure-compiler/compiler.jar] Error 1

And it fails.

**Comment by copy** [comment]
Try `rm -r closure-compiler` and then run make again.
