### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by Ganesha2282882** [copy/v86#346]
Will you add a desktop app for v86? You could use nativefier or something like that but don't fall for paid plans. That is weird and i hate ':star: Upgrade' buttons.

**Comment by liudonghua123** [comment]
There are some desktop apps wrapped with electron. You can check and try https://github.com/felixrieseberg/windows95, https://github.com/liudonghua123/windows98.

**Comment by pandruszkow** [comment]
How are https://github.com/felixrieseberg/windows95 and https://github.com/liudonghua123/windows98 different from a desktop app for v86? The main way to turn v86 into a desktop app is to use Electron, something these two already do.
