### ISSUE TITLE
Windows 3.1 doesn't boot after splash screen

### ISSUE THREAD

**Issue by shreejalmaharjan-27** [copy/v86#349]
I have installed Windows 3.1 using qemu but in v86, when I type "win", the splash screen appears for a brief second and I am back to MS-DOS screen. What may possibly be issue here?

**Comment by shreejalmaharjan-27** [comment]
If I boot from qemu, I works.

**Comment by copy** [comment]
Indeed, see https://github.com/copy/v86/issues/208
