### ISSUE TITLE
Windows POSRedy 2006

### ISSUE THREAD

**Issue by 12brendon34** [copy/v86#356]
I'm creating this for me to document the process of installing / making a build of Windows POSRedy 2006 to boot on copy.sh/v86/. My goal is to try to create a version of Windows POSRedy 2006 that can run well and is very small like my windows xp 90mb ISO. and to post what I have made along the way. Even though it's based on windows xp service pack 3 technically its a completely different version of windows and a difficult challenge.

**Comment by 12brendon34** [comment]
lets start with the download link and a key
Windows Embedded POSReady 2009 microsoft download link 
https://www.microsoft.com/en-us/download/details.aspx?id=11196
Windows Embedded POSReady 2009 key
KFF8R-TMHF4-GKT2P-KGDHH-FXPMB

Windows Embedded POSReady 2009 iso size is 647mb
and the install size is around 520 minimum

**Comment by 12brendon34** [comment]
If you install the image onto a vhd you can mount it into windows via disk management and modify the vhd directly, and when you want to unmount it just left click and press eject

Mounting
open disk management
select Action menu at the top of the window, select attach vhd then navigate to the location of your vhd select it then it will be mounted

**Comment by 12brendon34** [comment]
this can be used to make modification to the OS like adding wallpapers changing and deleting themes deleting files and folders with full rights and much more.

**Comment by iiiGerardoiii** [comment]
Did you just open an issue to write notes?

**Comment by copy** [comment]
@12brendon34 I appreciate your work, but this probably belongs somewhere else.
