### ISSUE TITLE
Not an issue: Add support for pentium 3 or any AMD close to that timeframe 

### ISSUE THREAD

**Issue by JVGA8837** [copy/v86#358]
Not sure if it is possible but instead of emulating x64 CPUs, could it be possible to do pentium 3 or any AMD K around the same release of the Pentium 2 or 3

**Comment by copy** [comment]
Is there any OS in particular you would like to run?

**Comment by JVGA8837** [comment]
I would like to run either Xp or any type of server version like 2008, to host a mini web server. Since most of the time I don’t have access to my computer. Hope this in some way helps

**Comment by copy** [comment]
There are no plans to support anything newer than XP since it isn't abandonware. Closing.
