### ISSUE TITLE
Async loading of DOS doesn't seem to work

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#36]
Accessing http://copy.sh/v86/?profile=custom&fda.url=images/freedos722.img&fda.size=737280 makes FreeDOS just repeat it's name and never boot.

**Comment by ysangkok** [comment]
I think it might just be a problem on copy.sh, cause it seems to work locally.

**Comment by copy** [comment]
Yeah, the images are served with `Content-Encoding:gzip`, which shouldn't happen for responses with a partial content. Server misconfiguration.

**Comment by ysangkok** [comment]
But is this really the issue? If the chunks are gzipped, isn't it still transparent to the application?

Here's a hexdump where it looks like the data is decompressed correctly. In the Network tab in Chrome, I see the same. It's true that it says `Content-Encoding:gzip`, but this header will still be visible after decompressing. On my own server, it won't do range requests if I enable DEFLATE, so I didn't do that. It's interesting that your server does, but I don't understand how it would break something.

```
$ exec 5>&1; curl -D /dev/fd/5 --compress "copy.sh/v86/images/freedos722.img" | xxd | head 
HTTP/1.1 200 OK
Date: Mon, 16 Feb 2015 00:17:27 GMT
Server: Apache/2.2.3 (CentOS)
Last-Modified: Tue, 24 Jun 2014 23:35:47 GMT
ETag: "33001c-906d2-4fc9d6b4b3ac0"
Accept-Ranges: bytes
Content-Length: 591570
Connection: close
Content-Type: application/octet-stream
Content-Encoding: gzip

0000000: eb3c 9046 7265 6544 4f53 2000 0202 0100  .<.FreeDOS .....
0000010: 0270 00a0 05f9 0300 0900 0200 0000 0000  .p..............
0000020: 0000 0000 0000 29e8 5cc9 e44e 4f20 4e41  ......).\..NO NA
0000030: 4d45 2020 2020 4641 5431 3220 2020 fafc  ME    FAT12   ..
0000040: 31c0 8ed8 bd00 7cb8 e01f 8ec0 89ee 89ef  1.....|.........
0000050: b900 01f3 a5ea 5e7c e01f 0000 6000 8ed8  ......^|....`...
0000060: 8ed0 8d66 a0fb 807e 24ff 7503 8856 24c7  ...f...~$.u..V$.
0000070: 46c0 1000 c746 c201 00e8 e900 4672 6565  F....F......Free
0000080: 444f 5300 8b76 1c8b 7e1e 0376 0e83 d700  DOS..v..~..v....
0000090: 8976 d289 7ed4 8a46 1098 f766 1601 c611  .v..~..F...f....

**Comment by ysangkok** [comment]
Ah, executing `exec 5>&1; curl --trace-ascii /dev/fd/5 --compress -H "Range: bytes=0-100" "copy.sh/v86/images/freedos722.img" | wc -c` I see that the header says it's gzipped, but it seems like it's actually not. And curl outputs 0 bytes, probably because it can't decompress it.

**Comment by copy** [comment]
Fixed, thanks.

For future information, if you want to reroute requests to pre-gzipped files, exclude requests with a `Range` header (line 2 added):
```
RewriteCond %{HTTP:Accept-encoding} gzip
RewriteCond %{HTTP:Range} !bytes
RewriteCond %{REQUEST_FILENAME}.gz -s
RewriteRule ^(.+) $1\.gz [L]
```
