### ISSUE TITLE
(Not an issue)Update the v86 version on web browser

### ISSUE THREAD

**Issue by gitrats07** [copy/v86#361]
Can you update the v86 version on web browser please? The version on web browser is from 2018 and it's pretty old.
![image](https://user-images.githubusercontent.com/63937606/88367088-1008ac80-cdb5-11ea-8af1-e565d2ab604c.png)
And also, will you add more OSes in the Quickstart (like Windows 2000, Macintosh, or even Windows XP, Windows 7, macOS X)?

**Comment by ITAC85v2** [comment]
Windows 2000 could be added yourself via the source code. Of course, you'd have to obtain the image files and snapshots yourself, but you probably could get it working with the right configuration. In fact, Windows ME at some point might have been getting implemented as you can see below.
![image](https://user-images.githubusercontent.com/47468644/95366132-06b1bb00-08a1-11eb-8f7f-a89a7edbef83.png)
(found via [copy.sh debug mode](http://copy.sh/v86/debug.html))
Also, there really isn't a huge need to update the webpage, as it's open-source and anybody can request updates, as well as maybe include what they added.
One more thing: Windows XP, Windows 7 and macOS X are not abandonware yet, so they will not be added officially.

I just wanted to clarify that. But yes, an update would be nice to have.

**Comment by polygonnedpotato** [comment]
Also, Macintosh is impossible to virtualize using an x86 hypervisor, or almost any hypervisor. Macintosh System Software and macOS X can only run on PowerPC computers / Hypervisors.

**Comment by jackmawer** [comment]
> 
> 
> Also, Macintosh is impossible to virtualize using an x86 hypervisor, or almost any hypervisor. Macintosh System Software and macOS X can only run on PowerPC computers / Hypervisors.

macOS hasn't supported PowerPC since Snow Leopard in 2009.

**Comment by polygonnedpotato** [comment]
> > Also, Macintosh is impossible to virtualize using an x86 hypervisor, or almost any hypervisor. Macintosh System Software and macOS X can only run on PowerPC computers / Hypervisors.
> 
> macOS hasn't supported PowerPC since Snow Leopard in 2009.

what about macOS 8 or macOS 9?

**Comment by copy** [comment]
Done.

**Comment by gitrats07** [comment]
> Windows 2000 could be added yourself via the source code. Of course, you'd have to obtain the image files and snapshots yourself, but you probably could get it working with the right configuration. In fact, Windows ME at some point might have been getting implemented as you can see below.
> ![image](https://user-images.githubusercontent.com/47468644/95366132-06b1bb00-08a1-11eb-8f7f-a89a7edbef83.png)
> (found via [copy.sh debug mode](http://copy.sh/v86/debug.html))
> Also, there really isn't a huge need to update the webpage, as it's open-source and anybody can request updates, as well as maybe include what they added.
> One more thing: Windows XP, Windows 7 and macOS X are not abandonware yet, so they will not be added officially.
> 
> I just wanted to clarify that. But yes, an update would be nice to have.

thanks 👍
