### ISSUE TITLE
(Still not an issue)Better CPU and add GPU?

### ISSUE THREAD

**Issue by gitrats07** [copy/v86#362]
Can you make the cpu better (like pentium 3 or 4) and add a graphic card (like voodoo banshee or geforce 256) so we can play games and run more OSes?

**Comment by copy** [comment]
GPU is not planned, but a PR will be accepted. wrt CPUs see https://github.com/copy/v86/issues/358

**Comment by gitrats07** [comment]
what is a PR? I didn't know
