### ISSUE TITLE
It boots Windows LiveXP!

### ISSUE THREAD

**Issue by dilsonnn** [copy/v86#365]
Today I was playing around with some images and came across this heavy editted version of WinXP:
https://archive.org/details/livexp

I was surprised that it actually worked in v86 and even some tools like calculator and task manager are usable.

Congratulations to all the devs involved! :D

**Comment by copy** [comment]
Good to know, I'll consider putting it on the website. Closing in favour of https://github.com/copy/v86/issues/86.

**Comment by kilickerem066** [comment]
C O O L !

**Comment by gitrats07** [comment]
hey

**Comment by gitrats07** [comment]
the given link of livexp does not work
