### ISSUE TITLE
GNU GRUB can't load

### ISSUE THREAD

**Issue by Ganesha2282882** [copy/v86#366]
So I created a parody OS and tested it in Virtual x86 and it can't boot. The specs that I set were:

- 256 MB RAM
- 16 MB vRAM

And it does not boot. It just stays saying `Booting from CD/DVD...` I don't know if this is an issue of the vRAM or something!

In QEMU it works lovely.

A screenshot of the Virtual x86 VM:
![v86](https://user-images.githubusercontent.com/59745725/90931632-07fb5700-e3cb-11ea-8b73-8a693a1772e6.png)

A screenshot of the QEMU VM:
![QEMU](https://user-images.githubusercontent.com/59745725/90931715-3416d800-e3cb-11ea-9e16-c60d402fe11c.png)
(Yes, I use Comic Sans on my Host.)

**Comment by copy** [comment]
Should be fixed now.
