### ISSUE TITLE
Add SSE

### ISSUE THREAD

**Issue by jakiki6** [copy/v86#369]
Hey, I tried running [skiftOS](https://github.com/skiftOS/skift/) in v86 but it crashes because of some invalid opcodes which belong to SSE. Are there any plans to implement SSE?

**Comment by copy** [comment]
Yes, https://github.com/copy/v86/issues/48

**Comment by copy** [comment]
There's full SSE2 support now and skift works: https://copy.sh/v86/?profile=skift
