### ISSUE TITLE
XMS Swap not working in FreeDOS

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#37]
http://copy.sh/v86/?profile=custom&hda.url=http://k%C3%A6n.guru/files/doom19.img&fda.url=http://k%C3%A6n.guru/files/freedos-ipx1.img

It gets stuck after trying to load XMS Swap, I assume it's because it's trying to write to the disk. If I don't specify the hard drive, it boots, but has some issues.

These images work in QEMU and JPC.

**Comment by copy** [comment]
I can reproduce this. I'll see what's going on here. Thanks.
