### ISSUE TITLE
Windows 10 Show Its Boot Screen But Dis Not Boot 

### ISSUE THREAD

**Issue by lc67846** [copy/v86#376]
Maybe It Must Be My Copy Of Windows 10 Because I Got It Off The A Youtuber Website And That Youtuber Name Is Enderman And He Dis Windows Stuff

**Comment by pitust** [comment]
1) how do you know it doesn't boot win10, maybe it works but takes hours to start (iirc android did that)
2) Under linux emulation, the latest kernel is arch linux, kernel 4.40. My laptop run 5.90.
3) Windows 10 isn't abandonware, you can't put it up.
4) Why do you expect so much from a browser-based virtual machine? Just use proper solutions like QEMU.

**Comment by kilickerem066** [comment]
> 1. how do you know it doesn't boot win10, maybe it works but takes hours to start (iirc android did that)
> 2. Under linux emulation, the latest kernel is arch linux, kernel 4.40. My laptop run 5.90.This does not indicate support for the latest software.
> 3. Windows 10 isn't abandonware, you can't put it up.
> 4. Why do you expect so much from a browser-based virtual machine? Just use proper solutions like QEMU.

I totally agree with you

**Comment by copy** [comment]
Closing as v86 is very unlikely to support W10 at any point.

**Comment by lc67846** [comment]
k

**Comment by lc67846** [comment]
Here i Got Screenshots

**Comment by lc67846** [comment]
#378

**Comment by lc67846** [comment]
![Screenshot 2020-11-23 at 7 33 36 PM](https://user-images.githubusercontent.com/64691261/100941230-ee37d880-34be-11eb-8e13-1cdb8db726d0.png)
Boom

**Comment by pitust** [comment]
That was fixes for win98.

**Comment by gitrats07** [comment]
> ![Screenshot 2020-11-23 at 7 33 36 PM](https://user-images.githubusercontent.com/64691261/100941230-ee37d880-34be-11eb-8e13-1cdb8db726d0.png)
> Boom

did it works?

**Comment by abundant-ray** [comment]
windows 10 is never going to work on this as it requres a proper setup that cant be built in a browser
