### ISSUE TITLE
Windows 2000 not loading

### ISSUE THREAD

**Issue by abundant-ray** [copy/v86#377]
Windows 2000 boots to the setup screen but freezes 

![image](https://user-images.githubusercontent.com/62371914/100395883-9c024c00-30a7-11eb-88d8-6cf22d2959c9.png)

**Comment by kilickerem066** [comment]
This happens on Windows XP, too.
**It is not actually freezes, as you can see speed is 98kIPS.**
_This happens because v86 is too slow._

**Comment by abundant-ray** [comment]
How is it too slow? i can run the windows 98 setup just fine (cant actually install as there is nowhere to install) but i have sat here for quite a while with the speed sitting around 200 kLPS but it just stays at the same screen.

**Comment by abundant-ray** [comment]
i have seen how the build-in windows 98 is a bit slow and that is because of browser limitations but it still runs. so im a bit confused. maybe v86 just dosent like it?

**Comment by copy** [comment]
>  This happens because v86 is too slow.

This is incorrect, Windows 2000 is currently not supported by v86. See https://github.com/copy/v86/issues/296 for some discussion.

**Comment by abundant-ray** [comment]
How isen't it supported? i don't get a bsod it just never loads the setup.

**Comment by kilickerem066** [comment]
sorry

**Comment by kilickerem066** [comment]
> > This happens because v86 is too slow.
> 
> This is incorrect, Windows 2000 is currently not supported by v86. See #296 for some discussion.

Sorry :(
I am not an expert about v86

**Comment by copy** [comment]
With PC type set to Standard PC Windows 2000 seems to work pretty well in v86 (see below). 

![Screenshot_2021-01-16_21-58-28](https://user-images.githubusercontent.com/1816456/104830650-e66ea080-5880-11eb-82f9-cf75d6a41194.png)

I updated the Readme and fixed some minor issues. Also added Windows 2000 as a profile to the website: https://copy.sh/v86/?profile=windows2000. Now we can play Pinball.


![Screenshot_2021-01-16_22-02-33](https://user-images.githubusercontent.com/1816456/104830684-4bc29180-5881-11eb-87d1-6c3480a85899.png)
