### ISSUE TITLE
Linux can't seem to collect entropy

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#38]
http://copy.sh/v86/?profile=custom&cdrom.url=http://k%C3%A6n.guru/files/ttylinux-i386-5.3.iso

Boot goes great until "Generating DSS host key".

**Comment by ysangkok** [comment]
You can abort it with control-c though, and log in with root:root.

**Comment by copy** [comment]
It works for me. It takes quite long (about 7 minutes) though.

**Comment by ysangkok** [comment]
We can close this for my sake, I just wanted to let you know about this issue.
