### ISSUE TITLE
android X86 not working 

### ISSUE THREAD

**Issue by SavagePy10** [copy/v86#380]
![Screenshot_2020-12-01-12-33-24-98](https://user-images.githubusercontent.com/75002427/100860929-1a0d8b00-34cc-11eb-8add-9156ba2c63f4.jpg)

**Comment by SavagePy10** [comment]
Im on mobile so i need to enable "desktop site" option to make input work

**Comment by SomeDevHere** [comment]
There is this issue regarding getting Android x86 to work https://github.com/copy/v86/issues/224

**Comment by copy** [comment]
In your screenshot there's no hard error, you'll need to wait a bit longer. See also the related issue.
