### ISSUE TITLE
Do any of the preset operating systems support c compilers?

### ISSUE THREAD

**Issue by someotherotherguy** [copy/v86#383]
To familiarize myself with v86, I've been trying to write a simple c program and compile it using just the preset operating systems on the website. However, it appears I am out of my depth here as I can't seem to find any c compiler included among the presets. Is there some way to add one (e.g. to linux, freedos, etc.), or is it too difficult given the limitations of the emulator?

Thanks in advance!

**Comment by copy** [comment]
The FreeBSD profile has clang and the Arch Linux profile has gcc. Does that work for you?

**Comment by someotherotherguy** [comment]
Yes it does, thank you! Just one other question, what are the accepted file formats for adding a hard drive disk image? Is there a recommended way to add or create one in general?

**Comment by copy** [comment]
Only raw images are supported. I'd generally recommend going through the install process in qemu and using the resulting image in v86. There is some documentation for creating an Arch Linux image here: https://github.com/copy/v86/blob/master/docs/archlinux.md
