### ISSUE TITLE
Add files to filesystem from browser

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#39]
It would be really nice if there was a way to upload files to the home directory, like in jor1k. I think the same FS API is used, so it shouldn't be too hard. In jor1k, this works:

```
jor1kgui.message.Send('MergeFile', {
          name: ascii_filename,
          data: Uint8Array_instance
      });
```

**Comment by copy** [comment]
If I understand you correctly, this already exists: https://github.com/copy/v86/blob/master/docs/api.md#create_filestring-file-uint8array-data-functionobject-callback

Please let me know if the documentation is unclear or needs extensions (it's relatively new and plain).

**Comment by ysangkok** [comment]
Oh, I didn't see that. How do I get the emulator instance in the production build? Using the debug build, the emulator doesn't boot (an assertion fails).

**Comment by copy** [comment]
It's defined here: https://github.com/copy/v86/blob/master/src/browser/main.js#L520 
You can insert your code there. Alternatively, you can work on one of the library examples, see https://github.com/copy/v86/tree/master/docs/samples
In the latter case no compilation is necessary.

If an assertion fails it could be a bug, by the way.

**Comment by ysangkok** [comment]
Thanks for the tip! The assertion fails with the ttylinux-2015.01 image I
mentioned previously. I am currently working on adding a local HTTP proxy
so that it wouldn't be necessary to go through the proxy for all requests.

2015-02-22 0:40 GMT+01:00 Fabian <notifications@github.com>:

**Comment by ysangkok** [comment]
I see you fixed this, thanks.
