### ISSUE TITLE
win 2000 image 

### ISSUE THREAD

**Issue by inyourface34456** [copy/v86#390]
I put in a win 200 image (https://drive.google.com/file/d/1pnzOkjAEUX2COq4BQnkSffzYNAxsUJ1G/view?usp=sharing) and when it is done installing, will say that there is no hdd only after it has loaded everything.

**Comment by programmeruser2** [comment]
Perhaps try installing on QEMU first then uploading the disk image to v86?

**Comment by inyourface34456** [comment]
@programmeruser2 how do you do that
I am not that skilled

**Comment by copy** [comment]
Installing in v86 is not supported. I added a Windows 2000 profile to the website (experimental): https://copy.sh/v86/?profile=windows2000
