### ISSUE TITLE
Windows 7 actually boot!

### ISSUE THREAD

**Issue by gitrats07** [copy/v86#391]
I got Windows 7 Extreme Lite V2 actually boot on copy.sh
VM Configuration:
256MB Ram
32MB Video Memory
ACPI enabled
I got it booted, but unfortunately it requires 512MB Ram, so close...
I will soon update...
![IMG20210115152010](https://user-images.githubusercontent.com/63937606/104700496-d357b580-5746-11eb-9832-f22f9a3a224d.jpg)

**Comment by gitrats07** [comment]
i think we should try to install it with 512MB Ram

**Comment by inyourface34456** [comment]
where did you get the ios file

**Comment by gitrats07** [comment]
i got it from Bob Pony a long time ago

**Comment by gitrats07** [comment]
can i share the link here?

**Comment by copy** [comment]
> can i share the link here?

Let's not: https://forum.winworldpc.com/discussion/9882/rule-do-not-request-windows-xp-or-office-2000

**Comment by OfficialGH98** [comment]
@gitrats07 You cannot boot Windows 7 or Vista on copy.sh. According to WinWorld, it says you cannot request Windows XP or higher. You'll be immediately banned, so don't even try. Windows XP can work on copy.sh, though.

**Comment by OfficialGH98** [comment]
One time I try to use a Windows 7 Live CD, it failed, and displays a Windows Boot Manager Error.

**Comment by gitrats07** [comment]
ok i won't try

**Comment by OfficialGH98** [comment]
Thank you

**Comment by OfficialGH98** [comment]
Wait, @gitrats07, I made a mistake. You can actually run Windows 7 on copy.sh. Ignore the message I said 18 days ago. Please forgive me.

**Comment by OfficialGH98** [comment]
But however, you might need a Windows 7 PE ISO or a Windows 7 Lite IMG, but not all Windows 7 IMG files work on copy.sh. You also need ACPI enabled, too.

**Comment by OfficialGH98** [comment]
Plus, you need a really good computer, as running Windows 7 on copy.sh is really slow.

**Comment by OfficialGH98** [comment]
And I know by the fact that you **ABSOLUTELY** cannot run Windows 8.x or Windows 10 on copy.sh. It won't work. (apologies for posting more than 1 comment)

**Comment by IAW9927** [comment]
Please try to actually put in VRAM 256MB and RAM 1024/512MB/1GB (1024 MB)

**Comment by BYTRA0911** [comment]
i tried installing windows 7 super nano lite but this error shows up 
![Screenshot 2023-05-07 191005](https://user-images.githubusercontent.com/132814422/236676665-9edd8d5e-3d14-4a58-9b60-cc52f3ee9e46.jpg)
does anyone know how this fix this?

**Comment by spetterman66** [comment]
> i tried installing windows 7 super nano lite but this error shows up ![Screenshot 2023-05-07 191005](https://user-images.githubusercontent.com/132814422/236676665-9edd8d5e-3d14-4a58-9b60-cc52f3ee9e46.jpg) does anyone know how this fix this? maybe changing the iso?

**do it in a qemu virtual machine with hard disk and iso then run the hard disk in v86**

**Comment by incognito69420** [comment]
can you send me the link

**Comment by incognito69420** [comment]
btw i once booted up windows 10 for 0.5 seconds

**Comment by 36479756** [comment]
you can install fat windows 7 using qemu using .img &, also acpi *experiential*

**Comment by 36479756** [comment]
![download](https://github.com/copy/v86/assets/108029852/b4932903-abb2-498a-a354-f096de7f62c0)

**Comment by 36479756** [comment]
![download](https://github.com/copy/v86/assets/108029852/75319bd8-47f7-4e8f-aee5-985b31b6c519)
no

**Comment by 36479756** [comment]
![download](https://github.com/copy/v86/assets/108029852/afda3511-02c6-400d-9a9d-596700acb461)
newermind

**Comment by carterlion13sAltAcc** [comment]
I'm going to see if I can do it

**Comment by estefaniaespinosa959** [comment]
Can You Send A Link

**Comment by momonono17-dev** [comment]
vous voulez un lien voici tous les img fichier sauf windows 10 et 11:https://archive.org/details/windows-image-collection

**Comment by paa55389** [comment]
I'm going to see if you archived the ISO

**Comment by hadis1778** [comment]
guys how to use qemu in cmd and how to make a disk without qemu so it hass a prepared disk for windows 7 on copy.sh?

**Comment by SniffGo-search** [comment]
> One time I try to use a Windows 7 Live CD, it failed, and displays a Windows Boot Manager Error.

It's because you don't have ACPI on

**Comment by ClovisRouze** [comment]
im stuck with the driver problem can anyone tell me where to find it ?

**Comment by m4plus2** [comment]
@ibay613 No you can run Windows 7 im pretty sure. Not sure about 8 or 10 but i got 7 setup to boot up, And plus this thread is from 2021 i think Copy.sh has advanced a lot since

**Comment by manthetoad102-maker** [comment]
> [@ibay613](https://github.com/ibay613) I ended up booting windows 7 from img
