### ISSUE TITLE
win98 disk support

### ISSUE THREAD

**Issue by ethanaobrien** [copy/v86#394]
I tried uploading a vhd, vmdk, and a vdi but windows 98 gave the error

"Setup cannot install windows 98 on your computer.
An error was detected while trying to read or write to your hard disk.
To quit setup press F3"

What types of disk images does copy support? Do I need to use virtualbox to give the disk partitions first?

**Comment by pitust** [comment]
A few things:
 - the name of the emulator is `v86`, not `copy` (copy == the name of the author)
 - iirc the emulator uses raw images (usually img/bin)
 - there is a win98 image pre-made (http://copy.sh/v86/?profile=windows98)

**Comment by copy** [comment]
Like @pitust wrote, only raw images are supported. You can convert from most formats to raw using qemu-img.
