### ISSUE TITLE
Android x86 major update (I found the problem)

### ISSUE THREAD

**Issue by ethanaobrien** [copy/v86#397]
Hello, I am continuing off of [this thread](https://github.com/copy/v86/issues/224) (kind of). It was kinda an old thread which is why I am making another thread. 
As @BenNottelling said in the thread mentioned we need SSE3 to be able to boot android 4.1 or newer.
There is a non SSE3 build on [this website](https://sites.google.com/site/twisteroidambassador/android-x86/kitkat-non-sse3-build). @BenNottelling also tried to boot this but it did not work. I managed to get it to boot. I pressed tab on the `LIVE CD - VESA mode` option and changed andoridboot.hardware to `androidboot.hardware=eeepc` As shown in the screenshot. (PLEASE NOTE that the `_` in the screenshot after `eeepc` is actually my mouse cursor.) I tried changing `androidboot.hardware` to this `eeepc` factor on the android x86 official image and all I got was a crash.
![download (1)](https://user-images.githubusercontent.com/77750390/106323182-9c040100-623c-11eb-8039-7fe68fb67526.png)
And here is the boot log
![download](https://user-images.githubusercontent.com/77750390/106328164-f30dd400-6244-11eb-9c15-836d15775cdf.png)
After an hour of waiting (because I am using a chromebook (with x86_64 cpu)) I got this
![Screenshot 2021-01-29 2 27 50 PM](https://user-images.githubusercontent.com/77750390/106324335-8f80a800-623e-11eb-860d-169182d8df98.png)
None of my clicks seemed to do anything (Might be a problem with this custom build) but I could move the mouse. This proves that the SSE3 aspect is the reason modern builds of android x86 are not working, therefore we have 2 options that we can do if the demand for android is high enough

Option 1 - Someone can build their own custom build (As described [here](https://sites.google.com/site/twisteroidambassador/android-x86/kitkat-non-sse3-build)) and put it up for all v86 users (this option would take a lot of work, even on the website the image he used did not properly run apks)

Option 2 - We implement SSE3 into v86 (I dont know a whole lot about SSE3 so I dont know what the difficulty would be)

SSE3 IS THE REASON WHY Android x86 WILL NOT BOOT. (and the fact that I had to change the `androidboot.hardware` variable to `eeepc`)

**Comment by omerjerk** [comment]
Can you post the custom build also? Just to get everyone on same page. Thank you!. :)

Amazing progress.

**Comment by cleanremote** [comment]
Does anyone know why this error happens in #393? It happens after the BIOS but before the Windows logo shows up. Windows is trying to do something that causes the emulator to crash.

**Comment by cleanremote** [comment]
It that gets fixed, Windows 8/10 might work in v86

**Comment by ethanaobrien** [comment]
If SSE2 is supported is SSE3 the same thing or are they 2 different things?

**Comment by ethanaobrien** [comment]
I got... Closer? This is android 4.4 r5 in debug.html with everything enabled and I made a few changes to the boot line.
![download (3)](https://user-images.githubusercontent.com/77750390/106489211-22595680-647a-11eb-9c27-c394a0d8bb63.png)

**Comment by ethanaobrien** [comment]
In virtualbox, you have to use android you have to change the graphics controller from vmsVGA to VboxVGA, if you dont change it all you get is a command line. Could this be the problem?

**Comment by copy** [comment]
> If SSE2 is supported is SSE3 supported? Are they the same thing or are they 2 different things?

SSE3 is version 3 of SSE. So no, SSE2 doesn't imply SSE3. I don't think SSE3 is the reason that Android isn't working, but contributions are welcome. SSE3 only has 13 new instructions. In the screenshots that you posted, it looks like a performance problem. Even with the wasm jit, v86 is still 10x-100x slower than hardware.

**Comment by ethanaobrien** [comment]
@copy 
Yeah, I think that's the problem now that I think about it.

In virtualbox, I installed android x86, But I didn't have on hardware accelerated virtualization, and until I enabled this the speed was about the same as android goes inside v86.

To put it simply - v86 WILL NEVER be able to run android x86. (not unless we could use hardware accelerated virtualization, which I am going to assume is impossible.)

**Comment by copy** [comment]
> To put it simply - v86 WILL NEVER be able to run android x86. (not unless we could use hardware accelerated virtualization, which I am going to assume is impossible.)

I wouldn't quite agree with this conclusion, but let's just agree that at the moment the performance isn't good enough.
