### ISSUE TITLE
Starting of the provided test images fail

### ISSUE THREAD

**Issue by s-macke** [copy/v86#4]
Hi,

I cloned the repository, compiled and downloaded the test images from the demo website and put them into the folder images/

The emulator starts but within one seconds the kIPS counter stops with zero and nothing happens. There is no error message. The image seems to be loaded according to Firefox and Chrome. The same happens when you select the file.

My console output in Firefox (debug.html) looks as follows:

Expected declaration but found '/'.  Skipped to next declaration. @ http://localhost:8080/v86/v86.css:28
Expected declaration but found '/'.  Skipped to next declaration. @ http://localhost:8080/v86/v86.css:29
Expected declaration but found '/'.  Skipped to next declaration. @ http://localhost:8080/v86/v86.css:31
Expected declaration but found '/'.  Skipped to next declaration. @ http://localhost:8080/v86/v86.css:32
Expected declaration but found '/'.  Skipped to next declaration. @ http://localhost:8080/v86/v86.css:33
"[PCI ] PCI:  enabled=1 bdf=38 addr=0 80003800"
"[PCI ] PCI:  enabled=1 bdf=40 addr=0 80004000"
"[PCI ] PCI:  enabled=1 bdf=48 addr=0 80004800"
"[PCI ] PCI:  enabled=1 bdf=50 addr=0 80005000"
"[PCI ] PCI:  enabled=1 bdf=58 addr=0 80005800"
"[PCI ] PCI:  enabled=1 bdf=60 addr=0 80006000"
"[PCI ] PCI:  enabled=1 bdf=68 addr=0 80006800"
"[PCI ] PCI:  enabled=1 bdf=70 addr=0 80007000"
"[PCI ] PCI:  enabled=1 bdf=78 addr=0 80007800"
"[PCI ] PCI:  enabled=1 bdf=80 addr=0 80008000"
"[PCI ] PCI:  enabled=1 bdf=88 addr=0 80008800"
"[PCI ] PCI:  enabled=1 bdf=90 addr=0 80009000"
"[PCI ] PCI:  enabled=1 bdf=98 addr=0 80009800"
"[PCI ] PCI:  enabled=1 bdf=A0 addr=0 8000A000"
"[PCI ] PCI:  enabled=1 bdf=A8 addr=0 8000A800"
"[PCI ] PCI:  enabled=1 bdf=B0 addr=0 8000B000"
"[PCI ] PCI:  enabled=1 bdf=B8 addr=0 8000B800"
"[PCI ] PCI:  enabled=1 bdf=C0 addr=0 8000C000"
"[PCI ] PCI:  enabled=1 bdf=C8 addr=0 8000C800"
"[PCI ] PCI:  enabled=1 bdf=D0 addr=0 8000D000"
"[PCI ] PCI:  enabled=1 bdf=D8 addr=0 8000D800"
"[PCI ] PCI:  enabled=1 bdf=E0 addr=0 8000E000"
"[PCI ] PCI:  enabled=1 bdf=E8 addr=0 8000E800"
"[PCI ] PCI:  enabled=1 bdf=F0 addr=0 8000F000"
"[PCI ] PCI:  enabled=1 bdf=F8 addr=0 8000F800"
"[BIOS] Unable to unlock ram - bridge not found"
"[PCI ] PCI:  enabled=1 bdf=0 addr=0 80000000"
"[BIOS] Ram Size=0x04000000 (0x0000000000000000 high)"
"[BIOS] malloc preinit"
"[BIOS] Relocating init from 0x000e2d21 to 0x03fe37a0 (size 51092)"
"[BIOS] malloc init"
"[IO  ] write port #510 <- 00  (PORT_QEMU_CFG_CTL)"
"[IO  ] write port #511 <- 00  (PORT_QEMU_CFG_DATA)"
"[IO  ] read port  #511  (PORT_QEMU_CFG_DATA)"
"[BIOS] init ivt"
"[RTC ] cmos write index F: 0"
"[BIOS] init bda"
"[BIOS] init bios32"
"[BIOS] init PMM"
"[BIOS] init keyboard"
"[BIOS] init mouse"
"[IO  ] write port #00D <- 00  (PORT_DMA1_MASTER_CLEAR)"
"[IO  ] write port #0DA <- 00  (PORT_DMA2_MASTER_CLEAR)"
"[IO  ] write port #0D6 <- C0  (PORT_DMA2_MODE_REG)"
"[IO  ] write port #0D4 <- 00  (PORT_DMA2_MASK_REG)"
"[BIOS] init pic"
"[PIC ] icw1 = 11"
"[PIC ] interrupts are mapped to 8 (master)"
"[PIC ] interrupts are mapped to 70 (slave)"
"[PIC ] icw3: 4"
"[PIC ] icw3: 2"
"[PIC ] icw4: 1"
"[BIOS] math cp init"
"[IO  ] write port #061 <- 11  (PORT_PS2_CTRLB)"
"[PIT ] Control: mode=0 ctr=2 read_mode=3 bcd=0"
"[PIT ] counter2 reload=800 tick=1.7164192656729511ms"
"[IO  ] write port #061 <- 10  (PORT_PS2_CTRLB)"
"[BIOS] CPU Mhz=9"
"[BIOS] init timer"
"[PIT ] Control: mode=2 ctr=0 read_mode=3 bcd=0"
"[PIT ] counter0 reload=FFFF tick=54.92457840618987ms"
"[RTC ] Periodic interrupt, a=26 t=0.9765625"
"[RTC ] cmos write index D: 2"
"[RTC ] cmos read from index D"
"[BIOS] pci setup"
"[BIOS] === PCI bus & bridge init ==="
"[PCI ] PCI:  enabled=1 bdf=0 addr=0 80000000"
"[BIOS] PCI: pci_bios_init_bus_rec bus = 0x0"
"[PCI ] PCI:  enabled=1 bdf=0 addr=0 80000000"
"[PCI ] PCI:  enabled=1 bdf=8 addr=0 80000800"
"[PCI ] PCI:  enabled=1 bdf=10 addr=0 80001000"
"[PCI ] PCI:  enabled=1 bdf=18 addr=0 80001800"
"[PCI ] PCI:  enabled=1 bdf=20 addr=0 80002000"
"[PCI ] PCI:  enabled=1 bdf=28 addr=0 80002800"
"[PCI ] PCI:  enabled=1 bdf=30 addr=0 80003000"
"[PCI ] PCI:  enabled=1 bdf=38 addr=0 80003800"
"[PCI ] PCI:  enabled=1 bdf=40 addr=0 80004000"
"[PCI ] PCI:  enabled=1 bdf=48 addr=0 80004800"
"[PCI ] PCI:  enabled=1 bdf=50 addr=0 80005000"
"[PCI ] PCI:  enabled=1 bdf=58 addr=0 80005800"
"[PCI ] PCI:  enabled=1 bdf=60 addr=0 80006000"
"[PCI ] PCI:  enabled=1 bdf=68 addr=0 80006800"
"[PCI ] PCI:  enabled=1 bdf=70 addr=0 80007000"
"[PCI ] PCI:  enabled=1 bdf=78 addr=0 80007800"
"[PCI ] PCI:  enabled=1 bdf=80 addr=0 80008000"
"[PCI ] PCI:  enabled=1 bdf=88 addr=0 80008800"
"[PCI ] PCI:  enabled=1 bdf=90 addr=0 80009000"
"[PCI ] PCI:  enabled=1 bdf=98 addr=0 80009800"
"[PCI ] PCI:  enabled=1 bdf=A0 addr=0 8000A000"
"[PCI ] PCI:  enabled=1 bdf=A8 addr=0 8000A800"
"[PCI ] PCI:  enabled=1 bdf=B0 addr=0 8000B000"
"[PCI ] PCI:  enabled=1 bdf=B8 addr=0 8000B800"
"[PCI ] PCI:  enabled=1 bdf=C0 addr=0 8000C000"
"[PCI ] PCI:  enabled=1 bdf=C8 addr=0 8000C800"
"[PCI ] PCI:  enabled=1 bdf=D0 addr=0 8000D000"
"[PCI ] PCI:  enabled=1 bdf=D8 addr=0 8000D800"
"[PCI ] PCI:  enabled=1 bdf=E0 addr=0 8000E000"
"[PCI ] PCI:  enabled=1 bdf=E8 addr=0 8000E800"
"[PCI ] PCI:  enabled=1 bdf=F0 addr=0 8000F000"
"[PCI ] PCI:  enabled=1 bdf=F8 addr=0 8000F800"
"[PCI ] PCI:  enabled=1 bdf=0 addr=0 80000000"
"[PCI ] PCI:  enabled=1 bdf=8 addr=0 80000800"
"[PCI ] PCI:  enabled=1 bdf=10 addr=0 80001000"
"[PCI ] PCI:  enabled=1 bdf=18 addr=0 80001800"
"[PCI ] PCI:  enabled=1 bdf=20 addr=0 80002000"
"[PCI ] PCI:  enabled=1 bdf=28 addr=0 80002800"
"[PCI ] PCI:  enabled=1 bdf=30 addr=0 80003000"
"[PCI ] PCI:  enabled=1 bdf=38 addr=0 80003800"
"[PCI ] PCI:  enabled=1 bdf=40 addr=0 80004000"
"[PCI ] PCI:  enabled=1 bdf=48 addr=0 80004800"
"[PCI ] PCI:  enabled=1 bdf=50 addr=0 80005000"
"[PCI ] PCI:  enabled=1 bdf=58 addr=0 80005800"
"[PCI ] PCI:  enabled=1 bdf=60 addr=0 80006000"
"[PCI ] PCI:  enabled=1 bdf=68 addr=0 80006800"
"[PCI ] PCI:  enabled=1 bdf=70 addr=0 80007000"
"[PCI ] PCI:  enabled=1 bdf=78 addr=0 80007800"
"[PCI ] PCI:  enabled=1 bdf=80 addr=0 80008000"
"[PCI ] PCI:  enabled=1 bdf=88 addr=0 80008800"
"[PCI ] PCI:  enabled=1 bdf=90 addr=0 80009000"
"[PCI ] PCI:  enabled=1 bdf=98 addr=0 80009800"
"[PCI ] PCI:  enabled=1 bdf=A0 addr=0 8000A000"
"[PCI ] PCI:  enabled=1 bdf=A8 addr=0 8000A800"
"[PCI ] PCI:  enabled=1 bdf=B0 addr=0 8000B000"
"[PCI ] PCI:  enabled=1 bdf=B8 addr=0 8000B800"
"[PCI ] PCI:  enabled=1 bdf=C0 addr=0 8000C000"
"[PCI ] PCI:  enabled=1 bdf=C8 addr=0 8000C800"
"[PCI ] PCI:  enabled=1 bdf=D0 addr=0 8000D000"
"[PCI ] PCI:  enabled=1 bdf=D8 addr=0 8000D800"
"[PCI ] PCI:  enabled=1 bdf=E0 addr=0 8000E000"
"[PCI ] PCI:  enabled=1 bdf=E8 addr=0 8000E800"
"[PCI ] PCI:  enabled=1 bdf=F0 addr=0 8000F000"
"[PCI ] PCI:  enabled=1 bdf=F8 addr=0 8000F800"
"[BIOS] === PCI device probing ==="
"[BIOS] PCI probe"
"[PCI ] PCI:  enabled=1 bdf=0 addr=0 80000000"
"[PCI ] PCI:  enabled=1 bdf=8 addr=0 80000800"
"[PCI ] PCI:  enabled=1 bdf=10 addr=0 80001000"
"[PCI ] PCI:  enabled=1 bdf=18 addr=0 80001800"
"[PCI ] PCI:  enabled=1 bdf=20 addr=0 80002000"
"[PCI ] PCI:  enabled=1 bdf=28 addr=0 80002800"
"[PCI ] PCI:  enabled=1 bdf=30 addr=0 80003000"
"[PCI ] PCI:  enabled=1 bdf=38 addr=0 80003800"
"[PCI ] PCI:  enabled=1 bdf=40 addr=0 80004000"
"[PCI ] PCI:  enabled=1 bdf=48 addr=0 80004800"
"[PCI ] PCI:  enabled=1 bdf=50 addr=0 80005000"
"[PCI ] PCI:  enabled=1 bdf=58 addr=0 80005800"
"[PCI ] PCI:  enabled=1 bdf=60 addr=0 80006000"
"[PCI ] PCI:  enabled=1 bdf=68 addr=0 80006800"
"[PCI ] PCI:  enabled=1 bdf=70 addr=0 80007000"
"[PCI ] PCI:  enabled=1 bdf=78 addr=0 80007800"
"[PCI ] PCI:  enabled=1 bdf=80 addr=0 80008000"
"[PCI ] PCI:  enabled=1 bdf=88 addr=0 80008800"
"[PCI ] PCI:  enabled=1 bdf=90 addr=0 80009000"
"[PCI ] PCI:  enabled=1 bdf=98 addr=0 80009800"
"[PCI ] PCI:  enabled=1 bdf=A0 addr=0 8000A000"
"[PCI ] PCI:  enabled=1 bdf=A8 addr=0 8000A800"
"[PCI ] PCI:  enabled=1 bdf=B0 addr=0 8000B000"
"[PCI ] PCI:  enabled=1 bdf=B8 addr=0 8000B800"
"[PCI ] PCI:  enabled=1 bdf=C0 addr=0 8000C000"
"[PCI ] PCI:  enabled=1 bdf=C8 addr=0 8000C800"
"[PCI ] PCI:  enabled=1 bdf=D0 addr=0 8000D000"
"[PCI ] PCI:  enabled=1 bdf=D8 addr=0 8000D800"
"[PCI ] PCI:  enabled=1 bdf=E0 addr=0 8000E000"
"[PCI ] PCI:  enabled=1 bdf=E8 addr=0 8000E800"
"[PCI ] PCI:  enabled=1 bdf=F0 addr=0 8000F000"
"[PCI ] PCI:  enabled=1 bdf=F8 addr=0 8000F800"
"[BIOS] Found 0 PCI devices (max PCI bus is 00)"
"[BIOS] === PCI new allocation pass #1 ==="
"[BIOS] PCI: check devices"
"[BIOS] === PCI new allocation pass #2 ==="
"[BIOS] PCI: No VGA devices found"
"[BIOS] No apic - only the main cpu is present."
"[BIOS] init ACPI tables"
"[BIOS] Scan for VGA option rom"
"[BIOS] Running option rom at c000:0003"
"[BIOS] Start SeaVGABIOS (version rel-1.7.3-74-g3061815-dirty-20131005_235930-eevee)"
"[PCI ] PCI:  enabled=1 bdf=0 addr=0 80000000"
"[BIOS] VBE DISPI: lfb_addr=e0000000, size 8 MB"
"[BIOS] Removing mode 11c"
"[BIOS] Removing mode 11d"
"[BIOS] Removing mode 11e"
"[BIOS] Removing mode 11f"
"[BIOS] Removing mode 147"
"[BIOS] Removing mode 17e"
"[BIOS] Removing mode 17f"
"[BIOS] Removing mode 180"
"[BIOS] Removing mode 181"
"[BIOS] Removing mode 182"
"[BIOS] Removing mode 183"
"[BIOS] Removing mode 184"
"[BIOS] Removing mode 185"
"[BIOS] Removing mode 186"
"[BIOS] Removing mode 187"
"[BIOS] Removing mode 188"
"[BIOS] Removing mode 189"
"[BIOS] Removing mode 18a"
"[BIOS] Removing mode 18b"
"[BIOS] Removing mode 18c"

**Comment by ItsTheAwesomestChannel85** [comment]
If you Çee this message right no,kÞleaseØdial (8lÒ) ###-#### and tell›hem that yäu haveëfoun
 úhs flasE drive, and go to our address,MwhicÆ s 32½¤West 22nd Strent, Co##n ton K(####4. ‚nce yoØ getŠthere, tell uÁ tat you h›ve found §his flÅsh drive a‘dötha| weÌshould caim it bacN if we w]nt itk If we say no, *ou are fèee to do w_atever you wznt to th×s flaÌh driv¢. Else, y©u do NO{ pave pe:mission to change any con
ents of thisBf¬ash driz or even des~roy the flxsh drive!
 §Thaßk you!
ˆ
N¥te t’at if you gžve Ahe flash nri˜eTdamaged or the ©oñÁents of the flash driveßwas chs7ged, tuere my be a chance´that we may dial 911 =ue to invading ÷popôe' ñrvacy.
