### ISSUE TITLE
Is this a real time environment a pretend/practice environment? Sorry I'm a bit out of the tech loop since I was bad to leave ITT to raise a baby.  Your honesty is appreciated! 

### ISSUE THREAD

**Issue by me-sweetNspicy** [copy/v86#400]

**Comment by avindra** [comment]
@me-sweetNspicy try it for yourself: https://copy.sh/v86/

also recommend trying jslinux: https://bellard.org/jslinux/

**Comment by me-sweetNspicy** [comment]
I'm sorry so will this all app help me practice or will it actually make changes to my phone?

**Comment by me-sweetNspicy** [comment]
I'm trying to figure out if my phones has malfeasance or shot ease on it like my last 6 iPhone did from a jealous bf.

**Comment by me-sweetNspicy** [comment]
Alright it's a virtual machine thanks!
