### ISSUE TITLE
Windows 7 works?

### ISSUE THREAD

**Issue by techydud** [copy/v86#401]
![image](https://user-images.githubusercontent.com/71298520/107467041-fabd5a80-6b19-11eb-80a7-fdb18d700bd7.png)

**Comment by techydud** [comment]
![image](https://user-images.githubusercontent.com/71298520/107468646-360d5880-6b1d-11eb-8663-535984e8c6c9.png)

**Comment by techydud** [comment]
![image](https://user-images.githubusercontent.com/71298520/107468773-7967c700-6b1d-11eb-8517-d8780d4432fa.png)

Still loading

**Comment by techydud** [comment]
Finally.... After 30 minutes.... The moment of Truth
![image](https://user-images.githubusercontent.com/71298520/107469790-44f50a80-6b1f-11eb-9911-d3e217684dfa.png)
By the way I had to use a cut down version of Windows 7

**Comment by techydud** [comment]
![image](https://user-images.githubusercontent.com/71298520/107550457-e9119c80-6b85-11eb-95d7-b4c6f1bc4505.png)
A little help?

**Comment by ethanaobrien** [comment]
Install within qemu, then try to run in v86 and see what happen @techydud

**Comment by techydud** [comment]
Sorry, but I'm kind of a noob when it comes to Qemu commands so... a little help here?

**Comment by techydud** [comment]
Also, is there a way to run Windows 8/8.1/10/XP?

**Comment by ethanaobrien** [comment]
Idk, try it out in qemu and try to import it to v86. And Yeah, I created 3 batch scripts (because qemu is a bit complicated) 1 to create a raw disk image, 1 to run 32 bit and 1 to run 64 bit. Assuming you use windows I uploaded the files to this repository. [](https://github.com/ethanaobrien/qemu-batch-scripts) Any questions? Just ask me! 

p.s. In my opinion, windows vista was the best.

**Comment by techydud** [comment]
Where is the repository? And, maybe you could copy/paste in the .bat contents for the raw disk image here? (I'm new to this stuff)

**Comment by ethanaobrien** [comment]
Sorry. Thought I sent the link. And I cant copy and paste the batch file contents, it would make things really complicated. [https://github.com/ethanaobrien/qemu-batch-scripts](https://github.com/ethanaobrien/qemu-batch-scripts)

**Comment by techydud** [comment]
How big should my raw disk image be for Windows 7?

**Comment by techydud** [comment]
Considering its a super thin Windows 7 ISO (1.46GB) and its 32-bit.

**Comment by ethanaobrien** [comment]
At least 20 gigabytes. I recommend 35 or so. Only 32 bit systems are supported in v86 so make sure you dont install a 64 bit operating system.

**Comment by ethanaobrien** [comment]
If its a thin disk then idk. I would still use at least 20 gb just in case.

**Comment by techydud** [comment]
Jeez, thats a lot, but what exaclty is a raw disk image? Is it the virtual storage for Windows?

**Comment by ethanaobrien** [comment]
Yes, the disk image is like the hard drive for your virtual computer.

**Comment by techydud** [comment]
Will Qemu portable work with your batch files?

**Comment by ethanaobrien** [comment]
It should work as long as the folder is on the desktop named qemu and that when you click on this folder you should not have to click into any sub-directories to be able to see the qemu-system-i386 or something like that. To test go to windows explorer and copy and paste this `%USERPROFILE%\Desktop\qemu\qemu-system-i386.exe` It will work as long as it does not say that the file is not found.

**Comment by ethanaobrien** [comment]
@techydud there was a bug I found in the create qemu image. If it wasnt working, it should work now

**Comment by techydud** [comment]
Yeah, when I entered the amount of GB, it would just close and do nothing. 

p.s, windows 7 is my favorite

**Comment by ethanaobrien** [comment]
@techydud did you download the new version of the create qemu image.bat ?

**Comment by ethanaobrien** [comment]
PLEASE NOTE that the bat file should be on your desktop next to your qemu folder

**Comment by techydud** [comment]
Does Ubuntu 32-bit run on v86?

**Comment by ethanaobrien** [comment]
yes

**Comment by pitust** [comment]
> yes

Did you try it though?

**Comment by Unzor** [comment]
> ![image](https://user-images.githubusercontent.com/71298520/107550457-e9119c80-6b85-11eb-95d7-b4c6f1bc4505.png) A little help?

You should probably upload a hard disk image along with the CDROM. You can either use it by creating a file named "disk.img" or running:
```
qemu-img -f raw disk.img 60G
```
