### ISSUE TITLE
Requirement URL update request

### ISSUE THREAD

**Issue by levelKro** [copy/v86#407]
The requirement for compiling with the Google Closure Compiler has changed, need to remove details about the LATEST download for this one;
`https://dl.google.com/closure-compiler/compiler-20200719.zip`

The notice about the remove of symlink for the latest was available here: https://github.com/google/closure-compiler/wiki/Binary-Downloads . No more binary was compiled on the GitHub, but source are always updated.

Or and you can also provide steps to compile from the Git with help of this page;
`https://github.com/google/closure-compiler#building-it-yourself`

**Comment by copy** [comment]
The Makefile was already doing the right thing when this issue was opened: https://github.com/copy/v86/blob/c4843ce/Makefile#L240

I updated the wiki, thanks.
