### ISSUE TITLE
Windows 3.1 not starting

### ISSUE THREAD

**Issue by abundant-ray** [copy/v86#409]
I tried to use windows 3.1, i read some other issue about it not working so i thought i would just play around with it but it just gets stuck here
![image](https://user-images.githubusercontent.com/62371914/110034285-204b2600-7d9f-11eb-83e8-cdea2d723734.png)
it just stays here and isent doing anything. any ideas?

I have tried with acpi on and off but it hasent fixed anything. tried different memory values but nothing has changed. :(

**Comment by copy** [comment]
Duplicate of https://github.com/copy/v86/issues/208
