### ISSUE TITLE
source not working for me

### ISSUE THREAD

**Issue by abundant-ray** [copy/v86#410]
I made a clone of this using the clone command and i installed make and everything it needs but when i type 'make' in the v86 folder it does this
![image](https://user-images.githubusercontent.com/62371914/110049330-82fbec00-7db6-11eb-9bd2-285405fcc268.png)

I have tried to just run the main html file and it gets me to this screen
![image](https://user-images.githubusercontent.com/62371914/110049382-9e66f700-7db6-11eb-8bd7-cf122c0c0096.png)

but i cant interact with them, none of the buttons work and i cant run my own files. it just stays on this screen.

**Comment by copy** [comment]
See [Dockerfile](https://github.com/copy/v86/blob/master/tools/docker/test-image/Dockerfile). You probably need to run `apt install build-essential`

**Comment by abundant-ray** [comment]
That hasent worked it still says this: fatal error: 'bits/libc-header-start.h' file not found

**Comment by abundant-ray** [comment]
i will try redoing it all to see if i can change something

**Comment by abundant-ray** [comment]
its just not working ill just use the web version
