### ISSUE TITLE
Snowdrop OS seem to work

### ISSUE THREAD

**Issue by PoweredByWill** [copy/v86#411]
http://www.sebastianmihai.com/snowdrop/

Might need to add some RAM or make some small adjustments... as a GUI app or two seemed to implode/segfault but it boots and things seem to mostly work.

**Comment by copy** [comment]
Cool! Added: https://copy.sh/v86/?profile=snowdrop

**Comment by copy** [comment]
FYI, I couldn't reproduce the faults. If you can still reproduce them, let me know.

**Comment by PoweredByWill** [comment]
> FYI, I couldn't reproduce the faults. If you can still reproduce them, let me know.

I tried a few more times and it seems fine now for me as well.
My Edge on Windows 10 (S-Mode even) ended up having some pending updates so that could have been the issue...
