### ISSUE TITLE
Custom Emulation doesnt work

### ISSUE THREAD

**Issue by ChrDur1** [copy/v86#417]
using the online version here, can't setup Windows Millenium Edition
![Screen Shot 2021-03-10 at 14 36 40](https://user-images.githubusercontent.com/57975171/110694553-5e38b780-81ae-11eb-994c-b04c1d6194a8.png)

also if your are wondering my setup, here it is.

![Screen Shot 2021-03-10 at 14 37 36](https://user-images.githubusercontent.com/57975171/110694588-68f34c80-81ae-11eb-8d7f-d96766476192.png)

**Comment by ChrDur1** [comment]
was i doing something wrong

**Comment by copy** [comment]
This is a known issue: https://github.com/copy/v86/issues/225

In order to create a bootable image for v86, I'd recommend using qemu for the installation, e.g.:

```
qemu-img create disk.img 20G
qemu-system-x86_64 -drive file=disk.img,format=raw -cdrom cd.iso -m 1G -enable-kvm
```

**Comment by ChrDur1** [comment]
how do i install qemu then
