### ISSUE TITLE
bootBASIC doesn't boot

### ISSUE THREAD

**Issue by childishbeat** [copy/v86#418]
The [https://github.com/nanochess/bootBASIC bootBASIC] image doesn't boot, whether I use Standard PC or ACPI. As a floppy disk, it's stuck at Downloading images [2/3] 100%, but the serial console appears. As a CD, I get code 0003. As a hard disk, it simply says it couldn't be read.

**Comment by copy** [comment]
Seems to be working fine: https://copy.sh/v86/?profile=bootbasic

It needs to have the correct size to detect the floppy type. There's an error in the console. I extended it as follows:

```
dd if=/dev/zero of=bootbasic.img ibs=1k count=1440
dd if=basic.img of=bootbasic.img conv=notrunc
```
