### ISSUE TITLE
Debug version can't boot from hard drive, but compiled version can

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#42]
This works:

http://copy.sh/v86/?profile=custom&hda.url=http://k%C3%A6n.guru/files/FDSTD10.IMG

This doesn't:

http://copy.sh/v86/debug.html?profile=custom&hda.url=http://k%C3%A6n.guru/files/FDSTD10.IMG

**Comment by copy** [comment]
Ack. Seabios uses IDE DMA in way that is not compatible with our implementation. The seabios binary for debugging is probably compiled with  `CONFIG_ATA_DMA` and the normal one isn't. 

Will fix, thanks!

**Comment by copy** [comment]
This has been fixed some time ago.
