### ISSUE TITLE
Would the Raspberry Pi OS be compatible?

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#421]
I know it's 32-bit.

**Comment by copy** [comment]
Yes: Download the i386 version from here: https://www.raspberrypi.org/software/raspberry-pi-desktop/, change memory to 512MB. Takes about 10 minutes to boot to desktop.

![Screenshot_2021-03-24_19-13-46](https://user-images.githubusercontent.com/1816456/112400975-d3a59b80-8d09-11eb-9fc7-84c9c986d029.png)

**Comment by hello-smile6** [comment]
How would I do that, @copy ? What choice do I choose to load the iso?

**Comment by copy** [comment]
@hello-smile6 As CD image
