### ISSUE TITLE
I have Ubuntu and Raspberry Pi OS booting with excessive memory, but they got stuck after the initial boot menu.

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#425]
Why won't it work? I'm using the i386 images this time.

**Comment by BenNottelling** [comment]
Open up the developer console on your browser and look for errors being displayed
Then submit what is displayed

**Comment by hello-smile6** [comment]
Okay.

**Comment by hello-smile6** [comment]
Sorry, @BenNottelling , but I had to run a `tskill *` that wiped out all my UI processes, including Edge, due to a critical memory shortage.

**Comment by hello-smile6** [comment]
Here's another attempt, about 20 seconds in on Raspberry Pi OS. Edge Stable v89.0.774.63 on Windows 10 (OS build 19042.867)
![Image](https://user-images.githubusercontent.com/73048226/112763576-df1eee00-8fb9-11eb-9e4a-203f9dca931c.png)

**Comment by hello-smile6** [comment]
Well, I froze it.

**Comment by hello-smile6** [comment]
It won't load now.

**Comment by copy** [comment]
You probably need more ram.
