### ISSUE TITLE
Where could I get an Android ISO?

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#428]
I would like to try to boot the latest version of Android in the emulator.

**Comment by copy** [comment]
Please search for existing issues before creating new ones: https://github.com/copy/v86/issues/428

**Comment by hello-smile6** [comment]
@copy You just linked to this issue. #428 which you linked to is the same as the #428 which I asked this in. Telling me to look at what I'm already looking at tells me nothing. Do you know?
