### ISSUE TITLE
Public service alert: Do not run a v86 emulator with over 1024mb memory allocated alongside a QEMU emulator with 1024mb memory allocated and multiple resource-heavy Node servers on a Windows machine with 8GB of memory.

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#429]
# Seriously.
It's a bad idea, no matter how good of a computer you have. Even an Apple M1 chip can get overloaded.

If you do that, you can create a power shortage on your machine, which could potentially brick your computer. I did that, and suddenly the screen went dark (like, not RGB #000000; , literally completely dark). If I hadn't immediately done Windows + R and `tskill *` to force it to abort all CPU tasks, I could've bricked the device. Do not make the same mistake I did. Please. Basically, never run multiple VMs _or_ run VMs alongside other programs. Even though the device was in "high-performance" mode, it still caused a power drain.

Also, remember: the ISOs you run in VMs don't know or care whether they're on a VM. They just run, no matter what. Even if your machine is maxed out and every program is cutting the CPU usage, VMs will keep going. Therefore, they can cause extreme damage to computers. Unless you want to risk heap corruption at the system level and errors worse than a Windows Blue Screen of Death, do not attempt to run multiple VMs at once. Same goes with benchmarks. Never run multiple CPU benchmarks or stress tests at once. No matter what.
If you do, be ready to take down your PC with `tskill *`.

**Comment by robtech21** [comment]
Good to know... Not that I'll ever be in this situation

**Comment by hello-smile6** [comment]
Okay. Good. If anyone has a Reddit account, it would be nice if they copied this announcement there.

**Comment by cleanremote** [comment]
Is this a creepypasta?

**Comment by copy** [comment]
Good to know but completely unrelated to v86.

**Comment by robtech21** [comment]
> Is this a creepypasta?

Probably not

**Comment by hello-smile6** [comment]
It is related, since v86 was running when the crash occured.

**Comment by hello-smile6** [comment]
Please note: I did not have to restart the device to fix it, luckily. If you have to restart your device and this occurs, wait at least 1 hour before BIOS/UEFI startup to make sure you don't accidentally have the system attempt to access the memory from the problematic session and wreck your device that way.
