### ISSUE TITLE
Resolution 640x480 and less is enlarged 2 times

### ISSUE THREAD

**Issue by Pixelsuft** [copy/v86#431]
![1](https://user-images.githubusercontent.com/68371847/113112685-a7bb7600-9233-11eb-9856-ab1fc23ab3fe.png)<br />
![2](https://user-images.githubusercontent.com/68371847/113112681-a68a4900-9233-11eb-9534-b1d55fe95ee3.png)<br />
![3](https://user-images.githubusercontent.com/68371847/113112684-a722df80-9233-11eb-8249-2a5f11c7bfab.png)

**Comment by copy** [comment]
This is intentional since these resolutions look to small, especially on high-dpi screens and OSes that don't support larger resolutions (e.g. bootchess, Windows without driver). Do you think this behaviour should be changed?

**Comment by Pixelsuft** [comment]
Maybe you need to change only if the browser window is not smaller than the resolution * 2?

**Comment by copy** [comment]
Fixed in #623.
