### ISSUE TITLE
the main page is messed up

### ISSUE THREAD

**Issue by logan-webGL-openGL** [copy/v86#432]
i dont know if its another language
fix pls i cant work testing linux

**Comment by logan-webGL-openGL** [comment]
![Screenshot 2021-04-01 7 10 05 AM](https://user-images.githubusercontent.com/74722466/113285817-640b4f80-92b9-11eb-8348-a8f857234c75.png)
![Screenshot 2021-04-01 7 09 58 AM](https://user-images.githubusercontent.com/74722466/113285819-64a3e600-92b9-11eb-8fff-c85b6ef2774d.png)
![Screenshot 2021-04-01 7 09 49 AM](https://user-images.githubusercontent.com/74722466/113285820-64a3e600-92b9-11eb-98df-56d4d649a873.png)

**Comment by Pixelsuft** [comment]
same

**Comment by ayunami2000** [comment]
april fools update

**Comment by copy** [comment]
Seems to have resolved itself.

**Comment by loniop** [comment]
im dumb :()))

**Comment by loniop** [comment]
i still feel stupid to this day
