### ISSUE TITLE
Changing the license to the MIT License

### ISSUE THREAD

**Issue by MilkyDeveloper** [copy/v86#434]
The BSD 2 Clause license is way more fragmented and harder to understand than the MIT License. They are [basically the same](https://softwareengineering.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license), except the MIT license is much easier to understand. Any thoughts?

**Comment by robtech21** [comment]
Seems reasonable enough

**Comment by copy** [comment]
We would need to ask everyone that has contributed code to v86 for permission. Seems to be too much trouble for little gain. Is there actually a strong reason to do this?

**Comment by MilkyDeveloper** [comment]
I forgot about that aspect of things. I'll close the issue, but (just wondering) isn't the BSD 2 Clause compatible with the MIT License? I've heard many people stating that you can fork/use a library of a BSD 2c project and then license it as MIT.

**Comment by copy** [comment]
@MilkyDeveloper You can combine MIT and BSD in projects, even on a per-file basis, but you can't remove or replace the BSD license unless you're the copyright holder.

**Comment by MilkyDeveloper** [comment]
I see, thank you! Kudos to your amazing project! Here is SliTaz running with save state (1 second bootup time) on a little web app I hacked together.
![image](https://user-images.githubusercontent.com/48262994/113495255-e52f3600-94b5-11eb-920c-0a57d4ede1ae.png)
