### ISSUE TITLE
loading isos from url and automaticly start

### ISSUE THREAD

**Issue by Glowman554** [copy/v86#436]
Hello i think it would be a cool feature to be apel to put an url like http://copy.sh/v86/?profile=custom&iso=https://glowman554.github.io/downloads/nextos.iso to be abel to automaticly load this iso and start the emulation

**Comment by copy** [comment]
You should be able to do this already, for example: https://copy.sh/v86/?profile=custom&cdrom.url=https://k.copy.sh/android-x86-1.6-r2.iso

**Comment by Glowman554** [comment]
Oh thanks I will try this

**Comment by Glowman554** [comment]
https://copy.sh/v86/?profile=custom&cdrom.url=https://raw.githubusercontent.com/Glowman554/NextOS/master/cdrom.iso sadly dosent work

**Comment by copy** [comment]
The server needs to set the appropriate CORS headers to allow copy.sh to make an XHR request to your domain. Apparently github doesn't do it.

**Comment by Glowman554** [comment]
Oh OK that's kinda sad I wish I could use this website to have a direct link in my readme

**Comment by Glowman554** [comment]
I did do it now like this and it works fine https://www.github.com/Glowman554/NextOS/tree/master/README.md
