### ISSUE TITLE
error Error code: Out of Memory 

### ISSUE THREAD

**Issue by 178900PRITAM** [copy/v86#437]
https://copy.sh/v86/?profile=custom&cdrom.url=https://k.copy.sh/android-x86-1.6-r2.iso
Showing aw snap Error code: Out of Memory

**Comment by logan-webGL-openGL** [comment]
![Screenshot 2021-04-12 8 08 00 AM](https://user-images.githubusercontent.com/74722466/114392410-baed1080-9b66-11eb-9c66-8cc3b6195010.png)

**Comment by logan-webGL-openGL** [comment]
its only halv of the screen but it works

**Comment by logan-webGL-openGL** [comment]
try a better computer cause it uses real memory

**Comment by inyourface34456** [comment]
When i clicked on the provided link, i heard a crackling sound while it was booting.  Anyone know why that is?
Some screenshots:
![image](https://user-images.githubusercontent.com/62214409/114395487-6e0b3900-9b6a-11eb-8467-3962e11f0ee8.png)
![image](https://user-images.githubusercontent.com/62214409/114395555-83806300-9b6a-11eb-8095-07d278e618fa.png)
