### ISSUE TITLE
Lack of support for non-byte-serving servers causes breakage when loading cached images

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#44]
Cached XHR don't seem to send Accept-Range, which breaks the emulator. This happens in Chrome.

**Comment by copy** [comment]
I'm not sure what's going on here and I can't reproduce the problem. The server doesn't send an Accept-Range header? It shouldn't make a difference.

**Comment by ysangkok** [comment]
Okay, I can't seem to reproduce this... I'll reopen if I eventually figure this out...

**Comment by ysangkok** [comment]
Ok, I managed to reproduce this. If you change the harddisk or floppy image after it has been cached, the problem occurs. You need to reload the page without manually clearing the cache. Pressing F5 with the developer tools open seems to clear the cache, so that won't do. I always do it with the tools closed. 

Here's how I reproduce:

1. load page with developer tools open
1. append garbage `echo -ne '\0' >> freedos-ipx1.img`
1. copy url, close tab, new tab, paste url, enter (this is because other forms of reloading seem to clear the cache)
1. open developer tools
1. error is visible:

![2015-04-19-222724_1280x800_scrot](https://cloud.githubusercontent.com/assets/284023/7221237/4aff906a-e6e3-11e4-8833-b72d6c7b4076.png)

**Comment by copy** [comment]
Chromium is being smart and adding an `If-Range` header to the request. Since the file changed on the server, it replies with the whole file, which causes the assertion to fail.

Thanks for the report, will be fix soon.
