### ISSUE TITLE
Some Display Fixes

### ISSUE THREAD

**Issue by Pixelsuft** [copy/v86#440]
# Some Display Fixes
## Text Mode Color Fix
Before:
![before1](https://user-images.githubusercontent.com/68371847/113564015-d621c280-9632-11eb-9c8b-f369630ba24f.png)
After:
![after1](https://user-images.githubusercontent.com/68371847/113564027-d9b54980-9632-11eb-9e1a-72f221312a6b.png)
Before: 
![before2](https://user-images.githubusercontent.com/68371847/113564330-68c26180-9633-11eb-8073-270794ee0912.png)
After:
![after2](https://user-images.githubusercontent.com/68371847/113564490-af17c080-9633-11eb-9cb7-91b056d3a321.png)
[Edited screen.js](https://github.com/Pixelsuft/v86_tests/blob/master/src/browser/screen_color.js) ([raw](https://github.com/Pixelsuft/v86_tests/raw/master/src/browser/screen_color.js))
[Example](https://pixelsuft.github.io/v86_tests/color.html)
## Blinking Cursor
Without:
![without_cursor](https://user-images.githubusercontent.com/68371847/113565174-c5724c00-9634-11eb-9ef9-dfcf1620b199.png)
With:
![with_cursor](https://user-images.githubusercontent.com/68371847/113565013-817f4700-9634-11eb-8b06-264f4f60ce09.gif)
[Edited screen.js](https://github.com/Pixelsuft/v86_tests/blob/master/src/browser/screen_cursor.js) ([raw](https://github.com/Pixelsuft/v86_tests/raw/master/src/browser/screen_cursor.js)) (With No Black Background Test)
[Edited v86.css](https://github.com/Pixelsuft/v86_tests/blob/master/v86.css) ([raw](https://github.com/Pixelsuft/v86_tests/raw/master/v86.css))
[Example](https://pixelsuft.github.io/v86_tests/cursor.html)
## Windows 95 Logo Fix
Detect "Starting Windows 95..." text and scale width to 640 if resolution is 320x400
Before:
![logo_before](https://user-images.githubusercontent.com/68371847/113566006-25b5bd80-9636-11eb-86e5-026a0f1f5fc9.png)
After:
![logo_after0](https://user-images.githubusercontent.com/68371847/113566293-a1176f00-9636-11eb-807a-c7bd846d818f.png)
or (Example 2):
![logo_after2](https://user-images.githubusercontent.com/68371847/113566040-2ea68f00-9636-11eb-9e40-ae2ada7000a7.png)
[Edited screen.js](https://github.com/Pixelsuft/v86_tests/blob/master/src/browser/screen_logo1.js) ([raw](https://github.com/Pixelsuft/v86_tests/raw/master/src/browser/screen_logo1.js))
[Example 1](https://pixelsuft.github.io/v86_tests/logo1.html)
[Edited screen.js from Example 2](https://github.com/Pixelsuft/v86_tests/blob/master/src/browser/screen_logo2.js) ([raw](https://github.com/Pixelsuft/v86_tests/raw/master/src/browser/screen_logo2.js))
[Example 2](https://pixelsuft.github.io/v86_tests/logo2.html) (with image changing)
## Update: my try to Draw Text Mode On Canvas
![lol](https://user-images.githubusercontent.com/68371847/113657590-770e8d00-96c8-11eb-91db-76bd48a0d699.png)
[Edited screen.js](https://github.com/Pixelsuft/v86_tests/blob/master/src/browser/screen_canvas.js) ([raw](https://github.com/Pixelsuft/v86_tests/raw/master/src/browser/screen_canvas.js))
[Example](https://pixelsuft.github.io/v86_tests/canvas.html)

**Comment by 178900PRITAM** [comment]
great
