### ISSUE TITLE
Improve ui

### ISSUE THREAD

**Issue by 178900PRITAM** [copy/v86#444]
i suggest you to use vbox ui https://camo.githubusercontent.com/95270a6b3d349a65c666a96907b5cb87908f695b23e86a5d30bbf4c8ed2e4446/687474703a2f2f612e6673646e2e636f6d2f636f6e2f6170702f70726f6a2f7068707669727475616c626f782f73637265656e73686f74732f7068707662312e706e67

**Comment by copy** [comment]
https://github.com/copy/v86/issues/24
