### ISSUE TITLE
Issue in the browser version

### ISSUE THREAD

**Issue by TheSafeBoi** [copy/v86#449]
When i opened windows 2000, it had a black screen, it wasn't showing anything, yes i clicked the run button, it was running but it's still just  black screen , no mouse, no resolution, no bpp

**Comment by TheSafeBoi** [comment]
The browser that i was using is chrome

**Comment by copy** [comment]
Anything in the console (ctrl+shift+j)? Can you also try http://copy.sh/v86/debug.html?profile=windows2000

**Comment by TheSafeBoi** [comment]
I can't do it, I'm in mobile, and debug doesn't work

**Comment by copy** [comment]
Probably the browser doesn't let us allocate the initial memory. Not much we can do on our side.
