### ISSUE TITLE
VM using 100% CPU on Linux 3+

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#45]
This doesn't happen using linux.iso. Low CPU usage is very important to me, do you know why this happened? Is the kernel configuration available?

**Comment by ysangkok** [comment]
I solved this using `CONFIG_NO_HZ_IDLE` and HZ=100.

**Comment by s-macke** [comment]
Yes, that's indeed a problem. Under Javascript the idle time should exceed 4ms. For jor1k I put even HZ=50 here.

**Comment by xming** [comment]
I wonder how do you avoid 100% CPU (on one core) with Linux, all the Linux images (2.6.x and 3.x) on copy.sh use 100% and my self compiled kernel with CONFIG_NO_HZ_IDLE=y and HZ=50 too, on both firefox and chromium.

**Comment by s-macke** [comment]
Well, I have everything under my control. My own distribution, my own emulator, my own compiled Linux, my own programmed Linux idle function (which wasn't implemented yet). 
x86 is much more complicated. So I am not sure, what the Linux operating system expects for a system. I guess you compiled also for a single core.

**Comment by ysangkok** [comment]
This repo builds an ISO image for v86 that didn't use 100% CPU last time I tested: https://github.com/ysangkok/build-v86-9p-linux

The repo contains a Linux config that uses the settings I mentioned earlier in this thread.

**Comment by s-macke** [comment]
I would try to debug the setTimeout function in Javascript. to see what is the average timeout in ms for the Javascript engine. Also there is the update of the screen now and then which could influence the total CPU usage. 
I tried it myself and it looks like, that the IPS indeed decrease when idle but the CPU usage remains the same.

**Comment by s-macke** [comment]
ysangkok: Do you have a binary?

**Comment by ysangkok** [comment]
@s-macke yes

Here's the ISO image: https://hushfile.it/55681e725bfa2#HGrNrA2-vQP4QW20zblBtY-AjHfqrpStbaqhurka
Here's the root filesystem: https://hushfile.it/55681fc278c8d#DgLyVmrj8E-EEes80V2duyTEPQ0Sdgkai2SDpu0C
Here's the root filesystem JSON: https://hushfile.it/55682033f0e6f#8yX12xOCqtYu_a98KyRS9r5ts15NjkqtaTv5wH8H

And here's a sample HTML file that has a 9p filesystem configured for it: https://github.com/ysangkok/browser-http-proxy/blob/master/basic.html
