### ISSUE TITLE
How to change simple vga mode before linux kernel start?

### ISSUE THREAD

**Issue by proxy-m** [copy/v86#453]
How to change VGA mode to 160x50, or 80x50, or 132x25 (text)? I see bios switches mode on startup.

**Comment by copy** [comment]
For the buildroot profile the cmdline is hardcoded [here](https://github.com/copy/v86/blob/3791d63ffd09881782690902c6ee57f0edbd56a3/src/browser/main.js#L294), but we could provide a url parameter to override it.

In the [Tinycore](https://copy.sh/v86/?profile=tinycore) and [OpenWrt](https://copy.sh/v86/?profile=openwrt) profiles you can press tab in the boot menu and add a `vga=` parameter.

The Arch profile uses a framebuffer, so the resolution can be changed using fbset (which currently isn't installed, but I'll add it the next time I make an update).

**Comment by proxy-m** [comment]
Yes, but I am about v86 side. I found `vga.js` and `screen.js`. Only 80x25 supported from text modes (+ more graphical modes)?

Also I found that video mode is firstly setted by seabios on `bootsplash.c -> enable_vga_console - > call16_int10`.

**Comment by copy** [comment]
v86 supports arbitrary text mode resolutions: https://github.com/copy/v86/blob/3791d63ffd09881782690902c6ee57f0edbd56a3/src/vga.js#L1249

I doesn't seem that the standard VGA bios supports anything besides 80x25 or 40x25 though (tetris.com in [FreeDOS](https://copy.sh/v86/?profile=freedos) uses 40x25, for example): https://github.com/coreboot/seabios/blob/b0d61ec/vgasrc/stdvgamodes.c#L276-L311

So it's up to the OS to set it up correctly.

**Comment by proxy-m** [comment]
**OK. Not all video modes supported by seabios.** Thank you for answer.

Other non-common text video modes (e.g. 
0x2F 160x50;
0x23 0x08 0x14 0x17 0x1B 0x27 0x41 0x109 132x25; 
0x66 0xC8 80x50; 0x1D 0x42 0x56 0x10A 132x43; 
0x1A 0x25 0x26 0x43 0x5A 0x108 80x60;
): https://github.com/Mati365/i8086.js/blob/89ede87f54b5dcd39c275ccd0e6fda7fec09c2d0/assets/videomodes.txt

**Comment by proxy-m** [comment]
> For the buildroot profile the cmdline is hardcoded [here](https://github.com/copy/v86/blob/3791d63ffd09881782690902c6ee57f0edbd56a3/src/browser/main.js#L294), but we could provide a url parameter to override it.
> 
> In the [Tinycore](https://copy.sh/v86/?profile=tinycore) and [OpenWrt](https://copy.sh/v86/?profile=openwrt) profiles you can press tab in the boot menu and add a `vga=` parameter.
> 
> The Arch profile uses a framebuffer, so the resolution can be changed using fbset (which currently isn't installed, but I'll add it the next time I make an update).

Yes, for clarification `vga=ask` not supported on `linux 3.x+ (e.g. 3.11) + grub 2`. Last full support was on `linux 2.6.x + grub1/grub4dos`.
`vga=<mode_number_here>` may work on `linux 3.x+` via grub2 `linux16` or grub1 0.97 parameter `kernel` (for properly configured linux).

Later `vga=<mode_number_here>` replaced to `video=<WIDTH>x<HEIGHT>` (may conflict with grub gfx or modesetting by quiet splash).

So, if somebody needs to fast check vga modes via grub1/grub4dos + linux 2.6 simper to use one of puppy linux iso: e.g. https://github.com/copy/v86/issues/455

**Comment by proxy-m** [comment]
Video modes used by dosemu (example): https://github.com/dosemu2/dosemu2/blob/1c64a39265b1881b1ad3d1e5e813e10476167246/src/base/dev/vga/vgaemu_modelist.h
