### ISSUE TITLE
I was wondering if I could play touhou 6 on one of the emulators

### ISSUE THREAD

**Issue by CableTV1123** [copy/v86#458]
I was using the windows 98 emulator and I was wondering if there was anyway I could play touhou 6 (I have the game downloaded but I can't play it because I'm on a chromebook)

**Comment by copy** [comment]
Only one way to find out: Get Windows 98 from [here](https://winworldpc.com/product/windows-98/98-second-edition), install it in qemu, install your game in it, confirm that it works in qemu, test the resulting image in v86. Not really a task for the developers of v86 though, but feel free to reopen if you encounter any issues in the last step.
