### ISSUE TITLE
Basic block in tight loop unnecessarily split into multiple jit blocks

### ISSUE THREAD

**Issue by viorelcanja** [copy/v86#462]
First of all, thank you for v86!

I was running some tests to evaluate JIT performance for a tight loop. Looking at the basic blocks created I noticed that one basic block that was part of the loop was split on a boundary that did not make sense to me (a "SAR" instruction in the middle of a page). I did a bit of digging and that was caused by the fact that the respective location was registered as an entry point because a run of "jit_run_interpreted" finished when iteration limit was reached on that particular instruction. The next cycle started from that location and triggered jit_increase_hotness_and_maybe_compile which eventually registered that as an entry point.  

I propose to fix it by changing this:
 while !jit_block_boundary
        && Page::page_of(*previous_ip as u32) == Page::page_of(*instruction_pointer as u32)
        && i < INTERPRETER_ITERATION_LIMIT
    {
to this:
 while !jit_block_boundary
        && Page::page_of(*previous_ip as u32) == Page::page_of(*instruction_pointer as u32)
        && (i < INTERPRETER_ITERATION_LIMIT || (*previous_ip as u32) <  (*instruction_pointer as u32))
    {

This way "jit_run_interpreted" will exit after the limit is reached but it will wait for either the end of page to be reached (limiting the problem to what is already accepted since right now JIT does not cross page boundary) or for a back jump. My intention was to detect a intra page jump and this was the easiest way I found. If only forward jumps exist in the page then eventually the end of page will be reached. This does mean that INTERPRETER_ITERATION_LIMIT may be passed by (worst case) 4k+ instructions which might not be acceptable (maybe for low values of INTERPRETER_ITERATION_LIMIT?).

In this particular test this change improved perf by apx 5% (from 340MIPS to 359MIPS, I am relying on debug info reported by v86 in the UI). It is likely this will benefit all tight loops scenarios since jit_run_interpreted will most likely exit in the middle of the loop.

Finally, my knowledge of v86 and rust is not great (to say the least) so it is possible that I got a few things wrong.
Hope this helps!

**Comment by copy** [comment]
Excellent analysis, thanks. Indeed your suggested change improves the performance significantly on some benchmarks (I've measure a ~25% increase in iterations per second on some tests of nbench, which indeed mostly contains tight loops).

Would you mind sending a PR? That would also list you as a contributor to v86.

> This does mean that INTERPRETER_ITERATION_LIMIT may be passed by (worst case) 4k+ instructions which might not be acceptable

I'm pretty sure that's not an issue: `INTERPRETER_ITERATION_LIMIT` exists to 1) prevent endless loops and 2) eventually enter the jit even in the absence of calls or indirect jumps or page crossings. Both are still covered by the new implementation.

**Comment by viorelcanja** [comment]
I opened this PR:
https://github.com/copy/v86/pull/464 .

**Comment by copy** [comment]
Thanks!
