### ISSUE TITLE
Instructions on downloading images no longer works

### ISSUE THREAD

**Issue by gr33k** [copy/v86#465]
```
➜  images git:(master) ✗ wget -P images/ https://copy.sh/\{linux.iso,linux4.iso,buildroot-bzimage.bin,openbsd-floppy.img,kolibri.img,windows101.img,os8.img,freedos722.img\}
--2021-05-04 17:37:27--  https://copy.sh/%7Blinux.iso,linux4.iso,buildroot-bzimage.bin,openbsd-floppy.img,kolibri.img,windows101.img,os8.img,freedos722.img%7D
Resolving copy.sh (copy.sh)... 192.248.180.97, 2001:19f0:6c01:3e6:5400:3ff:fe01:c520
Connecting to copy.sh (copy.sh)|192.248.180.97|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-04 17:37:28 ERROR 404: Not Found.
```

What's the deal with 403 Forbidden when we try to grab your images? I used to be able to grab them so I can mirror this site for testing, but now they are 403 or 404. Please let us grab all images that you use (They are easily obtained but you did all the hard work, which I greatly appreciate...so please let us benefit from the fruits of your labor).

Ok appears i missed the ` ... this worked but still of course no windows images. Can't paste it here because it converts it to code just add one before and at end of the wget command (the whole thing)

**Comment by copy** [comment]
The command from the readme should work (don't put a backslash in front of the `{` or `}` characters):

```
wget -P images/ https://k.copy.sh/{linux.iso,linux4.iso,buildroot-bzimage.bin,openbsd-floppy.img,kolibri.img,windows101.img,os8.img,freedos722.img}
```

Alternatively, if you shell doesn't expand the braces correctly, you download them one by one:

```
wget -P images/ https://k.copy.sh/linux.iso
wget -P images/ https://k.copy.sh/linux4.iso
…
```

The reason I don't provide links for the larger image files, including the Windows images, is that I'm paying for the bandwidth, and it's fairly easy to create them from scratch. If you'd like to mirror them publicly or need them for testing, send me an email and I'll share them with you.
