### ISSUE TITLE
Unnecessary large tlb_data ?

### ISSUE THREAD

**Issue by viorelcanja** [copy/v86#467]
Looking at the definition of tlb_data it seems to me that the vector is too large but most likely I am missing something since I am new to the code.

pub static mut tlb_data: [i32; 0x400000] = [0; 0x400000];
The max number of pages is 0x100000.

What am I missing ?

**Comment by copy** [comment]
You're not missing anything :-). Probably a leftover from the port from JavaScript to Rust (0x400000 bytes vs 0x100000 elements). Mind sending a PR?

**Comment by viorelcanja** [comment]
Done: https://github.com/copy/v86/pull/468

**Comment by copy** [comment]
Thanks, merged!
