### ISSUE TITLE
Nodejs canvas output

### ISSUE THREAD

**Issue by Pixelsuft** [copy/v86#470]
I'm wrote [script](https://gist.github.com/Pixelsuft/28c0d7e8487814a3c031d9b40788c071) that translates text screen output to console, it works good:
![image](https://user-images.githubusercontent.com/68371847/117664881-763bb000-b1cc-11eb-9cb5-97b8fb203ca4.png)
But now I want to translate graphic screen to GUI (but I cant find normal gui lib like sdl for nodejs (I found, but it's not installing), so I want to save screenshots to file).
But this not works

**Comment by copy** [comment]
>  But now I want to translate graphic screen to GUI (but I cant find normal gui lib like sdl for nodejs (I found, but it's not installing), so I want to save screenshots to file).
But this not works

Can you clarify? What's the issue?

**Comment by Pixelsuft** [comment]
I found module canvas for nodejs and tested it.
I can save screenshot using canvas.toDataURL(), encoding from base64 and converting to buffer.
https://gist.github.com/Pixelsuft/5d83ca4cf4fa26c9e3c89d5dc5885143
It works, but when I'm adding listeners for emulator in graphic mode (for exaple, 'screen-fill-buffer-end', 'screen-clear', 'screen-set-size-graphical'), they not works

**Comment by Pixelsuft** [comment]
@copy
> Screenshots uses the canvas api, which is not available in node.

[**nope**](https://gist.github.com/Pixelsuft/573150092bef2971dae711745b3fcd1d)
![nope1](https://user-images.githubusercontent.com/68371847/118349598-c6739300-b57b-11eb-9f53-f28ae3eed9f7.png)
![nope2](https://user-images.githubusercontent.com/68371847/118349602-c83d5680-b57b-11eb-9c76-5e7ef277be4d.png)
![nope3](https://user-images.githubusercontent.com/68371847/118349603-c8d5ed00-b57b-11eb-824c-7e6478954c05.png)

**Comment by hello-smile6** [comment]
Wow!
