### ISSUE TITLE
Ubuntu 10 works!

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#474]
It takes about an hour to boot with 512 MB of memory on a fast internet connection. It doesn't work on a slow internet connection, strangely. I tried to save the state, but it doesn't save correctly, even when paused and saved with the ISO. Could it be added as an operating system?

**Comment by logan-webGL-openGL** [comment]
is it suppose
![Screenshot 2021-06-10 10 56 56 AM](https://user-images.githubusercontent.com/74722466/121548011-a8624c80-c9da-11eb-937e-d5cd6294a7ae.png)
 to do this?

**Comment by hello-smile6** [comment]
I don't know. Try waiting a while or restarting, @logan-webGL-openGL .

**Comment by hello-smile6** [comment]
Transferring to GitHub Discussions

**Comment by hello-smile6** [comment]
Continued in #494 !

**Comment by hello-smile6** [comment]
Now that I think about it, this should stay open.

**Comment by logan-webGL-openGL** [comment]
i cant find a fix

**Comment by copy** [comment]
I fixed a bug related to Ubuntu 10.04 and it seems to work now. You can download it from here: http://old-releases.ubuntu.com/releases/10.04.0/ubuntu-10.04.4-desktop-i386.iso.

Note that newer versions of Ubuntu don't work due to missing PAE support (https://github.com/copy/v86/issues/97).

![Screenshot_2021-11-13_20-07-24](https://user-images.githubusercontent.com/1816456/141663698-e02c7825-eb24-4b16-a559-c3630c5bfccf.png)

**Comment by hello-smile6** [comment]
> I fixed a bug related to Ubuntu 10.04 and it seems to work now. You can download it from here: http://old-releases.ubuntu.com/releases/10.04.0/ubuntu-10.04.4-desktop-i386.iso.
> 
> Note that newer versions of Ubuntu don't work due to missing PAE support (#97).
> 
> ![Screenshot_2021-11-13_20-07-24](https://user-images.githubusercontent.com/1816456/141663698-e02c7825-eb24-4b16-a559-c3630c5bfccf.png)

Awesome, only 15 min. to boot!

**Comment by Unzor** [comment]
Wait, do you use an HDA and a CDROM image or is it only the CDROM? It's been stuck on loading for an hour or so

**Comment by Unzor** [comment]
![Screenshot 2022-01-06 12 21 12 PM](https://user-images.githubusercontent.com/71789103/148431623-244bd5d2-d8b8-4d1d-ac0c-5e06c8ca78f7.png)

**Comment by hello-smile6** [comment]
> ![Screenshot 2022-01-06 12 21 12 PM](https://user-images.githubusercontent.com/71789103/148431623-244bd5d2-d8b8-4d1d-ac0c-5e06c8ca78f7.png)

What disk image?

**Comment by Unzor** [comment]
I used http://old-releases.ubuntu.com/releases/10.04.0/ubuntu-10.04.4-desktop-i386.iso.

**Comment by copy** [comment]
> Wait, do you use an HDA and a CDROM image or is it only the CDROM? Is it on a specific memory? It's been stuck on loading for 20 mins

I booted it as a cdrom with 512 MB.

**Comment by logan-webGL-openGL** [comment]
also stuck on load

**Comment by ghost** [comment]
uh were is the file dowload?

**Comment by SuperMaxusa** [comment]
See above:

> You can download it from here: http://old-releases.ubuntu.com/releases/10.04.0/ubuntu-10.04.4-desktop-i386.iso.

**Comment by ghost** [comment]
oh sorry it dose not work it dose not load idk why
