### ISSUE TITLE
Make v86  allow loading ISOs via WebTorrent

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#475]
I think that would be the perfect solution for sharing custom disk images.

**Comment by copy** [comment]
Not sure if WebTorrent provides any advantages over using a CDN (e.g. https://bunny.net/):

- You need a server to host the original files anyway
- I believe you're leaking visitors IPs to each other, so I couldn't with good conscience enable it by default
- v86 doesn't have that many concurrent users anyway
- Probably some extra infrastructure is required to relay users to each other

For the above reasons I'll close this issue.
