### ISSUE TITLE
Automatically pause when memory is limited

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#476]
v86 should pause when the `performance.memory` values indicate low memory and the tab is not in focus, to avoid being unloaded. Additionally, an `alert` should be triggered to pause execution and further avoid being unloaded.

**Comment by copy** [comment]
I don't think pausing will reduce memory usage, unless the guest is running new programs which cause the jit to generate new wasm modules. In that case it should be up to the user to pause the emulator. 

Moreover, I'd rather fix the underlying issue, i.e. reduce memory usage by generating more compact wasm modules.

**Comment by hello-smile6** [comment]
That would be nice.

**Comment by copy** [comment]
Let's close this then.
