### ISSUE TITLE
SSE

### ISSUE THREAD

**Issue by copy** [copy/v86#48]
The following applications currently don't work because of missing support for SSE.
- Nodejs (older versions work)
- Golang

**Comment by ysangkok** [comment]
gccgo works, if you pass GOARCH=387 to make it use x87 for floating-point. I am using it to build my browser-http-proxy.

**Comment by ZaDarkSide** [comment]
You should checkout this link https://hacks.mozilla.org/2014/10/introducing-simd-js/
Maybe we could implement most of SSE instructions with SIMD.js

**Comment by Creeper20428** [comment]
My solution (in my own emulator) was to use four Float32Arrays and do operations on them.
I'm not sure whether this works or not (I've never tested...), but it's worth a try. 
Simply said, it's not that hard to implement 128-bit floats.
I've gotten through about 2/3 of the ops for MMX/SSE, and it took me about two hours.
The hardest part was the supporting cast: SIMD excetions, MXCSR, F3 prefixes, etc.

**Comment by Creeper20428** [comment]
Wait. Node.js works? Where? I wanna try!
I'm excited now. >:)

**Comment by copy** [comment]
> My solution (in my own emulator) was to use four Float32Arrays and do operations on them.

Yep, this is known as [double-double](https://en.wikipedia.org/wiki/Double-double_%28arithmetic%29#Double-double_arithmetic). I don't have a high priority on this, because not many things depend on it (especially the precision).

> Wait. Node.js works? Where? I wanna try!

Grab [this](https://nodejs.org/download/release/v0.10.42/node-v0.10.42-linux-x86.tar.gz) older version (0.10.42) and unpack it. Go to http://copy.sh/v86/?profile=archlinux. On the right side choose "send files to emulator" and send the node binary. Run `chmod +x /node; /node`

**Comment by Creeper20428** [comment]
Ooh That sounds cool! I'll try it ASAP.

SSE is really boring because most operations are redundant. I stopped in the middle of the F3 0F A2 range.

Another problem is the casting of bytes to floats. I did it really slow by creating a new Float32Array every single time.

**Comment by arcanis** [comment]
What would you say is the estimate of the work needed for this to work if it was done by someone with little x86 experience but willing to learn?

I'd like to make Yarn run in-browser (for demo purposes, nothing too weird), and v86 looks the only credible choice - except for its missing Node support 😅 so maybe I could help, if it "only" requires a reasonable amount of time.

**Comment by copy** [comment]
There's full SSE2 support in #338. SSE3 or higher is not planned.
