### ISSUE TITLE
Create v86 channel on dirc

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#481]
[v86 - dirc](https://chr15m.github.io/dirc/#v86)
Dirc is not a real IRC client. It is an open-source WebRTC IRC-_like_ chat which works P2P. It's perfect for v86 discussion.

**Comment by BenNottelling** [comment]
We already have a gitter and the github issues. What would the benefit be?

**Comment by hello-smile6** [comment]
For users to be able to contribute without having a GitHub account. Also, then users could discuss things easier. I'll explain over at https://chr15m.github.io/dirc/#v86 . @BenNottelling

**Comment by hello-smile6** [comment]
Did you even look?

**Comment by copy** [comment]
I appreciate your effort, but I already have too many chat clients and networks. Like @BenNottelling we have a [gitter](https://gitter.im/copy/v86) that is quite active and you can even connect via [matrix](https://matrix.to/#/#copy_v86:gitter.im]), so you don't need a github account. I'm also on IRC so I wouldn't mind creating a channel there if anybody is interested.

**Comment by hello-smile6** [comment]
IRC is too restrictive, though.
