### ISSUE TITLE
Challenge Ubuntu developers to get Ubuntu 20 running in v86

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#482]
v86 is a long way from supporting Ubuntu 20. However, if we challenged the Ubuntu developers to get Ubuntu 20 running in v86, we might be able to get a lot of contribution from them if even just a few people tried to reach that goal.

**Comment by copy** [comment]
Just to be clear, any issues that prevent you from running Ubuntu 20 are v86's side, not on Ubuntu's. The primary issue right now would be https://github.com/copy/v86/issues/97 as well as https://github.com/copy/v86/issues/133. I don't think it's reasonable to bother Ubuntu developers about issues in other projects, so I'll close this.
