### ISSUE TITLE
Windows 95 MS-DOS

### ISSUE THREAD

**Issue by Pixelsuft** [copy/v86#484]
When I'm running MS-DOS on Windows 95, I'm getting this:
![image1](https://user-images.githubusercontent.com/68371847/120910253-96656e80-c6a7-11eb-966d-68c0fed1b2e7.png)
(320x406)
When I'm pressing Alt+Enter to go fullscreen, It works:
![image2](https://user-images.githubusercontent.com/68371847/120910271-aed58900-c6a7-11eb-9fa1-85365b0e7dd1.png)
But when I'm pressing alt+enter to exit fullscreen, It works:
![image](https://user-images.githubusercontent.com/68371847/120910319-1986c480-c6a8-11eb-9723-a965036106a9.png)

_Maybe, we need to press alt+enter 2 times, when resolution is 320x406?_

**Comment by Pixelsuft** [comment]
> But when I'm pressing alt+enter to exit fullscreen, It works:
> ![image0](https://user-images.githubusercontent.com/68371847/120910319-1986c480-c6a8-11eb-9723-a965036106a9.png)

Yes, it works, but how:
![image1](https://user-images.githubusercontent.com/68371847/120913730-7774d580-c6c3-11eb-9610-4e04c3a808f1.png)
![image2](https://user-images.githubusercontent.com/68371847/120913752-93787700-c6c3-11eb-9751-7e3f99c1b051.png)

**Comment by copy** [comment]
This is a known issue with the [VBE driver](https://web.archive.org/web/20210319160959/https://bearwindows.zcm.com.au/vbe9x.htm) for Windows:

> Installation note 0: Current driver unsolved problems:
> ...
>    Locking and garbage problems when entering DOS WDM or console session. 

Not a v86 issue, so let's close this.
