### ISSUE TITLE
Python 3 fails

### ISSUE THREAD

**Issue by copy** [copy/v86#49]
Python 3 currently doesn't work in the Archlinux image. It fails with the following exception:

```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [Errno 29] Illegal seek
```

There's a debug build and gdb in the VM, in case someone wants to look into this.

**Comment by limeb** [comment]
is there an image this work in?

**Comment by copy** [comment]
@limeb Python 3 is present in the [Arch](http://copy.sh/v86/?profile=archlinux) image, if that's what you're asking.
