### ISSUE TITLE
Slax 9.11.0 Works!

### ISSUE THREAD

**Issue by Pufffins** [copy/v86#490]
Slax works on v86:
![image](https://user-images.githubusercontent.com/77994742/121743906-150b4300-cad0-11eb-952b-13fb68e371a5.png)
This is how it should look like when you first boot it:
![image](https://user-images.githubusercontent.com/77994742/121744009-3cfaa680-cad0-11eb-9cf2-098d88f8303b.png)
Make Sure to download the 32-Bit version, not the 64-Bit, because if you used the 64-Bit on v86, it would tell you that the thing has an error.
![image](https://user-images.githubusercontent.com/77994742/121744321-b7c3c180-cad0-11eb-9f6c-b90e04ce6bb9.png)
Take a look at this video: it shows the slax loading.

https://user-images.githubusercontent.com/77994742/121752702-b0a3b000-cade-11eb-9990-710f61d10dc5.mp4

Hooray, it booted!
![image](https://user-images.githubusercontent.com/77994742/121761525-4e5aa780-cafe-11eb-9492-972e3ddf2ee7.png)

Download the ISO file from <a href="http://ftp.sh.cvut.cz/slax/Slax-9.x/slax-32bit-9.11.0.iso">here.

**Comment by Pixelsuft** [comment]
How I know, any 32-bit linux without PAE can run on v86

**Comment by Pufffins** [comment]
Uh...yeah

**Comment by Pixelsuft** [comment]
I'm not tested it, but I think that it can works if it is x86 and not need PAE support

**Comment by Pufffins** [comment]
@Pixelsuft Oh yeah...Like how Android 1.6 RC2 can work with internet

**Comment by copy** [comment]
Nice.
