### ISSUE TITLE
How to connect network on custom boot?

### ISSUE THREAD

**Issue by Pufffins** [copy/v86#491]
@copy how do you connect to a network on custom boot? it says <code>wss://</code>, but I don't understand how to connect. When you connect network, it's usually an IP Address. So how do you connect with <code>wss://</code>?

![image](https://user-images.githubusercontent.com/77994742/121758750-ba361380-caf0-11eb-9d6a-ab8390fdf8a1.png)

**Comment by Pixelsuft** [comment]
It working on linux:
![screen1](https://files.gitter.im/55f20a3c0fc9f982beb05000/AHor/image.png)
How I know, to get network working on guest Windows, you can type this into cmd:
```sh
ipconfig /release_all
ipconfig /renew_all
```

**Comment by Pufffins** [comment]
> It working on linux:
> ![screen1](https://camo.githubusercontent.com/1ce29982a48a7c7d4dd68f4a0aeecd280d04e66bb61a76c05afdc433dd16ada9/68747470733a2f2f66696c65732e6769747465722e696d2f3535663230613363306663396639383262656230353030302f41486f722f696d6167652e706e67)
> How I know, to get network working on guest Windows, you can type this into cmd:
> 
> ```shell
> ipconfig /release_all
> ipconfig /renew_all
> ```

@Pixelsuft Oh yeah...But Slax is Linux too, but it doesn't have internet

**Comment by copy** [comment]
The `ws://` link points at a websocket proxy, e.g. https://github.com/benjamincburns/websockproxy

**Comment by Pufffins** [comment]
@copy thanks!
