### ISSUE TITLE
I GOT NODEJS TO RUN IN ARCH LINUX!

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#492]
First, you have to copy unzip and the dependencies from Buildroot to Arch Linux. Then, you get a NodeJS unofficial release (about v12), extract, and recompress as `.zip` . Then, you load it in and unpack to the root directory. `/bin/node` is safe to overwrite. Finally, you resolve any inexecutable files. On a side note, why did it work to copy the unzip binary and the dependencies (obtained from `ldd` over? I will upload a snapshot of Arch Linux with it installed, I can't get it to upload.
![webserver](https://user-images.githubusercontent.com/73048226/121979721-961c4180-cd3f-11eb-8121-6260df875a83.png)
![success](https://user-images.githubusercontent.com/73048226/121979723-96b4d800-cd3f-11eb-9385-fa9ae6c456c7.png)
![DONE](https://user-images.githubusercontent.com/73048226/121979727-974d6e80-cd3f-11eb-9118-d18974d9e0c3.png)
Yay!

**Comment by copy** [comment]
Node is already installed, so all of this stuff shouldn't be necessary: https://copy.sh/v86/?profile=archlinux&c=node

**Comment by hello-smile6** [comment]
Wait, what? How? I installed Node myself! What about NPM? @copy

**Comment by hello-smile6** [comment]
I actually overwrote Node with an older version! Now, let's figure out how to get networking working. Then we can make a P2P network using [Bugout](https://github.com/chr15m/bugout) and claim the next IP space for a TCP-over-WebTorrent internet! We can now make the P2P web real! @copy

**Comment by copy** [comment]
Let's close this then.
