### ISSUE TITLE
MS-DOS 4.01 wont boot

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [copy/v86#503]
i recently tried a MS-DOS 4.01 Bootdisk with Windows 2.03 installed on v86  , it gets stuck at "Booting from Floppy"
why?

**Comment by copy** [comment]
Can you share the bootdisk image? Does it work in qemu in a similar configuration to v86?

**Comment by Siddhant-Mashalkar** [comment]
This is the floppy image 
 [win203floppy.zip](https://github.com/copy/v86/files/6873468/win203floppy.zip)

**Comment by Siddhant-Mashalkar** [comment]
i've tried it in Bochs , it too doesn't boot , i tried MS-DOS 4.01 Compaq OEM Bootdisk, that also didn't work
![image](https://user-images.githubusercontent.com/71384075/126890012-5a53b8f6-533e-4668-9d46-cc27bd38211e.png)

**Comment by Siddhant-Mashalkar** [comment]
wait , now it works, previously it didn't
