### ISSUE TITLE
Certificate of relay.widgetry.org is expired now

### ISSUE THREAD

**Issue by nwtgck** [copy/v86#504]
Hi, thank you so much for the super fantastic project!

I had an error in browser console. I guess the certificate was expired.

```
WebSocket connection to 'wss://relay.widgetry.org/' failed: Error in connection establishment: net::ERR_CERT_DATE_INVALID
```

<img width="291" alt="image" src="https://user-images.githubusercontent.com/10933561/126890820-c7ba8dba-6464-4ff6-bf20-ba1091ab3a90.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/10933561/126890843-50d4026c-87f6-410b-82ee-49640949a8aa.png">

**Comment by copy** [comment]
Seems to be fixed now.
