### ISSUE TITLE
MS-DOS 6.22 crashes on "Starting MS-DOS" Screen  

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [copy/v86#506]
i made a MS-DOS 6.22 Boot Floppy that loads Windows 1 into RamDisk and runs it, but it's stuck at "Starting MS-DOS" , and here is console log:
![image](https://user-images.githubusercontent.com/71384075/127279442-7c023b8f-6229-4bb2-bb80-7c1b9422c485.png)
note: the drivers loaded in CONFIG.SYS are:
HIMEM.SYS (XMS Manager)
EMM386.EXE (Expanded Memory Manager)
RAMDRIVE.SYS (for Creating RamDisk Drive)
Setver.exe (for Windows 1 to NOT crash on "Incorrect DOS Version" while loading)
GSCDROM.SYS (CD-ROM Driver)

and here is the floppy image:
[Windows1-Ramdrive.zip](https://github.com/copy/v86/files/6891039/Windows1-Ramdrive.zip)

**Comment by Siddhant-Mashalkar** [comment]
why hasn't anyone responded yet

**Comment by BenNottelling** [comment]
Because people aren't paid anything for this, and therefore have no obligation to you

**Comment by Siddhant-Mashalkar** [comment]
okay , i was just asking

**Comment by BenNottelling** [comment]
You don't have to close the issue. It is still a valid issue, it just seemed you expected an immediate response as if you put a support request in at a large company that you bought a product from, which just isn't how open source software like this is. 
It may or may not get fixed, but asking "why hasn't anyone responded yet" seems quite rude when it's a project people work on in their free time

**Comment by Siddhant-Mashalkar** [comment]
okay, i didn't know this is rude .

**Comment by BenNottelling** [comment]
I was probably more rude than you were, honestly
