### ISSUE TITLE
CPU Architecture setting?

### ISSUE THREAD

**Issue by Unzor** [copy/v86#508]
Hello,
I have an ISO that I am testing, and it gives me this error when I try to set it up:
```
This kernel requires an x86-64 CPU, but only detected an i686 CPU. 
Unable to boot - please use a kernel appropriate for your CPU.
```
Is there a setting that can let me change this?
Thanks

**Comment by Pixelsuft** [comment]
This emulator is emulates x86 CPU, but you trying to run x64 system

**Comment by copy** [comment]
See https://github.com/copy/v86/issues/133
