### ISSUE TITLE
Save Hard Drive state

### ISSUE THREAD

**Issue by Darin755** [copy/v86#509]
I noticed on copy.sh/v86 that there is a button to download the current state of the hard drive. Is this implemented in the api? If so, how do I download a copy of the hardrive image?

**Comment by copy** [comment]
Yes, see: https://github.com/copy/v86/blob/3648b4ba8895b7c8b01f13aa8e340775e3e17c88/src/browser/main.js#L1337-L1374

**Comment by Paril** [comment]
Is this feature gone from the site version now? I realized I needed it, but can only save state and memory, no disk image option.

**Comment by copy** [comment]
@Paril Which exact image are you missing? If the image is stored on a server, it only works for small (fully downloaded) images.

**Comment by Paril** [comment]
Essentially I was using it to open some ancient files for extraction (like 16-bit executables), but I was having trouble finding a way to get the files off of the VM. After a few hours I managed to find an FTP client that was small enough to fit on the tiny hard drive on the VM and worked with my FTP server to sync the files, so it's all good; I was just hoping there would be an option to download the entire hard drive to an iso or something so I could open it.
Specifically I mean the copy.sh/v86 version, if that helps.

**Comment by copy** [comment]
If you provide a local image (i.e. `?profile=custom`) the "Get hard disk image" button should be there. Or did you use one of the existing profiles (e.g. `?profile=windows98`)?
