### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by maribun20** [copy/v86#511]
please release the apk files in github too sir...
Because your program on playstore full sir..
I'am can't download the apk files on playstore...
Thanks....

**Comment by BenNottelling** [comment]
V86 is web-based and doesn't have an Android specific release

**Comment by Siddhant-Mashalkar** [comment]
> please release the apk files in github too sir...
> Because your program on playstore full sir..
> I'am can't download the apk files on playstore...
> Thanks....

V86 runs in browser
but you can create an apk with some sites that convert website to apk

**Comment by copy** [comment]
We don't have an Android app (although it is possible that someone else created one).
