### ISSUE TITLE
Feature Request: 486 cpu support

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [copy/v86#512]
it will be great to add 486 CPU support, as Windows NT 3.51 boots up fine on qemu with 486 cpu
but on v86, it doesn't boot and crashes at "Inaccessible Boot Device"

**Comment by Pixelsuft** [comment]
I've runned Windows NT 4.0 on v86 (but I had some problems).
I think that NT 3.51 can work on v86.
Later I can try to install it

**Comment by copy** [comment]
There's a flag to make some versions of NT work, but I haven't tested it in a long time: https://github.com/copy/v86/blob/3648b4b/src/rust/cpu/instructions_0f.rs#L3152

**Comment by Siddhant-Mashalkar** [comment]
how do i enable it?

**Comment by Pixelsuft** [comment]
You can set this flag to **true** and then compile v86

**Comment by Siddhant-Mashalkar** [comment]
ok, also which cpu does v86 emulate? 386 ,486 or pentium?

**Comment by Pixelsuft** [comment]
pentium

**Comment by Siddhant-Mashalkar** [comment]
ok
