### ISSUE TITLE
Arch Linux dhcpcd Networking not working

### ISSUE THREAD

**Issue by JVGA8837** [copy/v86#528]
I've attempted to use dhcpcd to no avail, any other things I could try, sorry if this is a repeat, i'm probably just stupid.
![download](https://user-images.githubusercontent.com/67811123/134551412-b0b7e447-8c84-4846-90d9-17c75fe02533.png)

**Comment by copy** [comment]
In the Arch profile you need to run `modprobe ne2k-pci` first. Or just run `./networking.sh` which does everything for you.

**Comment by JVGA8837** [comment]
Thanks copy 
![Screenshot 2021-09-23 13 33 51](https://user-images.githubusercontent.com/67811123/134556204-0d1847db-fa4f-4af1-9053-2dc02753b367.png)

**Comment by Tanyajackson638** [comment]
#847 #848 #810
