### ISSUE TITLE
Fix TODOs

### ISSUE THREAD

**Issue by Creeper20428** [copy/v86#53]

**Comment by Creeper20428** [comment]
Oops pressed enter too soon! :O
Let me explain:
I was running an OS. Then, the emulator stopped working. What was going on? My browser wasn't hanging... Thirty minutes passed (as I worked on other things) and it still didn't work.
Looking at my Developer Tools, there was one exception thrown -- "Uncaught TODO".
A quick peek in build/cpu.js and ctrl+f showed me the problem--something was unimplemented! 
A quick find-and-replace commenting out of the 'throw "TODO";'s there made my browser do this:
... output ...
……[     ] Error:
 …… stacktrace ……
… more output …
……[     ] Error:
 …… same stacktrace ……

I'm not at all familiar with x86 or this code, (but know about the 8086 arch and JavaScript) so can anyone fix this?

**Comment by copy** [comment]
I'll need to know which TODO was hit (probably an instruction). Better yet, link me to an image of the OS you're trying to run so that I can reproduce the problem locally.

**Comment by Creeper20428** [comment]
Thanks for replying!!!
Well... I probably deleted it by now.
But you can grab a lot of boot discs from www.allbootdisks.com/
Several of those discs make it throw a "TODO" -- But I'm not sure which one... (the stacktrace wasn't very clear and I had a lot of things to do).
But anyways, it would be great if all those 'throw "TODO"'s were fixed.

**Comment by Creeper20428** [comment]
I've had some more free time on my hands this week, so I've been able to test some operating systems.

Windows 95 does not boot (I tested), but somehow, Windows XP (a copy on a virtual hard disk, set memory size over 1600 MB) gets all the way to the screen that says "Windows did not shut down properly. Please choose an option blah blah blah". However, when selecting any of them, they all seem to stop working. On closer inspection, all of the options seem to throw a "Double Fault" error. 

Microsoft says that this is caused by the ESP register going out of bounds, therefore causing a page fault exception. And then, it does it again, causing a double fault (or at least what I read on https://support.microsoft.com/en-us/kb/842465 and https://support.microsoft.com/en-us/kb/137539). 

IMO, booting Windows XP would be amazing.

**Comment by copy** [comment]
I'm testing multiple versions of Windows regularly too. At this point newer versions (2000 and up) don't run because we don't have an [APIC](http://wiki.osdev.org/Apic).

**Comment by Gmoney2123** [comment]
> I'm testing multiple versions of Windows regularly too. At this point newer versions (2000 and up) don't run because we don't have an APIC.

How hard would it be to implement this?

**Comment by copy** [comment]
> How hard would it be to implement this?

Have a look at chapter 10 of [this manual file](https://www-ssl.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-system-programming-manual-325384.pdf). It'd probably be a few weekends for me, but right now I'm busy with other projects.

**Comment by copy** [comment]
APIC is now there and XP boots.
