### ISSUE TITLE
Save Hard Drive state [Node.js]

### ISSUE THREAD

**Issue by StreamerYT** [copy/v86#535]
How do I do this in Node.js? #509

**Comment by copy** [comment]
`emulator.disk_images.hda` gives you the right object. 

You could implement writing back to the file here: https://github.com/copy/v86/blob/85df1ec/src/browser/lib.js#L334

Or implement this: https://github.com/copy/v86/blob/85df1ec/src/browser/lib.js#L395 or use this: https://github.com/copy/v86/blob/85df1ec/src/browser/lib.js#L401
