### ISSUE TITLE
British keyboard doesnt work

### ISSUE THREAD

**Issue by Milo123459** [copy/v86#536]
If you use a british keyboard, pressing the @ key gets transformed to ". This shouldn't happen. This also happens when I press the " key, it transforms to @

**Comment by pitust** [comment]
good. The en-US keyboard layout is objectively superior.

**Comment by Milo123459** [comment]
Still a bug. I'm not going for a war over keyboard layouts

**Comment by copy** [comment]
Not a bug in v86, we only forward physical keys and it's up to the guest OS to interpret them. You can change they layout in the guest. On Linux you can run `loadkeys uk`.
