### ISSUE TITLE
Serial port terminal supports 24 bit color, but console does not

### ISSUE THREAD

**Issue by mrled** [copy/v86#539]
When I run programs that output "true color" aka "24bit color", they work as expected on the terminal.js attached to the serial port, but not on the console.

I tested this with a custom [browser-vm](https://github.com/humphd/browser-vm) and a Go program called [rainbow](https://github.com/arsham/rainbow/). On my host macOS machine and on the serial port, `rainbow` shows 24 bit color, but on the video console it shows only 8 bit color.

I built `rainbow` like so:

```sh
export BROWSER_VM_LOCAL_BIN=/path/to/browser-vm/buildroot-v86/board/v86/rootfs_overlay/usr/local/bin/

go get github.com/arsham/rainbow
cd $GOPATH/pkg/mod/github.com/arsham/rainbow@v1.1.1
GOOS=linux GOARCH=386 go build -o $BROWSER_VM_LOCAL_BIN/rainbow
```

And then I built browser-vm according to its instructions. The `rainbow` binary I placed inside of rootfs_overlay is copied automatically into the image.

Note that the top terminal (the serial console) has fine gradients of color, but the bottom console (the video console) has only bright/dim versions of the basic colors.

![Screen Shot 2021-10-15 at 15 39 41](https://user-images.githubusercontent.com/129654/137550764-a9ba778b-6501-4f61-aa29-56015686f967.png)

Is there something I can do differently to get true color support on the video console, so I don't have to go over serial? For what it's worth, I don't need X or anything graphical.

**Comment by copy** [comment]
The linux kernel console doesn't fully support full colours (https://github.com/termstandard/colors#partial-support). The vga text modes don't support it either, as far as I know. There are some framebuffer terminal emulators that might support full colours (e.g. https://salsa.debian.org/debian/fbterm and https://github.com/aligrudi/fbpad), but they require a graphical vga mode. Not much we can do on our side, unfortunately.

**Comment by copy** [comment]
Closing as nothing to do on our side.
