### ISSUE TITLE
Where to put downloaded image files from https://github.com/copy/images/

### ISSUE THREAD

**Issue by Denisbg2011game** [copy/v86#546]
hi i am setting up v86 on my webserver and i am wondering where are the defualt images stored i put tem in a images directory inside the v86 folder but when i try to click on the presets they dont load, i would like to know where to put these images because i want the presets to work
i can give the server address so you can see
i have full access to the machine but it dosent have systemd
i dont think thats a problem
looking forward

if you need the website here it is https://denis.run-eu-central1.goorm.io/v86-emu.php
_

**Comment by Denisbg2011game** [comment]
edit: my website will be down because my laptop has low batter but if you can tell me where to put the files i would be happy

thanks
-denis

**Comment by Denisbg2011game** [comment]
@copy can i get help, please

**Comment by copy** [comment]
Responded in gitter.

**Comment by Denisbg2011game** [comment]
thanks i will look on there!
