### ISSUE TITLE
HDD & CDROM

### ISSUE THREAD

**Issue by well0nez** [copy/v86#55]
hi everyone,

its not possible to use CDROM and HDD at the same time.

If i select my ISO and my HDD it tries to boot from the hdd.

**Comment by xming** [comment]
I can confirm this, boot_order doesn't seems to work when both cd and hdd images are selected, v86 always tries to boot floppy then hdd and never tries cd.

**Comment by scheurneus** [comment]
I believe this issue is with the used BIOS. Limbo on Android also suffered from this for me. Both use SeaBIOS AFAIK.

**Comment by copy** [comment]
@scheurneus This might well be the case. I've had problems with many old operating systems that rely on the BIOS for disk services.

Anyway, I have a fix this issue, but I'll do some more testing with different images before pushing it.

**Comment by rafaelgieschke** [comment]
I had the same issue (boot_order arbitrary, only one device being detected by the operating system), could only be solved by using the bochs BIOS (`bochs-bios.bin`, `bochs-vgabios.bin`); with the bochs BIOS it immediately ran very fine, though.
