### ISSUE TITLE
Vista 5112 booting in V86

### ISSUE THREAD

**Issue by ruslanshchur** [copy/v86#552]
Here is a Vista 5112 booting in V86, but it fails to boot with a BSOD DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS, but we can at least get into the boot screen thanks to ACPI
![Vista5112bootinginV86](https://user-images.githubusercontent.com/88822931/140786810-6264974e-f449-4902-88eb-5c96cd03b182.PNG)
![Vista5112failstoboot](https://user-images.githubusercontent.com/88822931/140787084-6518d412-a568-491e-9bbc-ed9ac291c65b.PNG)
(Note I use the Longhorn Server 5112 ISO, as I am too lazy to download the Vista 5112 ISO)

**Comment by copy** [comment]
Interesting. See https://github.com/copy/v86/issues/404 for some more discussion.
