### ISSUE TITLE
possible typo?

### ISSUE THREAD

**Issue by ReconEvacuateDEVX** [copy/v86#553]
![image](https://user-images.githubusercontent.com/89051107/140955088-1cb6742a-07d9-44b6-8b67-55d471cfccd4.png)

**Comment by copy** [comment]
What's the typo?

**Comment by hello-smile6** [comment]
> What's the typo?

```diff
- written in
+ that fits into
the boot sector.
```

**Comment by hello-smile6** [comment]
@copy
