### ISSUE TITLE
ARCH LINUX: Loading the image `http://localhost:8000/arch/undefined` failed (status 404)

### ISSUE THREAD

**Issue by crossdev-app** [copy/v86#558]
Hi, buddy.

I was trying to build an arch linux system to embed on my site.. so i follow all steps on archlinux.md documentation.

At first i face an error when i run build.sh, it says that iso_checksum is deprecated so i run the qemu template_fix to fix the template.json. And its fixed.

And then i continue to run build.sh, now i face another error, when its come to execute pacstrap and trying to install all package. it says that it from unknown trust. so the all the package fail to install.
trying to fix that error with bypass the SigLevel on pacman.conf, add to it "Never TrustAll". then i continue the proccess, its work, the pacstrap success to install all package.

Now i have an arch.img file that run normally on qemu. Then i continue to next step. build 9p filesystem.
The proccess run normaly, im not facing the error at this time.
I run RangeHTTPServer.py, edit the arch.html as the documentation says.
And, this is the main problem. It says that Loading the image `http://localhost:8000/arch/undefined` failed (status 404).

What happen? did i missing something? Any advice?

**Comment by crossdev-app** [comment]
The stack-trace

	a
libv86.js:formatted:12214
ServerFileStorageWrapper.prototype.load_from_server/<
libv86.js:formatted:13337
ServerFileStorageWrapper.prototype.load_from_server
libv86.js:formatted:13336
ServerFileStorageWrapper.prototype.read
libv86.js:formatted:13347
FS.prototype.get_data
libv86.js:formatted:13841
FS.prototype.Read
libv86.js:formatted:13745
Virtio9p.prototype.ReceiveRequest
libv86.js:formatted:1118
Virtio9p/this.virtio<.notification.handlers<
libv86.js:formatted:708
IO.prototype.port_write16
libv86.js:formatted:1476
io_port_write16
libv86.js:formatted:12568
<anonymous>
http://localhost:8000/build/libv86.js line 704 > WebAssembly.instantiate:1611764:-2147482395
<anonymous>
http://localhost:8000/build/libv86.js line 704 > WebAssembly.instantiate:1434722:-2147482395
<anonymous>
http://localhost:8000/build/libv86.js line 704 > WebAssembly.instantiate:1648290:-2147482375
<anonymous>
http://localhost:8000/build/libv86.js line 704 > WebAssembly.instantiate:1648699:-2147482373
CPU.prototype.do_many_cycles
libv86.js:formatted:10203
CPU.prototype.do_run
libv86.js:formatted:10196
CPU.prototype.main_run
libv86.js:formatted:9978
v86.prototype.do_tick
libv86.js:formatted:1580
a
libv86.js:formatted:1627

**Comment by copy** [comment]
I pushed a fix to the [`wip`](https://github.com/copy/v86/tree/wip) branch, could you rerun with the `fs2json.py` from that branch and let me know if it fixes your issue?

Also, instead of `hda: { … }` you can specify `bzimage_initrd_from_filesystem: true` and `cmdline: "…"` (remove `--exclude /boot/`).  See [arch.html](https://github.com/copy/v86/blob/master/examples/arch.html). Then you won't need the `arch.img` file and the boot process will be a bit faster.

**Comment by crossdev-app** [comment]
Hey, feb.

wich one should i rerun? fs2json.py ? copy-to-sha256.py? or both?

then, i should run the command without --exclude /boot/ ?

**Comment by copy** [comment]
Yes, rerun both.

Omit `--exclude /boot/` only if you want to switch from `hda` to `bzimage_initrd_from_filesystem` (have a look at the example I linked above).

**Comment by crossdev-app** [comment]
Hey, feb.

on 'build.sh', i see the command to run 'fs2json.py' like this
-> 'sudo python resources/fs2json.py --exclude /boot/ --out output/images/fs.json diskmount'

then i should change it to be like this
-> 'sudo python resources/fs2json.py --out output/images/fs.json diskmoun'

But,when i'm looking on documentation to run the command for 'copy-to-sha256.py', i can't find it.
Is it same cammand like to run 'fs2json.py'?

**Comment by crossdev-app** [comment]
I've run build.sh with modification command above and i got an error says like this..

(After provsioning process)

==> Wait completed after 24 minutes 14 seconds

==> Builds finished. The artifacts of successful builds are:
--> qemu: VM files in directory: output-qemu
Making sure mountpoint is empty
umount: diskmount: no mount point specified.
losetup: /dev/loop0: detach failed: No such device or address
Mounting the created image so we can convert it to a p9 image
Creating file tree ...
Traceback (most recent call last):
  File "/home/crossdev/Development/Project/ISOFIX/archlinux-v86-builder/resources/fs2json.py", line 272, in <module>
    main()
  File "/home/crossdev/Development/Project/ISOFIX/archlinux-v86-builder/resources/fs2json.py", line 84, in main
    (root, total_size) = handle_dir(logger, path, args.exclude)
  File "/home/crossdev/Development/Project/ISOFIX/archlinux-v86-builder/resources/fs2json.py", line 202, in handle_dir
    assert existing is None or existing == file_hash, "Collision in short hash (%s and %s)" % (existing, file_hash)
AssertionError: Collision in short hash (eaa5df853be8f16fc3b6016c1ad2d6220b6cb88ada74c03279e1aa85a99ca7f7 and eaa5df852f5773bd4bf9ce434b275b8473cce279bd7487c86e75cf6e2d420bfb)
Copying the filesystem to output/arch
Cleaning up mounts

**Comment by copy** [comment]
@crossdev-app Apologies, the process has changed and we forgot to update the docs. Will update the docs as soon as possible.

Run both `copy-to-sha256.py` and `fs2json.py` from the `tools` directory of the `wip` branch, as follows:

- `v86/tools/fs2json.py diskmount --out output/images/fs.json`
- `v86/tools/copy-to-sha256.py diskmount output/images/arch`

And use the following settings (with the paths adapted to the output of the commands above): https://github.com/copy/v86/blob/master/examples/arch.html#L10-L31

It's not necessary (but also not harmful) to copy the `diskmount` directory or the `arch.img` file. You should only need `fs.json` and a directory full of `.bin` files in your webserver directory.

**Comment by crossdev-app** [comment]
@copy ,

I've run both of files as flows. but i got some error, when it's start execute `copy-to-sha256.py`.
it says like this: `NameError : name 'path' is not defined`

and then i'm checking on the file, i got some warning on `line-46` . says 'path' is not defined to.
where is this 'path' referring to? is it refer to 'from_path'?

My speculation, it's refer to 'from_path', so i changed it like so.

and now i got error again. Haha
it says like this -> `ErrNo2: No such file or directory`

What sould i do now? I'm not master at python yet.

**Comment by crossdev-app** [comment]
Stack-trace

==> Builds finished. The artifacts of successful builds are:
--> qemu: VM files in directory: output-qemu
Making sure mountpoint is empty
umount: diskmount: no mount point specified.
losetup: /dev/loop0: detach failed: No such device or address
Mounting the created image so we can convert it to a p9 image
::>>>>> Now your turn to execute aunaly python file..
Creating file tree ...
Creating json ...
cp diskmount/bootstrap.sh output/images/arch/7b01aff7.bin
Traceback (most recent call last):
  File "/home/crossdev/Development/Project/ISOFIX/archlinux-v86-builder/resources/copy-to-sha256.py", line 94, in <module>
    main()
  File "/home/crossdev/Development/Project/ISOFIX/archlinux-v86-builder/resources/copy-to-sha256.py", line 46, in main
    handle_dir(logger, from_path, to_path)
  File "/home/crossdev/Development/Project/ISOFIX/archlinux-v86-builder/resources/copy-to-sha256.py", line 74, in handle_dir
    shutil.copyfile(absname, to_abs)
  File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'output/images/arch/7b01aff7.bin'
Copying the filesystem to output/arch
Cleaning up mounts

**Comment by copy** [comment]
`mkdir -p output/images/arch` before running the script

**Comment by crossdev-app** [comment]
Hey, fab..

You're amazing!
its working now. No error on building the files for v86.

only one problem left.. when it start booting on v86, it run command `init=/usr/bin/init-openrc`. unfortunately the file doesn't exist.
When i run `pacman -S openrc` it says package not found.. so i try to find solution for it that it should install manually from AUR.
[here](https://wiki.archlinux.org/title/OpenRC)
I'm afraid that it will going wrong. and make other error.

do you have any solution to solve that problem? or it must be install manually from AUR?

**Comment by copy** [comment]
@crossdev-app Remove `init=/usr/bin/init-openrc`. systemd should be installed as `/bin/init` and should be executed automatically.

**Comment by copy** [comment]
Fixed in 0247e75.
