### ISSUE TITLE
SectorLISP appears to hang after "Booting from Floppy..."

### ISSUE THREAD

**Issue by foxsouns** [copy/v86#565]
does not seem to move past this point, also broken when using latest sectorlisp.bin from https://github.com/jart/sectorlisp/blob/040852302c1bd37b16bfb8f123083b80c07fd0be/bin/sectorlisp.bin
![stuck](https://user-images.githubusercontent.com/60267141/145286313-e781f8e4-557e-4f45-8fb6-4b27533ed120.png)

**Comment by copy** [comment]
That means it's working. There is no command prompt.

![Screenshot_2021-12-08_20-23-45](https://user-images.githubusercontent.com/1816456/145317418-119d2dbf-f13b-493b-a2bf-770bcd334294.png)

(I have no idea how to lisp)

**Comment by jart** [comment]
@copy It looks like you got snagged by undefined behavior D:  You likely wanted something more like this:

![image](https://user-images.githubusercontent.com/49262/147049741-4ff9835f-9bb4-4c7d-b85a-924e6d4ff9fa.png)

I would recommend we upgrade to SectorLISP v2 which has a "sectorlisp-friendly.bin" disk image. https://justine.lol/sectorlisp2/ 
It'll be a much better friend, since it supports the niceties (but non-essential) features that will be a much better friend to anyone getting started, e.g. `DEFINE`, dot cons literals, function parameters defaulting to `NIL`, undefined variable reporting. etc.

**Comment by hello-smile6** [comment]
> @copy It looks like you got snagged by undefined behavior D: You likely wanted something more like this:
> 
> ![image](https://user-images.githubusercontent.com/49262/147049741-4ff9835f-9bb4-4c7d-b85a-924e6d4ff9fa.png)
> 
> I would recommend we upgrade to SectorLISP v2 which has a "sectorlisp-friendly.bin" disk image. https://justine.lol/sectorlisp2/ It'll be a much better friend, since it supports niceties (but non-essential features) like `DEFINE`, dot cons literals, function parameters defaulting to `NIL`, undefined variable reporting. etc.

???

**Comment by jart** [comment]
That's a screenshot of SectorLISP v2 running in Blinkenlights. Read the blog post for more context. There's also a discussion on Hacker News https://news.ycombinator.com/item?id=29630293

**Comment by foxsouns** [comment]
thats jarts emulator, its neat
https://justine.lol/blinkenlights/

**Comment by hello-smile6** [comment]
> thats jarts emulator, its neat https://justine.lol/blinkenlights/

Is that a 64-bit emulator???

**Comment by foxsouns** [comment]
> > thats jarts emulator, its neat https://justine.lol/blinkenlights/
> 
> Is that a 64-bit emulator???

its an x86 emulator for programs, i think. if you wanna know what it is, look at that link i posted.

**Comment by hello-smile6** [comment]
> > > thats jarts emulator, its neat https://justine.lol/blinkenlights/
> > 
> > 
> > Is that a 64-bit emulator???
> 
> its an x86 emulator for programs, i think. if you wanna know what it is, look at that link i posted.

Could someone send me a Slax ISO on https://instant.io/ please?

**Comment by foxsouns** [comment]
lol, ok, but no more discussion here. let us stop necroposting on a gh issue i posted: my email is on my profile page here.

**Comment by hello-smile6** [comment]
> lol, ok, but no more discussion here. let us stop necroposting on a gh issue i posted: my email is on my profile page here.

I don't use email. Use https://dirc.9pfs.repl.co/#v86

**Comment by hello-smile6** [comment]
> lol, ok, but no more discussion here. let us stop necroposting on a gh issue i posted: my email is on my profile page here.

Are you on dirc?

**Comment by foxsouns** [comment]
yes, are you?

**Comment by foxsouns** [comment]
whatever. x86_64 or x86, ill post the link when im done

**Comment by hello-smile6** [comment]
It's not connecting, try reloading

**Comment by foxsouns** [comment]
@hello-smile6 okay then, take both
https://instant.io/#69bd5fe50f34e3c0447ff6ae3cf6cf2a1f8ab1ab

**Comment by hello-smile6** [comment]
> @hello-smile6 okay then, take both https://instant.io/#69bd5fe50f34e3c0447ff6ae3cf6cf2a1f8ab1ab

Keep the tab open

**Comment by foxsouns** [comment]
closing tab.

**Comment by hello-smile6** [comment]
> closing tab.

My device went down right as you sent the link, unfortunately. How would I run Slax using libv86?

**Comment by copy** [comment]
> I would recommend we upgrade to SectorLISP v2 which has a "sectorlisp-friendly.bin" disk image. https://justine.lol/sectorlisp2/
It'll be a much better friend, since it supports niceties (but non-essential features) like DEFINE, dot cons literals, function parameters defaulting to NIL, undefined variable reporting. etc.

Amazing work! I've updated the version on the website the friendly version.
