### ISSUE TITLE
Microsoft Edge SmartScreen Warning

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#567]
@copy copy.sh is in Microsoft's SmartScreen site blacklist! Just letting you know.

**Comment by copy** [comment]
Neither myself nor @ErnWong could reproduce this. Will close for now, but if you see it again could you post a screenshot?

**Comment by hello-smile6** [comment]
@copy I managed to reproduce.
![Annotation 2021-12-13 185335](https://user-images.githubusercontent.com/73048226/145924502-e21d98f5-19b7-4431-8df8-a01aba5ca718.png)
URL that caused it: https://copy.sh/v86/?profile=custom

**Comment by ErnWong** [comment]
I tried your link, and I can reproduce it too. It only seems to be for https://copy.sh/v86/?profile=custom specifically, and only when I enter it from the address bar. It doesn't seem to be triggered when I start a machine instance dynamically from https://copy.sh/v86/.

Other urls seem fine for me:

<details>
<p dir="auto"><a href="https://copy.sh/" rel="nofollow">https://copy.sh/</a><br>
<a href="https://copy.sh/v86/" rel="nofollow">https://copy.sh/v86/</a><br>
<a href="https://copy.sh/v86/?profile=archlinux" rel="nofollow">https://copy.sh/v86/?profile=archlinux</a><br>
<a href="https://copy.sh/v86/?profile=dsl" rel="nofollow">https://copy.sh/v86/?profile=dsl</a><br>
<a href="https://copy.sh/v86/?profile=buildroot" rel="nofollow">https://copy.sh/v86/?profile=buildroot</a><br>
<a href="https://copy.sh/v86/?profile=reactos" rel="nofollow">https://copy.sh/v86/?profile=reactos</a><br>
<a href="https://copy.sh/v86/?profile=windows2000" rel="nofollow">https://copy.sh/v86/?profile=windows2000</a><br>
<a href="https://copy.sh/v86/?profile=windows98" rel="nofollow">https://copy.sh/v86/?profile=windows98</a><br>
<a href="https://copy.sh/v86/?profile=windows95" rel="nofollow">https://copy.sh/v86/?profile=windows95</a><br>
<a href="https://copy.sh/v86/?profile=windows1" rel="nofollow">https://copy.sh/v86/?profile=windows1</a><br>
<a href="https://copy.sh/v86/?profile=msdos" rel="nofollow">https://copy.sh/v86/?profile=msdos</a><br>
<a href="https://copy.sh/v86/?profile=freedos" rel="nofollow">https://copy.sh/v86/?profile=freedos</a><br>
<a href="https://copy.sh/v86/?profile=freebsd" rel="nofollow">https://copy.sh/v86/?profile=freebsd</a><br>
<a href="https://copy.sh/v86/?profile=openbsd" rel="nofollow">https://copy.sh/v86/?profile=openbsd</a><br>
<a href="https://copy.sh/v86/?profile=9front" rel="nofollow">https://copy.sh/v86/?profile=9front</a><br>
<a href="https://copy.sh/v86/?profile=haiku" rel="nofollow">https://copy.sh/v86/?profile=haiku</a><br>
<a href="https://copy.sh/v86/?profile=oberon" rel="nofollow">https://copy.sh/v86/?profile=oberon</a><br>
<a href="https://copy.sh/v86/?profile=kolibrios" rel="nofollow">https://copy.sh/v86/?profile=kolibrios</a><br>
<a href="https://copy.sh/v86/?profile=qnx" rel="nofollow">https://copy.sh/v86/?profile=qnx</a><br>
<a href="https://copy.sh/v86/?profile=snowdrop" rel="nofollow">https://copy.sh/v86/?profile=snowdrop</a><br>
<a href="https://copy.sh/v86/?profile=solos" rel="nofollow">https://copy.sh/v86/?profile=solos</a><br>
<a href="https://copy.sh/v86/?profile=bootchess" rel="nofollow">https://copy.sh/v86/?profile=bootchess</a><br>
<a href="https://copy.sh/v86/?profile=sectorlisp" rel="nofollow">https://copy.sh/v86/?profile=sectorlisp</a></p>
</details>

**Comment by hello-smile6** [comment]
> I tried your link, and I can reproduce it too. It only seems to be for https://copy.sh/v86/?profile=custom specifically, and only when I enter it from the address bar. It doesn't seem to be triggered when I start a machine instance dynamically from https://copy.sh/v86/.
> 
> Other urls seem fine for me:

Same for me.

**Comment by copy** [comment]
Thanks. I've reported the url as non-malicious. Let's see what happens.

**Comment by hello-smile6** [comment]
MSFTis clueless, LOL.

**Comment by hello-smile6** [comment]
@copy MSFT's giving false malware alerts again!
![image](https://user-images.githubusercontent.com/73048226/147784339-f79da603-8c6e-4fa3-b3b5-ca898fa45a07.png)
Same URL as the first time.
