### ISSUE TITLE
Networking between two or more instances

### ISSUE THREAD

**Issue by nicopace** [copy/v86#569]
Is this posible?

**Comment by copy** [comment]
You should be able to listen to `net0-send` events on one instance, send it to `net0-receive` of the other instance and vice versa.

**Comment by hello-smile6** [comment]
It works. 🙂

**Comment by copy** [comment]
Would probably be nice to add this to [examples/two_instances.html](https://github.com/copy/v86/blob/master/examples/two_instances.html).

Closing since everything is working.

**Comment by hello-smile6** [comment]
> Would probably be nice to add this to [examples/two_instances.html](https://github.com/copy/v86/blob/master/examples/two_instances.html).
> 
> Closing since everything is working.

"Working" is a strong word; every VM broadcasts packets, instead of sending them to the destination, but ICMP and TCP (HTTP, tested using Arch and Win2k) work perfectly.

**Comment by wiwwo** [comment]
Hi everybody!
I'm still not able to run this in `two_instances.html`...
Is it being implemented?
@hello-smile6 could you share your config?

Thanks a ton everybody!

**Comment by wiwwo** [comment]
Forgetaboutit, done! :-)
