### ISSUE TITLE
Single-file copy

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#570]
Is there a single-file version of v86 (base64-encoded WASM file as part of the binary) that would work from a `file:///` context?

**Comment by copy** [comment]
Not yet, but contributions are welcome.

**Comment by hello-smile6** [comment]
> Not yet, but contributions are welcome.

Could you simply make libv86 accept a URL rather than a path for the WASM file and send an `Access-Control-Allow-Origin: *` header on the https://copy.sh/v86 v86.wasm file?

**Comment by copy** [comment]
> Could you simply make libv86 accept a URL rather than a path for the WASM file and send an Access-Control-Allow-Origin: * header on the https://copy.sh/v86 v86.wasm file?

I have no plans of adding CORS headers to my website, so no.

**Comment by hello-smile6** [comment]
Not even just for the WASM file? Also, personal-server.9pfs.repl.co/v86.wasm

**Comment by copy** [comment]
You can pass `wasm_path: "http://personal-server.9pfs.repl.co/v86.wasm"` to use a self-hosted v86.wasm.

**Comment by hello-smile6** [comment]
> You can pass `wasm_path: "http://personal-server.9pfs.repl.co/v86.wasm"` to use a self-hosted v86.wasm.

Okay.

**Comment by hello-smile6** [comment]
Could I have a working example?
