### ISSUE TITLE
Stuck at boot screen does not boots

### ISSUE THREAD

**Issue by PREKNOWLEDGEWEB** [copy/v86#572]
![image](https://user-images.githubusercontent.com/83751707/146148459-b3a35b6e-5085-415b-8e3c-7a4a8b3f53f9.png)

**Comment by BenNottelling** [comment]
V86 doesn't support a lot of the hardware requirements that new OS's require.

The newest version of windows that might work is like vista

**Comment by Pixelsuft** [comment]
> V86 doesn't support a lot of the hardware requirements that new OS's require.
> 
> The newest version of windows that might work is like vista

Windows 7 works, too.


How I know, Windows 11 is only x64, but v86 supports only x86

**Comment by BenNottelling** [comment]
It only supports x86 and does NOT support PAE emulation which is a requirement for any of the recent versions of windows. (I think starting with windows 8)

There are probably many other CPU instructions that would be missing as well, but without PAE there's really no hope unless you somehow manage to patch the OS

**Comment by copy** [comment]
If you send me the iso I might have a look. That said, it's probably better to use a thread with the corresponding Windows version.

**Comment by hello-smile6** [comment]
See #571
