### ISSUE TITLE
Arch Linux - Stuck on Boot

### ISSUE THREAD

**Issue by crossdev-app** [copy/v86#573]
Hello Fabian | @copy ,

I found something bad again. :(
I've successfully build the file system. But, when I try to load those file on webserver, it stuck.
![Screenshot_74](https://user-images.githubusercontent.com/39781274/146489190-fe97e42b-2e02-4ab5-b37a-90c54768b00b.png)
![Screenshot_75](https://user-images.githubusercontent.com/39781274/146489206-05cd18c5-3c99-493a-8d42-3ee8a28a2986.png)

Is there something I miss-configurating the build?

**Comment by hello-smile6** [comment]
That's not your build, that's the v86 download script, I think.

**Comment by crossdev-app** [comment]
Yaa i think there's no problem with the build, bcs it run normally on qemu.

But which one v86 script that cause the error?
I download the libv86.js, v86_all.js, xterm.js, and v86.wasm when i run Arch Linux on copy.sh
Is that doesn't match with my build?

**Comment by hello-smile6** [comment]
> Yaa i think there's no problem with the build, bcs it run normally on qemu.
> 
> But which one v86 script that cause the error? I download the libv86.js, v86_all.js, xterm.js, and v86.wasm when i run Arch Linux on copy.sh Is that doesn't match with my build?

IDK, but check #575 .

**Comment by copy** [comment]
I can't reproduce this issue, could you:

- Show the contents of the network ("Jaringen") tab
- Replace libv86.js with libv86-debug.js (you will also need v86-debug.wasm) and post the contents of the console tab (right click -> save as)

**Comment by copy** [comment]
Feel free to reopen with clearer instructions to reproduce this issue.
