### ISSUE TITLE
support for shift + f10?

### ISSUE THREAD

**Issue by desplol** [copy/v86#579]
im new on github so i have no idea how to add labels

**Comment by copy** [comment]
Which OS?

**Comment by desplol** [comment]
microsoft oses, like windows

**Comment by desplol** [comment]
sorry i didnt respond its been christmas

**Comment by copy** [comment]
Seems to be working for me in both Chromium and Firefox (it opens a context menu on the desktop).

**Comment by hello-smile6** [comment]
> Seems to be working for me in both Chromium and Firefox (it opens a context menu on the desktop).

Same for me. It seems like the VM is handling the button press.

**Comment by desplol** [comment]
ok, thanks it didnt work for me at the time
