### ISSUE TITLE
Running a QBasic program freezes my cursor

### ISSUE THREAD

**Issue by ullenboom** [copy/v86#58]
The QBasic editor works fine, but if I want to start a program (Shift+F5) it is hanging and also freeze my browser one time. (Has to be a bug in Chrome.) Also not working in IE.

If you want to try it yourself, remove ".jpg" from the attached Floppy disk image and rename it to qbasic.img e.g.

![qbasic img](https://cloud.githubusercontent.com/assets/5071169/7402050/12a99b6e-eec9-11e4-9fba-530b7572408a.jpg)

**Comment by copy** [comment]
I cannot reproduce the freezing, but the screen turns black. Is that the problem you're having?

**Comment by ullenboom** [comment]
This is exactly the problem, the screen stays black. At the begining thats ok, but the basic programm should run, like shown in the screenshot.
![unbenannt](https://cloud.githubusercontent.com/assets/5071169/7408122/cc1cd4b2-ef19-11e4-9374-07c919bd228c.JPG)

**Comment by copy** [comment]
Got it, thanks. The interpreter actually seems to work (you can see the result by selecting the text), but the text colour is incorrect. I'll fix this soon.
