### ISSUE TITLE
WebGPU

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#580]
WebGPU is a new web API which allows websites to directly access the GPU (with restrictions). Could v86 use WebGPU to either:

- Allow VMs to use the GPU
- Somehow run CPU instructions using the GPU
- Address more memory

I'm hoping that there's some way v86 can use WebGPU.

**Comment by hello-smile6** [comment]
@copy Could something be done using WebGPU?

**Comment by copy** [comment]
Yes, see https://github.com/copy/v86/issues/51. However, I won't have time to work on anything anytime soon.

**Comment by hello-smile6** [comment]
> Yes, see #51. However, I won't have time to work on anything anytime soon.

So, would it be possible to let VMs directly use the GPU via WebGPU?

**Comment by copy** [comment]
Closing, see https://github.com/copy/v86/issues/51#issuecomment-976047113
