### ISSUE TITLE
Use decimal for hexadecimal values???

### ISSUE THREAD

**Issue by hello-smile6** [copy/v86#581]
I noticed that many numbers in 
https://github.com/copy/v86/blob/7117e2880c90263f2a0380d7ea08b8b71b3e87b9/src/cpu.js#L1-L1523

 are stored as hexadecimal. For instance:
https://github.com/copy/v86/blob/7117e2880c90263f2a0380d7ea08b8b71b3e87b9/src/cpu.js#L823
Would it be more efficient (for performance) to store them in decimal form?

**Comment by copy** [comment]
Representation in source code has no impact on performance.
