### ISSUE TITLE
Very poor network performance.

### ISSUE THREAD

**Issue by leoleoasd** [copy/v86#582]
I ran an instance of `websockproxy` on my mac using docker, then from inside v86, I tried `curl` a file on my mac served using `python3 -m http.server` from my mac's LAN IP.
I'm only getting about 1-2 kbps. What am I doing wrong, or the performance is this bad indeed?

**Comment by copy** [comment]
The server is rate-limited to prevent abuse. You can change it here: https://github.com/benjamincburns/websockproxy/blob/41889d8/switchedrelay.py#L25

In general, the performance isn't very good anyways (the server is written in Python, the network card in JavaScript, it's slow network card and the transport is websocket), but it should be better than a few kbps.

**Comment by BenNottelling** [comment]
If you're using docker, I already have an image on dockerhub that has the limit removed
`docker run --privileged -p 8080:80 --name relay bennottelling/websockproxy`
