### ISSUE TITLE
How to set boot order to specific drive

### ISSUE THREAD

**Issue by Unzor** [copy/v86#583]
Hello,
I have a Pop! OS disk image and I need to set the boot order to D:. Is it possible to do that? Thanks!

**Comment by Unzor** [comment]
(Oh, and by the way, I mean using the libv86 API)

**Comment by hello-smile6** [comment]
> (Oh, and by the way, I mean using the libv86 API)

Not sure. Do you know how to set up networking and mount a directory using `showDirectoryPicker`?

**Comment by Unzor** [comment]
Nope

**Comment by hello-smile6** [comment]
> Nope

Ugh. :(

**Comment by copy** [comment]
You can pass `boot_order` to V86, which in turn is passed to seabios. Unfortunately it doesn't look like seabios allows specifying a second hard drive though: https://github.com/coreboot/seabios/blob/a5cab58e9a3fb6e168aba919c5669bea406573b4/src/boot.c#L271-L285

**Comment by hello-smile6** [comment]
> You can pass `boot_order` to V86, which in turn is passed to seabios. Unfortunately it doesn't look like seabios allows specifying a second hard drive though: https://github.com/coreboot/seabios/blob/a5cab58e9a3fb6e168aba919c5669bea406573b4/src/boot.c#L271-L285

How would I mount a directory using `showDirectoryPicker()` and enable networking?
