### ISSUE TITLE
VM using 100% CPU

### ISSUE THREAD

**Issue by xming** [copy/v86#59]
I wonder how do you avoid 100% CPU (on one core) with Linux, all the Linux images (2.6.x and 3.x) on copy.sh use 100% and my self compiled kernel with CONFIG_NO_HZ_IDLE=y and HZ=50 too, on both firefox and chromium.

**Comment by xming** [comment]
hehe, who would have thought that. Adding
```
<link rel="stylesheet" href="v86.css">
```
will solve the 100% CPU issue with 50Hz kernel.

**Comment by copy** [comment]
It hasn't anything to do with the stylesheet.

If you rebuilt any files in `build/`, that's probably the cause. I've fiddled with this recently and the built files from the repository might be a bit different from the ones I pushed.

**Comment by xming** [comment]
Currently I am using recompiled v86_all.js and it works, it might be the old v86_all.js or libv86.js that was troubling.

But the browser still uses 100% when v86 is not the active tab.

**Comment by s-macke** [comment]
Can you debug the place were the Javascript execution is sent to sleep? Should be somewhere at a setTimeout function.
The sleeping time should be around 20ms for 50Hz ticks. Sleeping times below 10ms might be very inaccurate and below 4ms it is not guaranteed, that he sleeps at all.
