### ISSUE TITLE
Add support for file upload to emulator

### ISSUE THREAD

**Issue by Unzor** [copy/v86#594]
Hello,
I have been wondering if it is possible to upload a file to an emulator, as I want to upload a .png image to KolibriOS.
Thanks

**Comment by SuperMaxusa** [comment]
This feature is already available in [Arch Linux](https://copy.sh/v86/?profile=archlinux) and [Buildroot Linux](https://copy.sh/v86/?profile=buildroot), but this works on 9pfs, which not supporting on KolibriOS.

**Comment by hello-smile6** [comment]
If you want to get data out, use this.
```
command>tmpfile.txt;dd if=tmpfile.txt|gzip --compress --stdout|base64|dd of=/dev/ttyS0
```
Then, copy and paste the base64-encoded gzipped data into a file.
On the host OS or another VM (such as Buildroot/Arch (Use https://copy.sh/v86/?profile=buildroot if you want a VM that only has what you need), run this.
```
cd /mnt
dd if=tmpfile.txt.gz.base64|base64 -d|gzip --decompress --stdout>tmpfile.txt
```
Then, export the file `tmpfile.txt` via the 9p filesystem and use it for whatever you need.

**Comment by Unzor** [comment]
This is not what I was looking for. Also, I am closing this because @SuperMaxusa has given an answer.

**Comment by hello-smile6** [comment]
> This is not what I was looking for. Also, I am closing this because @SuperMaxusa has given an answer.

Okay, but it works. You may be able to use `btoa()` and a JS implementation of gzip to automate that.
