### ISSUE TITLE
Screen in linux text mode completely black after upgrade to new version

### ISSUE THREAD

**Issue by rdancer** [copy/v86#595]
After upgrade from 867e9d to 6b9d1f, the screen  is entirely black (text-mode Linux). In fact, text is being displayed, but it is black-on-black:

`<span style="background-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">Lorem Epsom donor sit Ahmed</span>`

This is for both default colour, and for all kinds of colours set via escape sequences.

Before upgrade:
![Screenshot 2022-01-08 at 21 12 17](https://user-images.githubusercontent.com/51028/148660179-49232e1d-c0b4-4347-a71a-c24028324958.png)

After upgrade:
![Screenshot 2022-01-08 at 21 10 21](https://user-images.githubusercontent.com/51028/148660174-6dc548e7-6aa1-4f6f-b27b-c7790f6db03c.png)

**Comment by hello-smile6** [comment]
> After upgrade from 867e9d to 6b9d1f, the screen is entirely black (text-mode Linux). In fact, text is being displayed, but it is black-on-black:
> 
> `<span style="background-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">Lorem Epsom donor sit Ahmed</span>`
> 
> This is for both default colour, and for all kinds of colours set via escape sequences.
> 
> Before upgrade: ![Screenshot 2022-01-08 at 21 12 17](https://user-images.githubusercontent.com/51028/148660179-49232e1d-c0b4-4347-a71a-c24028324958.png)
> 
> After upgrade: ![Screenshot 2022-01-08 at 21 10 21](https://user-images.githubusercontent.com/51028/148660174-6dc548e7-6aa1-4f6f-b27b-c7790f6db03c.png)

Try running your VM on https://github.com/hello-smile6/libv86-terminal-forwarding with a modified server. Does that work?

**Comment by rdancer** [comment]
Yes, that's working as expected:

![Screenshot 2022-01-08 at 22 07 33](https://user-images.githubusercontent.com/51028/148661582-d61c5dac-a15f-4cf0-8e16-3ba0e61c013c.png)

**Comment by hello-smile6** [comment]
> Yes, that's working as expected:
> 
> ![Screenshot 2022-01-08 at 22 07 33](https://user-images.githubusercontent.com/51028/148661582-d61c5dac-a15f-4cf0-8e16-3ba0e61c013c.png)

Is that tab still open?

**Comment by hello-smile6** [comment]
> Yes, that's working as expected:
> 
> ![Screenshot 2022-01-08 at 22 07 33](https://user-images.githubusercontent.com/51028/148661582-d61c5dac-a15f-4cf0-8e16-3ba0e61c013c.png)

@rdancer You leaked your terminal server address. If that tab's still open, anyone could access that VM. Don't share your terminal address.

**Comment by rdancer** [comment]
Isn't that generated anew on each page load?

**Comment by hello-smile6** [comment]
> Isn't that generated anew on each page load?

It is. However, I can change that. Should I? It'd make it easier to create a persistent VM.

**Comment by hello-smile6** [comment]
@rdancer Should I?

**Comment by copy** [comment]
@rdancer 867e9d is quite old. Did you update seabios?

**Comment by rdancer** [comment]
I just did a straight `git pull` after some five years. It should have updated the VGA bios and the SeaBIOS, and it did:

```sh
$ : working -- 867e9d0 from 2017
$ md5sum seabios.bin vgabios.bin 
ea9d16985058488cbbf42ca197db6fdc  seabios.bin 
52f1bf48b8e5fbd53cf0ed856cab2b2f  vgabios.bin 

$ : not working -- 6b9d1f  latest commit on master
$ md5sum seabios.bin vgabios.bin
ed52c23d996a549f7cecee6a540bd728  seabios.bin 
e8acaa929079296b3ca7c691ddc30914  vgabios.bin 
```

Does the fact that it works on the page you linked to mean that if I do a fresh install, it ought to work, or are there some uncommitted changes in the page you linked?

**Comment by rdancer** [comment]
As to your question, session persistence is a good option to have, but probably ought to require a manual save. It is unexpected for full remote access to be opened without authentication simply by sharing a screenshot, and would require manual revocation, which is probably more work than manual save.

A good middle ground may be to write into window.location.hash (which currently is only being read), so that the URL can be both shared and bookmarked.

**Comment by rdancer** [comment]
To be clear, I absolutely expected for remote access to be opened, and I expected it to be ephemeral and regenerated on each page reload. But I am a tiny minority of a tiny minority of people, and you yourself expected me not to realise that, which tells you that this would not be a feature that you expect people to intuitively grasp.

**Comment by copy** [comment]
Does it work if you boot your image in [basic.html](https://github.com/copy/v86/blob/master/examples/basic.html)? If not, could you send me the disk image and I will have a look. If it does work in basic.html, could you work out the difference between it and your own html?

**Comment by copy** [comment]
Feel free to reopen as per my last comment.
