### ISSUE TITLE
FreeNOS v.1.0.3 stops before logging in system

### ISSUE THREAD

**Issue by SuperMaxusa** [copy/v86#597]
Before logging into the system, the speed in the emulator drops to 0 mIPS.

Settings:
RAM: 128 MB
VRAM: 8 MB
ACPI: enabled

Version (v86): 6b9d1f74d
Debug log: https://pastebin.com/339c1e8a
ISO: http://www.freenos.org/pub/FreeNOS/releases/X86/FreeNOS-1.0.3.iso
Client: Chrome 96 and Edge 97, Windows 10

![image](https://user-images.githubusercontent.com/41739128/148679986-d0f59367-d70f-4dfb-ad23-2da316b40b61.png)

**Comment by copy** [comment]
I can reproduce this.

**Comment by SuperMaxusa** [comment]
UPD: I was able to run FreeNOS v.0.0.1 (http://www.freenos.org/pub/FreeNOS/releases/X86/FreeNOS-0.0.1.iso), all versions above v.1.0.0 do not start.
![image](https://user-images.githubusercontent.com/41739128/148821544-77d0f6fc-dd36-44c7-804b-320548ee701e.png)

**Comment by copy** [comment]
https://copy.sh/v86/?profile=freenos
