### ISSUE TITLE
How to run a multiboot kernel image

### ISSUE THREAD

**Issue by Unzor** [copy/v86#598]
Hello,
I need to run a kernel image at http://copy.sh/v86/debug.html, but how do I actually switch to it? It only says this: 
```
SeaBIOS (version rel-1.12.1-0-ga5cab58)
Booting from Floppy...
Boot failed: could not read the boot disk
Booting from Hard Disk...
Boot failed: could not read the boot disk
No bootable device. Retrying in 60 seconds.
```
Thanks

**Comment by copy** [comment]
Could you point me to the multiboot image?

**Comment by Unzor** [comment]
Yes. I am trying to run NodeOS. https://img-1.seven7four4.repl.co/kernel

**Comment by copy** [comment]
The file isn't a multiboot image (it doesn't contain the multiboot magic bytes as per the [specification](https://www.gnu.org/software/grub/manual/multiboot/multiboot.html)). It's a Linux kernel bzimage, which is also supported by v86, but currently not in the UI (a PR would be welcome). You can boot it by changing `cdrom: …` to `bzimage: …` in the [basic example](https://github.com/copy/v86/blob/master/examples/basic.html).

**Comment by copy** [comment]
https://copy.sh/v86/?profile=nodeos
