### ISSUE TITLE
duplicated HDD

### ISSUE THREAD

**Issue by xming** [copy/v86#60]
When using one hdd image, I get both sda and sdb referencing to the same disk

```
[    2.175070] sd 0:0:0:0: [sda] 30720 512-byte logical blocks: (15.7 MB/15.0 MiB)
[    2.195071] sd 0:0:1:0: [sdb] 30720 512-byte logical blocks: (15.7 MB/15.0 MiB)
```

**Comment by copy** [comment]
Yep (and they access the same underlying buffer). This is a duplicate of #14 though.
