### ISSUE TITLE
debian 11 apci error

### ISSUE THREAD

**Issue by logan-webGL-openGL** [copy/v86#600]
the bios and apci seem broken no different if no apci (is it enabled? yes i enabled it so please don't ask.) 
![Screenshot 2022-01-14 10 43 08 AM](https://user-images.githubusercontent.com/74722466/149543701-b860d437-9ba1-44d3-8c7b-1194bebd1915.png)

**Comment by logan-webGL-openGL** [comment]
it just spat out more 
![Uploading Screenshot 2022-01-14 10.46.43 AM.png…]()

**Comment by logan-webGL-openGL** [comment]
yo i went in debug and...
![Screenshot 2022-01-14 12 10 07 PM](https://user-images.githubusercontent.com/74722466/149557215-81ba5040-efc0-4dac-817d-b4d88d46b798.png)

**Comment by copy** [comment]
Those are non-critical errors.

**Comment by logan-webGL-openGL** [comment]
maybe unrelated but i got a error/snap on chrome

**Comment by logan-webGL-openGL** [comment]
thought it was related
