### ISSUE TITLE
File doesn't get uploaded in Arch Linux, but uploading works in Buildroot

### ISSUE THREAD

**Issue by mobluse** [copy/v86#602]
When selecting a file for uploading in Arch Linux on https://copy.sh/v86/?profile=archlinux it doesn't get uploaded to /mnt. This works for Buildroot https://copy.sh/v86/?profile=buildroot

**Comment by SuperMaxusa** [comment]
For Arch Linux, try "cd /" and find your file(s).

![image](https://user-images.githubusercontent.com/41739128/149674076-e157376a-c52c-4b36-b7e4-fcd4ab1cba07.png)
