### ISSUE TITLE
Error on Node.js: RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by Unzor** [copy/v86#603]
Hello,
I am trying to run v86 on Node.js, but every time I run, I get this error:
```
RangeError: offset is out of bound
```

Is there something I need to do?

**Comment by copy** [comment]
Could you post a minimal reproducing testcase?

**Comment by Unzor** [comment]
What is that, and how do I do it?

**Comment by copy** [comment]
Show me the code that fails.

**Comment by copy** [comment]
@Unzor I don't think using `eval` is the way to go. Anyway, does the [node example](https://github.com/copy/v86/blob/master/examples/nodejs.js) have the same issue?

**Comment by Unzor** [comment]
Yes.

**Comment by copy** [comment]
I can't reproduce the issue with the node example. What's your node and v86 version? Did you run `make build/libv86.js`? What does `sha256sum images/linux4.iso` print?

**Comment by proxy-m** [comment]
?

1) `node --version`

2) version of libv86

3) your os arch (32 bit, 64 bit ...)

4) your machine ram size

**Comment by proxy-m** [comment]
@Unzor ?

**Comment by copy** [comment]
@Unzor Try with a clean repo, build and image:

```
cd /tmp
git clone https://github.com/copy/v86.git
mkdir images
curl https://k.copy.sh/linux4.iso > images/linux4.iso
make build/libv86.js build/v86.wasm
./examples/nodejs.js
```
