### ISSUE TITLE
upload files (custom liveCD)

### ISSUE THREAD

**Issue by m-asyua** [copy/v86#605]
I created a custom CentOS-Based Live CD and it works. Is there a way to upload a file on my linux by the custom LiveCD, like demos of Arch Linux and Buildroot which can upload a file? Is a tool needed for LiveCD?

**Comment by SuperMaxusa** [comment]
If your Centos LiveCD supports 9pfs, then you can add this line to the V86Starter configuration, as done in [Buildroot](https://github.com/copy/v86/blob/master/src/browser/main.js#L359):
```js
filesystem: {},
```

To upload files in v86 use the function `create_file()`: https://github.com/copy/v86/issues/596#issuecomment-1008208368

If the system supports 9pfs, then it will be visible in `df`, for example, like this:
![image](https://user-images.githubusercontent.com/41739128/150673919-0fed48db-b54d-4e65-bcda-35a9504f05f0.png)

The easiest way to check that 9pfs is working properly is to run this in the DevTools console:
```js
emulator.create_file("/hello_world", "");
```
![image](https://user-images.githubusercontent.com/41739128/150674239-a546580c-8715-4935-884f-59428c5c2026.png)

(This example is not suitable for file uploads. To upload and download files to 9pfs, use the code from main.js)
https://github.com/copy/v86/blob/229310e6864ac8c271e629782cf03597c9b9d372/src/browser/main.js#L1751-L1796

**Comment by copy** [comment]
In addition to what @SuperMaxusa wrote, you'll need to run mount `host9p -t 9p /mnt/` in the guest to mount the filesystem.

**Comment by m-asyua** [comment]
Thank you for your information. I could prepare the system that supports 9pfs, and I will try to create a LiveCD.

<img width="401" alt="9p" src="https://user-images.githubusercontent.com/83494645/151093574-2d6f36e1-b806-4846-af84-f3c247f7136c.png">

**Comment by m-asyua** [comment]
It works. I can send a sample file. Thank you very much! 
I need the option to run.  mount -t 9p -o trans=virtio,version=9p2000.L host9p /mnt

<img width="489" alt="test9p" src="https://user-images.githubusercontent.com/83494645/151664931-67029f82-b098-40aa-bd8e-f5bea6cf7d20.png">
