### ISSUE TITLE
KolibriOS image gives a 404 error

### ISSUE THREAD

**Issue by CreaZyp154** [copy/v86#606]
## Affected page
https://copy.sh/v86/?profile=kolibrios

## Error shown on the page
```
Loading //builds.kolibrios.org/eng/data/data/kolibri.img failed. Check your connection and reload the page to try again.
```

## Error shown on the devtool's console
```
Loading the image //builds.kolibrios.org/eng/data/data/kolibri.img failed (status 404)
r.onload @ v86_all.js:349
```
## Possible fixes
Hosting the image somewhere else, and use it either by default or as a fallback.

**Comment by SuperMaxusa** [comment]
https://github.com/copy/v86/issues/141 (https://github.com/copy/v86/commit/a41919f8ed02c020d8ab8c16be8dab93ba66d705)

Use this profile, it downloads the image from copy.sh, not from the AutoBuild KolibriOS server.
https://copy.sh/v86/?profile=kolibrios-fallback

**Comment by SuperMaxusa** [comment]
UPD: A few hours ago, builds on auto-build server appeared, now [KolibriOS](https://copy.sh/v86/?profile=kolibrios) profile is working.
![Screenshot_2022-01-24-21-38-05-407_org mozilla firefox](https://user-images.githubusercontent.com/41739128/150854908-787a3863-0a80-416c-ba7b-05e5e7b34c06.png)

**Comment by copy** [comment]
> I think it would be nice if it used the fallback automatically when receiving 404

A PR would be welcome. However since this is the first time the kolibrios server has been down in seven years, I consider it a low priority and will close this issue.
