### ISSUE TITLE
Progress on Red Star OS

### ISSUE THREAD

**Issue by Unzor** [copy/v86#611]
I want to share the process of running Red Star OS (north korean OS). Here's what I got when I booted it up:
- Black screen with hints of green at top
- Crashed after a few seconds

I am using Red Star OS 3.

**Comment by copy** [comment]
Seems to be working. Installed in qemu and ran with 2G of ram.

![Screenshot_2022-01-31_18-52-24](https://user-images.githubusercontent.com/1816456/151896953-9942a41a-c77c-4b97-8ada-5ed4131f5c49.png)

Now … should I upload it?

**Comment by Unzor** [comment]
Sure

**Comment by copy** [comment]
I'll think about it, but let's close this for now.

**Comment by Unzor** [comment]
Hey,
I've been trying to set Red Star OS in QEMU but it has not worked. Do you have the commands for Red Star?
Thanks!

**Comment by copy** [comment]
I followed this guide: https://kevinchen.co/blog/installing-north-korea-red-star-os/ with `qemu-system-x86_64 -cdrom redstar_desktop3.0_sign.iso -nic none -enable-kvm -m 2G -drive file=redstar.img,format=raw -boot d`. It worked for the install process, but the resulting image didn't work in qemu, only in v86.
