### ISSUE TITLE
low resolution 2x scale overflows on many devices

### ISSUE THREAD

**Issue by pengan1987** [copy/v86#622]
Commit 514c2ad3031fdc61db00fe91bf1cd7800b9e9717 add 2x scale to all resolution lower or equal to 640 width, when running a VGA(640x480) guest system on 1366x768 browser (still the 2nd popular resolution on the web) and 1440x900 or 1600x900 display will overflow since scaled picture has 960 height.

It's better to add a switch parameter to enable/disable this function

![autoscale_overflow](https://user-images.githubusercontent.com/2333797/153740477-3992bb60-86f4-45db-8394-ae7f9194bdf1.png)

**Comment by copy** [comment]
I'd suggest a only applying the base scaling if it fits into `window.innerWidth` and `window.innerHeight`. Mind sending a PR?
