### ISSUE TITLE
Mouse doesn't work properly

### ISSUE THREAD

**Issue by kenorb** [copy/v86#63]
When testing [Windows 1.01](http://copy.sh/v86/?profile=windows1) and [Solaris](http://copy.sh/v86/?profile=solos) (graphics mode) it seems the mouse doesn't work properly in Chrome. It's shifted far away to the right bottom and sometimes it's going crazy clicking by it-self.

**Comment by copy** [comment]
I can reproduce this. Happens when using mouse and keyboard at the same time.

**Comment by copy** [comment]
Side note: The bug still exists in Solar OS, it's a bug in the os, not in the emulator.
