### ISSUE TITLE
Cannot install NPM module anymore

### ISSUE THREAD

**Issue by boidushya** [copy/v86#631]

**Comment by copy** [comment]
See https://github.com/copy/v86/issues/456#issuecomment-827909359

**Comment by myschoolstory** [comment]
I know this is old, but I figured out what was going on. It appears that whoever packaged it the last time left out two important scripts, After a bit of digging I found them (or recreated them from scratch. I publish my package [here](https://github.com/users/myschoolstory/packages/npm/package/v86). Sometimes one of the scripts doesn't work, but you just need the attached file, and drop it into the build folder of v86 in your node modules. 

[Sorry for the zip file, Github wouldn't let me upload .cjs](https://github.com/user-attachments/files/20504387/libwabt.zip)

**Comment by myschoolstory** [comment]
Sure! There should be build/capstone-x86.min.js and build/libwabt.cjs. These are required by it, but for some reason they aren't bundled automatically.

**Comment by SuperMaxusa** [comment]
Are you talking about `libv86.js` or `libv86-debug.js`?

> There should be build/capstone-x86.min.js and build/libwabt.cjs. These are required by it, but for some reason they aren't bundled automatically.

These libraries were optional and only used for debugging: https://github.com/copy/v86/pull/647#pullrequestreview-973030197.

**Comment by myschoolstory** [comment]
So when I ran my app it said that those were required, and it couldn't find them.

**Comment by SuperMaxusa** [comment]
Does your app use bundlers/frameworks? If so, it could have checked all `require` calls in V86 lib and not found capstone and libwabt.

Looking at code, there are two `require` calls with these libraries:
https://github.com/copy/v86/blob/a07e43bc3156d463445cc7fdd9b7b40614d84c2d/src/cpu.js#L2398-L2408 https://github.com/copy/v86/blob/a07e43bc3156d463445cc7fdd9b7b40614d84c2d/src/cpu.js#L2459-L2467

I removed these debug functions from release build, should helps: https://github.com/SuperMaxusa/v86/commit/1a10f07ff252315051e079100673644942b58459 (download from [artifacts](https://github.com/SuperMaxusa/v86/actions/runs/15395888002) or build with [patch](https://github.com/SuperMaxusa/v86/commit/1a10f07ff252315051e079100673644942b58459.patch)).

**Comment by copy** [comment]
I have included @SuperMaxusa patch in https://github.com/copy/v86/commit/174bb9b2522c1948de8d505cad9e3f1ca3639b01 (not merged yet), so this should be fixed soon.
