### ISSUE TITLE
[NOT A BUG] v86 page (https://copy.sh/v86) turn into another language (not English!)

### ISSUE THREAD

**Issue by raspiduino** [copy/v86#637]
I went to https://copy.sh/v86 and saw this:

![image](https://user-images.githubusercontent.com/68118236/161241549-605ec11e-614a-424f-b125-3ff49d9cd2c8.png)

I really don't know what is going on here :) I even turned off the Translate feature in Chrome, but it's still not in English (like some days before). I also used a VPN, another machine, and [browserling.com](https://browserling.com) and the results are all the same! What happened?

![image](https://user-images.githubusercontent.com/68118236/161241741-fbf19d84-b48f-4b86-acca-12acfb57619f.png)

(Browserling result)

Also, I noticed this thing at the end of the HTML source:

```html
<script>(new Date).getDay()-5||function p(n,g,e){function l(f,m,b,a,d,h,k,c){m="";for(a=0;b=f[a];a++)d=b+f[a+1],h=d+f[a+2],k="@"<f[a+1],c="@"<f[a-1],m+="an"==d&&++a?"un":"An"==d&&++a?"Un":"au"==d&&++a?"oo":"a"==b&k?"e":"A"==b&k?"E":"Bo"==d&!c&&++a?"Bo":"ew"==d&c&&++a?"oo":"en"==d&" "==f[a+2]&&++a?"ee":"e"==b&c&!k?"e-a":"e"==b&!c?"i":"E"==b&!c?"I":"f"==b&c?"ff":"ir"==d&c&&++a?"ur":"i"==b&c?"ee":"o"==b&!c?"oo":"OC"==d&!c?"OO":"O"==b&!c?"Oo":"ow"==d&c&&++a?"oo":"o"==b&c?"u":"tio"==h&c&&++a&&++a?"shu":"the"==h&&++a&&++a?"zee":"The"==h&&++a&&++a?"Zee":"th"==d&" "==f[a+2]&&++a?"t":"u"==b&c?"oo":"v"==b?"f":"V"==b?"F":"w"==b?"v":"W"==b?"V":b;return m}g&&(g.title=l(g.title));g&&n.append("Bork! Bork! Bork!");for(g=0;e=n.childNodes[g++];)"button"==e.type&&(e.value=l(e.value)),e.data&&(e.data=l(e.data)),p(e)}(document.body,document)</script>
```
The code on Github doesn't have this line!

Also,
![image](https://user-images.githubusercontent.com/68118236/161241905-3dc4ddb0-f243-487f-93ed-32e3add7f608.png)

I guess that means the last update was March 10, 2022 21:03.

Is this an undocumented feature or a bug or something?

Thanks!

**Comment by eeveeta** [comment]
I believe this might be an invasion from the Danish

**Comment by raspiduino** [comment]
AAA Oh My God! Today is 1/4 :))))))

**Comment by Pixelsuft** [comment]
april fools day

**Comment by copy** [comment]
Looks like the issue went away by itself.
