### ISSUE TITLE
Changing clock speed at which the OS is emulated at?

### ISSUE THREAD

**Issue by IoIxD** [copy/v86#640]
I'm planning on selfhosting v86 for a project and I noticed when my Linux distro boots, it reports a clock speed of 1000MHz. This is fine, but given the scope of my project (which I won't go into in detail here) and the fact that it sometimes crashes on my PC (which has a Ryzen 7 3700X) I was wondering if I could lower it to 750MHz or (extreme) 500MHz?

**Comment by IoIxD** [comment]
Accidentally hit enter too early, my bad

**Comment by copy** [comment]
The 1000MHz is just a number reported to the guest OS, it doesn't affect how v86 runs, how much CPU it uses or much else. You can still [change it](https://github.com/copy/v86/blob/master/src/config.js#L61) if you want.

If you do want to change certain factors about v86's jit or execution, you may want to have a look at one of these:

- The size of generated wasm modules: https://github.com/copy/v86/blob/master/src/rust/jit.rs#L327 (setting this to 1 will likely make the crashes go away)
- The tick function: https://github.com/copy/v86/blob/master/src/main.js#L124-L125 (you may want to comment out the first line and increase the timeout passed to setTimeout)
- https://github.com/copy/v86/blob/master/src/rust/jit.rs#L72 (change this to a lower value to reduce the memory usage at the cost of lower execution speed)
- https://github.com/copy/v86/blob/master/src/rust/jit.rs#L70 (increase this value to run the jit less often)
