### ISSUE TITLE
Ubuntu 4.10 screen glitch during boot

### ISSUE THREAD

**Issue by prtechindiaoss** [copy/v86#641]
![image](https://user-images.githubusercontent.com/83751707/163011644-e5acd87f-9c61-404c-af0d-a666e0b73bc2.png)
after this screen glitch it boot s perfectly

**Comment by copy** [comment]
We should probably clear vga memory when vbe is enabled (https://wiki.osdev.org/Bochs_VBE_Extensions#Clearing_display_memory).
