### ISSUE TITLE
changing system time

### ISSUE THREAD

**Issue by 3p3r** [copy/v86#646]
Hello! Thanks for the amazing project and open sourcing it.

I noticed system date and time is static and never updated post boot. Can this be changed to read wall clock and set it as the initial system time on boot?

The [Arch demo for example](https://copy.sh/v86/?profile=archlinux), if I open it every time and execute `date`, it returns a static date (which I assume is the date the .iso was built).

**Comment by 3p3r** [comment]
`date -s` seems to work. I am confused where `RTC.js` is used though. my original question is answered.

**Comment by copy** [comment]
To be exact, the Arch image is restored from a memory dump, so it completely skips the boot process. You can run `hwclock --hctosys` to synchronise from the rtc (and we should probably do that automatically). 

> I am confused where RTC.js is used though.

It calls [`io.register_{read,write}`](https://github.com/copy/v86/blob/654abe9/src/rtc.js#L78-L85), which the guest OS can access through [IN](https://c9x.me/x86/html/file_module_x86_id_139.html) and [OUT](https://c9x.me/x86/html/file_module_x86_id_222.html) instructions.

**Comment by 3p3r** [comment]
uh! that all makes sense now. thanks so much for detailed explanation.
