### ISSUE TITLE
Versioned releases

### ISSUE THREAD

**Issue by nerfpops** [copy/v86#649]
I'm making a tutorial on how to compile Buildroot Linux for v86 and would like to add checksums for all packages. Is it possible to make versioned releases to enable that?

**Comment by copy** [comment]
I don't assign version numbers to v86 as that entails stability guarantees that I can't hold up. v86 is a hobby project and I want to be able to ignore it for months at a time. I'd recommend pinning to a certain commit. After #647 we'll probably have a revision number so we can preserve old releases, but I'll close this for now.
