### ISSUE TITLE
Windows 2000: internet not working

### ISSUE THREAD

**Issue by stasoid** [copy/v86#651]
How to reproduce:
* open [Windows 2000 VM](https://copy.sh/v86/?profile=windows2000)
* open Internet Explorer
* press Refresh button (apparently when http://copy.sh is first opened it is loaded from cache, so need to refresh)

This is what I get:
![image](https://user-images.githubusercontent.com/2577509/168429207-ed4e3c76-bbfd-4d25-be34-d4bd548250c3.png)

**Comment by hello-smile6** [comment]
Steps to fix:
1. Open Device Management.
2. Disable the network adapter.
3. Re-enable it.
4. Open cmd.
5. Run `ipconfig /release *` and `ipconfig /renew *`, just for good measure.

After that, the VM will be on the network. There's `ftp`, so you can open Arch and start an FTP server, then send files to your VM.

**Comment by stasoid** [comment]
Doesn't work for me:
![image](https://user-images.githubusercontent.com/2577509/170871482-e990fdc8-b1bd-4b21-a4c1-5f903d4300c0.png)

**Comment by hello-smile6** [comment]
> Doesn't work for me: ![image](https://user-images.githubusercontent.com/2577509/170871482-e990fdc8-b1bd-4b21-a4c1-5f903d4300c0.png)

Try `ipconfig release` before you cycle the network adapter.

**Comment by copy** [comment]
Should be fixed now (after a519c62bce484b1c5a0be4e59e64fb3b050b1bfc and d1013f82f8d8983896e3eedbca40fbd907c024b5) (there's a "A duplicate name exists on the network" error, but web browsing works fine).

**Comment by copy** [comment]
(websites with JavaScript crash due to https://github.com/copy/v86/issues/708)

**Comment by SSP6904** [comment]
It's not really working on my relay docker found in the networking.md file in the docs folder..
I wonder why, considering it's on the eth0 interface..

Also it thinks it's offline for some reason, and that has not been fixed for me right now!

Maybe docker is thinking something else other the eth0 interface I guess.. 😒
