### ISSUE TITLE
OS X 10.6?

### ISSUE THREAD

**Issue by sussygamedeveloper** [copy/v86#656]
![image](https://user-images.githubusercontent.com/98538512/169151741-953b46a6-067d-41d8-93de-5d643bc8bb1e.png)
Yea... so umm i got the bootloader to work... imma try to get to the desktop... (lol ik this won't work)
I chose 10.6 because it is the first version with Intel CPU support, and it is 32-bit, and is the most lightweight.

**Comment by sussygamedeveloper** [comment]
@copy do you think there would be a way to add a second CD drive, like i said, this is just the bootloader, its fine if you can't get 2 CD drives, i can just combine the bootloader with the OS X iso.

**Comment by copy** [comment]
If you have anything that works in qemu (i386) I might have a look at it.

**Comment by sussygamedeveloper** [comment]
alright

**Comment by sussygamedeveloper** [comment]
UPDATE: I figured out that OS X 10.6 CAN run in qemu(i386), but...... imma have to install linux to do it 🤦, but im still gonna do it, ill update soon.

**Comment by sussygamedeveloper** [comment]
> UPDATE: I figured out that OS X 10.6 CAN run in qemu(i386), but...... imma have to install linux to do it 🤦(because WSL is annoying and slow with QEMU, so ubuntu would be WAY easier for me at least), but im still gonna do it cuz why not, ill update soon.

I was gonna do it in VirtualBox but after reading some issues, i realized that if you create it in VBox, it most likely won't work in V86.

**Comment by hello-smile6** [comment]
> > UPDATE: I figured out that OS X 10.6 CAN run in qemu(i386), but...... imma have to install linux to do it 🤦(because WSL is annoying and slow with QEMU, so ubuntu would be WAY easier for me at least), but im still gonna do it cuz why not, ill update soon.
> 
> I was gonna do it in VirtualBox but after reading some issues, i realized that if you create it in VBox, it most likely won't work in V86.

If you have a USB drive, install [Slax](https://slax.org/) on it. Then it'll work.
