### ISSUE TITLE
How can I make bootable linux autostart with my saved state?

### ISSUE THREAD

**Issue by bitcoinmeetups** [copy/v86#658]
Hello,

I'm MB. A very nice and polite guy.

Really like this project, I have been thinking about something like this for a long time.

How can I make bootable linux autostart with my saved state?

I would like to be able to customize the os, save the state and then make a website that goes into fullscreen when the user visits but with my custom os instead of the blank os.

**Comment by copy** [comment]
Start with this: https://github.com/copy/v86/blob/master/examples/basic.html

And add `initial_state: { url: "state.bin" },`

**Comment by bitcoinmeetups** [comment]
I have tested that now. It works with the normal settings but not with mine which are:

GNU nano 6.3                          v86.html
<!doctype html>
<title>Basic Emulator</title>                                    
<script src="libv86.js"></script>
<script>
"use strict";

window.onload = function()
{
    var emulator = window.emulator = new V86Starter({
        wasm_path: "v86.wasm",
        memory_size: 32 * 1024 * 1024,                                                      vga_memory_size: 2 * 1024 * 1024,
        screen_container: document.getElementById("screen_container"),
        initial_state: { url: "v86state.bin" },
        bios: {
            url: "seabios.bin",
        },
        vga_bios: {
            url: "vgabios.bin",                                                             },
        cdrom: {
            url: "linux.iso",
        },

The state here (v86state.bin) should be a buildroot state. Not sure if I have got the bios and cdrom files right.

Output for the above is screen flashes black and then white and then nothing.

**Comment by copy** [comment]
Anything in the console?

**Comment by bitcoinmeetups** [comment]
Note: Memory size mismatch. we=33554432 state=268435456

**Comment by copy** [comment]
Does it work if you fix the memory size mismatch?

**Comment by bitcoinmeetups** [comment]
How? By adjusting the memory_size in the HTML file? I have tried increasing to 32 x 4048 x 4048 but it still flickers white and disappears.

-------- Original Message --------

**Comment by copy** [comment]
The value needs to be the same as what was specified when you created the state image.
