### ISSUE TITLE
What would you suggest for cloning and running sample repos

### ISSUE THREAD

**Issue by alliv8** [copy/v86#663]
I was looking at this project as a candidate to clone sample git repos and executing them from the browser, let's say for node projects, which would need
- git
- node && npm
- other dev dependencies

Is there a package that could be used directly or that I can add these on top of?

**Comment by copy** [comment]
Building a linux image for v86 is covered here: https://github.com/copy/v86/blob/master/docs/archlinux.md

There's networking and you probably want to run your own proxy: https://github.com/copy/v86/blob/master/docs/networking.md

You can programmatically read and write files on the 9p filesystem, and send shell commands via the serial console, for example: https://github.com/copy/v86/blob/master/examples/lang.html
