### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by piranna** [copy/v86#67]
Adapt the project so it can be used on Node.js. It could be used for example to test NodeOS without needed to use QEmu.

**Comment by copy** [comment]
Node.js is already partially supported, have a look at https://github.com/copy/v86/blob/master/examples/nodejs.js. It's currently missing screen output (akin to [browser/screen.js](https://github.com/copy/v86/blob/master/src/browser/screen.js)), if you could make NodeOS ouput to the serial terminal, it would work.

**Comment by piranna** [comment]
Cool! :-D Yes, NodeOS can be used directly on the terminal :-) Is v86 published in npm?

**Comment by copy** [comment]
Currently not. Could you npmify it?

**Comment by piranna** [comment]
I'm a bit busy lately and my to-do lists is constantly increasing, but hope some day to get into it :-P

I've review the screen code and as I supposed you are using canvas, so in Node.js it could be used node-canvas instead. In fact, I helped to give framebuffer support, so we could have a real screen in Node.js for the emulator... :-)

**Comment by copy** [comment]
SDL would a lighter and simpler dependency to do the rendering. New issue: #80
