### ISSUE TITLE
Arch Linux crashes the tab process on iOS

### ISSUE THREAD

**Issue by TheAwesome98-Real** [copy/v86#670]
When loading the Arch Linux VM, the tab crashes with the “A problem occurred on this page, so it was reloaded” message. This normally happens, I believe, if the main thread hangs for too long. This doesn’t happen with other VMs such as the 9front or FreeDOS one.

**Comment by hello-smile6** [comment]
That's an iOS error. It uses too much memory, most likely.

**Comment by TheAwesome98-Real** [comment]
ah, right, forgot about jetsam. it does work on my computer so I think you’re right about it being an iOS issue
