### ISSUE TITLE
Add Android to profiles list.

### ISSUE THREAD

**Issue by glitch128** [copy/v86#683]
I would like it if the profiles list included the android profile for ease of access.

**Comment by copy** [comment]
Should I add it, considering it's [quite slow](https://copy.sh/v86/?profile=android)? React with 👍 if I should add it and with [👎](https://emojipedia.org/thumbs-down/) otherwise.

**Comment by hello-smile6** [comment]
> Should I add it, considering it's [quite slow](https://copy.sh/v86/?profile=android)? React with 👍 if I should add it and with [👎](https://emojipedia.org/thumbs-down/) otherwise.

#575 ?

**Comment by hello-smile6** [comment]
> Should I add it, considering it's [quite slow](https://copy.sh/v86/?profile=android)? React with 👍 if I should add it and with [👎](https://emojipedia.org/thumbs-down/) otherwise.

5 likes

**Comment by copy** [comment]
Done!

**Comment by hello-smile6** [comment]
> Done!

Yay!

**Comment by hello-smile6** [comment]
@copy Did you change something to make it load faster?

**Comment by hello-smile6** [comment]
It now starts in 8 minutes.
