### ISSUE TITLE
Struggling to get ext4 to load. 

### ISSUE THREAD

**Issue by akingscote** [copy/v86#684]
I have some images that I've built with Yocto, to get a basic X86 image. I dont want to use the 9p filesystem setup.
- `bzImage`
- `core-image-minimal-initramfs-qemux86.cpio.gz`
- `core-image-minimal-qemux86.ext4`

The following works with QEMU
```
qemu-system-i386 -kernel bzImage -initrd core-image-minimal-initramfs-qemux86.cpio.gz -hda core-image-minimal-qemux86.ext4 -append root=/dev/sda
```

If i omit the `-append root=/dev/sda`, I get waiting for removable media error.
![image](https://user-images.githubusercontent.com/25075013/173232277-2f1c8a57-25e1-4fea-8c18-7b0b0d62cfaa.png)
With the x86 emulator, using the default upload page, I can replicate the same issue.
![image](https://user-images.githubusercontent.com/25075013/173232560-cbde74ef-8a28-4b95-8ef4-a6dd51dc2590.png)
So essentially, i think i need to supply the ` -append root=/dev/sda` flag as a `cmdline`.
Ive been playing around with the HTML/JS (`basic.html`) and i cannot get it to do much. I've been editing the file on the container directly.

```
var emulator = window.emulator = new V86Starter({
        wasm_path: "../build/v86.wasm",
        memory_size: 32 * 1024 * 1024,
        vga_memory_size: 2 * 1024 * 1024,
        screen_container: document.getElementById("screen_container"),
        bzimage: {
            url: "../images/bzImage",
        },
        initrd: {
            url: "../images/core-image-minimal-initramfs-qemux86.cpio.gz",
        },
        hda:{
            url: "../images/core-image-minimal-qemux86.ext4",
            async: true,
            size: 13594624
        },
        autostart: true,
        cmdline: [
            "rw",
            "root=/dev/sda"
        ].join(" "),
    });
```
Im a novice at this, so any help would be appreciated. Im hoping its something basic im missing.

**Comment by copy** [comment]
Can you attach the three files to this issue?

**Comment by akingscote** [comment]
Here are the images, really appreciate the help! Cheers
[images.tar.gz](https://github.com/copy/v86/files/8885978/images.tar.gz)

**Comment by copy** [comment]
This config seems to work for me:

```js
    var emulator = window.emulator = new V86Starter({
        wasm_path: "../build/v86.wasm",
        memory_size: 128 * 1024 * 1024,
        vga_memory_size: 2 * 1024 * 1024,
        screen_container: document.getElementById("screen_container"),
        bios: { url: "../bios/seabios.bin" },
        vga_bios: { url: "../bios/vgabios.bin" },
        bzimage: { url: "linux/bzImage" },
        initrd: { url: "linux/core-image-minimal-initramfs-qemux86.cpio.gz" },
        hda:{
            url: "linux/core-image-minimal-qemux86.ext4",
            async: true,
            size: 13594624,
        },
        cmdline: "rw root=/dev/sda",
        autostart: true,
    });
```

It prints `[   30.454940] traps: awk[382] trap invalid opcode ip:550955 sp:bfbcc4b0 error:0` during boot, apparently since it uses sse3 instructions which v86 doesn't support. But that doesn't seem to cause any issues. You may want to recompile for an older architecture.

**Comment by akingscote** [comment]
Thanks for your help! Unfortunately, I'm still having some problems.
Inside the container, I'm seeing the following error:
```
172.17.0.1 - - [12/Jun/2022 16:28:55] "GET /examples/basic.html HTTP/1.1" 200 -
172.17.0.1 - - [12/Jun/2022 16:28:55] "GET /linux/bzImage HTTP/1.1" 200 -
172.17.0.1 - - [12/Jun/2022 16:28:55] "GET /linux/core-image-minimal-initramfs-qemux86.cpio.gz HTTP/1.1" 200 -
172.17.0.1 - - [12/Jun/2022 16:29:01] "GET /linux/core-image-minimal-qemux86.ext4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('172.17.0.1', 55184)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/http/server.py", line 653, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.9/http/server.py", line 660, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/local/lib/python3.9/http/server.py", line 860, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/local/lib/python3.9/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "/usr/local/lib/python3.9/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```
All three files are showing `200`, so it looks like ive got the paths right.
The emulator is giving me the following error:
![image](https://user-images.githubusercontent.com/25075013/173243272-71096abd-072f-4b73-a02c-441479878546.png)

Using your config in `examples/basic.html`.

**Comment by copy** [comment]
Python's webserver cannot be used for async images, because it doesn't support the range header. Try `async: false` or a different webserver. If you use libv86-debug.js you should get a proper error message.

**Comment by akingscote** [comment]
@copy Thanks so much for your help! Over the moon to get this working.
