### ISSUE TITLE
Custom BIOS file and faster processer

### ISSUE THREAD

**Issue by TCFFan123** [copy/v86#686]
It would be nice to choose a custom BIOS instead of SeaBIOS. It could make it possible for an OS to boot in UEFI mode.
Also, you might need to use a faster processor to run Windows 11 or some other EFI OS.
(please do not use an i386 processer as it is slow)

**Comment by copy** [comment]
You can select a bios here: https://github.com/copy/v86/blob/master/examples/basic.html#L15-L20

The processor has no effect on performance. v86 runs instructions as fast as it can.
