### ISSUE TITLE
Unable to use mouse to highlight terminal content

### ISSUE THREAD

**Issue by mattpass** [copy/v86#688]
Thank you for such an amazing solution with v86, really impressive!! :)

However, pretty much on any terminal based Linux VM eg [Buildroot](https://copy.sh/v86/?profile=buildroot), the mouse pointer isn't able to click & drag to highlight text? (to then allow copy to clipboard).

Clicking "Disable Mouse" keeps the pointer visible to my local OS, which fits my use case (would like to retain it) but clicking & dragging doesn't select text? [xterm.js alone does this](https://codesandbox.io/s/yv21krq4x) and I wonder why it doesn't have that behavior in v86.

Is it possible to implement/enable somehow?

**Comment by copy** [comment]
That's a bug. This is the offending line: https://github.com/copy/v86/blob/7a6eaf3/src/browser/main.js#L1716

I believe it was added because sometimes, when clicking on the screen to lock the mouse, some outside text is selected. I guess it should be disabled when mouse forwarding is disabled.

**Comment by copy** [comment]
This should be fixed now.
