### ISSUE TITLE
MS-DOS prompt freezes Windows 95

### ISSUE THREAD

**Issue by boxofbytes** [copy/v86#697]
Launching the MS-DOS prompt on v86 Windows 95 resizes the display and freezes the cursor

Steps to reproduce:
- Start v86 Windows 95 https://copy.sh/v86/?profile=windows95
- Press on the "Start" button
- Press on or hover over the "Programs" button
- Click on the "MS-DOS prompt" button, launching the program

**Comment by Pixelsuft** [comment]
It's VBE video driver bug.
Press alt + enter to go fullscreen.

**Comment by boxofbytes** [comment]
That doesnt really fix it though

**Comment by copy** [comment]
Like @Pixelsuft wrote, we can't fix this on our side. It's a known bug in the [VBE driver](https://bearwindows.zcm.com.au/vbe9x.htm) ("Locking and garbage problems when entering DOS WDM or console session.")

**Comment by SuperMaxusa** [comment]
[vmdisp9x](https://github.com/JHRobotics/vmdisp9x) works well with the MS-DOS prompt in Windows 95 RTM.

![w95-vmdisp9x](https://github.com/user-attachments/assets/b804b1e2-a8fb-4bc1-a684-bb8e263bcb51)
