### ISSUE TITLE
nodejs won't use websocket

### ISSUE THREAD

**Issue by tchereau** [copy/v86#711]
Hi,
I have an image of alpine linux, it's work on website of copy.sh/v86 with default websocket proxy,
it's also work when I clone this repo and make a web server and take the default websocket proxy.
it's work on nodejs, but no internet connection

Now I maked a docker with the websocket proxy source
on copy.sh and my clone, while I put my own websocket link, it's work fine
but with nodejs, same problem, no connection, and worst, nodejs don't even try to connect

I used this proxy like a tcpdump [proxy](https://github.com/kklis/proxy)
I can get packet from my browser 

`GET / HTTP/1.1
Host: localhost:8080
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://127.0.0.1
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Sec-GPC: 1
Sec-WebSocket-Key: X4MoVVOZk0Y5srvDFJ+Szw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: ArqKDekfnTYdyfEMAZBXIX3UuCA=

▒b"'▒▒▒L▒▒ET▒▒5E]
▒O▒%>▒▒b"'▒▒▒L▒▒ET▒▒5@▒
▒O?▒%▒e▒▒*"'▒▒▒L▒▒▒L▒▒H
"'▒
▒O
`

at this point I can say it, no trace of life of nodejs
I use the file nodejs.js on examples folder

I added try this (not in same time)
`network_relay_url: "wss://relay.widgetry.org/",
 network_relay_url: "ws://localhost:8080/",
"network_relay_url" : "ws://localhost:8080/",`

no one of them seems to work

**Comment by tchereau** [comment]
I finaly get from nodejs a sign of life by adding this on ligne 12276 of libv86
`        b.network_adapter ? (this.network_adapter = b.network_adapter(this.bus)) : b.network_relay_url && (this.network_adapter = new NetworkAdapter(b.network_relay_url, this.bus));
        console.log(this.network_adapter.connect)`

result on logs :

`node

▒▒▒o▒W▒`▒▒W>z▒g▒Wg▒Qo▒W>z▒e▒▒So▒Wo▒]o▒Wo▒Wo▒Wo▒Wo▒W▒*"'▒▒▒L▒▒▒L▒▒H
"'▒
▒O▒▒VH▒▒▒N▒O▒] ▒▒@G▒IOB▒▒▒▒▒H▒HD▒xN▒▒/t▒▒▒H▒H▒H▒H▒] ▒▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒H▒Ha 7▒K:▒H%▒▒;▒JG5▒I▒GDrf▒+w"▒f56▒z
                                                          ▒'cg]H▒H▒H▒H▒~\"'▒▒▒L▒▒E▒N)▒@▒▒

▒OCD:!▒▒qgs
▒O
▒O
"'▒c▒Sc56
3▒:▒;▒▒▒
▒▒

node

▒▒▒▒▒▒▒c3▒e▒▒▒▒▒2▒▒Ǥ▒▒▒▒▒▒▒▒▒▒▒2▒▒▒8▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒*"'▒▒▒L▒▒▒L▒▒H
"'▒
\▒%▒▒▒▒▒▒▒`▒▒▒▒▒▒e▒n▒/▒(▒/▒▒▒%▒▒$▒▒▒$▒▒▒▒▒▒▒%▒▒▒/▒(▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒▒▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒%▒▒▒F(▒▒▒▒▒"▒▒▒0▒"▒▒▒▒▒▒▒#▒▒▒▒▒▒A▒▒▒▒▒▒▒▒▒!▒▒▒@U▒▒%▒▒▒%▒▒▒%▒▒▒▒~\"'▒▒▒L▒▒E▒N▒ @e

▒OCD:▒▒qgs
▒O
▒O
"'▒c▒Sc56
3▒:▒;▒▒▒
▒▒

node

▒▒▒▒TZ&▒▒ Z8▒s▒▒RZT\▒UZ8▒s▒▒Q▒U▒TZ▒TP▒UZ▒TZ▒TZ▒TZ▒TZ▒*"'▒▒▒L▒▒▒L▒▒H
"'▒
▒O`

it's seems to be malformed request :/

**Comment by copy** [comment]
What exactly are you trying to do? Make a custom proxy? Note that the packets send on the WebSocket channel are [ethernet frames](https://en.wikipedia.org/wiki/Ethernet_frame), so they cannot trivially be passed to a TCP proxy. Have a look at this project: https://github.com/benjamincburns/websockproxy

**Comment by tchereau** [comment]
> What exactly are you trying to do? Make a custom proxy? Note that the packets send on the WebSocket channel are [ethernet frames](https://en.wikipedia.org/wiki/Ethernet_frame), so they cannot trivially be passed to a TCP proxy. Have a look at this project: https://github.com/benjamincburns/websockproxy

no you don't understand
I've made my docker with websockproxy, with my browser, it's work, with node js, it's don't work

I use a tcp proxy to see what is sent, with my browser pointing to this tcp proxy who pointing to the docker websockproxy, it's work, and I'm able to see what my browser send and what the websock proxy answer (like a tcpdump or wireshark); websocket use tcp
and because i'm able to see this, I notice that, nodejs send nothing

**Comment by copy** [comment]
Okay, I see. network.js uses the `WebSocket` constructor from the global scope, which is not present in node. You'll need to change network.js to use a nodejs WebSocket library (e.g. [ws](https://github.com/websockets/ws)), or implement your own WebSockets.

**Comment by tchereau** [comment]
it's worked thanks
