### ISSUE TITLE
Using serial_terminal with Xterm.js?

### ISSUE THREAD

**Issue by Unzor** [copy/v86#715]
Hello,
I am using libv86 for a project. I would like to know if instead of using a textarea as a serial_container, could I use Xterm.js as a serial_container?
Thanks!

**Comment by Pixelsuft** [comment]
`starter.js` code:
```js
if(options["serial_container_xtermjs"])
{
    this.serial_adapter = new SerialAdapterXtermJS(options["serial_container_xtermjs"], this.bus);
}
```
So, you should pass an element to `serial_container_xtermjs` option
