### ISSUE TITLE
Windows 2000 True Color

### ISSUE THREAD

**Issue by HunterBoy344** [copy/v86#719]
How can I enable true color support for Windows 2000 in the emulator? I've installed all of the plug and play hardware that was detected when I loaded my converted QEMU HD image into v86, but there's still no option in display settings to change the colors to anything other than 16 colors.

**Comment by copy** [comment]
Install this driver: https://bearwindows.zcm.com.au/vbemp.htm

**Comment by HunterBoy344** [comment]
Okay, cool. By the way, is there any way to get this driver on a Windows Live CD? Would be a little more convenient

**Comment by copy** [comment]
Adding it on a floppy disk image should work.

**Comment by dylaniscool54** [comment]
what do u install it to? there are no adapters

**Comment by dylaniscool54** [comment]
i tried to install to the video controller (VGA Compatible) and it did this.
![image](https://github.com/copy/v86/assets/106529128/38fc40bc-2984-48a8-b718-01a8245c4e10)
![image](https://github.com/copy/v86/assets/106529128/f40fdebc-1611-4067-ac57-7c53640bd1d6)
weird files which appeared

**Comment by dylaniscool54** [comment]
nvm i reset and it was fine thanks so much brooo
this link btw https://bearwindows.zcm.com.au/vbempg.zip
