### ISSUE TITLE
Missing operating system (Windows XP)

### ISSUE THREAD

**Issue by HunterBoy344** [copy/v86#722]
I've created a Windows XP installation in QEMU with FAT32, but when I try to boot it in v86 the BIOS simply says "Missing operating system" and doesn't boot. What should I do? I've already disabled ACPI in Device Manager, so I don't think that's the issue.

**Comment by copy** [comment]
Did you create a raw image? If not, you can convert it using `qemu-img convert -O raw`.

**Comment by HunterBoy344** [comment]
I did make a raw image, but I'll try reconverting it just in case

**Comment by HunterBoy344** [comment]
@copy No success... should I try installing the VM on a qcow2 image, then converting to raw?

**Comment by copy** [comment]
No, that shouldn't make a difference. Did you check that the image boots in qemu (with `-hda …`)?

**Comment by HunterBoy344** [comment]
Yes, QEMU boots the image just fine.

**Comment by HunterBoy344** [comment]
@copy I'd also like to mention that the VM didn't work when I used NTFS, also.

**Comment by copy** [comment]
Just to confirm, do you get this issue when you open [debug.html](https://copy.sh/v86/debug.html), use the xp image as a hard drive and increase the memory size to 256MB or more? Could you post a log from the browser console?

**Comment by HunterBoy344** [comment]
@copy I did it in debug.html with the XP image as a hard drive, the memory set to 1024 MB, and the video memory set to 256 MB. Here is the log: https://pastebin.com/9vPxymHf

**Comment by copy** [comment]
It's a weird issue, so I'm guessing a bit in the dark here. Can you:

- Try with a lower memory size
- Let me know the size of the image, and if it isn't a small multiple of 1GB, retry with 8GB or so?
- Try qemu with `-no-acpi -cpu pentium`
- Post the complete qemu command line of the installation and when running it?
- Try this commit: cc073388edcf3f67a8de839734d11b80d8cbd93f (Run `git checkout cc07338`, then `make` and open `debug.html`)

**Comment by HunterBoy344** [comment]
Alright, I’ll try it as soon as I can.
