### ISSUE TITLE
 [Request] Config used for buildroot image

### ISSUE THREAD

**Issue by wiwwo** [copy/v86#725]
Hi!
Would you share the config you used to create the image used in
https://k.copy.sh/buildroot-bzimage.bin
I tried to reproduce the image, and kept failing getting network work.

TIA!

**Comment by copy** [comment]
Try adding `CONFIG_NE2K_PCI=y` to the kernel config.

**Comment by wiwwo** [comment]
Uhm.. Fail:-D
Attaching `linux.config`, `v86_defconfig` and `dmesg` output...

```
$ modprobe ne2k-pci
modprobe: module ne2k-pci not found in modules.dep
```

Any hint? 
P.s.: seen you have a bug on Postgres; there is something about it in the `dmesg`, might be helpful 

[linux.config.txt](https://github.com/copy/v86/files/9490518/linux.config.txt)
[v86_defconfig.txt](https://github.com/copy/v86/files/9490523/v86_defconfig.txt)
[dmesg.txt](https://github.com/copy/v86/files/9490499/dmesg.txt)

**Comment by copy** [comment]
>  P.s.: seen you have a bug on Postgres; there is something about it in the dmesg, might be helpful

This issue is tracked in #726, a preliminary fix is in the wip branch.

I believe this config has networking: https://github.com/skiffos/SkiffOS/blob/master/configs/browser/v86/kernel/01-base

**Comment by wiwwo** [comment]
Works! Tnx!

**Comment by ppacory** [comment]
The buildRoot distribution provided is 5MB in size, you can find the config files (.config ...etc), thanks a lot

**Comment by copy** [comment]
Here are the last config files I have (they are from a backup, so not necessarily working or up-to-date). The SkiffOS version is more recent.

[buildroot-config.txt](https://github.com/copy/v86/files/9965098/buildroot-config.txt)
[linux-config.txt](https://github.com/copy/v86/files/9965099/linux-config.txt)

**Comment by SuperMaxusa** [comment]
Config files from `buildroot-bzimage68.bin` (Buildroot [2024.05.2](https://buildroot.org/downloads/buildroot-2024.05.2.tar.gz)): https://gist.github.com/SuperMaxusa/19a789c9e9b4a69b3237947fdb86d61e

[config-buildroot-with-toolchain.txt](https://github.com/user-attachments/files/17011558/config-buildroot-with-toolchain.txt)
[config-buildroot-with-bootlin.txt](https://github.com/user-attachments/files/17011574/config-buildroot-with-bootlin.txt)
[config-linux.txt](https://github.com/user-attachments/files/17011559/config-linux.txt)
[rootfs.patch](https://github.com/user-attachments/files/17011557/rootfs.patch)

<details>
<summary>[wip] buildroot 2026.05 with linux 7.0.11</summary>

[config-buildroot-with-toolchain7.txt](https://github.com/user-attachments/files/29905631/config-buildroot-with-toolchain7.txt)
[config-buildroot-with-bootlin7.txt](https://github.com/user-attachments/files/29905558/config-buildroot-with-bootlin7.txt)
[config-linux7.txt](https://github.com/user-attachments/files/29905559/config-linux7.txt)

</details>

_(thanks to @copy and @basicer for suggestions/corrections)_

**Comment by chschnell** [comment]
@copy, @SuperMaxusa: I've added DHCP/DNS server `dnsmasq` to the `buildroot` image, and a script to launch it, previously [brought up here](https://github.com/copy/v86/pull/1216#issuecomment-2614374008).

The new image file is attached to this comment: **[buildroot-bzimage68_latest.tar.gz](https://github.com/user-attachments/files/18643872/buildroot-bzimage68_latest.tar.gz)**.

**Changes**

* added package `dnsmasq` using `make menuconfig` under
  `Target packages -> Networking applications -> [X] dnsmasq`
* enabled kernel option [`INOTIFY_USER`](https://cateee.net/lkddb/web-lkddb/INOTIFY_USER.html) (needed by dnsmasq) using `make linux-menuconfig` under
  `File systems -> Inotify support for userspace -> [X] Inotify support for userspace`
* added executable script `/usr/sbin/v86-inbrowser-router` to `rootfs.patch`, see the Details section at the bottom for its source code
* The image is also based on [buildroot-2024.05.2](https://buildroot.org/downloads/buildroot-2024.05.2.tar.gz) (I couldn't get their latest release to build).

**Updated buildroot config files**

* [`config-buildroot_20250203.txt`](https://gist.githubusercontent.com/chschnell/22345dcc8d3bce1c577f853edd2ff598/raw/a15e3e089a320e5dac1f7a81c1a95ef34dc67607/config-buildroot_20250203.txt) (based off `config-buildroot-with-bootlin.txt`)
* [`config-linux_20250203.txt`](https://gist.githubusercontent.com/chschnell/7c0af26fe9156bb03436f55d1a0b2866/raw/cb44c8c34ac8e32499e7dab3f77f28fc9b4124c3/config-linux_20250203.txt)
* [`rootfs_20250203.patch`](https://gist.githubusercontent.com/chschnell/9ba411733237bb9daf09575bb066e6f6/raw/21763a46626737dc621baff60ab9fe9c67589904/rootfs_20250203.patch)


**Usage example**

Launch two v86 instances (hosts) in two browser tabs using the new buildroot image and the `inbrowser` network backend. In the first host, enter:

```
v86-inbrowser-router
```

and in the second host (its DNS name `example` is freely chosen here):

```
udhcpc -F example
```

Now you can immediately ping the 2nd host from the 1st one using either:

```
ping example
ping example.v86.local
```

and the 1st from the 2nd host using (`router` is the DNS name automatically assigned to the host that acts as the router):

```
ping router
ping router.v86.local
```

Voilà!

**Details**

<details>
<summary>Instructions used to build `buildroot-bzimage68_latest.bin`</summary>

```bash
# create and enter build directory ~/buildroot-v86
cd
mkdir -p buildroot-v86/config-v86
cd buildroot-v86

# download v86 config file gists in raw format into ./config-v86/
curl -L --output config-v86/config-buildroot_20250203.txt \
    https://gist.githubusercontent.com/chschnell/22345dcc8d3bce1c577f853edd2ff598/raw/a15e3e089a320e5dac1f7a81c1a95ef34dc67607/config-buildroot_20250203.txt
curl -L --output config-v86/config-linux_20250203.txt \
    https://gist.githubusercontent.com/chschnell/7c0af26fe9156bb03436f55d1a0b2866/raw/cb44c8c34ac8e32499e7dab3f77f28fc9b4124c3/config-linux_20250203.txt
curl -L --output config-v86/rootfs_20250203.patch \
    https://gist.githubusercontent.com/chschnell/9ba411733237bb9daf09575bb066e6f6/raw/21763a46626737dc621baff60ab9fe9c67589904/rootfs_20250203.patch

# download and unpack buildroot into ./buildroot-2024.05.2/
curl -LO https://buildroot.org/downloads/buildroot-2024.05.2.tar.gz
tar xfz buildroot-2024.05.2.tar.gz
cd buildroot-2024.05.2

# install v86 config files
cp ../config-v86/config-buildroot_20250203.txt .config
cp ../config-v86/config-linux_20250203.txt linux-config
patch -p1 < ../config-v86/rootfs_20250203.patch

# apply v86 config files
make oldconfig

# build bzImage and copy bzImage to parent directory
make && cp output/images/bzImage ../buildroot-bzimage68_latest.bin

```

</details>

<details>
<summary>Source code of script "v86-inbrowser-router"</summary>

```bash
#!/bin/sh

# /usr/sbin/v86-inbrowser-router
# Make host act as the IPv4 router, DHCP and DNS server in a v86 inbrowser network.
#
# Network configuration:
#   Router:      192.168.86.1
#   DHCP server: 192.168.86.1, range: 192.168.86.2 ... 192.168.86.254
#   DNS server:  192.168.86.1, names "router" and "router.v86.local" resolve to 192.168.86.1
#   DNS domain:  v86.local
#
# Note:
#   In other VMs, use "udhcpc -F HOSTNAME" to get a DHCP lease with assigned DNS name HOSTNAME.

# bring up 127.0.0.1
ip link set lo up

# bring up eth0, bind to 192.168.86.1
ifconfig eth0 up arp 192.168.86.1

# setup /etc/hosts
echo -e "127.0.0.1    localhost\n192.168.86.1 router router.v86.local" > /etc/hosts

# setup /etc/resolv.conf
echo -e "nameserver 192.168.86.1\ndomain v86.local\nsearch v86.local" > /etc/resolv.conf

# launch DHCP/DNS server (uses /etc/hosts and resolv.conf)
dnsmasq --no-ping \
    --listen-address=192.168.86.1 \
    --dhcp-range=192.168.86.2,192.168.86.254,255.255.255.0,86400s \
    --dhcp-option=option:router,192.168.86.1 \
    --dhcp-option=option:dns-server,192.168.86.1 \
    --dhcp-sequential-ip \
    --domain=v86.local

```

</details>

@SuperMaxusa: I picked dnsmasq because I couldn't find [`udhcpd`](https://github.com/copy/v86/pull/1216#issuecomment-2614405760) from busybox in buildroot's `make menuconfig`.

**Comment by SuperMaxusa** [comment]
Awesome, thank you!

> I picked dnsmasq because I couldn't find udhcpd from busybox in buildroot's make menuconfig.

Ah, it can be selected in `busybox`'s package config using `make busybox-menuconfig`: https://doc-en.rvspace.org/VisionFive2/SDK_Quick_Start_Guide/JH7110_SDK/install_sdk.html#install_sdk__section_z5t_zvn_35b

**Comment by SuperMaxusa** [comment]
> You think it can stay the way it is now?

Yes, dnsmasq is also a good choice, feel free to leave it.

**Comment by chschnell** [comment]
Two additional changes I'd like to propose, one affects `config-buildroot` and the other `config-linux`.

**Changess**

* **[buildroot-bzimage68_latest.tar.gz](https://github.com/user-attachments/files/18736803/buildroot-bzimage68_latest.tar.gz)**
  The latest image.
* [config-buildroot_20250210.txt](https://github.com/user-attachments/files/18736800/config-buildroot_20250210.txt)
  Based off `config-buildroot_20250203.txt`. Added package [`iperf`](https://en.wikipedia.org/wiki/Iperf) (buildroot option `BR2_PACKAGE_IPERF`), very helpful for debugging network issues and performance measurements.
* [config-linux_20250210.txt](https://github.com/user-attachments/files/18736802/config-linux_20250210.txt)
  Based off `config-linux_20250203.txt`. Removed kernel option [`CONFIG_INPUT_EVBUG`](https://cateee.net/lkddb/web-lkddb/INPUT_EVBUG.html), it seems unnecessary and spams the `dmesg` output.
* [rootfs_20250203.patch](https://github.com/user-attachments/files/18736801/rootfs_20250203.patch)
  Unchanged.

**iperf usage example**

See the [iperf man page](https://linux.die.net/man/1/iperf) about iperf command line options.

It's best to run the **iperf server** within the guest network on the same machine that executes the websock proxy server.  [`wsnic`](https://github.com/chschnell/wsnic) optionally provides an embedded iperf server, below a general method for other Docker images:

<details>
<summary>Example iperf server instructions for Docker images</summary>

```bash
# find the Docker CONTAINER_ID of the running proxy server
docker ps -a
# enter interactive bash session using CONTAINER_ID
docker exec -it CONTAINER_ID bash
# install iperf
apt install iperf
# find network router IP address (usually a TAP device, in this example: 10.5.0.1)
ifconfig
# run iperf server on router IP
iperf -s -B 10.5.0.1 -f m
```

</details>

Once the iperf server is up and running on IP address `a.b.c.d`, boot the buildroot iamge and start the **iperf client** with:

```bash
udhcpc
iperf -c a.b.c.d -f m -r -i 2
```

Command line options `-r` instructs iperf to make two tests, first client to server and then server to client.

<details>
<summary>Example iperf client output of "bellenottelling/websockproxy" (64.8 Mbits/sec up, 6.91 Mbits/sec down)</summary>

```
$ iperf -c 10.5.0.1 -f m -r -i 2
[  1] local 10.5.128.100 port 59184 connected with 10.5.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-2.00 sec  17.4 MBytes  72.9 Mbits/sec
[  1] 2.00-4.00 sec  16.1 MBytes  67.6 Mbits/sec
[  1] 4.00-6.00 sec  15.1 MBytes  63.4 Mbits/sec
[  1] 6.00-8.00 sec  16.3 MBytes  68.2 Mbits/sec
[  1] 8.00-10.00 sec  15.3 MBytes  64.0 Mbits/sec
[  1] 0.00-10.39 sec  80.3 MBytes  64.8 Mbits/sec
[  2] local 10.5.128.100 port 5001 connected with 10.5.0.1 port 51863
[ ID] Interval       Transfer     Bandwidth
[  2] 0.00-2.00 sec  1.48 MBytes  6.20 Mbits/sec
[  2] 2.00-4.00 sec  1.67 MBytes  6.99 Mbits/sec
[  2] 4.00-6.00 sec  1.72 MBytes  7.23 Mbits/sec
[  2] 6.00-8.00 sec  1.69 MBytes  7.07 Mbits/sec
[  2] 8.00-10.00 sec  1.65 MBytes  6.94 Mbits/sec
[  2] 0.00-10.02 sec  8.25 MBytes  6.91 Mbits/sec
```

</details>

<details>
<summary>Example iperf client output of "chschnell86/wsnic" (330 Mbits/sec up, 320 Mbits/sec down)</summary>

```
$ iperf -c 192.168.86.1 -f m -r -i 2
[  1] local 192.168.86.2 port 45396 connected with 192.168.86.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-2.00 sec  55.0 MBytes   231 Mbits/sec
[  1] 2.00-4.00 sec  79.9 MBytes   335 Mbits/sec
[  1] 4.00-6.00 sec  85.1 MBytes   357 Mbits/sec
[  1] 6.00-8.00 sec  86.3 MBytes   362 Mbits/sec
[  1] 8.00-10.00 sec  88.8 MBytes   372 Mbits/sec
[  1] 0.00-10.04 sec   395 MBytes   330 Mbits/sec
[  2] local 192.168.86.2 port 5001 connected with 192.168.86.1 port 47986
[ ID] Interval       Transfer     Bandwidth
[  2] 0.00-2.00 sec  72.2 MBytes   303 Mbits/sec
[  2] 2.00-4.00 sec  76.1 MBytes   319 Mbits/sec
[  2] 4.00-6.00 sec  74.1 MBytes   311 Mbits/sec
[  2] 6.00-8.00 sec  78.0 MBytes   327 Mbits/sec
[  2] 8.00-9.97 sec  79.3 MBytes   338 Mbits/sec
[  2] 0.00-9.97 sec   380 MBytes   320 Mbits/sec
```

</details>

**Comment by arcanis** [comment]
@chschnell I'm likely doing something wrong but when following your instructions from a docker image I get an error because BR2_TOOLCHAIN_EXTERNAL_URL isn't set - I suspect it's because it doesn't detect the Bootlin toolchain which is supposed to be used, but I have no idea why it fails to do so. Does this ring a bell?

**Comment by chschnell** [comment]
> [@chschnell](https://github.com/chschnell) I'm likely doing something wrong but when following your instructions from a docker image I get an error because BR2_TOOLCHAIN_EXTERNAL_URL isn't set - I suspect it's because it doesn't detect the Bootlin toolchain which is supposed to be used, but I have no idea why it fails to do so. Does this ring a bell?

I built it natively under Debian 12 Amd64 without Docker, and I don't believe to have needed an external toolchain, I compiled with the default gcc (12.2.0) that comes with Debian IIRC. I'm sure you've seen my build instructions above, and I don't know about BR2_TOOLCHAIN_EXTERNAL_URL.

Which toolchain do you have installed in Docker?

**Comment by arcanis** [comment]
I found out the issue - using the `/` character in menuconfig I figured out that the Bootlin toolchains are gated behind `BR2_HOSTARCH=x86_64`. Since I was using Docker on a M1, it was `aarch64` and couldn't work. I tried moving the build into a GitHub Action and things appear to work fine, thanks to your guide!

**Comment by chschnell** [comment]
New: Added support for PCI IDE controller, floppy drives, ATA harddisks and ATAPI CD-RWs, plus ext2 and msdos file systems.

**Buildroot release** (*[previous release](https://github.com/copy/v86/issues/725#issuecomment-2648530139)*)

* **[buildroot-bzimage68_latest.tar.gz](https://github.com/user-attachments/files/22863425/buildroot-bzimage68_latest.tar.gz)**
  The latest image.
* [config-buildroot_20250210.txt](https://github.com/user-attachments/files/18736800/config-buildroot_20250210.txt)
  Unchanged.
* [config-linux_20251011.txt](https://github.com/user-attachments/files/22863428/config-linux_20251011.txt)
  Based off `config-linux_20250210.txt`, see #1431 for details.
* [rootfs_20250203.patch](https://github.com/user-attachments/files/18736801/rootfs_20250203.patch)
  Unchanged.

**Known issues**

When booting you might see log messages similar to these:

```
clocksource: timekeeping watchdog on CPU0: Marking clocksource 'tsc' as unstable because the skew is too large:
clocksource:                       'pit' wd_nsec: 511924417 wd_now: eabc64d9 wd_last: eab312d6 mask: ffffffff
clocksource:                       'tsc' cs_nsec: 515444445 cs_now: 2ca59b66ff1c cs_last: 2ca57cadf03f mask: ffffffffffffffff
clocksource:                       Clocksource 'tsc' skewed 3520028 ns (3 ms) over watchdog 'pit' interval of 511924417 ns (511 ms)
clocksource:                       'tsc' is current clocksource.
tsc: Marking TSC unstable due to clocksource watchdog
TSC found unstable after boot, most likely due to broken BIOS. Use 'tsc=unstable'.
sched_clock: Marking unstable (1323950092, 10997275)<-(1335999999, -1219299)
```

One way to fix this is to add option `tsc=unstable` to the kernel command line.

**Comment by chschnell** [comment]
I have moved my v86 buildroot configuration into repository **https://github.com/chschnell/v86-buildroot**, from now on I will maintain it there which is a lot more convenient.

This small repository only contains the required buildroot customizations for v86, the buildroot source tree is kept strictly separated from these configuration files and is not included in the repository. The buildroot source tree remains unmodifed when building, it is now an out-of-tree build.

The rootfs overlay is no longer stored in a patch file, instead the rootfs tree is now a regular tree of files in the repository.

It now also includes a top-level Makefile which makes it very easy to use for everybody.
