### ISSUE TITLE
Kolibri Profile instructions

### ISSUE THREAD

**Issue by rocheston** [copy/v86#728]
I'm unable to boot Kolibri using this configuration. What am I doing wrong?

`window.onload = function()
{
    var emulator = window.emulator = new V86Starter({
        wasm_path: "../build/v86.wasm",
        memory_size: 512 * 1024 * 768,
        vga_memory_size: 4 * 1024 * 768,
        screen_container: document.getElementById("screen_container"),
        bios: {
            url: "../bios/seabios.bin",
        },
        vga_bios: {
            url: "../bios/vgabios.bin",
        },
        hda: {
            url: "../images/kolibri.img",
        },
        autostart: true,
    });
}
</script>`

**Comment by rocheston** [comment]
This is the error I get. Other OSs boot fine except this on my server.

SeaBIOS (version rel-1.12.1-0-ga5cab58)                                         
Booting from Floppy...                                                          
Boot failed: could not read the boot disk                                       
                                                                                
Booting from Hard Disk...                                                       
                                                                                
Starting system

**Comment by Pixelsuft** [comment]
Maybe it's floppy disk image, not hard drive?

**Comment by rocheston** [comment]
I used the same kolibri.img  image from v86 github. I tried hda and fdd both don't work. Maybe my settings are wrong. Can you help me?

![grab3](https://user-images.githubusercontent.com/16910669/188341474-2282756a-511c-43b5-b017-1a5a7222cdd9.jpg)

**Comment by rocheston** [comment]
It is fda and not hda. I get the blue screen and that's it. No OS is shown.

![grab4](https://user-images.githubusercontent.com/16910669/188342664-be136f2f-208c-4f33-8457-e5a069894d41.jpg)

**Comment by rocheston** [comment]
It works now. I was using the wrong wasm file. Thanks.

![grab5](https://user-images.githubusercontent.com/16910669/188345164-c7966f75-7788-4e06-b9c4-729607776a8b.jpg)
