### ISSUE TITLE
[Feature request-Web Interface] Tab/Window close prevention

### ISSUE THREAD

**Issue by wiwwo** [copy/v86#729]
Hi there!
I am sure and I know the "web interface" is none of your priorities, but using it I found very frustrating when I accidentally cose the tab my VM was running.
On to bottom of your pile, could you implement some JS mechanism so that the is a confirmation before closing the tab/widow?

TIA!

**Comment by copy** [comment]
There already is a mechanism that prevents accidentally closing when using ctrl-w: https://github.com/copy/v86/blob/d4831d3/src/browser/main.js#L1885-L1904  I'd be open to add more keyboard shortcuts to this list.

That said, I'm reluctant to add this in general. I think it's more common to want to quickly close v86 than to accidentally close it.

**Comment by copy** [comment]
It's a fair point, but I think not annoying users who want to close the tab is more important. If you don't mind, I'll close this.
