### ISSUE TITLE
I can't build correctly wasm file by use the makefile

### ISSUE THREAD

**Issue by Joinhack** [copy/v86#735]
I try to write v86-wasi and I execute the make to build wasm file, but the target file have 2 problem in the jit.

1. I can't got (import "env" "__indirect_function_table" (table $timport$0 638 funcref))
2. call_indirect1 look's like not corrently

I used rust 1.63.0.
this is my wasm file by use make command. 
[v86-debug.wasm.zip](https://github.com/copy/v86/files/9596754/v86-debug.wasm.zip)

**Comment by copy** [comment]
Can you explain what you trying to do? Are you running some sort of command line tool in the v86-debug.wasm file?

**Comment by Joinhack** [comment]
Actually the v86 project is running in browser and that's cool, and I take this project run in command line with runtime wasmtime, and I rewrite the js with rust. and I already boot from linux without JIT mode. 
when I will try to open JIT  mode, I found there problem, and maybe you can help me to fix.

**Comment by Joinhack** [comment]
By the way, when I use the WASM file build by myself, also crash when run in the browser, the error is call_indirect instruction use the table out of bounds.

**Comment by Joinhack** [comment]
"__indirect_function_table" this problem is fixed, thanks

**Comment by Joinhack** [comment]
"__indirect_function_table" this problem is fixed, thanks, and got "IndirectCallToNull" thanks.

**Comment by Joinhack** [comment]
"__indirect_function_table" this problem is fixed, thanks, and I turn on the JIT, thank you.

**Comment by copy** [comment]
Let's close this then.
