### ISSUE TITLE
Using Command "make" and "make all" Giving an Error

### ISSUE THREAD

**Issue by blocky-boi** [copy/v86#737]
Hello! I'm trying to use the commands "make" and "make all", but it keeps giving an error.

Error:
<img width="616" alt="Screenshot 2022-09-24 210037" src="https://user-images.githubusercontent.com/104800375/192125044-b6a0c9a9-97a1-408c-97d4-8e8f46cb6087.png">

**Comment by spetterman66** [comment]
https://stackoverflow.com/questions/54082459/fatal-error-bits-libc-header-start-h-no-such-file-or-directory-while-compili

**Comment by blocky-boi** [comment]
> https://stackoverflow.com/questions/54082459/fatal-error-bits-libc-header-start-h-no-such-file-or-directory-while-compili

I installed the multilib, but then i ran "make" and ran into this error.

**Comment by spetterman66** [comment]
Hmm ok weird…

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: ***@***.***>
Verzonden: zondag 25 september 2022 04:01
Aan: ***@***.***>
CC: ***@***.***>
Onderwerp: [copy/v86] Using Command "make" and "make all" Giving an Error (Issue #737)


Hello! I'm trying to use the commands "make" and "make all", but it keeps giving an error.

Error:
[Screenshot 2022-09-24 210037]<https://user-images.githubusercontent.com/104800375/192125044-b6a0c9a9-97a1-408c-97d4-8e8f46cb6087.png>

**Comment by copy** [comment]
@blocky-boi Can you provide some context? Is there any error message?
