### ISSUE TITLE
Page Directory entry address computing issue

### ISSUE THREAD

**Issue by aaron-elkins** [copy/v86#74]
In `src/cpu.js line 3177`:

```
page_dir_addr = (this.cr[3] >>> 2) + (page >> 10) | 0,
```

Here `page_dir_addr` is the entry of Page Directory, and why `this.cr[3] >>> 2` instead of just `this.cr[3]`? AFAIK, we can compute this physical address by adding the control register cr3 (`this.cr[3]`) and the 10 most significant bits of a linear address (here is `page >> 10`).

Can you explain why?

**Comment by copy** [comment]
`page_dir_addr` is used to index `mem32s`, which doesn't let you do unaligned accesses (`mem32s[1]` accesses bytes 4 through 7).

**Comment by aaron-elkins** [comment]
Good explanation.

Did not notice that `mem32s` is `new Int32Array(buffer);`

Thanks
