### ISSUE TITLE
Windows 2000 demo: enable TLS 1.0

### ISSUE THREAD

**Issue by collinanderson** [copy/v86#743]
Hi All,

It might be nice to enable TLS 1.0 in the default Windows 2000 demo, which would allow visiting more websites.

It's under Internet Options -> Advanced -> Security -> Use TLS 1.0

Most websites no longer enable 1.0, but some websites still allow it.

Thanks,
Collin

**Comment by spetterman66** [comment]
on windows 2000 (ie5,6), there is only sha-1 support (so i guess only https://badssl.com works). everything uses sha-2 encryption since https://shattered.io/ happened. check out their website to see more

**Comment by collinanderson** [comment]
Hah, I guess badssl.com was the only website I tested. Ok make sense. Thanks

**Comment by spetterman66** [comment]
If you'd want sha-2 tls 1.0 (and newer https protocols), download opera 12.02 http://www.oldversion.com/windows/opera-12-02. Don't save as .php, save as any extention then replace .php with .exe
