### ISSUE TITLE
Unable to set time or enable NTP on Arch Linux

### ISSUE THREAD

**Issue by BreadTeleporter** [copy/v86#746]
The Arch Linux install on the demos page is unable to have it's time and date set, or enable NTP.

`System has been booted with systemd as init system (PID 1) Can't operate.`
`Failed to connect to bus: Host is down`

This issue could maybe be solved by using grub instead of systemd

## Edit:
Any CTL command (timedatectl, systemctl, etc) also do not work

**Comment by hello-smile6** [comment]
> The Arch Linux install on the demos page is unable to have it's time and date set, or enable NTP.
> 
> `System has been booted with systemd as init system (PID 1) Can't operate.` `Failed to connect to bus: Host is down`
> 
> This issue could maybe be solved by using grub instead of systemd
> 
> ## Edit:
> Any CTL command (timedatectl, systemctl, etc) also do not work

Use `hwclock -s`

**Comment by BreadTeleporter** [comment]
> > The Arch Linux install on the demos page is unable to have it's time and date set, or enable NTP.
> > `System has been booted with systemd as init system (PID 1) Can't operate.` `Failed to connect to bus: Host is down`
> > This issue could maybe be solved by using grub instead of systemd
> > ## Edit:
> > Any CTL command (timedatectl, systemctl, etc) also do not work
> 
> Use `hwclock -s`

Thank you! This has fixed the problem.
