### ISSUE TITLE
SerenityOS image doesn't have Get disk image button

### ISSUE THREAD

**Issue by HaikuUserLinux** [copy/v86#747]
Hello everybody! I found that SerenityOS image doesnt have Get disk image button. Please add this feature if you can. Thank you for understanding.

**Comment by copy** [comment]
That's [by design](https://github.com/copy/v86/blob/ef3654f/src/buffer.js#L282). You're free to build your own SerenityOS image (the one used by v86 is unmodified from upstream sources). If you select a local file, the "Get disk image" button should be visible.
