### ISSUE TITLE
display type

### ISSUE THREAD

**Issue by glitch128** [copy/v86#752]
add a display type identifier to tell us which OS's are a terminal or GUI on boot

**Comment by copy** [comment]
Can you clarify what you mean by this?

**Comment by glitch128** [comment]
what I mean by display type is, when it's fully booted up, does it boot as a console, such as Archlinux or MS-DOS, or is it a desktop, such as Windows, ReactOS, or Android.

**Comment by copy** [comment]
https://github.com/copy/v86/pull/935
