### ISSUE TITLE
Files sent via serial from Windows 95 are getting corrupted

### ISSUE THREAD

**Issue by aaronk6** [copy/v86#753]
The command in MS-DOS prompt to send the file:

```
copy bubbles.bmp com1
```

The JavaScript code to receive the file on the web page and download it:

```
let file = '';
let clear = false;
let timeout;

emulator.add_listener("serial0-output-char", function(char) {

    if(clear) {
        file = '';
        clear = false;
    }

    window.clearTimeout(timeout);
    
    file += char;
    
    timeout = window.setTimeout(() => {
        clear = true;
    }, 500);
});

document.getElementById('download').addEventListener('click', function () {           
    let blob = new Blob([file]);
    let link = document.createElement('a');
    link.download = 'bubbles.bmp';
    link.href = URL.createObjectURL(blob);
    link.click();
});
```

The resulting file slightly differs from the original:

<img width="1506" alt="Screen Shot 2022-10-25 at 22 17 51" src="https://user-images.githubusercontent.com/446063/197875861-b42f3d8a-5607-4bd6-8a89-e0dd771b331f.png">

When I do the same with qemu (redirecting serial to a file), it works fine.

```
qemu-system-i386 -hda win95_clean.img -cpu pentium -vga std -device sb16 -serial file:bubbles.bmp
```

Test files attached.

[bubbles.zip](https://github.com/copy/v86/files/9863860/bubbles.zip)

**Comment by copy** [comment]
It seems that strings don't round-trip, could you try something like this:

```js
let file = [];
emulator.add_listener("serial0-output-char", function(char) {
    file.push(char.charCodeAt(0));
});
new Uint8Array(file)
```

**Comment by aaronk6** [comment]
Thanks! This improves the situation, but the resulting file is still not 100% correct. For some reason, 3 bytes are missing.

<img width="1290" alt="Screen Shot 2022-10-26 at 08 34 22" src="https://user-images.githubusercontent.com/446063/197952082-8eab86f2-fde6-424f-8b3d-19aadba8c699.png">

My updated code looks like this:

```
let file = [];
let clear = false;
let timeout;

emulator.add_listener("serial0-output-char", function(char) {

    if(clear) {
        file = [];
        clear = false;
    }

    window.clearTimeout(timeout);
    
    file.push(char.charCodeAt(0));
    
    timeout = window.setTimeout(() => {
        clear = true;
    }, 500);
});

document.getElementById('download').addEventListener('click', function () {           
    let blob = new Blob([new Uint8Array(file)]);
    let link = document.createElement('a');
    link.download = 'test.bmp';
    link.href = URL.createObjectURL(blob);
    link.click();
});
```

**Comment by aaronk6** [comment]
I just tried another file where it truncates the file (using the updated code with Uint8Array):

<img width="1278" alt="Screen Shot 2022-10-26 at 08 45 07" src="https://user-images.githubusercontent.com/446063/197953969-01f071af-13f0-4456-9752-8e4a56eb0df2.png">

Test files attached.

[test_gif.zip](https://github.com/copy/v86/files/9866858/test_gif.zip)

**Comment by copy** [comment]
This should be fixed.
