### ISSUE TITLE
No read-write image and the freedos image cannot save files when running

### ISSUE THREAD

**Issue by kwccoin** [copy/v86#76]
I would try the built root to solve this issue but in the mean time, cannot find a way to have a read-write image running in the v86 i.e. whatever you do, after you quit the system it is all gone.

Another related but even worst issue is with the freedos dos floppy image. While the image run ok in DosBox (except VIM is not working) and files can be saved/edit/asm/..., the freedos image can run but cannot save any file whilst running under v86.  What I mean is that if you do these

copy hello.asm  hello2.asm
==> saying said it is copied
dir
==> you can see hello2.asm
dir
==> hello2.asm no more!!!

The same for fdos/edit ... (I do not try vim as that vim software does not work under DosBox as well; but fdos\edit work) strangely you can nasm a hello.asm to generate something and the timestamps seems update.  You just cannot save any file via editing ...  Would try over the weekend along side with the built root what is going on.

The software is amazing to see it run.  But so far cannot be "use" unfortunately.   Trying hard to see whether it is my problem or its.  Cheers!

**Comment by copy** [comment]
I can reproduce this. Probably an issue with floppy drive emulation, I'll have a look.

**Comment by kwccoin** [comment]
Thanks.  I double check build root seems a long route for me.  I may concentrate on hacking the boatload of x86 real (segmented) mode this weekend instead. Would spend more time how yours working on the first phase dealing with Assembler call, BIOS call etc.  Take that build root route route after that.  

Doing the http://www.brokenthorn.com/Resources/OSDevIndex.html and the step-by-step book.  

Hobby way out ...

It would be nice to "self-hacking" if yours work as those tools could run under yours and in turn hack the its simulation base.

**Comment by kwccoin** [comment]
still cannot save any files under freedos version.  May be there is a way to create a r/w one.  I use my other image on bochs and it is working.

**Comment by copy** [comment]
@kwccoin It's not online yet. For now, pull from the repository and rebuild.

**Comment by Tanyajackson638** [comment]
#363  #848 #815 #54
