### ISSUE TITLE
Android-x86 Gingerbread 2.3.5 runs on Copy.sh/V86, but has no Internet connectivity

### ISSUE THREAD

**Issue by spetterman66** [copy/v86#763]
![Schermafbeelding 2022-11-10 193727](https://user-images.githubusercontent.com/69303239/201179072-807c5a71-6a0b-47b0-9b2e-2a537a8d8b4f.png)

Operating system in question is https://archive.org/details/sjarb_android_20110828 (eeepc iso)

**Comment by spetterman66** [comment]
https://archive.org/details/sjarb_android_3.2RC2 also doesn't have Internet connectivity (again, eeepc iso)

**Comment by copy** [comment]
It might not have an ne2k driver, could you check?

**Comment by spetterman66** [comment]
probably not... 
![image](https://user-images.githubusercontent.com/69303239/201359721-7be81bb2-99c5-4a4a-9a02-6dbddba898aa.png)
(it happens when you click the "ethernet devices" menu)

**Comment by copy** [comment]
Confirmed that it doesn't have a ne2k driver (using `qemu -nic user,model=ne2k_pci`), so let's close this.
