### ISSUE TITLE
Bochs graphics adapter BGA version is too old

### ISSUE THREAD

**Issue by binarymaster** [copy/v86#768]
v86 is emulating a Bochs graphics adapter (`1234:1111`) which identifies itself a BGA version `0xb0c0`. However, the emulator correctly supports 32 bpp and linear address mode, so it should announce itself as `0xb0c2` compatible.

This problem makes `bochsmp.sys` driver fail to load (ReactOS build 0.4.15-dev-5407-g79b0fce), so the color depth is reduced to 4 bpp.

See [CORE-18651](https://jira.reactos.org/browse/CORE-18651) and a [comment there](https://jira.reactos.org/browse/CORE-18651?focusedCommentId=136825&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-136825).

**Comment by copy** [comment]
Thanks! I've pushed a fix to the wip branch, and will merge it in a few days if nothing else breaks.
