### ISSUE TITLE
Memory Mapped I/O confuse

### ISSUE THREAD

**Issue by aaron-elkins** [copy/v86#77]
Hi Fabian,

I am not fully understanding Segment/Paging and Memory Mapped I/O in v86.

Let me make an example:

If I need to manipulate a status of an I/O device at address 0xABCDEFG (fake address as an example) with this instruction

`mov 0xABCDEFG 0x01`

 (Let’s say I just move 0x01 to this address to change the I/O devices status), so what does the hardware do to get the address (0xABCDEFG) of this instruction will be like this:
					
`0xABCDEFG` --------Segmentation--------->   `Linear Address` --------Paging--------->  `Physical Address`

What’s missing is: Where does Memory Mapped I/O’s read/write functions (I mean the registered `read_func8, write_func8, read_func32, write_func32` functions via IO.prototype.mmap_register) called in this process? I do not see the paging function (`CPU.prototype.do_page_translation()`) call `Memory.prototype.mmap_read8` and other similar functions.

Any help?

**Comment by aaron-elkins** [comment]
Uh-oh, I miss-understood what `CPU.prototype.do_page_translation()` do.

`Memory.prototype.mmap_read8` is called in `Memory.prototype.read8` which is called in `CPU.prototype.read_write_e8`.

Can close the issue now. solved.

**Comment by copy** [comment]
> Memory.prototype.mmap_read8 is called in Memory.prototype.read8 which is called in CPU.prototype.read_write_e8.

Yep, and also in many other places.
