### ISSUE TITLE
websockproxy

### ISSUE THREAD

**Issue by krishenriksen** [copy/v86#773]
So the [websockproxy](https://github.com/benjamincburns/websockproxy) is not the fastest in the world, we know this.

However I have just finished building a new one using Node.js.
This allows me to permessage-deflate compress the raw ethernet frames using zlibDeflate.

The current settings are close to default, as I haven't tested all variables for maximum throughput.

```JavaScript
const wss = new WebSocket.Server({
	port: 80,
	perMessageDeflate: {
		zlibDeflateOptions: {
			chunkSize: 1024,
			memLevel: 7,
			level: 3,
		},
		zlibInflateOptions: {
			chunkSize: 10 * 1024
		},
		clientNoContextTakeover: true, // Defaults to negotiated value.
		serverNoContextTakeover: true, // Defaults to negotiated value.
		serverMaxWindowBits: 10, // Defaults to negotiated value.
		// Below options specified as default values.
		concurrencyLimit: 10, // Limits zlib concurrency for perf.
		threshold: 1024, // Size (in bytes) below which messages should not be compressed.
	}
});
```

However if someone could test the speed compared against [websockproxy](https://github.com/benjamincburns/websockproxy) and post here, it would be appreciated.

Use Docker, or build yourself for aarch64 architecture or any other using `run.sh`

[node-relay](https://github.com/krishenriksen/node-relay)

An example:

I am running a Full Node Blockchain daemon using v86 as underlying technology, and I needed more throughput to download the blocks in a reasonable time frame. ( Code: https://github.com/bloqifi/v86/tree/bloqcoin )

## Bloqcoin full node running in browser
https://www.bloqifi.com/node_experimental

**Comment by copy** [comment]
Thanks, this is quite useful. I'm getting around 300 KiB/s with a local proxy in Arch Linux.  I've added a link in [networking.md](https://github.com/copy/v86/blob/master/docs/networking.md).
