### ISSUE TITLE
Once more about Memory Mapped I/O

### ISSUE THREAD

**Issue by aaron-elkins** [copy/v86#78]
In this line:  `vga.js line 251`

```
  io.mmap_register(0xE0000000, this.vga_memory_size,
        function(addr) { return me.svga_memory_read8(addr); },
        function(addr, value) { me.svga_memory_write8(addr, value); },
        function(addr) { return me.svga_memory_read32(addr); },
        function(addr, value) { me.svga_memory_write32(addr, value); }
    );
```

Here address `0xE0000000` is a logical address or a psychical address?

If it is a psychical address, then how can cpu know which logical address correspond to this psychical address (through segmentation or paging)? That's to say, how segmentation & paging translate it's logical address to `0xE0000000`? AFAIK, the vga does not tell the outside world of itself this address, or am I missing something?

This is where I really get confused about Memory Mapped I/O here.

**Comment by copy** [comment]
It's a physical address. Memory mapped IO is not backed by physical memory. It can be backed by a buffer, but this would be implemented in the device itself. Whenever a CPU instruction causes a read or write to an address that is mapped this way, only the corresponding callbacks are called. You can see that the vga controller never writes to `Memory`, it only writes to its own buffer (`svga_memory` etc.).

When given a physical address, it's not (always) possible to find a corresponding logical address and this is never done in a cpu.

**Comment by aaron-elkins** [comment]
'''
...Whenever a CPU instruction causes a read or write to an address that is mapped this way, only the corresponding callbacks are called.
'''
This is what I want to know. Thanks in advance.
