### ISSUE TITLE
How to access localhost running in archlinux in host system or new tab?

### ISSUE THREAD

**Issue by kryptoniancode** [copy/v86#783]
In http://copy.sh/v86/?profile=archlinux, how can `python -m http.server` allow us to access in new tab or computer?

**Comment by copy** [comment]
It's not reachable from the internet. You could spin up a second VM (even a different one) and connect to the other VM:

![Screenshot_2022-12-09_14-45-26](https://user-images.githubusercontent.com/1816456/206793355-46791bd2-ca61-4f6e-a702-934687537311.png)


Alternatively, you could run your own [websockproxy](https://github.com/benjamincburns/websockproxy) and configure forwarding with iptables or so.

There may also be some other options that were discussed in https://github.com/copy/v86/issues/198, but none is currently implemented.

**Comment by kryptoniancode** [comment]
Thanks, I got it.

**Comment by SuperMaxusa** [comment]
You can use tunneling solutions (**localhost.run**, **ngrok**, **Cloudflare Tunnel/ArgoTunnel** and other) to make local server accessible outside the local network. 

For example, this is a running **PHP 8** development server with [localhost.run](https://localhost.run/docs/) tunnel:

![phpserver](https://user-images.githubusercontent.com/41739128/207445897-2ef9aa02-3b2b-4dfd-b849-cce81ef12d27.png)

(please note, that [websockproxy](https://github.com/benjamincburns/websockproxy) has a bandwidth limit of [40KiB/sec](https://github.com/benjamincburns/websockproxy/blob/main/switchedrelay.py#L26))

**Comment by kryptoniancode** [comment]
Thanks

**Comment by UserArham** [comment]
common...

**Comment by UserArham** [comment]
<img width="1338" height="380" alt="Image" src="https://github.com/user-attachments/assets/3bb66510-0b53-458c-a179-dd9cc5b48bdd" />

**Comment by UserArham** [comment]
I have the same thing
