### ISSUE TITLE
Enhancement: add antiX as a demo distro

### ISSUE THREAD

**Issue by SugarRayLua** [copy/v86#787]
I tested the antiX distro on copy v86, and it seems to work very well. It is an established lightweight distro based on Debian and comes in 32 and 64-bit versions. The "base" version seems to have reasonable functionality for use on copy v86. Would be nice if it was demo version so that users could then select antiX and install a few additional packages and then "save state" to be able to rapidly restart work in that distro in their browser. 

It would then be additionally useful if that demo antiX browser would be able to access the user's local filesystem (similar to how the ArchLinux demo distro does).

Thanks for considering this request.

**Comment by Darin755** [comment]
This sounds really cool from my point of veiw but I'm not a v86 dev. I do have the following concerns:

- The AntiX image is quite big for the web
- AntiX is going to be really slow once booted
- AntiX by default uses a kernel optimized for old hardware and would require a custom kernel to use virtio
- apt is network intensive and might put to much demand on the proxy

**Comment by Darin755** [comment]
If you are looking for a light distro you may want to consider compiling buildroot with only the minimal functionality configured. 

There are plenty of buildroot configs to base off of but here is mine https://github.com/Darin755/browser-buildroot

**Comment by SugarRayLua** [comment]
Thank you very much, @Darin755. I'll take a look at your buildroot as a base :-)

**Comment by SugarRayLua** [comment]
Your live demo does boot pretty fast, @Darin755. Probably be too hard to add R into your buildroot without a package manager to access a binary package of R? I imagine trying to compile R from source inside of buildroot in the emulator in the browser might take a while.

**Comment by copy** [comment]
Let's close this, as I don't plan to upload an antiX profile.

**Comment by Darin755** [comment]
> Your live demo does boot pretty fast, @Darin755. Probably be too hard to add R into your buildroot without a package manager to access a binary package of R? I imagine trying to compile R from source inside of buildroot in the emulator in the browser might take a while.

You don't compile it inside v86. You build the image on a local machine
