### ISSUE TITLE
Mount media/cd images

### ISSUE THREAD

**Issue by MentalGear** [copy/v86#788]
Truly impressive, if there was only a way to mount disc images, this would be a full emulation!

**Comment by spetterman66** [comment]
i guess you can mount your own .iso files on the custom profile setup, on the homepage (scroll down)

**Comment by MentalGear** [comment]
Thx for your input! Are the default OS images available somewhere ? ( so I only have to insert the cd .iso after the OS image )

**Comment by Darin755** [comment]
Yes, it is at the bottom of the readme. You can do something like ```wget -P images/ https://k.copy.sh/{linux.iso,linux4.iso,buildroot-bzimage.bin,openbsd-floppy.img,kolibri.img,windows101.img,os8.img,freedos722.img}```

**Comment by MentalGear** [comment]
Thx, however running for example `wget -P images/ https://k.copy.sh/windows101.img` only gets me a 1.4 mb .img file, which doesn't seem to be correct.

**Comment by Darin755** [comment]
> Thx, however running for example `wget -P images/ https://k.copy.sh/windows101.img` only gets me a 1.4 mb .img file, which doesn't seem to be correct - any idea how to get the full image ?

Does it boot?

**Comment by Pixelsuft** [comment]
It's floppy image

**Comment by MentalGear** [comment]
Yes, indeed windows101 boots when I load it into v86 as a floppy - I tried as hdd or CD first!

Actually, though I was looking for win98 or 2k which I can't find on k.copy.sh.

Does anyone know if a win98 or win2000 image is also available?
And also how I may add a program to it? (I'm not very read in the hardware emulation world yet)
Thx again!

**Comment by spetterman66** [comment]
how to get files from k.copy.sh: boot up a VM with the devtools network panel open. find a request for "k.copy.sh". if you do that on windows 2000 for example, you'll find https://k.copy.sh/windows2k_state-v2.bin.zst

**Comment by MentalGear** [comment]
That's actually the first thing I tried as well! However, the inspector's network tab indicates that it is of type 'stream' and the file itself only 22mb, which is too small for a whole windows 2000 OS. Also, trying to boot the file in v86 does not work.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/2837147/209674736-9f736330-4167-4cb7-9a4e-3a603569f613.png">

IMO [_state-v2.bin.zst](https://k.copy.sh/windows2k_state-v2.bin.zst) is a state file, or a partial file as v86 streams data as needed - which is super clever and greatly efficient, but bad if you want to get the full image.

**Comment by spetterman66** [comment]
it's compressed with .zst

**Comment by MentalGear** [comment]
While trying to decompress with "tar --use-compress-program=unzstd -xvf [windows2k_state-v2.bin.zst](https://k.copy.sh/windows2k_state-v2.bin.zst)"
I'm getting this error
```shell
zstd: error 70 : Write error : cannot write decoded block : Broken pipe 
tar: Error opening archive: Child process exited with status 70
```

It seems like the file is "corrupted" or not complete. While using https://copy.sh/v86/?profile=windows2000 and opening icons/using the OS, there's new data streaming in all the time, which seems to give strength to my earlier observation that the image is streamed only partly.
<img width="1549" alt="Screenshot 2022-12-28 at 00 19 11" src="https://user-images.githubusercontent.com/2837147/209735741-5a4cce9c-2e01-4cb5-9c2e-6871a44315ad.png">

Is anyone able to get the full, uncompressed image ?

**Comment by MentalGear** [comment]
Never mind, I was able to open it with `BetterZip` (mac app),
I assume I'd need to run the extracted .bin now somehow with qemu?

**Comment by MentalGear** [comment]
Update, got it into QEMU with "qemu-system-i386 -drive file=windows2k_state-v2.bin,format=raw -boot c -cpu pentium3"
But won't boot.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/2837147/209737017-48b89cc4-760e-41e3-93f9-ac8845de9d07.png">

**Comment by MentalGear** [comment]
Sorry for the many messages, and thanks everyone for the help so far!

I'd be super grateful if you could help me  figure out the last part on how to:
- boot the .bin
- install a legacy program on it, and get it back into v86.

I'd also be happy to add a step-by-step guide to the readme thereafter on "how to run legacy software / add a program to an v86 install" for all the other users with a similar "emulating legacy software" use-case which are also not so well versed in hardware emulation (which I think might be a significant chunk).

I think an easy step-by-step guide for this would greatly increase the accessibility and uses for this amazing emulating software!

**Comment by spetterman66** [comment]
you can save the v86 state

**Comment by MentalGear** [comment]
Thx for the input, Ryan! I assume you are reffering to the Save/Load State button on top of v86 ?

I'd like to save the state, but first need to install a program from an .iso image, which I'm not able to load from the standard install, therefore need a custom install (as you indicated [before](https://github.com/copy/v86/issues/788#issuecomment-1364678596) ).

So with a custom install, I would need to "bring my own OS", meaning the windows2000 OS image, which I only have as the .bin (or .zst). Neither one I can load in the custom loader as hdd or cd image, which bring me back to the question how can I load a .bin file into v86 or qemu.

**Comment by copy** [comment]
The .bin file is a v86-specific format containing a memory dump and the state of all registers and devices. It can't be used by any other software besides v86 (as far as I know), and isn't sufficient to run an OS (except if it doesn't access the disk after the state has been saved).

The disk images aren't available for download (at least not directly). Instead, I'd suggest downloading an installer from https://winworldpc.com/library/operating-systems and creating your own image in qemu. There is some documentation for Windows 2000 and XP [here](https://github.com/copy/v86/blob/master/docs/windows-xp.md).

Alternatively, it would be possible to add a floppy disk or cdrom at runtime (and possibly create a FAT or iso9660 filesystem on the fly), buthis is currently not implemented (#54, #480).

It might also be possible to transfer files through the network card or serial port (see e.g. https://github.com/copy/v86/issues/198 or https://github.com/copy/v86/issues/753)

**Comment by MentalGear** [comment]
Thx Fabian for the clear reply! I tried it out with qemu and the linked guide, got past the setup and installation of windows2000 but then, when trying to boot it again, the BIOS says  "a disk error occured".

I was able to load windows2000 in virtual box and install the software. The final step: How do I get the virtual box image into v86 ?

**Comment by copy** [comment]
v86 only supports raw images. If the image created by virtual box isn't raw, you can convert it using `qemu-img convert`. 

Note that it isn't guaranteed to work in v86, since v86 might emulate different hardware than virtual box. Windows is fragile in terms of hardware changes.

**Comment by tdbe** [comment]
I don't understand, so this closed issue, is saying, that I can't use https://copy.sh/v86/?profile=windows98 and load an iso into it, despite there being a button to "Insert CD Image" which accepts an iso? ~~I need to somehow find some unfindable windows 98 custom image that you have to make yourself? Because if that's what we're doing then I don't need the website I can just go through the trouble of a local VM.~~

[EDIT: 1] Update: it seems it doesn't work for windows 98, but it does work for [windows 2000](https://copy.sh/v86/?profile=windows2000). 
[EDIT: 2] Well, the program couldn't be installed on windows 2000. It can however also be installed on [Windows NT 4.0](https://copy.sh/v86/?profile=windowsnt4) via CD iso, but Windows NT's don't have sound devices for some reason, so no sound, which is a huge annoyance T_T

**Comment by SuperMaxusa** [comment]
> I can't use https://copy.sh/v86/?profile=windows98 and load an iso into it

Works for me with an ISO file (https://i.copy.sh/linux4.iso) and random files.
Note about ISO files: make sure the `.iso` part of the file name is in lowercase. This was [fixed](https://github.com/copy/v86/commit/777b8c397ceeeee15a3f20bf0d6b165b4018a4f1) in the repository, but not on copy.sh/v86.

<img width="727" height="437" alt="iso-w98" src="https://github.com/user-attachments/assets/38cf225f-c026-4010-8b25-3f8b198dec2f" />

<img width="912" height="427" alt="iso9660-w98" src="https://github.com/user-attachments/assets/490beb74-9564-4f61-99d0-cea3ed1612ad" />
