### ISSUE TITLE
Make F11 a way to escape fullscreen (FEATURE REQUEST)

### ISSUE THREAD

**Issue by Dimka380** [copy/v86#792]
Windows 7 is trapped in Windows 2000's "It's now safe to turn off the computer" screen, so please make it so the F11 key doesn't react to every OS, and only unlocks your mouse and gets you out of the fullscreen mode

Oh and yeah, can you also add feature requests as a thing? please.

**Comment by copy** [comment]
Let's close this, since browsers already provide a mechanism for exiting the mouse lock.
