### ISSUE TITLE
Origin of MS-DOS programs?

### ISSUE THREAD

**Issue by lovemeforareason** [copy/v86#793]
Hello,

May I please know the origin of some of the MSDOS programs in the "MS-DOS 6.22" image file?

Specifically the seemingly impossible "jumper.com" game, and all of the demos (ones I'm most interested in is "when.com" and "ll.com")

Thanks in advance.

**Comment by copy** [comment]
The demos are from https://www.pouet.net: https://www.pouet.net/prod.php?which=58722 https://www.pouet.net/prod.php?which=59007 https://www.pouet.net/prod.php?which=58423, etc. although I can't find when.

The games, IIRC were from https://www.freedos.org/software/, although it only seems to have invaders. I found the tetris [here](http://mirror.math.princeton.edu/pub/freeDOS/files/games/tetris/), but can't find jumper right now (did you know you can use the numpad arrows to double-jump?).

**Comment by SuperMaxusa** [comment]
I tried to find others demoscenes (thanks copy for [post above](https://github.com/copy/v86/issues/793#issuecomment-1382719192)) and made a list:

- `demos\lebhaft.com`: https://www.pouet.net/prod.php?which=58722
- `demos\when.com`: https://www.pouet.net/prod.php?which=59256
- `demos\LL.com`: https://www.pouet.net/prod.php?which=59007
- `demos\knead.com`: https://www.pouet.net/prod.php?which=58423
- `demos\manderbrot.com`: https://www.pouet.net/prod.php?which=63349
- `demos\misplace.com`: https://www.pouet.net/prod.php?which=58780
- `demos\dawn.com`: https://www.pouet.net/prod.php?which=59001
- `demos\cluster.com`: not found :(
