### ISSUE TITLE
Does v86 support tail calls?

### ISSUE THREAD

**Issue by unicomp21** [copy/v86#794]
https://github.com/WebAssembly/tail-call/issues/15

**Comment by copy** [comment]
With the current compilation scheme (the code for several pages is compiled into a single wasm module with a single function, see [how it works](https://github.com/copy/v86/blob/master/docs/how-it-works.md)), v86 doesn't benefit from tail calls. I plan to experiment with other compilation schemes once tail calls are more widely implemented.

**Comment by unicomp21** [comment]
But tail calls are implemented, and rolling out in chrome 113, right?
