### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getContext')

### ISSUE THREAD

**Issue by 49b** [copy/v86#795]
Hi, I am trying to test Virtual x86 in my own instance. I created a canvas element with the id c. This is the command I run that leads to the error.
```js
var emulator = new V86Starter({
    screen_container: document.getElementById("c"),
    bios: {
        url: "../../bios/seabios.bin",
    },
    vga_bios: {
        url: "../../bios/vgabios.bin",
    },
    cdrom: {
        url: "https://k.copy.sh/linux.iso",
    },
    autostart: true,
});
```

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getContext')
    at new ScreenAdapter (<anonymous>:204:60)
    at V86Starter.continue_init (<anonymous>:12569:52)
    at <anonymous>:12439:18
```

**Comment by copy** [comment]
It looks like the canvas isn't found. You may need to wrap your code around `window.onload = function() { ... };`

**Comment by 49b** [comment]
> It looks like the canvas isn't found. You may need to wrap your code around `window.onload = function() { ... };`

Hi, thanks for responding. I added the code to the `window.onload` function, however in the console I get the same error. I even tried running in DevTools, after the page loaded, but I still get an error.

**Comment by BelleNottelling** [comment]
Do you actually have the element created?
You didn't share the entirety of your code script, so we are left to assume that you've actually created it

**Comment by 49b** [comment]
> Do you actually have the element created? You didn't share the entirety of your code script, so we are left to assume that you've actually created it

Hi, Yes, I created the canvas element.

**Comment by BelleNottelling** [comment]
> > Do you actually have the element created? You didn't share the entirety of your code script, so we are left to assume that you've actually created it
> 
> Hi, Yes, I created the canvas element.

Okay, I assumed so, but you do sometimes see simple mistakes like that. 

Care to share the code snippet where you're creating the canvas?

**Comment by 49b** [comment]
> > > Do you actually have the element created? You didn't share the entirety of your code script, so we are left to assume that you've actually created it
> > 
> > 
> > Hi, Yes, I created the canvas element.
> 
> Okay, I assumed so, but you do sometimes see simple mistakes like that.
> 
> Care to share the code snippet where you're creating the canvas?

Hi, here is my code snippet: https://github.com/49b/49b.github.io/blob/main/v86/index.html

**Comment by BelleNottelling** [comment]
> > > > Do you actually have the element created? You didn't share the entirety of your code script, so we are left to assume that you've actually created it
> > > 
> > > 
> > > Hi, Yes, I created the canvas element.
> > 
> > Okay, I assumed so, but you do sometimes see simple mistakes like that.
> > 
> > Care to share the code snippet where you're creating the canvas?
> 
> Hi, here is my code snippet: https://github.com/49b/49b.github.io/blob/main/v86/index.html

Hey there, can you try moving the script from the ```<head>``` of the document to below where you include the v86 JS file?

**Comment by SuperMaxusa** [comment]
As far as I understand, `screen_container` (DOM-container) should contain `div` for text mode and `canvas` for graphics mode, like this:

https://github.com/copy/v86/blob/17a6b3b4e942ed04eb22098023d4b694f97020c0/examples/basic.html#L29-L33

I think this should fix the problem.

**Comment by 49b** [comment]
> As far as I understand, `screen_container` (DOM-container) should contain `div` for text mode and `canvas` for graphics mode, like this:
> 
> https://github.com/copy/v86/blob/17a6b3b4e942ed04eb22098023d4b694f97020c0/examples/basic.html#L29-L33
> 
> Try creating canvas in DOM-container and assign container to `screen_container` in `V86Starter`, I think this should fix the problem.

That solution worked, thanks.
