### ISSUE TITLE
network not working on Alpine-Linux 3.17

### ISSUE THREAD

**Issue by lxhlxh520** [copy/v86#798]
my websocket proxy is node-relay(https://hub.docker.com/r/krishenriksen/node-relay), i am sure the proxy is working, i also added the network_relay_url option, but no network, can you help me, thanks! The screenshot is as follows: 
![屏幕截图 2023-01-28 125227](https://user-images.githubusercontent.com/6287636/215243007-81b4fa9b-8705-4a37-9c82-5992197c1b63.png)

**Comment by SuperMaxusa** [comment]
I saw that this is using a virtual machine version of Alpine Linux (linux-virt kernel), which does not have a driver for the rtl8029, so Linux cannot start networking:
```
ip: ioctl 0x8913 failed: No such device
udhcpc: ioctl 0x8933 failed: No such device
```

Alpine Linux has a [ne2k-pci driver](https://pkgs.alpinelinux.org/contents?file=ne2k-pci*&path=&name=&branch=edge&arch=x86) only in [linux-lts](https://wiki.alpinelinux.org/wiki/Kernels). 

Can you try using **[Alpine Linux Standard](https://alpinelinux.org/downloads/)** and test the networking there? (as far as I know, the linux-lts kernel is used there)

**Comment by lxhlxh520** [comment]
> 

Thank you very much, I will try it

**Comment by lxhlxh520** [comment]
I used the standard version and network is working now
