### ISSUE TITLE
How can I split a large image file?

### ISSUE THREAD

**Issue by mingxingyuan** [copy/v86#805]
**hda: {
        "url": "os_out/os.img",
        "fixed_chunk_size": 134211,
         use_parts: true,
        "async": true,
        "size": 2684215296,
      },**

**Comment by SuperMaxusa** [comment]
With server-side CGI: https://github.com/copy/v86/issues/450#issuecomment-832159508
Without server-side: https://github.com/copy/v86/pull/483
