### ISSUE TITLE
Debian 11 (and Debian 11-based distros) don't work

### ISSUE THREAD

**Issue by spetterman66** [copy/v86#808]
Debian 11 (and Debian 11-based distros) don't work because when it's booting up, it tries to load the x11 graphics mode, which fails, and it keeps trying over and over so there's a loop

How to reproduce:
1: Download Debian 11 or any distro based on it, such as Kali Linux, BunsenLabs, etc
2; Boot it up in V86 with 768mb ram, 128mb vram, and acpi on
3: Wait until it tries to load the graphics

**Comment by TCFFan123** [comment]
Try nomodeset.

**Comment by glitch128** [comment]
@spetterman66 try [this image](https://cdimage.debian.org/debian-cd/current-live/i386/iso-hybrid/debian-live-11.6.0-i386-standard.iso). it works for me, even on a Chromebook, but it's a shell image, so try the other ones in the path.

**Comment by spetterman66** [comment]
Ok, will try the LXQT version right now once it's downloaded

**Comment by spetterman66** [comment]
OMG YES IT WORKS

**Comment by spetterman66** [comment]
but bunsenlabs and kali linux still don't work

**Comment by copy** [comment]
I tried Bunsenlabs (beryllium-1-i386.hybrid.iso) and it works:

![Screenshot_2023-08-26_16-27-25](https://github.com/copy/v86/assets/1816456/6477aa69-2576-455b-ab31-7e3d05eb9587)
