### ISSUE TITLE
Documentation for Making Linux-based Images with 9P or Buildroot?

### ISSUE THREAD

**Issue by czenzel** [copy/v86#81]
Hello,

Is there any documentation on how to build a fresh snapshot with ArchLinux and the F9(?) file system? I would like to try to build one from scratch but stumped on how. Maybe I missed something in the code snapshot?

Edit: 9P sorry. 

Thanks
Chris Zenzel (@czenzel)

**Comment by czenzel** [comment]
I found this link under one of the closed issues. Maybe I can contribute a documentation page if I get this to work?

https://github.com/ysangkok/build-v86-9p-linux

**Comment by czenzel** [comment]
I am also trying buildroot to try and make a simple image. Can't seem to get it to boot properly. Is there a howto on making a simple Linux image in any format?

**Comment by czenzel** [comment]
Perseverance was key tonight :smile:

I am going to try to document everything I did and publish it somewhere. What I did was use buildroot to generate an ISO with:

* grub (standard not grub2)
* latest kernel, etc for QEMU x86 board
* Set for i686 (not pentium pro because of PAE) under the compile settings
* Added the 9P and Networking
* Then recompiled the buildroot again to take the config changes
* Tested an ISO with basic tools.
* Then it booted.

```
CONFIG_NET_9P=y
CONFIG_NET_9P_VIRTIO=y
CONFIG_NET_9P_DEBUG=y
CONFIG_VIRTIO=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_MMIO=y
CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y
CONFIG_9P_FS=y
CONFIG_9P_FSCACHE=y
CONFIG_9P_FS_POSIX_ACL=y
```

**Comment by copy** [comment]
> I am going to try to document everything I did and publish it somewhere

That would be great. This absolutely needs to be documented. If you do, create a new file in `doc/`.

By the way, if your image has some interesting applications, I'd be happy to include it in the demo.
