### ISSUE TITLE
Networking on KolibriOS?

### ISSUE THREAD

**Issue by SSP6904** [copy/v86#815]
**Hi all!**

I'm having a issue where the relay docker images that I'm using for my v86 emulator, is not working when connected from the same server hosted with both my main website and v86 site..

I usually test the networking on kolibriOS to see if it did anything, but it somehow didn't want to connect to the internet or use the assigned ip address with the docker image at all!

I assume it was a configuration problem with my nginx server doing a proxy thing to reverse, or even a port number that was supposed to be in the command..

Can someone explain what I did wrong?
Thanks a lot! 😉

![](https://user-images.githubusercontent.com/75172901/224151701-aae024d2-5520-4dfa-a37c-d0d60df6254f.png)

**Comment by 5UP3R-D1N** [comment]
I think v86 networking doesn't work with KolibriOS because it doesn't say "Include network support" in copy.sh/v86 page

**Comment by SSP6904** [comment]
That's strange..

I thought the OS had some sort of tool that should "release" or "renew" ip command, but I guess not..

**Comment by tennox** [comment]
I know that other OSes on v86 require you to run a command like `modprobe ... `or `dhcpcd` on buildroot/debian /arch.
[See here](https://github.com/copy/v86/issues/528#issuecomment-926013394)

Probably something like that exusts for your OS

**Comment by SuperMaxusa** [comment]
@tennox As far as I understand, KolibriOS starts DHCP configuration via `zeroconf` (http://wiki.kolibrios.org/wiki/Networking_for_dummies) automatically at booting time.

By the way, I noticed that in the Debug Log, when trying to make an HTTP request, an error appears about failed contacting DNS-server (all IP settings were set automatically).

![2](https://user-images.githubusercontent.com/41739128/225234855-791ee5d3-7a67-46d4-867c-62a7ca118b48.png)

**Comment by SSP6904** [comment]
!(https://user-images.githubusercontent.com/75172901/226199649-8cad412f-bff2-40c2-ada8-f87850e2d539.png)

I mean, networking works in Virtualbox for some reason.

I have no idea why it did run or did dhcp thing on start up.

I even did it with the proxy provided from `relay.widgetry.org` anyway, but nothing.

**Comment by SSP6904** [comment]
> @tennox As far as I understand, KolibriOS starts DHCP configuration via `zeroconf` (http://wiki.kolibrios.org/wiki/Networking_for_dummies) automatically at booting time.
> 
> By the way, I noticed that in the Debug Log, when trying to make an HTTP request, an error appears about failed contacting DNS-server (all IP settings were set automatically).
> 
> ![2](https://user-images.githubusercontent.com/41739128/225234855-791ee5d3-7a67-46d4-867c-62a7ca118b48.png)
> 
> **UPD:** somehow it turned out to load the page with DNS turned off in `settings/network.ini` ![зображення](https://user-images.githubusercontent.com/41739128/226214250-49e7c610-abf2-4dfe-804e-e8acfbbd8984.png)

Hmm..

I did try this, but I'm not sure if the DNS line is supposed to be off or deleted..

**Comment by SuperMaxusa** [comment]
Also checked [node-relay](https://github.com/krishenriksen/node-relay) (more precisely fork [BelleNottelling/node-relay](https://github.com/BelleNottelling/node-relay)) the result is the almost same. 

I've noticed a few things so far:
- DNS is not working, what was mentioned earlier
- not all packets are received, for example, in the screenshots below only 4/7 successful packets on `8.8.8.8` are received, other reached `Timeout.` on both relays.
- on default relay, in Debug board I catched a message: 
```
RTL8029: Error on receive
```
on node-relay I had this:
```
TCP_send: IP error
IPv4_output: ARP error=FFFFFFFF
IPv4_output: ip=0xF80DE340
```
---------------------------
<details>
  <summary>node-relay</summary>
  
![node-relay](https://github.com/copy/v86/assets/41739128/d2ca018b-ccc4-4685-ab5a-19bc112d1258)

</details>

<details>
  <summary>default relay (websockproxy)</summary>
  
![websockproxy](https://github.com/copy/v86/assets/41739128/07ecc8b1-3451-4396-ba92-5084896e4955)

</details>

**Comment by copy** [comment]
This seems to be working now. Not sure if it was a change in v86 or kolibrios.

![Screenshot_2024-07-13_20-37-03](https://github.com/user-attachments/assets/b4ff6bb2-b8d8-400b-af4b-418319b4b54c)
