### ISSUE TITLE
Stuck in Fetching v86.wasm

### ISSUE THREAD

**Issue by imthehappy** [copy/v86#818]
Hi, i have a problem for you copy, everytime i click windows 95 and wait i think its stuck in Fetching v86.wasm, So can you fix this please? im begging you

**Comment by 5UP3R-D1N** [comment]
Hello, Please try changing your browser, turning off adblock, and switching network
It doesn't occur to me at all

**Comment by copy** [comment]
Anything in the browser console (JavaScript error or failing request in the network tab)?

**Comment by imthehappy** [comment]
IT KEEPS OCCURING TO ME WITHOUT ADBLOCK

**Comment by 5UP3R-D1N** [comment]
Then disable your adblock.

**Comment by imthehappy** [comment]
it still dont work since i disabled  adblock

**Comment by imthehappy** [comment]
SUP3R-D1N IT STILL DONT WORK SINCE I REMOVED ADBLOCK
