### ISSUE TITLE
npm / npx is not available in the demo

### ISSUE THREAD

**Issue by damodharanj** [copy/v86#821]
Pretty much the title. Is there a way I can install in the window ?

**Comment by spetterman66** [comment]
if it's arch linux, run `pacman -S nodejs`

**Comment by damodharanj** [comment]
thanks! 
but npm is not available now. When I run 
`pacman -S npm`
I get this error
<img width="1034" alt="Screenshot 2023-03-22 at 11 08 25 AM" src="https://user-images.githubusercontent.com/8286067/226812286-4f7bcde5-9da3-4a4b-af80-ad79f3ef0f8e.png">

**Comment by SuperMaxusa** [comment]
@damodharanj By default, Arch Linux starts without a networking
```
/root/networking.sh
pacman -S npm
```

**Comment by damodharanj** [comment]
<img width="1043" alt="Screenshot 2023-03-22 at 11 52 57 AM" src="https://user-images.githubusercontent.com/8286067/226819110-1a72eb7d-2370-4487-adff-28975e6b913d.png">
Fails in the last step!

**Comment by spetterman66** [comment]
Okay, will do step by step:
1: Start up your Arch Linux VM
2: ./networking.sh and be patient
3. `pacman -Syy` to update package lists (sorta like `apt update`)
4. `pacman -S npm`
5. PROFIT!

**Comment by damodharanj** [comment]
Thanks a lot @spetterman66! worked perfectly!
