### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by eternalconcert** [copy/v86#83]
Followed the steps of the Readme, and it fails with the following error:

mkdir -p build
ls -lh build/v86_all.js
ls: cannot access 'build/v86_all.js': No such file or directory

**Comment by copy** [comment]
I can't reproduce this. It shows the error, but continues compiling the script. Can you try `make -i`?

**Comment by hvm2hvm** [comment]
Hi!

I had the same issue and "make -i" fixed it. Didn't dig in any further though, let me know if you need more info.

Voicu

**Comment by eternalconcert** [comment]
Oops.. Missing environment variable. I close this issue. Thanks!
