### ISSUE TITLE
Missing char in map: keyCode=c1 code=IntlRo

### ISSUE THREAD

**Issue by maxmag-soft** [copy/v86#831]
When I pressed on my ABNT2 Keyboard the key `/` the error below is shown on javascript console:

`Missing char in map: keyCode=c1 code=IntlRo`

The key is the same with the symbols `?` and `/`

I have used this site to get the keycode: `https://keycode-visualizer.netlify.app/`
I got the info:
`"You Pressed: / The Key Code is: 193"`

Here is a image of my layout:
<img src="https://s2.glbimg.com/n3wKASJUcHCBEsDzl_jds8oTPIg=/0x0:695x232/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/a/g/BK0ZDPQ9KTQDIF0Q2AiA/2016-06-21-900px-kb-portuguese-brazilsvg-.png" />

How can I provide more details?

**Comment by copy** [comment]
It's documented here: https://www.w3.org/TR/uievents-code/#keyboard-104

There's probably no PS2 for this, so let's just translate it to `?/`.

**Comment by ChrisSmith2** [comment]
Hi!
I'm a computer science student at the University of Texas at Austin taking a Virtualization course and one of our assignments is to contribute to an open source project. Would I be able to work on resolving this issue?

**Comment by copy** [comment]
@ChrisSmith2 Sure!
