### ISSUE TITLE
KolibriOS Raytracing Demo Crashes due to missing sse3 support

### ISSUE THREAD

**Issue by rameshvarun** [copy/v86#835]
The Raytracing demo in KolibriOS crashes with `"Error: Unsupported processor instruction"` If I load the in-operating system debugger, it looks like a bunch of garbled instructions that don't match up with the [raytracer source](http://websvn.kolibrios.org/listing.php?repname=Kolibri+OS&path=%2Fprograms%2Fdemos%2Fray%2F). Possibly the CPU jumped to an incorrect location in memory?

![download](https://user-images.githubusercontent.com/889879/232813629-5de509e6-0099-41c9-a4ce-30e15f43ca0b.png)

Also stepping in the debugger doesn't work, likely because x86 single-stepping mode is not implemented.

**Comment by copy** [comment]
`F2 0F 7C` is [HADDPS](http://ref.x86asm.net/coder32.html#x0F7C), an sse3 instruction which currently not implemented in v86 (and apparently not implemented in KolibirOS's debugger either).

I'd accept a PR (this is instruction should be fairly easy to implement).

**Comment by rameshvarun** [comment]
Ah, thanks for pointing that out. I was able to add the instruction, and it looks like the demo now works. I'll make a PR.

<img width="1331" alt="Screenshot 2023-04-18 at 2 29 43 PM" src="https://user-images.githubusercontent.com/889879/232910041-9aef4ca8-4b7f-469c-b919-fd0a48435c45.png">
