### ISSUE TITLE
Internet not working on Windows 98

### ISSUE THREAD

**Issue by creeperita09** [copy/v86#839]
hi, i am trying to access the internet on windows 98 and it seems to not work

**Comment by creeperita09** [comment]
i think it's a dns problem becouse if i use numerical ip's it works

**Comment by copy** [comment]
Works for me, did you run networking.bat?

![Screenshot_2023-04-24_19-55-36](https://user-images.githubusercontent.com/1816456/234002587-90c32b25-2706-4171-b26f-7d71c6578af7.png)
