### ISSUE TITLE
SSE3 support

### ISSUE THREAD

**Issue by copy** [copy/v86#844]
After #837 it probably makes sense to fully support SSE3. It might be useful for modern versions of Windows and Android.

There's only 4 instructions (I don't think we care about [`MONITOR`/`MWAIT`](https://stackoverflow.com/questions/57471862/uses-of-the-monitor-mwait-instructions) for now):

- [ ] `FISTTP`
- [ ] `MOVS[DLH]DUP`
- [ ] `HADDP[SD]`
- [ ] `HSUBP[SD]`
- [ ] Update cpuid bit

**Comment by spetterman66** [comment]
PR => #906

**Comment by spetterman66** [comment]
PR: #906

**Comment by spetterman66** [comment]
can be closed i guess
