### ISSUE TITLE
Running Tiny8 [Windows 8] on copy.sh

### ISSUE THREAD

**Issue by BYTRA0911** [copy/v86#852]
![Screenshot copy sh](https://user-images.githubusercontent.com/132814422/236669251-777da267-73dc-49dd-a215-43c091c69ac8.jpg)
I tried running Tiny8 (trimmed down version of Windows 8) and this error popped up.
how do i fix it?

**Comment by copy** [comment]
Probably https://github.com/copy/v86/issues/845 and https://github.com/copy/v86/issues/844.

Closing as duplicate.

**Comment by spetterman66** [comment]
Try windows 8 build 8133, it's the latest that works in v86
