### ISSUE TITLE
Poor Node Performance in Emulator

### ISSUE THREAD

**Issue by cemalgnlts** [copy/v86#853]
Hi,

I wanted to test node on ArchLinux but it takes too long to run hello.js.

Can anyone run the node with better performance?

**Comment by spetterman66** [comment]
emulators are slow especially those running in your web browser

**Comment by cemalgnlts** [comment]
I spent almost all day building a light version of linux with buildroot and tried to run node 12. And I got the same result 😐.

But one thing caught my attention. Once I initialize Node with repl, `.load hello.js` runs faster.

**Comment by cemalgnlts** [comment]
I tried Node in Tiny Core, it gives up faster than Arch Linux:

~10 seconds.

![Screenshot 2023-05-17 16 17 44](https://github.com/copy/v86/assets/45357531/8aaef0ad-d299-4cba-baa2-ffcdffd62df6)
