### ISSUE TITLE
Issue loading states

### ISSUE THREAD

**Issue by SSP6904** [copy/v86#854]
I'm getting a weird error in the console when I try to load a state to v86, from the js file..

`Uncaught (in promise) RangeError: offset is out of bounds`

and

`Uncaught TypeError: Cannot read properties of null (reading 'data')`

What am I doing wrong?

**Comment by copy** [comment]
Could you re-run in debug.html or lib86-debug.js and post the contents of the console? Also could you upload your state file and code?

**Comment by SSP6904** [comment]
[Console log](https://github.com/copy/v86/files/11445402/127.0.0.1-1683747548801.log)

```
            }, {
                id: "windowsxp",
                H: 536870912,
                N: {
                    url: m + "winxp.img",
                    size: 2147483648,
                    async: !0,
                    J: 262144,
                    ca: !l
                },
                name: "Windows XP",
                state: {
                    url: m + "WindowsXPState1.bin"
                },
                Gb: !0
            }, {
```

I can't upload my state file, because of file upload limits..

**Comment by copy** [comment]
Did you specify the same `vga_memory_size` in this profile as when you created the state image?

**Comment by SSP6904** [comment]
I got it to work with that..

but now it's always stuck on `Status: loading...` on the disk status on the right every 1 minutes

**Comment by copy** [comment]
Is it stuck or just downloading files (see the network tab)?

**Comment by SSP6904** [comment]
I think that's due to either downloading files or disk size..

I did follow your guide on the Windows XP/2000 thing..

It's just due to the amount CPU usage when right clicking, according to the console log in debug.html..

**Comment by copy** [comment]
In that case it's probably just the disk sectors that Windows XP needs, so nothing we can do from our side. I'd suggest to close this issue.

**Comment by SSP6904** [comment]
Just asking..
How did your Windows 2000 demo work with parts?

I think that's the problem..
