### ISSUE TITLE
Arch Linux Boot Error

### ISSUE THREAD

**Issue by cemalgnlts** [copy/v86#859]
Hi,

I created a build with packer by following what is written in the Arch Linux document, then when I open the browser to test it, I get the following error.

![Screenshot 2023-05-14 14 52 51](https://github.com/copy/v86/assets/45357531/42030a25-b942-48c4-ac44-e007fac9fc57)

**Comment by cemalgnlts** [comment]
Yes, it got worse.

![Screenshot 2023-05-14 15 37 49](https://github.com/copy/v86/assets/45357531/089e58ab-5adc-4850-984b-d265c8f0720c)
![Screenshot 2023-05-14 15 34 23](https://github.com/copy/v86/assets/45357531/65da0a49-2e63-4b0f-80e7-c411219c5ec1)

**Comment by SuperMaxusa** [comment]
```
ERROR: device 'host9p' not found. Skipping fsck.
```
It appears that Arch Linux is trying to mount 9p as rootfs, but it ends up with an error. 
Have you tried changing kernel parameter `root=` and `disablehooks=9p_root` in `APPEND` in syslinux.cfg, as here?
https://github.com/copy/v86/blob/bbac74d589e2ea1de1ca2b434a68276101ebd722/docs/archlinux.md?plain=1#L282-L286

**Comment by cemalgnlts** [comment]
I followed the ArchLinux.md file and completed all these processes with packer:
https://github.com/cemalgnlts/v86-archlinux-builder/blob/main/packer/scripts/provision.sh#L175-L179

**Comment by zt1106** [comment]
@cemalgnlts I have the same problem following the docs/archlinux.md, says "device 'host9p' not found", how did you solve this?
<img width="1424" alt="image" src="https://github.com/copy/v86/assets/20970607/af1cd337-5767-49b7-8290-8a76e5259728">

**Comment by cemalgnlts** [comment]
@zt1106, I'm not sure, I didn't continue because I didn't have more time to spare.
I suggest you open a new issue, maybe someone who knows.
