### ISSUE TITLE
Can’t Virtualize ReactOS or Windows 2K

### ISSUE THREAD

**Issue by StereoMadnessss** [copy/v86#865]
Can’t virtualize OSes above Windows 98 (displays 0 mIPS on a black screen), probably a safari related issue
![IMG_1407](https://github.com/copy/v86/assets/77188051/f5e08222-66d9-4fbe-8592-ca3eb6784c27)

**Comment by spetterman66** [comment]
try it on Firefox or Google Chrome instead

**Comment by copy** [comment]
Probably not enough memory, or missing wasm features.
