### ISSUE TITLE
Can I ask if this project has used multi-process tech to speed up the performance?

### ISSUE THREAD

**Issue by yingshaoxo** [copy/v86#868]
I'm just wondering if web has limitations on multi-cpu-core usage. 

Because from what I see and feel, the emulation is very slow.

**Comment by yingshaoxo** [comment]
Hello again.

For this time, I got some new ideas: How about using `web_workers`? 

(https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)

By using `web_workers`, javascript in brower can open multiple threadings, in this case, it will match multi-process performence.

___

I don't know the details of how simulator works. But it should be:

Simulator parse the img system file, parse the cpu tasks a program says, then use the simulator_core to excute those small tasks.

Now with web_worker technology, those smaill cpu tasks could get seperated into different web workers.

Will it speed up the simulation? I don't know for now.

@copy

**Comment by copy** [comment]
Yes, web workers would be used to implement multiple processors. However, the following still stands:

> That said, the implementation complexity is high, and there are other changes that would have a more significant impact on performance.
