### ISSUE TITLE
fs9p.GetFullPath Issue

### ISSUE THREAD

**Issue by cemalgnlts** [copy/v86#879]
Hi,

I tried to get the file written with 9p-write-end but it only gives the filename and count.

https://github.com/copy/v86/blob/b81df778019dd1fd43f7c813aad7266d30f626cb/lib/9p.js#L648

In addition to these, I also added the inode ID.

```diff
- this.bus.send("9p-write-end", [filename, count]);
+ this.bus.send("9p-write-end", [filename, count, this.fids[fid].inodeid]);
```

Then I tried to get the full path of the file with this ID but it gives this error:
```js
emulator.fs9p.GetFullPath(inodeId);

/*
libv86.js:806 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status')
    at FS.is_forwarder (libv86.js?v=0.3.3:806:48)
    at FS.GetDirectoryName (libv86.js?v=0.3.3:785:90)
    at FS.GetFullPath (libv86.js?v=0.3.3:786:158)
    at V86Starter.filesystemWriteEnd (worker.js:112:28)
    at BusConnector.send (libv86.js?v=0.3.3:577:137)
    at Virtio9p.ReceiveRequest (libv86.js?v=0.3.3:44:118)
*/
```

Whereas I can access the inode information:
```js
emulator.fs9p.GetInode(inodeId);

{
  atime: 1686839081
  caps: undefined
  ctime: 1686839081
  direntries: Map(0) {size: 0}
  fid: 3
  foreign_id: -1
  gid: 0
  locks: []
  major: 0
  minor: 0
  mode: 33188
  mount_id: -1
  mtime: 1686839081
  nlinks: 1
  qid: {type: 128, version: 0, path: 4}
  sha256sum: ""
  size: 2
  status: 0
  symlink: ""
  uid: 0
}
```

**Comment by cemalgnlts** [comment]
When I tracked down the error and tried to solve it, I noticed an error:
https://github.com/copy/v86/blob/b81df778019dd1fd43f7c813aad7266d30f626cb/lib/filesystem.js#L965-L973

The `parent_inode` variable can be null. So if it is not null it should be added:

```diff
const parent_inode = this.inodes[this.GetParent(idx)];

- if(this.is_forwarder(parent_inode))
+if(parent_inode && this.is_forwarder(parent_inode))
{
     return this.follow_fs(parent_inode).GetDirectoryName(this.inodes[idx].foreign_id);
}

// Root directory. 
if(!parent_inode) return ""; 
```

It doesn't solve the error but I'll look into it some more.

**Comment by cemalgnlts** [comment]
I don't understand here. It wants a parent folder, but this information is not defined in the files.
| Code | File | Parent Folder |
|---------|-------|---------------------|
|![Screenshot 2023-06-15 21 00 16](https://github.com/copy/v86/assets/45357531/fc683701-fe60-4d13-b809-a1744bf7ab89)|![Screenshot 2023-06-15 21 01 53](https://github.com/copy/v86/assets/45357531/bba0f5a2-d60c-4533-8584-dafbe4a7e73a)|![Screenshot 2023-06-15 21 15 42](https://github.com/copy/v86/assets/45357531/ec5d86c3-f4c4-4275-9a48-225f8d09bd9c)

**Comment by cemalgnlts** [comment]
Here only the `direntries` are filled if it is a folder.
https://github.com/copy/v86/blob/b81df778019dd1fd43f7c813aad7266d30f626cb/lib/filesystem.js#L279-L289

If I change this and allow every file, the result is positive.

![Screenshot 2023-06-16 14 54 30](https://github.com/copy/v86/assets/45357531/6fe96b12-1f83-4301-9626-cfa373d2fd9a)

**Comment by copy** [comment]
Files inodes don't have a parent directory by design, since they may be (hard-)linked in more than one directory. Read e.g.: https://teaching.idallen.com/cst8207/13w/notes/450_file_system.html
