### ISSUE TITLE
404

### ISSUE THREAD

**Issue by mdomocos** [copy/v86#88]
http://104.131.53.7:8086/windows98_state.bin is returning 404

**Comment by copy** [comment]
This happens when your browser (or HTTP client) doesn't support http compression. Compression is important because the file is rather big (it contains the whole memory) and compresses well (down to 10-15 MB).

What http client are you using?

**Comment by mdomocos** [comment]
I was on my work station, using chrome, it may been a problem on the proxy server we are using.
On my home station is all good

**Comment by copy** [comment]
> I was on my work station, using chrome, it may been a problem on the proxy server we are using.

That's probably it then. Could be fixed by letting users download the file uncompressed, but that's not great either.

**Comment by Darker** [comment]
No, it happens due to CORS (cross origin resource policy). That happens because either:

 - the host doesn't allow remote AJAX request on content
 - http and https is mixed
