### ISSUE TITLE
Debian 12 still wont work

### ISSUE THREAD

**Issue by LeoKids** [copy/v86#882]
![fail2](https://github.com/copy/v86/assets/68135774/2298d0bd-a76e-4b6f-a915-89cd55539b9b)
![fail](https://github.com/copy/v86/assets/68135774/dfd755f6-f7a9-4211-a178-ec8cc9e25710)

**Comment by LeoKids** [comment]
Installed version,netinstall

**Comment by SuperMaxusa** [comment]
Lastest Debian 12 with 1024 MB RAM and disabled ACPI:
![debian](https://github.com/copy/v86/assets/41739128/4bce0be4-c8aa-4f8a-ae26-ae634e7402f5)

As far as I understand, those errors with `mce` and `ACPI BIOS Error` should not seem to affect the system startup.

Can you try press key `e` in GRUB menu, change `quiet` on `acpi=off console=ttyS0 console=tty0`, press _Ctrl+X_ and check startup log?

**Comment by copy** [comment]
Correct, these errors can be ignored. Everything working as expected, as far as I can tell.

**Comment by LeoKids** [comment]
The next time I try to install,I will ignore it and it will get to the setup.
