### ISSUE TITLE
[SUggestion] the ability to load files into the vpcs.

### ISSUE THREAD

**Issue by MesaBlack** [copy/v86#883]

**Comment by copy** [comment]
On Linux you can use 9pfs: https://github.com/copy/v86/blob/master/docs/filesystem.md

For other OSes we already have an issue: https://github.com/copy/v86/issues/824

**Comment by MesaBlack** [comment]
what about windows 2000?

**Comment by copy** [comment]
Please read:

> For other OSes we already have an issue: https://github.com/copy/v86/issues/824
