### ISSUE TITLE
Connect to internet in FreeBSD, OpenBSD and NetBSD

### ISSUE THREAD

**Issue by ercan1104** [copy/v86#884]
You can write script (like networking.sh in Linux-systems).

FreeBSD
```sh
ifconfig ed0 up
dhclient ed0
```

OpenBSD
```sh
ifconfig ne3 up
dhclient ne3
```

NetBSD
```sh
ifconfig ne1 up
dhclient ne1
```

**Comment by copy** [comment]
Nice! Could be added to the docs, but I'll close this as there is no issue here.
