### ISSUE TITLE
Support persistent drive by default 

### ISSUE THREAD

**Issue by upintheairsheep** [copy/v86#889]
Can you add a basic virtual external FAT drive that connects to the browser’s filesystem, with a txt explaining that this saves the data? The main thing that dissuades me from using the emulator is the lack of file saving support, so having the virtual drive would make this from a demo to something that someone could actually use. Additionally it should support uploading files to the virtual drive and downloading the files from it in another interface.

**Comment by SuperMaxusa** [comment]
see #824 and https://github.com/copy/v86/issues/883#issuecomment-1606544072
