### ISSUE TITLE
Support external .iso and .img via the Internet Archive

### ISSUE THREAD

**Issue by upintheairsheep** [copy/v86#894]
https://infinitemac.org/ is open-source and supports inserting CD and DVD images via HTTP range requests on the Internet Archive and Macintosh Garden

**Comment by copy** [comment]
Try `cdrom.url`/`hda.url`, e.g.: `https://copy.sh/v86/?profile=custom&hda.url=...`

**Comment by upintheairsheep** [comment]
> Try `cdrom.url`/`hda.url`, e.g.: `https://copy.sh/v86/?profile=custom&hda.url=...`

https://copy.sh/v86/?profile=windows95&cdrom.url=https://archive.org/download/Win95AllinOneIso/Win95ORTM.iso

**Comment by upintheairsheep** [comment]
> The internet archive doesn't send CORS headers, so directly loading doesn't work. infinitemac.org runs a proxy that downloads files from the internet archive on the server.
> 
> I don't have plans to run a proxy, but feel free to do so. Alternatively, you can download the files and use https://v86-upload.copy.sh

You should get in contact with the owners of infinitemac to share the proxy for v86 as well. After that, v86 is almost perfect, only an optional virtual drive that downloads files placed into it to your computer, and a way to upload files or share the filesystem (there is an API for that, ya know?) via another optional virtual drive

**Comment by upintheairsheep** [comment]
> The internet archive doesn't send CORS headers, so directly loading doesn't work. infinitemac.org runs a proxy that downloads files from the internet archive on the server.
> 
> I don't have plans to run a proxy, but feel free to do so. Alternatively, you can download the files and use https://v86-upload.copy.sh

https://blog.persistent.info/2023/08/infinite-mac-cd-roms.html?m=1

Does not appear to use some external server method at all.
