### ISSUE TITLE
VGA Glitches

### ISSUE THREAD

**Issue by Creeper20428** [copy/v86#90]
Note: This is probably not related to #26, since I'm dealing with all of VGA.

VGA is kind of glitchy: 
![w95-0](https://cloud.githubusercontent.com/assets/8443268/13545482/5dfab1d0-e242-11e5-990a-26978088f098.png)
![w98-0](https://cloud.githubusercontent.com/assets/8443268/13545485/7ec8495e-e242-11e5-8bc0-2ce8fef5f370.png)

Steps for reproducing problems:
 1a) Open Windows 95. (it's glitchy, downloaded from here: [http://www.mediafire.com/download/85w636eic9sv12h/W95.rar](W95.rar) since I'm lazy)
 2a) Open any application. I just opened IE3 since I wanted to see how Internet Explorer looked like in 1995.

 1b) Open Windows 98
 2b) Open the MS-DOS prompt

**Comment by fibo** [comment]
I guess it is a feature, also Windows glitches.

**Comment by Creeper20428** [comment]
> I guess it is a feature
This doesn't happen in Bochs or any other x86 emulator

**Comment by copy** [comment]
First of all – pretty cool that Windows 95 works at all. It's one of the versions I didn't test. I might put it one the website at some point.

Indeed our vga implementation isn't great. It's better to use a driver that supports vbe, which is implemented correctly, faster and supports bigger resolutions. A driver for Windows can be found here: http://www.navozhdeniye.narod.ru/vbe9x.htm (the same driver is used on Windows 98).

I'll leave this issue open since we might want to fix this at some point (for DOS games or so).

**Comment by computernewb** [comment]
I think it may be due to how it handles 16-colored programs and operating systems. 

Windows 2.03 has some bad graphical glitches as shown here.

<img src="http://i.imgur.com/E5bUETz.png"></img>

**Comment by Creeper20428** [comment]
Yeah... I tried Windows 2 but it's weird like that too.
Did anyone try Windows 3.11 or "Windows 3.X for Workgroups"?

But most of the operating systems I used look good, though.

**Comment by computernewb** [comment]
Yeah, most operating systems I've tried seem to be rendered fine, it's Windows that seems to have issues. Windows 98 is rendered perfectly fine though. I tried to boot Windows Me, but I am greeted by a "KRNL386.EXE" error. Safe mode seems to lock up after the initial "Windows is running in Safe Mode" message box, but it does start. It doesn't seem to have graphical glitches though. I will try a different combination in Bochs later and see if I can get it to load.

As for Windows 3.x, I have not had luck with getting Windows 3.1 to start. It displays the splash screen, but never gets past it. I have not tried Windows 3.0 or Windows 3.11 for Workgroups yet.

**Comment by BenNottelling** [comment]
Looks like this is fixed here: https://github.com/ErnWong/v86/tree/dev-vga
@ErnWong I can't wait to see a PR!
![win95](https://user-images.githubusercontent.com/17304943/34077214-0fb2d8e0-e2b3-11e7-8f48-56f2c239a4ec.PNG)
![win95_2](https://user-images.githubusercontent.com/17304943/34077215-0fca6f50-e2b3-11e7-8235-8eb4a6139ea8.PNG)

**Comment by ErnWong** [comment]
FYI, my upcoming PR only fixes some vga write modes, so it won't fix the ms-dos prompt glitch when used with the vbe driver unfortunately :worried: But at least, if you want ms-dos prompt working, you can remove the vbe driver to get the ms-dos prompt semi-usable (it still has some interesting non-graphical bugs though - the cursor jumps around to all sorts of weird places - that'll be a topic for another day)

**Comment by copy** [comment]
> FYI, my upcoming PR only fixes some vga write modes, so it won't fix the ms-dos prompt glitch when used with the vbe driver unfortunately 😟

Note that the bug is in the vbe driver, not in our emulation, so don't look for it. I'll see if Windows looks good enought in the old vga mode and, if yes, remove the vbe driver.

**Comment by copy** [comment]
This is now fixed. The buggy vbe driver has also been removed in favour of the standard vga driver, MS-DOS prompt is working now. Please test: http://copy.sh/v86/?profile=windows98
