### ISSUE TITLE
Add demo of ELKS [proposition]

### ISSUE THREAD

**Issue by toncho11** [copy/v86#902]
Hi,

Can you add an a new demo of ELKS OS https://github.com/jbruchon/elks/

For example you can use the following hdd image: https://github.com/jbruchon/elks/releases/download/v0.7.0/hd32-minix.img

Simply setting 1MB of RAM and 1 MB of video memory is enough to run it on your emulator.

**Comment by copy** [comment]
https://copy.sh/v86/?profile=elks

**Comment by toncho11** [comment]
Awesome! Thanks!

**Comment by toncho11** [comment]
I hope it is not too much to ask if you can add it to the list: https://copy.sh/v86/ and demo section on https://github.com/copy/v86.
