### ISSUE TITLE
Making a profile

### ISSUE THREAD

**Issue by computernewb** [copy/v86#91]
I have not found any documentation on making a profile in v86. I am hosting a version on my own website for testing.

Is there a tutorial on how to make a profile for v86?

**Comment by copy** [comment]
There's no tutorial, sorry.

The profiles are defined in [`main.js`](https://github.com/copy/v86/blob/master/src/browser/main.js#L187). Simpler examples can be found [here](https://github.com/copy/v86/tree/master/examples). The interface is documented [here](https://github.com/copy/v86/blob/master/docs/api.md).

**Comment by copy** [comment]
Feel free to reopen if you still have questions.

**Comment by computernewb** [comment]
So I found out how to make a profile.
Profiles are defined in build\v86_all.js as well as src\browser\main.js. Adding 

{id:"mikeos",Na:{url:"images/mikeos.img",size:737280},name:"MikeOS"}

to v86_all.js and adding
{
id: "mikeos",
fda: {
"url": "http://computernewb.com/x86emu/images/mikeos.img",
"async": true,
},
name: "MikeOS 4.5",
},

allows users to navigate to my fork of v86 and run MikeOS 4.5 (very minimal DOS-like OS that comes with games and apps)

http://computernewb.com/x86emu/?profile=mikeos
