### ISSUE TITLE
Can you start working on Windows ME and later?

### ISSUE THREAD

**Issue by Ao28th28** [copy/v86#910]
Also Windows 2000 is slow for me.

**Comment by spetterman66** [comment]
dude, if windows xp is not allowed on winworldpc.com then it also isn't allowed on v86. period.

**Comment by spetterman66** [comment]
only abandonware (win2k and older) and freely licensed operating systems (debian ubuntu arch slackware skift android ...)

**Comment by copy** [comment]
Already works.

![Screenshot_2023-09-08_10-58-38](https://github.com/copy/v86/assets/1816456/a1ae471b-002f-42c1-abdc-c0a83fabd572)
