### ISSUE TITLE
Virtual battery and AC adapter

### ISSUE THREAD

**Issue by upintheairsheep** [copy/v86#912]
Please make a virtual battery and AC adapter via the Battery Status API on supported devices.
https://www.mail-archive.com/qemu-devel@nongnu.org/msg776834.html - QEMU pull with info
https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API - API Docs

**Comment by upintheairsheep** [comment]
Windows 9x+, most Linux builds, and Android x86 support this.

**Comment by copy** [comment]
Why?

**Comment by Ryan8085309853409** [comment]
Yeah good question, why would a vm software have battery

**Comment by upintheairsheep** [comment]
Only for devices with batteries to pass through 


Sent from my Apple Watch

**Comment by spetterman66** [comment]
its not useful in any way...

**Comment by spetterman66** [comment]
@copy can you close this issue, these features aren't going to be implemented anyway

**Comment by copy** [comment]
A PR would we welcome, but considering that there are much more useful things to work on, let's close this.
