### ISSUE TITLE
[Feature request] fullscreen centering

### ISSUE THREAD

**Issue by glitch128** [copy/v86#914]
I would like it if when you went fullscreen, it appeared in the center, instead of to the left.

**Comment by mekanoe** [comment]
I can pick this up.

A question on UX, I'm assuming "center" is both vertically and horizontally centered, does this also involve a "zoom" so it'd fill as much as the screen as possible, and otherwise centered?

Mockups of what I'm asking

**Just centered** (keeps original scale)
![image](https://github.com/copy/v86/assets/1581674/eea05a6b-ac2d-4aee-9bc8-f454f57df4ad)

**Centered and scaled**
![image](https://github.com/copy/v86/assets/1581674/6c4a64ae-4970-4088-bd08-fdd84bbffa77)

(both on a 3440x1440 screen, dev-tools for scale)

**Comment by glitch128** [comment]
What I was thinking was that the existing "scale" parameter in the top button bar would handle that, but a "fit to screen" option would be great.

**Comment by mekanoe** [comment]
I dig that. 

I think a big downside to the scale parameter alone here is that it could end up larger than the screen, and then we'd need to scroll to use it (which doesn't currently work well in mockups)

**Comment by glitch128** [comment]
Actually, I was going to also say that, if needed, the screen would scale down to match the height of the screen

**Comment by SuperMaxusa** [comment]
> Personally, I'm indifferent, as the scaled version is technically nicer for a like-size screen, but centered alone matches pixel scale better. Could be an option?

About autoscaled fullscreen: #642
As far as I know, v86 makes 2x scale by default, if **graphical mode width** is less than 640 px and if **graphics mode width * 2** < **window width**: https://github.com/copy/v86/commit/5199c3dc872bb9b8a7fb54515f4cc2d6dcfa44f6

As for scaling with correct pixel scale, I think it’s better to use like a **pixel-perfect** (integer) scaling algorithm

**Comment by copy** [comment]
I think it should be scaled (as in the second image), and ignore the scale of non-fullscreen mode.

**Comment by glitch128** [comment]
Hey, has there been any progress on this?

**Comment by glitch128** [comment]
ok, so I tested the new css with a css injector(?) extension, and it works well, but only works on the graphical display, and not the text.

**Comment by MesaBlack** [comment]
> ok, so I tested the new css with a css injector(?) extension, and it works well, but only works on the graphical display, and not the text.

Any screenshots(

**Comment by spetterman66** [comment]
PR: https://github.com/copy/v86/pull/963

**Comment by spetterman66** [comment]
Close this issue, it has been implemented in d8c0acb
