### ISSUE TITLE
Mouse enable

### ISSUE THREAD

**Issue by SSP6904** [copy/v86#915]
How can I enable the mouse to focus on the VM with the API and starter files?

It won't go focus into the canvas once the mouse clicks on it.

**Comment by SuperMaxusa** [comment]
https://github.com/copy/v86/blob/5da61d617e8bd8b0a4ce686c59d40f8dbf0dac94/src/browser/starter.js#L1128-L1135
https://github.com/copy/v86/blob/5da61d617e8bd8b0a4ce686c59d40f8dbf0dac94/src/browser/main.js#L1975-L1981

**Comment by SSP6904** [comment]
For the `lock_mouse` variable, does that go with my v86 settings?

![image](https://github.com/copy/v86/assets/75172901/3b7018cf-ae2f-400e-920c-c4e94d325bd9)

**Comment by SuperMaxusa** [comment]
> For the `lock_mouse` variable, does that go with my v86 settings?

No, `emulator.lock_screen()` is function which need call on **screen_container**'s onclick event. 
Here is an simple example of how it should be in your case:

```js
window.onload = function()
{
    var emulator = window.emulator = new V86Starter({
        wasm_path: "v86.wasm",
        memory_size: 32 * 1024 * 1024,
        vga_memory_size: 2 * 1024 * 1024,
        screen_container: document.getElementById("screen_container"),
        bios: { ... },
        vga_bios: { ... },
        cdrom: { ... },
        autostart: true
    });

    // lock mouse on click
    document.getElementById("screen_container").onclick = function()
    {
        emulator.lock_mouse();
    };
}
```

**Comment by SSP6904** [comment]
Thank you! It's working now.
