### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by OverdueWeevil2** [copy/v86#925]
https://github.com/copy/v86/releases

**Comment by spetterman66** [comment]
They are located under tags => https://github.com/copy/v86/tags.

**Comment by BelleNottelling** [comment]
There should be a release unless an error happened with the workflow or if @copy deleted it.
But in the meantime, anyone with a GitHub account can download a zip containing the latest build pretty easily by going to the check summary: 
![Animation](https://github.com/copy/v86/assets/17304943/0b6abe90-627e-42b5-a01b-a71c9ab54dbe)

**Comment by copy** [comment]
> There should be a release unless an error happened with the workflow or if @copy deleted it.

I didn't delete it, but it only showed up as a draft. I've published it now, let's hope it stays published.

**Comment by copy** [comment]
Seems to be working now.
