### ISSUE TITLE
Multi-byte UTF-8 characters not displaying correctly on xterm.js

### ISSUE THREAD

**Issue by robertaboukhalil** [copy/v86#927]
When using xterm.js with v86, UTF-8 characters that are defined by multiple bytes are not displayed correctly.

**Reproduce:**
* Go to https://copy.sh/v86/?profile=archlinux
* Type `echo -e '\x24'` (single-byte) and that [correctly](https://en.wikipedia.org/wiki/UTF-8#Encoding_process) shows the `$`:
![Screenshot 2023-09-19 at 8 19 41 PM](https://github.com/copy/v86/assets/2009870/43ebaf5e-acba-441f-8d55-704d43e4ac19)

* Type `echo -e '\xc2\xa3'` (two bytes) and that shows the correct symbol in the original v86 renderer but not xterm.js:
![Screenshot 2023-09-19 at 8 20 49 PM](https://github.com/copy/v86/assets/2009870/a62e7410-8037-4b53-9c66-0330132ddf19)

I noticed this issue when using the linux `tree` command, where I see `â` characters instead of a horizontal line, but **only with xterm.js**:
![Screenshot 2023-09-19 at 8 24 11 PM](https://github.com/copy/v86/assets/2009870/022c1a5a-51be-466e-b8a9-d9b83217bbae)

I wasn't able to find the root cause but I **think** it has something to do with the UART logic sending [treating each byte separately](https://github.com/copy/v86/blob/23a4f4c772adea7ead30faa900aa39fc729c9a01/src/uart.js#L345), which then gets output one at a time in the [xterm.js serial adapter](https://github.com/copy/v86/blob/master/src/browser/serial.js#L240). Whereas with the regular serial adapter, the bytes are [appended before being rendered](https://github.com/copy/v86/blob/master/src/browser/serial.js#L60)?

**Comment by SuperMaxusa** [comment]
Judging by the debug log, these two bytes seem to be sent correctly.
```08:55:45+890 [SERI] interrupt enable: 0x7
08:55:45+891 [SERI] read interrupt identification: 0x2
08:55:45+892 [SERI] read line status: 0x60
08:55:45+892 [SERI] read modem status: 0x0
08:55:45+893 [SERI] data: 0xC2 
08:55:45+895 [SERI] data: 0xA3 
08:55:45+896 [SERI] interrupt enable: 0x5 
08:55:45+896 [SERI] read interrupt identification: 0x1 
08:55:45+896 [SERI] interrupt enable: 0x7
08:55:45+897 [SERI] read interrupt identification: 0x2
08:55:45+897 [SERI] read line status: 0x60
08:55:45+897 [SERI] read modem status: 0x0
08:55:45+897 [SERI] data: 0xD
08:55:45+898 [SERI] data: 0xA
08:55:45+898 [    ] SERIAL: ~% mm[J[J
08:55:45+898 [SERI] interrupt enable: 0x5
08:55:45+898 [SERI] read interrupt identification: 0x1
08:55:45+899 [SERI] interrupt enable: 0x7
08:55:45+899 [SERI] read interrupt identification: 0x2
08:55:45+899 [SERI] read line status: 0x60
08:55:45+899 [SERI] read modem status: 0x0
08:55:45+900 [SERI] interrupt enable: 0x5
08:55:45+900 [SERI] read interrupt identification: 0x1
```

It seems to me more that xterm.js itself is displaying codes incorrectly, I tried to display these characters through `term.write('\xc2\xa3')` and the result is the same:

![xtermjs](https://github.com/copy/v86/assets/41739128/af6c615d-0222-4223-9a33-05626167b1b7)

**Comment by copy** [comment]
According to the [docs](https://xtermjs.org/docs/guides/encoding/), `write` accepts a String that is already properly (utf16) encoded, or an `Uint8Array`, which will handle utf8 internally. So the mistake is that uart.js converts the character to a string. It's a breaking change, but it should pass the byte, which can then be written in an `Uint8Array`.

**Comment by robertaboukhalil** [comment]
Nice, that fixed it! Do you have a preference for how to implement this fix? A few options:

* Keep `serial-*-output-char` and adding a new `serial-*-output-byte`, where the raw byte is passed along, and the xterm.js listener does `term.write(new Uint8Array([out_byte]));`
* Replace `serial-*-output-char` with `serial-*-output-byte` and have each serial adapter treat the byte however they want.

**Comment by copy** [comment]
> Replace serial-*-output-char with serial-*-output-byte and have each serial adapter treat the byte however they want.

This one. It more accurately reflects how the uart works, and having both is problematic from a performance point of view.

**Comment by SuperMaxusa** [comment]
With #928 I was able to make a simple dummy hack to display UTF-8. 
Here, the required number of bytes is first found through bitwise (https://en.wikipedia.org/wiki/UTF-8#Encoding), then the sequence of the following bytes is formed and sent to xterm.js as **Uint8Array**.

![demo](https://github.com/copy/v86/assets/41739128/84c95032-c9de-452c-bc62-9f38342cfb0d)

```js
    // sorry for not so good code below

    let buffer = [];
    let bytecount = 0;

    emulator.add_listener("serial0-output-byte", function(s) {
        if (buffer.length == 0) 
        {
          if ((s >>> 3) === 0b11110)
          {
            // 4 bytes
            bytecount = 4;
            buffer.push(s);
          }
          else if ((s >>> 4) === 0b1110)
          {
            // 3 bytes
            bytecount = 3;
            buffer.push(s);
          }
          else if ((s >>> 5) === 0b110)
          {
            // 2 bytes
            bytecount = 2;
            buffer.push(s);
          }
          else
          {
            // 1 byte or not UTF-8 char
            // just send w/out buffer
            window.term.write(new Uint8Array([s]));
          }
      }
      else if (buffer.length == bytecount)
      {
        // write bytes from buffer
        window.term.write(Uint8Array.from(buffer))
        // clean buffer and bytecount
        bytecount = 0;
        buffer = [];
      }
      else
      {
        buffer.push(s);
      };
    });
```
</details>

**Comment by copy** [comment]
@SuperMaxusa xtermjs should already have this buffering logic internally. After all, a real uart doesn't do buffering either.
