### ISSUE TITLE
Migrating state file from version 5 to 6

### ISSUE THREAD

**Issue by Catz-uwu** [copy/v86#932]
I have an MS-DOS state file whose version is 5, and I would like to be able to load it on the live website. Loading it shows the following error:

```
Something bad happened while restoring the state:
Error: Version mismatch: dump=5 we=6

Note that the current configuration must be the same as the original
```

I was able to load the state file with a version archived on [https://archive.org/](https://archive.org/), but I still need to update the state file to version 6. In the git history the version seems to jump from 3 to 6 https://github.com/copy/v86/commit/2683d95db98bf850eb8825f2b596ca668fb18a62, is it possible to find the code for version 5?

**Comment by copy** [comment]
Here's version 5: https://github.com/copy/v86/commit/6abcc3ad4d56f08a5bd594c438e39ada805c52b4

The reason you're seeing a commit with 3->6 and one with 3->4->5->6 is that they exist on both sides of a big merge commit.

**Comment by copy** [comment]
Note that it's likely more work to implement state version 5 in the current version than recreating the state file. You might be able to recover the disk images in the state by loading it in an old version of v86 in debug mode and playing around with `cpu.devices.hda.master.buffer` (or `.fda) in the devtools console.

**Comment by RasmusAntons** [comment]
> Note that it's likely more work to implement state version 5 in the current version than recreating the state file. You might be able to recover the disk images in the state by loading it in an old version of v86 in debug mode and playing around with `cpu.devices.hda.master.buffer` (or `.fda) in the devtools console.

Thanks for your answer, I've tried to do this now and it's behaving a bit weird.

I can save the content of `cpu.devices.hda.master.buffer.buffer` into a file and mount that on my pc, but it contains the files from the demo image (vim.exe etc.), not the ones in our state file. I also noticed that if I load the state file and then disable smartdrv with `smartdrv c-`, the new files from the state file become unreadable and after changing directories, the files from the demo image show up again.

Does this mean that the files are only in memory? Would it be possible to transplant the memory into the current version of v86?
I tried to write it on the current build with `fetch('/mem.img').then(res => res.arrayBuffer()).then(buffer => cpu.mem8.set(0, new Uint8Array(buffer)))` but I don't think that did anything.

Alternatively, do you happen to know if it's possible to write whatever is in the memory to the hda? I tried `smartdrv c /c` with no success.

The reason we want to do this is that we have a file from a CTF kind of game and we would like to make it possible to play with the current version of the site. We don't exactly know how the state file was created and it includes a compiled binary that we don't have the source code of.
