### ISSUE TITLE
Trying to build using docker

### ISSUE THREAD

**Issue by bitcoinmeetups** [copy/v86#934]
Trying to build using docker (instructions on main page) outputs:

CACHED [stage-1 2/3] WORKDIR /v86                                                                      0.0s
CACHED [v86-builder 2/6] WORKDIR /v86                                                                  0.0s
CACHED [v86-builder 3/6] RUN apk add --update curl clang make openjdk8 npm python3                     0.0s
CACHED [v86-builder 4/6] RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y   0.0s
CACHED [v86-builder 5/6] COPY . .                                                                      0.0s
ERROR [v86-builder 6/6] RUN PATH="${HOME}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi  0.5s
------
 [v86-builder 6/6] RUN PATH="${HOME}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" make all && rm -rf closure-compiler gen lib src tools .cargo cargo.toml Makefile:
#13 0.372 make: *** No rule to make target 'all'.  Stop.
------
executor failed running [/bin/sh -c PATH="${HOME}/.cargo/bin:${PATH}" make all && rm -rf closure-compiler gen lib src tools .cargo cargo.toml Makefile]: exit code: 2
(base) @bitcoinmeetups ➜ ~/v86/tools/docker/exec (master) $

**Comment by copy** [comment]
Please put more effort in your issues.
