### ISSUE TITLE
When I executed the T command in the debug program, the entire simulator stopped responding

### ISSUE THREAD

**Issue by Crazyokd** [copy/v86#938]
![image](https://github.com/copy/v86/assets/74645100/2232f364-0c67-4278-a2ce-1a2dc838693a)

i try to modify the cs:ip or the instruct, but the result is same.
> please forgive i am not a native English speaker.

**Comment by SuperMaxusa** [comment]
#161

**Comment by Crazyokd** [comment]
@SuperMaxusa thank you.
