### ISSUE TITLE
Boot Syllable

### ISSUE THREAD

**Issue by copy** [copy/v86#941]
Currently uses a bunch of unimplemented apic features, then hangs forever on:

```
0:boot-shell::boot-shell(-1) : Starting init...
```

**Comment by SuperMaxusa** [comment]
Syllable Desktop LiveCD 0.6.6 ([iso.xz](https://syllable.metaproject.frl/Syllable/i586/systems/Desktop/0.6.6/SyllableDesktop-0.6.6-LiveCD.i586.iso.xz)) worked for me if runs via `Syllable in a Virtual Machine (VMware, Virtual PC, VirtualBox)` -> `Syllable in VirtualBox (no SMP/ACPI)`, but it have some graphical issues
![syllable](https://github.com/copy/v86/assets/41739128/6fe341d4-44c6-4075-92d5-36848ef76a32)

**Comment by copy** [comment]
@SuperMaxusa Nice find. Indeed it works after adding `disable_smp=true` to the kernel command line in `/boot/boot/grub/menu.lst`.

Will add a profile to the website soon.

**Comment by copy** [comment]
https://copy.sh/v86/?profile=syllable

A bit too large to put on the frontpage now, but still an interesting demo.
