### ISSUE TITLE
Serial terminal is buggy in recent version

### ISSUE THREAD

**Issue by mikaku** [copy/v86#942]
I've noticed that in the recent version the serial terminal seems buggy, it used to work in previous versions (5 July).
Is there a way to run old versions of v86 in your website? this would help to compare and detect code regressions.

You can check this issue by running FiwixOS, then edit `/etc/inittab` with `vi` and change the line:

`#S0:2345:respawn:/sbin/mingetty --autologin=root ttyS0`

by

`S0:2345:respawn:/sbin/agetty -L 9600 ttyS0`

Save the file with `:wq`, and under the system prompt type `telinit q`.
You'll see the login message appear in the COM1 window below. So far so good.

Try to log in with user `root` and when it prompts for the password you'll notice that you won't be able to type anything or whatever you type it will be sent as garbage.

If you prefer test this issue using a more trusted kernel like Linux, no problem. I've prepared a bootable floppy disk with the Linux kernel 2.2.6 with support for serial:

[linux-2.2.26+serial-ext2.img.zip](https://github.com/copy/v86/files/12837143/linux-2.2.26%2Bserial-ext2.img.zip)

Just boot the FiwixOS image with that floppy and then change the GRUB line to say:

`kernel /boot/vmlinuz-2.2.26 ro root=/dev/hda2`

Then proceed with the same instructions as in FiwixOS above.

**Comment by mikaku** [comment]
Do you think that it is related to #899?

**Comment by copy** [comment]
Did you try the git version, or just the one on the website?

> Do you think that it is related to https://github.com/copy/v86/issues/899?

There have been several bugfixes related to the serial console recently, I think https://github.com/copy/v86/pull/923 might be related.

**Comment by mikaku** [comment]
> Did you try the git version, or just the one on the website?

The one on the website.

**Comment by copy** [comment]
In current master I can't reproduce the issue, so I'll assume it has been fixed in one of the recent bug fixes (most likely #923). Will push a new version to the website soon.

**Comment by mikaku** [comment]
OK, then I'll check it again as soon as you push the new version.
Thanks.

**Comment by copy** [comment]
The fix should be online now, could you check again?

**Comment by SuperMaxusa** [comment]
After update, serial terminal work correctly in FiwixOS 3.2:

![com1](https://github.com/copy/v86/assets/41739128/6e669a65-ed97-4404-aa96-f7751dd9ca96)

**Comment by mikaku** [comment]
@copy, yes serial terminal is working back again.
Thank you very much!
