### ISSUE TITLE
Local OpenAI style Code Interpreter

### ISSUE THREAD

**Issue by chadbrewbaker** [copy/v86#947]
I was going to use jslinux, but this project looks better maintained. What would it take to run this alongside a WASM/WebGPU large language model in the browser?

I'm also a noob regarding websockets. Like to host something like https://relay.widgetry.org that jslinux is using for the proxy on a static URI.

**Comment by copy** [comment]
I'd recommend compiling directly to wasm/webgpu. GPU in VMs is tricky. There is virtio-gpu (https://github.com/copy/v86/issues/51), but even then it's unclear if it can be used for compute stuff like language models.

**Comment by copy** [comment]
Let's close this.
