### ISSUE TITLE
What's the format of the disk images?

### ISSUE THREAD

**Issue by piranna** [copy/v86#95]
I'm planning to use v86 for test and demo purposses for NodeOS and I have two doubts:
1. Is it possible to run v86 just by providing a multiboot kernel as it's possible with QEmu and the `-kernel` flag? If so, how?
2. Is it possible to use it as translator between platforms to exec directly programs as QEmu User Space?
3. What's the format of the disk images? Is it enough to use partition images (raw filesystem), or is it needed disk images with partitions and a bootloader inside them?

**Comment by copy** [comment]
1. This isn't possible right now, but it would be relatively easy to implement
2. This isn't possible
3. They need to have a bootloader

**Comment by piranna** [comment]
> This isn't possible right now, but it would be relatively easy to implement

Cool! :-)


> This isn't possible

Boo :-( Yeah, I suspected it would be more difficult since it needs to capture the syscalls... :-/


> They need to have a bootloader

Probably could this be fixed if point one gets implemented?

**Comment by copy** [comment]
> Probably could this be fixed if point one gets implemented?

Yep, when the emulator supports multiboot the OS doesn't need a bootloader any more, the OS image only needs to be multiboot compliant.

**Comment by copy** [comment]
Kernels can now be loaded directly, for example: https://github.com/copy/v86/blob/cc9795dbfca212fc173e6d8f5e3b2b7b25b2f0c4/tests/full/run.js#L227
And using 9p:
https://github.com/copy/v86/blob/cc9795dbfca212fc173e6d8f5e3b2b7b25b2f0c4/tests/full/run.js#L240-L244
