### ISSUE TITLE
Network on Arch Linux

### ISSUE THREAD

**Issue by inyourface34456** [copy/v86#954]
When I booted arch linux, I tried to access the internet.  When I tried to ping google.com, I got "temporary failure in name resolution."  When I set the DNS servers (1.1.1.1), I continued to get the same error.  How can I access the network in Arch?

**Comment by spetterman66** [comment]
Yes, that could be caused by a slow computer setup configuration. Please try it again with all your other programs and windows closed, then report again.

**Comment by inyourface34456** [comment]
I just tried with all applications either unloaded (not showing up in task manager) or closed completely. I ran the command twice with the same output (timed out).  The Mips peaked at  ~30 and then settled at .5 (about what idle is), so it is probably not my computer.

### Screen recording
[Screen recording 2023-12-04 2.37.09 PM.webm](https://github.com/copy/v86/assets/62214409/5946acd8-81c6-41a0-a0e0-9f810d2c0d6f)

**Comment by spetterman66** [comment]
Can you open https://relay.widgetry.org/ (Web Socket Proxy) in your web browser? This is what it's supposed to show:
![image](https://github.com/copy/v86/assets/69303239/c82be516-7e1c-4a89-bb9c-40d4d8a39a66)

**Comment by inyourface34456** [comment]
That website did not work for me.  That must be why i cannot connect to the internet.  Is there any other relay that I can connect to, or a way to host my own?

**Comment by SuperMaxusa** [comment]
> That website did not work for me.

You have NS error or something else?

> or a way to host my own?

see [websockproxy](https://github.com/benjamincburns/websockproxy#getting-started) or [node-relay](https://github.com/krishenriksen/node-relay#getting-started) (needed docker) and use `https://copy.sh/v86/?profile=archlinux&networking_proxy=ws://<your ws url>`
