### ISSUE TITLE
[Bug] [Guest OS] Save state not working on custom images

### ISSUE THREAD

**Issue by glitch128** [copy/v86#960]
![image](https://github.com/copy/v86/assets/78228404/ca3d0748-7948-4695-920b-988b50a9b98a)
here is the console error
this only happens on custom images as far as I have tested

**Comment by copy** [comment]
I can't reproduce this (tried a ReactOS cdrom with the default settings), can you provide more precise reproduction instructions (what disk images used, settings, what happened in the OS when you saved the state)?

**Comment by glitch128** [comment]
it still fails

**Comment by spetterman66** [comment]
probably because the copy.sh/v86 website was last updated on oct 8, 2023.
![image](https://github.com/copy/v86/assets/69303239/59b4aecc-4333-4d96-a992-d5fdc375bb08)
