### ISSUE TITLE
Allow for Real USB/CD devices to be plugged in as storage device

### ISSUE THREAD

**Issue by 1jammer1** [copy/v86#965]
I imagine this could work through the mechanism of USB devices and file editing as shown in the image I think this would be cool for use on a **Chromebook** or for actual saving of changes onto a file instead of it being run directly in RAM.

Thank you

![image](https://github.com/copy/v86/assets/77495892/39528170-ccc2-4fe1-8ea2-7ed72b1ad4c4)

**Comment by copy** [comment]
I'll gently close this as not planned. USB support is a lot of work, and there are other options to share files with the guest OS that are useful (https://github.com/copy/v86/issues/396#issuecomment-840099814 for 9pfs or https://github.com/copy/v86/issues/824 for other OSes).
