### ISSUE TITLE
Noob question about how V86 compares to WebAssembly

### ISSUE THREAD

**Issue by lonnietc** [copy/v86#966]
Hello,

I am researching in browser VM's and similar thing.  Have been reading up on WebAssembly and have now just come across V86 as well as WebVM, JSLinux (Fabrice of QEMU), and now V86 plus a few others that I have not yet sorted out.

Can you please tell me how V86 compares?

Also, from what I could find, it does not look like there may be any x86_64 version coming out anytime soon, or is that planned for later as it would be extremely useful to be able to run x64 applications.

Maybe what I am seeking is some type of wasm (or similar) type of sandbox container engine instead of VMM in a browser, but I am not sure on this.

Any thoughts would be greatly appreciated and have a great day.
Thanks in advance

**Comment by copy** [comment]
JSLinux is the first project. It was originally written in JavaScript and later ported over to wasm. It doesn't have a jit, so it's slower than v86 or webvm (but it's still very fast for what it does!)

webvm and v86's wasm port were both developed around the same time independently. Both projects have a jit that translates x86 to wasm, but webvm's engine is more advanced, and programs in webvm run faster. v86 emulates a full system, so it runs complete operating systems, while webvm implements the linux syscall interface, so it only runs linux executables. 

> Also, from what I could find, it does not look like there may be any x86_64 version coming out anytime soon, or is that planned for later as it would be extremely useful to be able to run x64 applications.

It'd be a nice addition, but I don't have the time to work on it.

> Maybe what I am seeking is some type of wasm (or similar) type of sandbox container engine instead of VMM in a browser, but I am not sure on this.

You're probably better off running wasm modules directly.
