### ISSUE TITLE
Network on ChromeOS

### ISSUE THREAD

**Issue by burnsboyamazing** [copy/v86#969]
When you try to ping www.google.com, services are also up. @inyourface34456 Uploading the screen recording.
[Screen recording 2023-12-27 6.39.41 PM.webm](https://github.com/copy/v86/assets/154830140/b6593cb1-e947-41c2-99e7-db63f2c42592)

**Comment by burnsboyamazing** [comment]
In https://github.com/copy/v86/issues/954, no Linux is needed. @inyourface34456 You need to upload the screenshot first, not the camera video or camera image.
![Screenshot 2023-12-27 6 43 24 PM](https://github.com/copy/v86/assets/154830140/00db179f-e248-4c2a-9555-1f187161cfb5)

**Comment by inyourface34456** [comment]
Why am I being pinged? I don’t think I have anything to do with this issue.

**Comment by burnsboyamazing** [comment]
Screenshot of the email because @inyourface34456 is pinging www.google.com.
![Screenshot 2023-12-27 6 48 18 PM](https://github.com/copy/v86/assets/154830140/3ff842e8-a635-4a81-9f6f-e9cb4f8d597b)

**Comment by inyourface34456** [comment]
Can you explain why I need to be involved in this issue?  Is there anything that I can help with? If so, what can I provide?  As far as I know, I have not been pinging google as of late.

**Comment by burnsboyamazing** [comment]
No, it's fine.

**Comment by burnsboyamazing** [comment]
Another screenshot of the email because it's pinging www.google.com. Want to ping again. Yes or no. Screen recording because it's pinging again.
[Screen recording 2023-12-27 6.54.11 PM.webm](https://github.com/copy/v86/assets/154830140/e0f9d7c7-918b-4f05-9cfe-e2551c82df2d)
![Screenshot 2023-12-27 6 52 59 PM](https://github.com/copy/v86/assets/154830140/86eca99d-7dd7-4198-bfe5-dc89d28cd386)

**Comment by burnsboyamazing** [comment]
Ok, no problem.

**Comment by burnsboyamazing** [comment]
Screenshot of the double email captured by @inyourface34456.
![Screenshot 2023-12-27 7 10 39 PM](https://github.com/copy/v86/assets/154830140/3e8cdfdf-9f78-47f6-bdd6-cda44f3cba8d)
