### ISSUE TITLE
How to quick build a small custom v86 linux image with gcc and make

### ISSUE THREAD

**Issue by slightc** [copy/v86#972]
How to quick build a small (<20MB) custom v86 linux image with `gcc` and `make`?

I tired build a image by 'https://github.com/humphd/browser-vm', and it build by buildroot, that could create small image (8MB), and `make` `fs` and `network` working great (I have modify some config for network), but buildroot not support create `gcc` to target image since 2012.

Have some guide for create image with gcc?

Thank for every one.

**Comment by slightc** [comment]
I think tinycc 'https://bellard.org/tcc/' is better choose, I will try compile it on buildroot

**Comment by slightc** [comment]
I tried it, but can't compile success, 🙃

**Comment by copy** [comment]
I'd suggest making an alpine image.
