### ISSUE TITLE
Download the IMG file after changes?

### ISSUE THREAD

**Issue by Darker** [copy/v86#98]
It's kinda sad one cannot download the changed virtual drive. I got Heroes of Might and Magic to work in the emulator. I would like to save the harddrive after all configuration is done.
![heroes](https://cloud.githubusercontent.com/assets/5508988/15467456/ed33c6fe-20de-11e6-8c76-8f534e4360e6.png)

**Comment by copy** [comment]
Good idea. Actually this exists for floppy disks, it should also be added for hard disks.
