### ISSUE TITLE
windows 2000: sound / audio not working (sb16)

### ISSUE THREAD

**Issue by Madde85** [copy/v86#982]
Hello all,

i was trying to add the audio/sound card to the windows2000 but no sound is outputted.
As far as i understood only soundblaster 16 is supported, i also checked the win98 of (copy.sh) where the sound is working (there is also the soundblaster 16 added).
I was able to add the soundblaster 16 see:
![grafik](https://github.com/copy/v86/assets/158088034/0199b1d5-0acf-4ad7-bb92-29a48e750ec3)

And Device Manager:
![grafik](https://github.com/copy/v86/assets/158088034/f2ea9360-37d4-4dad-9b67-22532b11e87c)

No yellow exclamation mark is shown for the soundcard, so windows thinks it is working.
If i try to play windows sounds it does not output anything.

Could someone please help me?
What did i wrong?

Kind regards and many many thanks :)
Martin

**Comment by Madde85** [comment]
Bug only appears in Firefox (latest version), in chrome sound works at beginngin.

**Comment by copy** [comment]
Probably https://stackoverflow.com/questions/62051711/is-it-possible-to-play-audio-without-the-user-interact-with-the-web-before-how
