### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by bradycodemaster** [copy/v86#995]
win 98 doesnt have graphic drivers 
sidebar sometimes always says idle when is not
some os dont boot

**Comment by copy** [comment]
> win 98 doesnt have graphic drivers

There is no gpu.

>  sidebar sometimes always says idle when is not

That's for disk access.

>  some os dont boot

Please be more specific.

**Comment by bradycodemaster** [comment]
so why does 3.1,95,2000 have 1024by768

**Comment by bradycodemaster** [comment]
and full color

**Comment by SuperMaxusa** [comment]
> win 98 doesnt have graphic drivers

If you about `windows98` profile, there has a problem by device conflicting with Standard VGA (Windows default driver) and VBE9x (uses in `windows95` profile for more resolutions and colors).

![win981](https://github.com/copy/v86/assets/41739128/2678ae6e-15b4-4a06-b2e9-db5a4583d1c0)

I tried make one trick: disable Standard Display Adapter (VGA), update VBE9x drivers from Windows driver storage (needed for enabling VBE9x) and rebooting via MS-DOS mode.

![win982](https://github.com/copy/v86/assets/41739128/9099b718-1190-471f-a5bd-90d73084df24)
